### ISSUE TITLE
Define SysAdmin team structure in order to help NWS recruit/assign people

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#1003]
Documentation considerations

- Responsibilities and controls
- Benefits and risks of this model
- Risk mitigation strategies
- Pull in the sysadmin scenarios from previous doc
- Any insights/guidance from NWS Chat 2.0

OOS

- assigning individuals

Working document outlining the role, approach and next steps based on NWS chat: [here](https://docs.google.com/document/d/1EFFY5OOL89vBD7T4DSQ58DXqCfcC0hmXLB2wWjY_1Iw/edit?usp=sharing)

Previously discussed notes on benefits, risks, scenarios, etc are still in the [Roles and Responsibilities doc](https://docs.google.com/document/d/1cqM9sU6O2fbAONCDbv8cAmzCm262F5jUR-r_CwN2vQ0/edit?usp=sharing) for now

**Comment by kmranjo** [comment]
Met with Brian this morning to discuss parallels to NWS chat admin team and how we might go about this. Next steps will be to write up a proposal/recommendation doc for how the team could be structured, recruited, and administrated, and a more detailed set of roles and responsibilities. I'll aim to have that done early next week.

**Comment by kmranjo** [comment]
@colinmurphy01  I put together a draft based on the notes we already had and the convo with Brian last week (its linked above). If this addresses the elements you expected, then I think it's ready to be discussed in PO/Design sync.

**Comment by colinmurphy01** [comment]
Provided feedback

**Comment by colinmurphy01** [comment]
Next steps

- Katrina finishes doc / documents risks
- POs will identify for final review
- Schedule meeting with sub group of champs
- Commit or investigate alternative SysAdmin options

**Comment by kmranjo** [comment]
@colinmurphy01 added a risks section to the doc with some potential mitigation measures

**Comment by colinmurphy01** [comment]
@coreypieper @shadkeene sometime next week, please review the doc Katrina has proposed after chatting with Brian.

**Comment by kmranjo** [comment]
Updated document coming out of our meeting this week, and opened #1216 to explore the updates to roles. We'll need that ticket to be completed before the document can be considered final.
