### ISSUE TITLE
Remove basic auth from the site and decide what we want out of a Drupal user/login page

### ISSUE THREAD

**Issue by loganmcdonald-noaa** [weather-gov/weather.gov#1006]
### Description

Followup to #952. We created a new login page for redirecting users upon logout (or pointing them to it as our login page) as part of this ticket, but as of now it is undesigned/styled. We can accomplish a lot by just removing entirely the root login username/password and that helps with simplifying design. However, we also need to figure out what we want from an interstitial page at all. 

### Questions and Considerations

Currently looks like: 
<img width="740" alt="Screenshot 2024-04-03 at 10 06 52 AM" src="https://github.com/weather-gov/weather.gov/assets/142825699/ea448627-92da-4a04-8e7b-90fda71b7422">

### Acceptance Criteria
- [x] Remove basic auth from form 
- [x] Remove /register and /password routes
- [ ] "Secure" the root account https://www.drupal.org/docs/administering-a-drupal-site/security-in-drupal/securing-the-admin-super-user-1
- [x] Document process of generating a login for the root user for our system admins
- [x] Ensure everyone on the team has appropriate admin permissions in every environment so no need for use of root account

**Comment by colinmurphy01** [comment]
Are disclaimers going to be required? There are a bunch on the current CMS login page.

**Comment by colinmurphy01** [comment]
Consideration is to get rid of UN and PW fields entirely and just managing via ICAM's NOAA account / PIV flow.

@loganmcdonald-noaa to discuss with Engineering
