### ISSUE TITLE
Accessibility: Screenreader spells out L-O-W within daily forecast?

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#1009]
### Description
Upon tabbing within a daily forecast component and reading the high / low temperature for the day. Voice Over on the mac reads "High" successfully but for some reason spells out "L-O-W" for low?

![Image](https://github.com/weather-gov/weather.gov/assets/24654605/722f6c79-f54c-4802-85a4-f546ec744e2c)

### Acceptance criteria

- [ ] Screen reader reads off "low" instead of spelling it out
- [ ] Tests have been implemented or modified to capture the bug
- [ ] Changes have been tested for accessibility

**Comment by greg-does-weather** [comment]
Might be incidentally fixed in #1017. Going to move to "doing" and will confirm after that one gets merged. If that PR doesn't fix it, I'll pick it up, but I think it does.

**Comment by greg-does-weather** [comment]
Confirming this one is done.
