### ISSUE TITLE
BUG: Current observation reports observation time as epoch timestamp instead of ISO8601

### ISSUE THREAD

**Issue by greg-does-weather** [weather-gov/weather.gov#1014]
### Description

Just what it says on the tin. The upshot is that we put a semantically invalid value into our `<time>` element. Our timestamp localization script expects the epoch timestamp, but in another PR (tk) I have updated it out of necessity to also work with ISO8601 timestamps.

However, epoch timestamps are not valid for the `<time>` element. ISO8601 timestamps are. So... let's make the switch.

### Acceptance criteria

- [ ] the current observations block returns the timestamp as an ISO8601 string
- [ ] the current observations e2e test captures the bug

**Comment by colinmurphy01** [comment]
Priority `medium`?

**Comment by greg-does-weather** [comment]
Low. There's no user impact. It's a 30-second change to be more spec-compliant.
