### ISSUE TITLE
Search: View recent results

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#1018]
Related to #914 

Ability for the search box to retain the last input location and serve it as the first option of results when revisited 
- If no search history, show normal state on click (nothing until user begins to search)
- If a user has search history, on focus into area show "recent locations". Continue to show as user enters until the recent items are "excluded". (Ie if a user has Oakland as a recent recent, continue to show oakland as a result under "recent" if user starts typing "Oak" but hide when types "Oakd..."
- Show up to three of the last locations searched at the top
- Use secondary font (see wireframe)

See [wireframes here](https://www.figma.com/file/0dSABt9zCqoknaKua6DHmP/NOAA---Weather.gov?type=design&node-id=4221%3A2523&mode=design&t=luBqhg1nI7iKv1TE-1)

To discuss as needed, engineering based decision:
- How will we store the recent searches? When do they clear?

**Comment by colinmurphy01** [comment]
@sarahmhgov can you help fill in this `eng` ticket with executional details for recent results in our combo box.

**Comment by sarahmhgov** [comment]
added some details! Whoever picks this up, feel free to reach out to pair
