### ISSUE TITLE
Accessibility: Combo Box Accessibility Iterations

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#1019]
### Description
After reviewing search component for WCAG compliance, the custom build component seemed to do the best and will be easier to customized with additional features. During the convo, the following suggestions were made:

- Maybe think about adding a field label on combo box (@kmranjo something like "type zip or city"?)
- Keep browser focus and screen reader focus on same elements - item in list 
- As user is typing, focus goes back to text field being entered
- Consider: testing for more unique breaking use cases

### Acceptance Criteria

- [ ] Field label is visible and read off
- [ ] Upon selection and enter, location page loads

**Comment by kmranjo** [comment]
For the field label, I would go with "Enter city or zip code"
