### ISSUE TITLE
Add capability to show International System of Units (e.g. °C vs. °F)

### ISSUE THREAD

**Issue by coreypieper** [weather-gov/weather.gov#1030]
In:

- Observations
- Daily summary
- Hourly table

paired with #1581

**Comment by coreypieper** [comment]
Both temps (C > F) and wind (mph > km/h) are done in the current "International System of Units" mode of P&C.

**Comment by colinmurphy01** [comment]
I believe this is `doing`?

**Comment by colinmurphy01** [comment]
Moved to `blocked` so that this can be picked up when #1581 is picked up

**Comment by partly-igor** [comment]
Engineering ticket #1985
