### ISSUE TITLE
Rework heading structure on location page

### ISSUE THREAD

**Issue by kmranjo** [weather-gov/weather.gov#1036]
Generated from #969

Once the content on the location page has been reordered (ticket TBD), the heading structure should be updated to reflect the outline in [this document](https://docs.google.com/document/d/1QM5piZgOpatkOlh7M-R5_eOnpp1v5fUAaWo9AnwufEM/edit?usp=sharing).

Note that in some instances, the heading will need to be screenreader-only text so as to not interfere with the visible version.  

- [x] H1: Location name (dynamic)
- [x] H2: Alerts (SR only)
  - [x] H3: [event type] (dynamic, for each hazard product) 
    - [x] H4: What
    - [x] H4: Where
    - [x] H4: When
    - [x] H4: Impacts
    - [x] H4: Additional details
    - [x] H4: What to do 
    - [x] H4: Areas impacted
    - [x] H4: Tips to stay safe 
- [x] H2: Current (SR only)
  - [x] H3: Current conditions
  - [x] H3: Radar 
- [x] H2: 7 Days (SR only)
  - [x] H3: Forecaster’s report 
  - [x] H3: Daily forecast (SR only) 
    - [x] H4: [day] (dynamic, repeat for each day displayed) 
      - [x] H5: Hourly forecast
      - [x] H5: Precipitation amounts
  - [x] H3: Your Local Forecast Office

**Comment by colinmurphy01** [comment]
Note: We want visual styling to remain the same, despite the shift down.
