### ISSUE TITLE
Create an internal feedback form

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#1039]
In addition to [our external touchpoints form](https://touchpoints.app.cloud.gov/touchpoints/22acf675/submit) we discussed making a separate one for internal folks.

This form would be linked on the internal Weather.gov 2.0 Ken's 10 page, training documentation, internal comms, and maybe within our CMS.

Example: https://docs.google.com/document/d/1sj_Yuy1bYlDVPtaWu4t-HmmzhIQG4BVV3VfrRU9wcLI/edit

**Comment by colinmurphy01** [comment]
Status of this?

**Comment by sarahmhgov** [comment]
Aligned on questions here https://docs.google.com/document/d/1PJnhnSGmo6wrNx2QbzF9fw7vk_SQUR8ZAWKBDNvGuNY/edit#heading=h.jbuijidoa1d6

Working on work-around to implement in NOAA drive

**Comment by sarahmhgov** [comment]
@colinmurphy01 cleaning this up but in case it unblocks you to have to link. I'm also happy to help set up the spreadsheet for managing if you're swamped. 

https://docs.google.com/forms/d/1ocB82_n9S_sZF4E3JSd3sWVYWMAu33FX3HVnXuPPrEI/edit?ts=66326356

**Comment by sarahmhgov** [comment]
This is in progress, adjusting some copy: https://docs.google.com/forms/d/1ocB82_n9S_sZF4E3JSd3sWVYWMAu33FX3HVnXuPPrEI/edit

**Comment by sarahmhgov** [comment]
Only big open question is whether we should remove the CMS questions for now all together

**Comment by colinmurphy01** [comment]
I think we keep it in there.

One question - the last two questions
- If you could prioritize one thing for the internal experience, what would it be?
- What other feedback would you like to share?

Are these only for CMS users or for anyone?

**Comment by sarahmhgov** [comment]
Not sure if this was throwing you off but just updated: "If you could prioritize one thing for the internal experience, what would it be?" 
to
"If you could prioritize one thing for the CMS experience, what would it be?

**Comment by colinmurphy01** [comment]
Yea saw that logic.

I didn't know if you wanted an open-ended field at the end for everyone prior to submission.

If this was created using an NWS account and is in their drive, then it looks good to me. 

I'll start working on #1111 later this week.

**Comment by colinmurphy01** [comment]
@coreypieper @shadkeene please take a look at this question in [the form](https://docs.google.com/forms/d/1ocB82_n9S_sZF4E3JSd3sWVYWMAu33FX3HVnXuPPrEI/edit).
> What area do you work within National Weather Service?

What should we do with the options. Do you want to keep as is?

**Comment by colinmurphy01** [comment]
Note to self, this form will then be added to

- Talking points
- Ken's 10 page
- Shad/Corey email signatures

**Comment by colinmurphy01** [comment]
Created a form to collect and tag external and internal feedback: https://docs.google.com/spreadsheets/d/16IXMjLwqRC2Tx_VnFCR6UGzh91Ym5QYAnfdhp5XO-Us/edit?resourcekey#gid=551505388

Will give it a try today.

**Comment by sarahmhgov** [comment]
@colinmurphy01 I think this one is done aside from the question on "role". 

Maybe next step to review by POs and close?

**Comment by colinmurphy01** [comment]
@coreypieper and @shadkeene assigned to you all

**Comment by coreypieper** [comment]
Just went through and filled it in. Looks good to me.

**Comment by colinmurphy01** [comment]
Will add to NWS Insider article as well #1206
