### ISSUE TITLE
Finish draft of internal talking points

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#1046]
Doc: https://docs.google.com/document/d/199YnTs2Ps-z5SsM-U-iFy8PwJY3xM5xnoVsq0UxrgLQ/edit

**Comment by shadkeene** [comment]
Have reviewed all @colinmurphy01 and @coreypieper .  Looks good.  HAve added some thoughts to the google doc.  will leave open for a few days...and if no additional thoughts, I can resolve comments and close, with draft complete.

**Comment by shadkeene** [comment]
Still needs review from me...then will forward to comms.

**Comment by shadkeene** [comment]
This is done--draft is done.
