### ISSUE TITLE
Accessibility: Combobox ARIA description 

### ISSUE THREAD

**Issue by partly-igor** [weather-gov/weather.gov#1059]
### Description

WAVE is reporting an error for the location search combobox:
> An aria-labelledby or aria-describedby reference exists, but the target for the reference does not exist.

Currently the combobox has `aria-describedby="combo-box-1--input--description"` , but there is no element with and `id` of `combo-box-1--input--description`

### Acceptance criteria

- [x] There is an element that matches the `id` of the `aria-describedby` attribute of the location search combobox, which properly describes the combobox. 
- [x] Changes have been tested for accessibility

**Comment by eric-gade** [comment]
Starting work on this, and I'm wondering why our a11y tests didn't pick it up

**Comment by eric-gade** [comment]
Closed by #1141
