### ISSUE TITLE
Location search combobox suggestion list is not tappable on mobile Safari

### ISSUE THREAD

**Issue by partly-igor** [weather-gov/weather.gov#1060]
### Description

When  trying to tap on one of the suggestions that appear in the list after typing in the location search combobox, the list closes but the location does not populate into the input box nor does the input submit and redirects the user the select location page. 

To replicate
1. Open Safari on iPhone
2. Type in part of a city name, such as "Ne" 
3. Try to tap on one of the suggestions that appear on in the list

### Acceptance criteria

- [ ] User can tap on one of the suggested locations that appears in the list
- [ ] Tapping the location name takes the user to that point-location page. 
- [ ] Tests have been implemented or modified to capture the bug
- [ ] Changes have been tested for accessibility

**Comment by colinmurphy01** [comment]
I was able to reproduce on safari phone and desktop

**Comment by greg-does-weather** [comment]
I believe this is fixed. I just tested it on my personal phone and it's working now. Gonna move this to review until one of y'all confirm as well.
