### ISSUE TITLE
Safety Info - Wind

### ISSUE THREAD

**Issue by kmranjo** [weather-gov/weather.gov#1069]
Content documented here: [link](https://docs.google.com/document/d/1lIEXBP7CBQWYJvpRQLC9msTR5jCgyXL3C3NAO3GP7oQ/edit?usp=sharing)

Needs: 
- [x] Corey review
- [x] SME review
- [ ] Alexander Tardy
- [x] Kimberly McMahon
- [x] Jessica Lee

**Comment by kmranjo** [comment]
Comments and suggestions from 2 of the 3 SMEs have been incorporated. @coreypieper should we wait for the last person before we consider this completed?

**Comment by coreypieper** [comment]
Email this morning confirms SME's have cleared! :)

**Comment by kmranjo** [comment]
Approved content has been authored and published in Beta

**Comment by coreypieper** [comment]
Looks like I misinterpreted their email. They are still going to run it by their SPT. I tried to unpublish wind ones, but I do not have permission. I'm sorry for the confusion.

**Comment by kmranjo** [comment]
Unpublished those items, they'll be ready when final reviews come in.

**Comment by kmranjo** [comment]
Prompting for review again this week

**Comment by coreypieper** [comment]
Emailed providing July 26 deadline. 
(Email subject "Dynamic Safety Information for weather.gov 2.0")

**Comment by kmranjo** [comment]
We received feedback on this one and it's been incorporated. With no outstanding comments or questions, I'm going to author it in beta and push it live.
