### ISSUE TITLE
Safety Info - Heat

### ISSUE THREAD

**Issue by kmranjo** [weather-gov/weather.gov#1070]
Documented here: [link](https://docs.google.com/document/d/1e4QNDj0Dme43XVnQ6ZihbgkaDSYbXdhr1wF3ZI1LFVM/edit?usp=sharing)

Needs: 
- [x] Corey review
- [x] SME review

**Comment by coreypieper** [comment]
Reviewed and sent along to NWS Heat SME's (Katrina CCed)

**Comment by kmranjo** [comment]
@coreypieper Reviewed and accepted edits from Jessica Lee and Robert Rausch. I see that there was a third person (Kimberly McMahon) included in your email to the SMEs, so should I wait to consider this completed until after she has had the chance to weigh in as well?

**Comment by coreypieper** [comment]
Email this morning (with Kimberly CCed) confirms that their comments have been resolved. SME's clear.

**Comment by kmranjo** [comment]
Excellent! The approved content has been published on beta.

**Comment by coreypieper** [comment]
Looks like I misinterpreted their email. They are still going to run it by their SPT. I tried to unpublish heat ones, but I do not have permission. I'm sorry for the confusion.

**Comment by kmranjo** [comment]
No worries! I unpublished them just now and we can publish whenever reviews are complete. There's a bug ticket in for the not-able-to-unpublish issue because Shad ran into the same thing and you both should definitely be able to do that.

**Comment by kmranjo** [comment]
@coreypieper Any chance we can get this set signed off on soon so that we can get it live for its busiest season?

**Comment by kmranjo** [comment]
Still waiting on final signoff from SMEs so Corey is going to prompt them this week and provide a deadline.

**Comment by coreypieper** [comment]
Emailed providing July 26 deadline. 
(Email subject "Dynamic Safety Information for weather.gov 2.0")

**Comment by kmranjo** [comment]
We received the last round of feedback and I've incorporated it into the doc. With no outstanding comments, going to author this in beta and push it live.
