### ISSUE TITLE
Safety Info - Flooding

### ISSUE THREAD

**Issue by kmranjo** [weather-gov/weather.gov#1071]
Documented here: [link](https://docs.google.com/document/d/1Na6vZmM5t5tkhQtpONMkZwJIsYSD_V_E9T6V_aAohe4/edit?usp=sharing)

Needs: 
- [x] Corey review
- [x] SME review

**Comment by coreypieper** [comment]
Reviewed and sent along to flood SME's (Katrina CCed)

**Comment by kmranjo** [comment]
@coreypieper I tried to find the email to SMEs so I could make a list of the specific folks reviewing, but I can't seem to find this one. Can you remind me who it was sent to?

**Comment by kmranjo** [comment]
No feedback yet on this one, SMEs may have changed, so Corey going to reach out again.

**Comment by coreypieper** [comment]
I've emailed the SME's with a July 26 deadline.
(email subject "Dynamic flood safety information for weather.gov 2.0")

**Comment by kmranjo** [comment]
Authored in beta and published
