### ISSUE TITLE
Change alert color to more appropriately communicate warnings vs watches

### ISSUE THREAD

**Issue by sarahmhgov** [weather-gov/weather.gov#1074]
### Description

Currently all WWA in the website are red. This has been called out by internal and external users as inconsistent with NWS practices and confusing. 

Update
- red: warning 
- orange: watch
- yellow: advisory/statement/other and considering all hazard components (hourly table, banners)

Considerations  
- For implementation should we also include color updates in hazard on a map implementation?
- do we need to inherit NWS hex colors for this implmentation or can we use USWDS?

### Acceptance Criteria
- Users are able to quickly know if a hazard is urgent or non-urgent using visual cues. 

Note that the color based definitions are a secondary indicator and do not require an alternate color-blind safe supplement.

**Comment by colinmurphy01** [comment]
This feels ready for `design`.

Does this need to be scoped further?

**Comment by colinmurphy01** [comment]
Product is aligned with moving forward with the simplified solution: red / yellow and considering all hazard components.

**Comment by shadkeene** [comment]
@partly-igor Do we know if this aligns with latest thinking from the hazsimp team?  Would be nice to be aligned with them on this.  I know several months ago, they said there were many options supported since the survey results were pretty even across the board.  Let me know if I can do something on this end to help.

**Comment by colinmurphy01** [comment]
Updated to also consider updating colors in the hazard on a map component.

**Comment by partly-igor** [comment]
Updated [alert colors documentation ](https://www.figma.com/file/0dSABt9zCqoknaKua6DHmP/NOAA---Weather.gov?type=design&node-id=5774%3A225412&mode=design&t=fwAylhpoqYdUlCyS-1)

**Comment by colinmurphy01** [comment]
Can you confirm that bext steps are:

1. Share with HazSimp team, no _red_ flags (elbow elbow) then
2. Ready for `eng`

**Comment by partly-igor** [comment]
😆 yes that sounds right

**Comment by colinmurphy01** [comment]
@igorkorenfeld in order to get them approved can you provide links to the examples in context. I think that helps more.

**Comment by partly-igor** [comment]
Sure thing:

[Mobile](https://www.figma.com/proto/0dSABt9zCqoknaKua6DHmP/NOAA---Weather.gov?page-id=5537%3A85832&type=design&node-id=5544-108489&viewport=-760%2C582%2C0.66&t=HkkZVKrK1oakYgSD-1&scaling=min-zoom&starting-point-node-id=5584%3A166282)

[Desktop](https://www.figma.com/proto/0dSABt9zCqoknaKua6DHmP/NOAA---Weather.gov?page-id=5537%3A85832&type=design&node-id=5591-166324&viewport=-760%2C582%2C0.66&t=HkkZVKrK1oakYgSD-1&scaling=min-zoom&starting-point-node-id=5584%3A166282)

**Comment by colinmurphy01** [comment]
@shadkeene @coreypieper do either of you want to send the colors and preview environments over to the HazSimp team for review and objections. It may require some context, so a short meeting may be necessary.

**Comment by shadkeene** [comment]
Yes @colinmurphy01 @coreypieper  , will do that today.

**Comment by shadkeene** [comment]
Closing this.  AFS may have some additional thoughts, but this has been coordinated with HazSimp team.

**Comment by shadkeene** [comment]
AFS supports the 3 color red/yellow/gray as prototype.  Waiting to hear from another AFS person (will probably hear next week) but going to close this for now b/c we have communicated/coordinated this with AFS.
