### ISSUE TITLE
Change alert accordions to be open by default

### ISSUE THREAD

**Issue by partly-igor** [weather-gov/weather.gov#1075]
In R3 we found that users were missing the second alert accordion, which was collapsed and sat between the top alert accordion and the safety information. We'd like to try having all accordions expanded by default, rather than only the first one being expanded. 

AC
- [ ] All alerts accordions on the alerts tab are expanded
- [ ] Alerts accordions are still collapsable

**Comment by eric-gade** [comment]
Closed by #1142
