### ISSUE TITLE
Safety Info - Air/Fog/Dust/Ash

### ISSUE THREAD

**Issue by kmranjo** [weather-gov/weather.gov#1076]
Generated from #777 

To potentially include: 

- Air Quality Alert
- Air Stagnation Advisory
- Dust Advisory
- Blowing Dust Advisory
- Dust Storm Warning 
- Ash Fall Advisory
- Ash Fall Warning
- Dense Smoke Advisory
- Dense Fog Advisory

Document ready for review [here](https://docs.google.com/document/d/1vtAK4SUHBrC-ZqFn2eCVc1rZDTRFz5HHYRXIja7Sc8g/edit?usp=sharing)

**Comment by coreypieper** [comment]
Reviewed and sent to Air Quality, Fog, Dust, Ash SME's (Katrina CCed)

**Comment by kmranjo** [comment]
Incorporated a lot of feedback from Kimberly McMahon and Jessica Lee. Some feedback and/or recommended edits might need some conversation. @coreypieper Do you want to take a look at the doc as it stands now? If the remaining recommendations look ok to you, we can just run with it. There are a couple of places where they have open questions I can't really speak to, and one bigger thing they recommend is not having any safety guidance for the air quality alert. Let me know what you think.

**Comment by kmranjo** [comment]
Yup, that makes sense. I had only combined them because I couldn't find anything int he WWA archive or on the website that really differentiated them for me. Broke them out in the document, responded to some of the questions, and we'll see where we go from there.

**Comment by kmranjo** [comment]
Discussed with Corey on 7/1, he's going to reach out to Kim about the few outstanding questions.

**Comment by kmranjo** [comment]
Authored and published in beta
