### ISSUE TITLE
Safety Info - Beach/Coastal

### ISSUE THREAD

**Issue by kmranjo** [weather-gov/weather.gov#1078]
Generated from #777

Products included: 
- High Surf Advisory
- High Surf Warning
- High Rip Risk
- Moderate Rip Risk
- Rip Current Statement

Guidance ready for review in [this document](https://docs.google.com/document/d/1i-kr_Lo7TvsXd7Nm9x9b4QQsdgTXCe3Yq6rrQvJGpJI/edit?usp=sharing)

Reviews needed: 

- [x] Corey
- [x] John Kuhn
- [x] Melinda Bailey
- [x] Wayne Weeks

**Comment by coreypieper** [comment]
I've reviewed and sent to beach SME's, but I've proposed a call with them (per the email sent/Katrina is CCed on) given the extra complexities in this program's products.

**Comment by kmranjo** [comment]
@coreypieper  I've updated the document based on our conversations last week, so it now reflects the 4 core products that can be issued and tries to be general enough for the products that can be nested within them. Take a look when you have time, and if it looks ok to you we can send along to the SMEs for re-review.

**Comment by kmranjo** [comment]
We sent for re-review in early June, haven't heard back yet but Corey is going to prompt again this week.

**Comment by coreypieper** [comment]
Sent email requesting final feedback by July 26.
(email subject "Dynamic beach/rip safety information for weather.gov 2.0")

**Comment by kmranjo** [comment]
Received final feedback, reviewed, and authored these in beta. They're now live on the site.
