### ISSUE TITLE
We use NOAA WOC for hosting

### ISSUE THREAD

**Issue by mgwalker** [weather-gov/weather.gov#108]
### Context

weather.gov has to be hosted somewhere in order to be available on the internet. Where we choose to host the product can have significant impacts on what we are able to build. Ideally, we would like to use a hosting provider that is already approved within NOAA/NWS rather than procuring something new.

### Decision

We have chosen to use the NOAA WOC as our hosting provider. It is already approved and supported within NOAA, and it is built on a large-scale commercial cloud provider that gives us a lot of freedom with what we build.

### Consequences

The WOC introduces another relationship and that could sometimes result in delays getting something done because we need their support or approval.

The WOC is using a particular commercial cloud hosting provider. While we will work towards a platform-agnostic application, the reality is that the plumbing to connect an application to its underlying infrastructure is always platform specific, so using the WOC will create a lock-in risk. (This risk is inherent in any hosting decision, but documenting it for completeness.)

**Comment by warrickmoran** [comment]
ESD Response: 
We use containers for development, testing, and production #107

18F - Decision
We have chosen to use the NOAA WOC as our hosting provider. It is already approved and supported within NOAA, and it is built on a large-scale commercial cloud provider that gives us a lot of freedom with what we build.


ESD - Response
The WOC, as with any hosting provided, must provide the required services and support to facilitate the full life-cycle development of a solution. This extends to technical needs and engineering and management processes to quickly respond to Weather.Gov needs.  

Questions:
What are the Weather.Gov cloud service and support requirements? Does the WOC have the ability to meet these requirements? 
What are the WOC’s constraints that will be applied to Weather.Gov? 
Is the WOC’s resource profile sufficient to support the Weather.Gov solution? 
What is the WOC’s long-term plan for their Cloud Environment?

**Comment by colinmurphy01** [comment]
@loganmcdonald-noaa what's the status of this ADR?

**Comment by greg-does-weather** [comment]
I'm just going to close this. ADRs are meant to be records of decisions, not decision-making aids. Since we've backed off the WOC decision for now, we can close this.
