### ISSUE TITLE
Safety Info - Tsunami

### ISSUE THREAD

**Issue by kmranjo** [weather-gov/weather.gov#1080]
Generated from #777

Products included: 
- Tsunami Advisory
- Tsunami Watch
- Tsunami Warning

Guidance is ready for review in [this document](https://docs.google.com/document/d/1gb--77MAYaKH-WeSbdNsYUEFgYenK_eRRNxAvVhAXg4/edit?usp=sharing)

Needs: 
- [x] Corey review
- [x] SME review (Dave Snider)

**Comment by kmranjo** [comment]
A bit blocked on this one - we got feedback from the SMEs but it's all language-focused and not accuracy focused. Happy to tweak the language too, but their edits make it a lot less plain language and a bit higher reading level. Will discuss with Corey.

**Comment by colinmurphy01** [comment]
@kmranjo I'd like to bring this to our champions, I think the conflict between integrity and accessibility is healthy. We can use this use case as an example for probably many more in the future.

**Comment by kmranjo** [comment]
@colinmurphy01 @coreypieper  I'm a little unsure what to do with this one. We had folks review and they changed quite a bit, most of it to be more detailed and technical. Should I try to rewrite them in a way that's a little bit closer to what they're asking, or are we still working on the overall conversation with champions about how these kinds of reviews work?

**Comment by colinmurphy01** [comment]
Have you tried replying back to the SMEs with that feedback?

**Comment by kmranjo** [comment]
Met with Corey today and talked through an approach to this. I've made some updates, and those are ready for SME review.

**Comment by coreypieper** [comment]
Emailed providing a July 26 deadline.
(Email subject "Dynamic tsunami safety information for weather.gov 2.0")

**Comment by kmranjo** [comment]
Received additional feedback and made a few small updates. I think we're ready to go with this one. @coreypieper  can we consider the last email to be Dave's signoff, and can I go ahead and publish this set?

**Comment by kmranjo** [comment]
Authored and published in beta
