### ISSUE TITLE
Safety Info - Missing Products

### ISSUE THREAD

**Issue by kmranjo** [weather-gov/weather.gov#1082]
To determine what products are missing from safety guidance so far, and determine if they should be added. 

[Working list of products here](https://docs.google.com/spreadsheets/d/1vVtI5lARcPPscvm2BgTLXguHwEScSytJsafa9JHhFHU/edit?usp=sharing)

Identified products: 
-  Extreme Fire Danger

Considerations (discussed with @coreypieper @shadkeene, don't need to do safety info for these) 
- SPS
- HWO
- PNS

**Comment by colinmurphy01** [comment]
BONUS for 3.17: Let's have convo about what should be in vs. out of scope for MVP.

**Comment by colinmurphy01** [comment]
Product would like an example of an `extreme fire danger` hazard

**Comment by coreypieper** [comment]
I've also reached out to NWS fire weather SME's to ask about `extreme fire danger`. I'll update once I hear back.

**Comment by kmranjo** [comment]
Updated above with a link to a hazard list I've been working from. If the "content in CMS" column reads TBD then it isnt one I've written any safety info up for. Not sure if we should look at assessing any of these to include until the ones we have get further along, since so many are still with SMEs

**Comment by colinmurphy01** [comment]
Did a rough count: 53/138 hazards are TBD.

I think it's a good idea to pause with what's a WIP for now. Let's break out another ticket for the rest of them, move to `Next` column, and pick them up later.

**Comment by kmranjo** [comment]
Created #1286  for this, so will close this one out
