### ISSUE TITLE
Compliance with AC-02 (3)

### ISSUE THREAD

**Issue by loganmcdonald-noaa** [weather-gov/weather.gov#1084]
### Description
We need to enact mechanisms to remove inactive accounts after 60 days, and document removal of accounts after revoked NOAA Account status. 

### Questions and Considerations
What happens to content associated with an "inactive" or "removed" account. 

### Acceptance Criteria
"Disable accounts within [24 hours] when the accounts: 
a. Have expired;
b. Are no longer associated with a user or individual;
c. Are in violation of organizational policy; or
d. Have been inactive for [60 days]."

**Comment by colinmurphy01** [comment]
@jamestranovich-noaa here's another

**Comment by jamestranovich-noaa** [comment]
Closing because we can't use GH; CF https://github.com/weather-gov/weather.gov/issues/1662
