### ISSUE TITLE
Configurations are being overwritten when new items are pushed to an environment

### ISSUE THREAD

**Issue by kmranjo** [weather-gov/weather.gov#1091]
In the last few weeks, we observed the following in the beta environment: 

1. I organized the taxonomy to reflect the correct structure
2. There was a release to beta
3. The taxonomy was reset to a previous iteration, and gained a number of duplicate entries, requiring rework

Separately: 

1. I reviewed the permissions associated with each role and set them to the desired levels
2. There was a release to beta
3. A number of options within each role were reset while others remained the same. In addition, the new options for new features (in this case, scheduling) were added to the role, but hadn't been configured yet so no one could use it. 

Can we look into: 

- Making it standard practice to include a review of permissions after new functionality is released (or create a related task for system admins).
- Putting any guardrails in place around releases to make sure configurations don't get altered or overwritten. They're fixable, but will make more work for system admins, and could interrupt work in progress.

**Comment by kmranjo** [comment]
@colinmurphy01  Created this coming out of our CMS session yesterday

**Comment by colinmurphy01** [comment]
@greg-does-weather can you check this out next week?

I wanna cut a release ahead of our CMS testing, but I'm hesitant to do so with this issue lingering.

**Comment by loganmcdonald-noaa** [comment]
Update of where we are at: 

We have started to socialize the difference between configuration and content on the team and come to a process/working understanding of what changes will impact configuration (necessitates a PR) and content (does not require a PR). When making configuration changes on the site, we should always be checking `/admin/config/development/configuration` and alerting the eng team to any changes we'd like to be permanent. It is better to experiment with these types of changes in an environment like `design` than `staging`. We are still considering if there is some sort of way we could automate the checking of this config sync prior to deploys to ensure that config someone has been working on isn't trampled over by a deploy but as of yet do not have a solution.

**Comment by loganmcdonald-noaa** [comment]
We haven't run into this problem in a couple weeks. @colinmurphy01 wdyt about closing this? The solution is basically that we should always be checking the UI to see if there is out of date config before releases to beta.

**Comment by greg-does-weather** [comment]
We decided this morning to add "check for config changes" to the release checklist, so we can close this.
