### ISSUE TITLE
Identify/begin path for LANTERN assistance with touchpoints responses

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#1092]
There is an opportunity for LANTERN assistance to analyze the plethora of feedback expected for both external and internal touchpoints surveys.  We need to determine a pathway/process for onboarding LANTERN assistance for this project.

**Comment by coreypieper** [comment]
Parking some info from NWS Comms here for our reference:

> Hi Corey,
> 
> I would start with the [LANTERN website](https://sites.google.com/noaa.gov/lantern/home?pli=1&authuser=1). The [process](https://sites.google.com/noaa.gov/lantern/lantern-opportunity-creators) is fairly straightforward but please reach out to me if you need help or have any questions. I would be happy to jump on a call with you and walk you through it and/or answer any questions next week.

**Comment by colinmurphy01** [comment]
@shadkeene @coreypieper After the disussion with @sarahmhgov we began drafting process proposal for when and how we want to review feedback.

As part of that we mentioned doing it ourselves first and then bringing people on to help. 

I'm going to close this ticket for now.
