### ISSUE TITLE
As a member of the public, I would prefer a narrative synopsis of the forecast

### ISSUE THREAD

**Issue by kmranjo** [weather-gov/weather.gov#110]
### Description
Plain language summaries of the the near-term forecast are valuable to all users (based on user interviews), especially for replacing technical weather jargon (apparent temp = "feels like") and accessibility needs.

**Related Epic: #55**

### Recommendation
The recommendation is to build a text narrative component that a forecaster can use to publish a weather narrative to the website. Based on the initial research performed in #69 

Note: This ticket addresses only the front end design, as several questions still need to be answered by subsequent research to design the back end processes. 

### Behavior
- Component should include the narrative text, the timestamp of its last update, and (if desired) the name of the forecaster who authored it 
- The timestamp should be automatically generated and include the date, time, and time zone
- Forecaster should not be able to enter more than 300 words in the field for narrative text 

### Acceptance Criteria 

As a site user, I should be able to

- Navigate to a page that displays a forecast for my location
- Read the published weather narrative on that page
- Quickly understand the expected weather conditions and any impact they may have 

I should not be able to
- See more than one weather narrative for a given location
- See no weather narrative for a given location 

### Examples
(examples are copied from existing sites - custom written examples to come) 

**Short version**
Temperatures will climb to the upper 80s today. After this morning's round of rain and storms, skies will clear which will help bring the chance for severe weather this afternoon and evening. 
Slight risk for severe storms late in the day for a vast area of the state and Wisconsin. A slight chance is a 2 out of 5 chance for severe weather. A few of these could be on the strong to severe side. Pay more attention to the weather later in the day. The main threats are hail and gusty wind.
We will see the mercury hover near and above our seasonal norms for the second half of the week with lots of sunshine. A warming trend persists through the weekend, with a few isolated storms expected on Saturday.

**Longer version**
Grab the umbrella out the door with a chance for rain early this morning. Skies will brighten this afternoon with highs reaching the mid-80s. With the humidity, it will still feel around 90 degrees. There is an isolated chance for a shower or storm this afternoon. The Storm Prediction Center has the DMV under the ‘Marginal’ risk category, which means one or two storms could reach severe limits with damaging winds and hail. The big MLS All-Star game tonight at Audi Field against Arsenal is forecast to be warm and dry with temperatures in the low 80s for kickoff at 8:30 p.m.
Tomorrow will be another hot and humid day with highs in the upper 80s and heat index values in the low 90s. An isolated shower or storm is possible in the afternoon with higher rain and storm chances Thursday evening and overnight. Pockets of heavy rain could lead to isolated flooding.
Friday will start off humid, but humidity will drop throughout the day with highs in the mid to upper 80s. An isolated afternoon t-shower is possible, but it is looking really nice for your Friday night plans.
The upcoming weekend is trending fantastic for late July with relatively low humidity, no rain chances and slightly below average temperatures in the mid to upper 80s. Heat index near 90.

**Version with hazards present**
Tuesday was the ninth consecutive day of temperatures 105+ degrees or hotter for Austin. This ties the all-time record – and, unfortunately, that record will soon be broken with temperatures reaching at least 105 degrees for the rest of the workweek. 
Wednesday afternoon will bring more record-breaking heat to Austin with a high of 107 degrees. A Heat Advisory will be in effect for most of Central Texas on Wednesday, and we continue to recommend avoiding strenuous activity during the peak heat of the day if possible. "Feels like" temperatures could climb as high as 111 degrees. The "heat dome" continues to strongly influence our weather through the work week with highs around 106 through Friday. 
Aside from the heat, elevated to near-critical wildfire concerns will continue through this week. Every county in the KVUE area except for Gillespie County is under a burn ban, so please avoid outdoor burning and be mindful of anything that could indirectly result in sparks.
This weekend, the "heat dome" will weaken slightly and retreat back to the west. This will not bring much heat relief, but it will drop temperatures closer to 105 over the weekend. A frontal boundary will approach Central Texas and bring a very small rain chance. Both Saturday and Sunday will have a very slim 10% chance of rain, but we still do not see any significant rain through the extended forecast. 
Next week continues to look very hot, with high temperatures of around 105 through Tuesday of next week. Continue to stay cool and stay safe in this heat!

**Comment by colinmurphy01** [comment]
Noted from other convos:
- This is mostly ready for eng, just needs to be laid out in FISMA
- Once that's done, it can be tagged with eng label 
- This and other components #34 #77 #49 should be discussed as to when we should build them. Is it better to build them together in a layout or individually? Adding as a topic for team discussion.

**Comment by colinmurphy01** [comment]
The component will be documented here #180 for dev. I believe this can be closed. Confirm @janelx @kmranjo?
