### ISSUE TITLE
Recent Locations: Add all recent locations to list

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#1107]
### Currently

- Visit beta
- Click use my location , it loads Shaker Heights
- I click the combo box to look up Washington DC
  - Shaker doesn’t come up as a recent location
- I load washington DC
- I click the combo box to look up Chicago
  - Washington DC shows up, Shaker Heights doesn’t show up

### Acceptance criteria

- [ ] Add any location page you visit to the list of recent locations, regardless of how you got there (via my location, search, or landed on the page)
- [ ] Tests have been implemented or modified to capture the bug
- [ ] Changes have been tested for accessibility

**Comment by colinmurphy01** [comment]
@sarahmhgov do you agree with this logic?

**Comment by sarahmhgov** [comment]
Yes - basically show any location that was recently visited, regardless of if it was searched.
