### ISSUE TITLE
Address redundancy in "severe" Watch products

### ISSUE THREAD

**Issue by shadkeene** [weather-gov/weather.gov#1115]
I believe the formatted "areas affected" is repeating the unformatted "counties" list above.  Can we eliminate this redundancy?  I understand these types of watches may be formatted differently.  Also, it's not completely clear that something like "Lamar, TX" in the formatted list is a county vs. a city.
![image](https://github.com/weather-gov/weather.gov/assets/139174561/e31636fb-c626-4249-9a2a-de9451c20181)

**Comment by colinmurphy01** [comment]
Assigning to Product to look for other examples and assess frequency of use case (across products and WFOs) and the purpose of the locations in the Description field.

**Comment by greg-does-weather** [comment]
Saved bundle of an example alert: [bundle_66390f4a23ee2.zip](https://github.com/weather-gov/weather.gov/files/15224038/bundle_66390f4a23ee2.zip)

**Comment by coreypieper** [comment]
New example: [North Platte, NE _ Weather.gov _ National Weather Service.pdf](https://github.com/weather-gov/weather.gov/files/15224070/North.Platte.NE._.Weather.gov._.National.Weather.Service.pdf)

Currently, severe/tor watches (which are unique, as they're issued by SPC vs. WFO's) in beta, have the impacted counties listed near the top, then a list of the cities, then a bulleted list of the counties (again).

Here is the API active endpoint for this product: 
[active.txt](https://github.com/weather-gov/weather.gov/files/15224072/active.txt)

**Comment by coreypieper** [comment]
Another: 
[Pierre, SD _ Weather.gov _ National Weather Service.pdf](https://github.com/weather-gov/weather.gov/files/15224503/Pierre.SD._.Weather.gov._.National.Weather.Service.pdf)

API output: 
[active (3).txt](https://github.com/weather-gov/weather.gov/files/15224504/active.3.txt)

**Comment by greg-does-weather** [comment]
The list of counties that we show under the "Areas impacted" heading are determined automatically based on what [forecasters draw in AWIPS](https://gsa-tts.slack.com/archives/C04UJTTH2NT/p1717454341003699?thread_ts=1717451503.750139&cid=C04UJTTH2NT) when they create the alert.

When there is additional place information, that's something forecasters manually added to the alert text, or something added for them in some local scripts or tools. The addition information adds context to the list of counties, identifying where geographically in the state the county is.

My proposal:
1. Change the "Areas impacted" heading to "Counties impacted"
2. After a quick look at the four examples captured in this issue (thanks @coreypieper!), the text prior to the manual counties is the same, and therefore we might be able to parse on it. We can put together a quick prototype where, if we identify that the manually-entered counties are present, we:
  - add additional subheadings under "Counties impacted" to reflect the regions of the state that the counties are in
  - maybe add a subheading for cities? All four examples captured here also include cities, and the formatting is identical between them.

## Big unknown

In the four examples we have, the alert description ends with the list of cities. Is this true for all alerts that will include this additional place information? Or are there alerts that could contain additional information after the extra place information?

Maybe we could ask the WFOs that originated these alerts directly how that text gets in there? They are North Platte (LBF; issued 2 of the 4), Hastings (GID), and Aberdeen (ABR).

---

<details>
<summary>Recording a plaintext, unformatted copy of one of the alert descriptions here for ease of reference</summary>

<code><pre>THE NATIONAL WEATHER SERVICE HAS ISSUED TORNADO WATCH 187 IN
EFFECT UNTIL 7 PM CDT THIS EVENING FOR THE FOLLOWING AREAS

IN KANSAS THIS WATCH INCLUDES 6 COUNTIES

IN NORTH CENTRAL KANSAS

JEWELL                MITCHELL              OSBORNE
PHILLIPS              ROOKS                 SMITH

IN NEBRASKA THIS WATCH INCLUDES 24 COUNTIES

IN CENTRAL NEBRASKA

GREELEY               HOWARD                MERRICK
NANCE                 SHERMAN               VALLEY

IN EAST CENTRAL NEBRASKA

POLK                  YORK

IN SOUTH CENTRAL NEBRASKA

ADAMS                 BUFFALO               CLAY
DAWSON                FILLMORE              FRANKLIN
FURNAS                GOSPER                HALL
HAMILTON              HARLAN                KEARNEY
NUCKOLLS              PHELPS                THAYER
WEBSTER

THIS INCLUDES THE CITIES OF ALMA, ARAPAHOE, AURORA, BEAVER CITY,
BELLAIRE, BELOIT, BLADEN, BLUE HILL, BOSTWICK, BURR OAK,
CAMBRIDGE, CAMPBELL, CENTRAL CITY, CLAY CENTER, CODELL, COZAD,
DESHLER, DOWNS, EDGAR, ELWOOD, EXETER, FAIRFIELD, FAIRMONT,
FRANKLIN, FULLERTON, GENEVA, GENOA, GOTHENBURG, GRAND ISLAND,
GREELEY, HARVARD, HASTINGS, HEBRON, HILDRETH, HOLDREGE,
HOLLINGER, INAVALE, IONIA, JEWELL, JOHNSON LAKE, KEARNEY,
KENSINGTON, LEXINGTON, LITCHFIELD, LOUP CITY, MANKATO, MINDEN,
NELSON, ORD, ORLEANS, OSBORNE, OSCEOLA, OXFORD, PHILLIPSBURG,
PLAINVILLE, POLK, RED CLOUD, ROSEMONT, SCOTIA, SHELBY,
SHERMAN RESERVOIR, SMITH CENTER, SPALDING, ST. PAUL, STOCKTON,
STROMSBURG, SUPERIOR, SUTTON, WILLOW ISLAND, WOLBACH, AND YORK.</pre></code>
</details>

**Comment by greg-does-weather** [comment]
The additional location information is created by a Python script. The entire alert:
> is completely automated in terms of output, other than the forecaster graphically validating which counties/parishes/marine zones are included.

The output is consistent, provided that the Python script doesn't change. So attempting to parse this free text into structured data is a risk. Note that we're already parsing free text into structured text for alerts simply because they are only provided as free text products.

Unfortunately, for the foreseeable future, there's no way to add formatting and structure to alerts without applying some parsing to free text and crossing our fingers a bit. (We should likely add a debt/bug ticket to appropriately handle the case where parsing an alert causes an exception – perhaps in that case, we just pass the unformatted alert text straight to the user?) Personally I think this is a reasonable risk, but I'm not a product owner. 😄
