### ISSUE TITLE
Keyboard navigation of content tabs

### ISSUE THREAD

**Issue by greg-does-weather** [weather-gov/weather.gov#1116]
### Description

During the demo today, a participant noted that when tabbing, the "current" tab received focus but the "7 day" tab did not. While the "current" tab was focused, using the arrow keys did not change tabs.

On the latter part, I suspect that they had focused the tab content rather than the tab button, as tab button arrow key support is well tested, but any confusion there is likely a direct result of the "7 day" tab button not getting tab focus.

Question is, I guess: should the tab buttons get tab focus? Inactive tab buttons current get `tabfocus="-1"` to take them out of the focus order, presumably to preserve reading order.

### Acceptance criteria

- [ ] Tests have been implemented or modified to capture the bug
- [ ] Changes have been tested for accessibility

**Comment by colinmurphy01** [comment]
Should we discuss this in our next API review?

**Comment by mgwalker** [comment]
Did you mean accessibility review? If so, maybe! I'd ask in the accessibility guild first, though.

**Comment by colinmurphy01** [comment]
Hypothesis is that it's working as expected.

**Comment by greg-does-weather** [comment]
This is indeed working as expected. From the [MDN tablist documentation](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Tablist_Role#keyboard_interactions):

> `Tab`
> When focus moves into the tab list, places focus on the active tab element.
>
> When the tab list contains the focus, moves focus to the next element in the page tab sequence outside the tablist, which is the tabpanel unless the first element containing meaningful content inside the tabpanel is focusable.

This accurately describes our tab behavior. And then:

> `Left Arrow`
> moves focus to the previous tab. If focus is on the first tab, moves focus to the last tab. Optionally, activates the newly focused tab
>
> `Right Arrow`
> moves focus to the next tab. If focus is on the last tab element, moves focus to the first tab. Optionally, activates the newly focused tab

Which also describes our behavior. @eric-gade knocked it out of the park!
