### ISSUE TITLE
Unable to unpublish content

### ISSUE THREAD

**Issue by shadkeene** [weather-gov/weather.gov#1118]
### Description

I created a weather story, and when trying to unpublish (following the process in first screen grab below), I got the following error (second screen grab image below).

![image](https://github.com/weather-gov/weather.gov/assets/139174561/ff0902f4-8d1e-45f7-8171-615c72265ef0)

![image](https://github.com/weather-gov/weather.gov/assets/139174561/9e48f9e5-0c52-451f-a56d-9eaa0947c3c9)

### Acceptance criteria

Content editors and content admins should be able to unpublish content so it is not deleted from the system, but it does not show up any longer on beta.weather.gov.

- [ ] Tests have been implemented or modified to capture the bug
- [ ] Changes have been tested for accessibility

**Comment by colinmurphy01** [comment]
This might be related to V2 refinement from testing (save, preview, publish, unpublish)

**Comment by loganmcdonald-noaa** [comment]
So weirdly the content editors _can_ unpublish content but only when editing that content in the view, not from this bulk action UI. Will try to figure out why this is happening, but yes with the changing flows this might go away.
