### ISSUE TITLE
Scope smaller lighthouse page load enhancements

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#1122]

**Comment by colinmurphy01** [comment]
Another consideration: https://github.com/sitespeedio/sitespeed.io

**Comment by colinmurphy01** [comment]
@greg-does-weather to check with @eric-gade on this and assess if the juice is worth squeeze

**Comment by greg-does-weather** [comment]
We've either done it or determined it wasn't worth doing, but we don't remember which. Either way, there's nothing left to do here.
