### ISSUE TITLE
Update "Twitter" to "X" in WFO Promo

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#1134]
What it says on the tin. Update Twitter logo and name to X in WFO promo.

![Image](https://github.com/weather-gov/weather.gov/assets/24654605/e03b5e32-1e85-4d64-aeb8-ae42c9bd0b7f)

**Comment by colinmurphy01** [comment]
@partly-igor do we have an X logo to replace twitter? Or is that something you'll need to creat?

**Comment by partly-igor** [comment]
One exists in USWDS but for some reason not in our spritesheet. So TBD how we will resolve it.

**Comment by greg-does-weather** [comment]
I think we "just" need to update USWDS and copy the updated USWDS spritesheet over.
