### ISSUE TITLE
Document and discuss the "time" issues

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#1136]
In a deck
- Document the challenges we've faced in dev and testing (and impact it's having on our work)
- Document any user research findings
- Open questions
  - Why the 6-6 time frame?
  - What else uses it and is dependent on it?

Discuss as a core team.

**Comment by sarahmhgov** [comment]
@eric-gade @igorkorenfeld wondering if this would be easier as a working session, maybe with Shad / Corey or whoever else might understand the NWS pov on this? I can pull in igor's diagram into a figjam and add some user notes to set up some framing.

**Comment by partly-igor** [comment]
I think that works!

**Comment by eric-gade** [comment]
Agree, that works better for me too

**Comment by sarahmhgov** [comment]
@eric-gade when do you want to plan to have this conversation? I'm out next eng/design sync but ya'll are welcome to have it without me.

**Comment by partly-igor** [comment]
[Template](https://docs.google.com/presentation/d/1zYK-oLix4Jrw9MNeJ-rZCJu6nplhqNHrGwk5PzuBjgQ/edit?usp=sharing) for diagramming timing

**Comment by colinmurphy01** [comment]
I believe this is `done`? 

The issues we discussed were:
- 6am to 6am (which we will continue to monitor via usability tests)
- 12am - 6am, across time zones (which our current solution does a good job of solving but is still hard on eng)
