### ISSUE TITLE
List alerts that we curently display on beta, circulate for feedback

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#1139]

**Comment by greg-does-weather** [comment]
Here is the list of hazards that we currently support, in the priority order that we use to sort them:

> [!NOTE]  
> We do ***NOT*** have priority ranking for these alerts:
>
> * freezing rain advisory
> * lake effect snow advisory
> 
> I don't know how they got into our list of supported advisories without also being in our prioritized list, but it's true that they did, so recording it here.
 
1. tsunami warning
1. tornado warning
1. extreme wind warning
1. severe thunderstorm warning
1. flash flood warning
1. flash flood statement
1. severe weather statement
1. shelter in place warning
1. evacuation immediate
1. civil danger warning
1. nuclear power plant warning
1. radiological hazard warning
1. hazardous materials warning
1. fire warning
1. civil emergency message
1. law enforcement warning
1. hurricane warning
1. typhoon warning
1. blizzard warning
1. snow squall warning
1. ice storm warning
1. winter storm warning
1. high wind warning
1. tropical storm warning
1. tsunami advisory
1. tsunami watch
1. avalanche warning
1. earthquake warning
1. volcano warning
1. ashfall warning
1. coastal flood warning
1. lakeshore flood warning
1. flood warning
1. high surf warning
1. dust storm warning
1. lake effect snow warning
1. excessive heat warning
1. tornado watch
1. severe thunderstorm watch
1. flash flood watch
1. flood statement
1. wind chill warning
1. extreme cold warning
1. hard freeze warning
1. freeze warning
1. red flag warning
1. hurricane watch
1. typhoon watch
1. tropical storm watch
1. hurricane local statement
1. typhoon local statement
1. tropical storm local statement
1. tropical depression local statement
1. avalanche advisory
1. freezing rain advisory
1. winter weather advisory
1. lake effect snow advisory
1. wind chill advisory
1. heat advisory
1. urban and small stream flood advisory
1. small stream flood advisory
1. arroyo and small stream flood advisory
1. flood advisory
1. hydrologic advisory
1. lakeshore flood advisory
1. coastal flood advisory
1. high surf advisory
1. dense fog advisory
1. dense smoke advisory
1. blowing dust advisory
1. lake wind advisory
1. wind advisory
1. frost advisory
1. ashfall advisory
1. freezing fog advisory
1. local area emergency
1. avalanche watch
1. blizzard watch
1. rip current statement
1. beach hazards statement
1. winter storm watch
1. coastal flood watch
1. lakeshore flood watch
1. flood watch
1. high wind watch
1. excessive heat watch
1. extreme cold watch
1. wind chill watch
1. lake effect snow watch
1. freeze watch
1. fire weather watch
1. extreme fire danger
1. 911 telephone outage
1. coastal flood statement
1. lakeshore flood statement
1. special weather statement
1. air quality alert
1. air stagnation advisory
1. hazardous weather outlook
1. hydrologic outlook
1. short term forecast
1. administrative message
1. test
1. child abduction emergency

**Comment by greg-does-weather** [comment]
@coreypieper has confirmed this list. :gavel:
