### ISSUE TITLE
CfA Lightning Talk Slides

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#1140]
Due May 3

approx. 10 slides ([template](https://docs.google.com/presentation/d/1iMkyx1ZUh4TBmtBnR1jSiaY6Zc80Gslxzz02DnFqk9E/template/preview))

[FAQ doc](https://docs.google.com/document/d/1HK74-KUvFGd88smK69Xs7CcDlWoUn2W7fYXveBAeOb0/edit)

**Comment by colinmurphy01** [comment]
[WIP deck](https://docs.google.com/presentation/d/1HeoUtZAu7oQ3MIO8Zm9-PQLAjPTeEla4z6NhAZ_P1TU/edit?pli=1#slide=id.g5ecdbbee9e_0_0)

**Comment by shadkeene** [comment]
Slides sent to CfA.  Now, to practice :)
