### ISSUE TITLE
Rectify high temperature hourly vs. daily differences 

### ISSUE THREAD

**Issue by coreypieper** [weather-gov/weather.gov#1153]
Forgive me if this is on an existing ticket. Another example today. 
![IMG_4571](https://github.com/weather-gov/weather.gov/assets/4570239/515a7d00-72dd-4dcd-85a3-5949231c3a2f)

**Comment by eric-gade** [comment]
One solution we had discussed in the recent past was to simply use all the hourly temperature data to figure out the high and low values for the corresponding time period. I don't remember offhand why we decided against this. But it is worth knowing that the daily forecasts day/night temps don't always correspond to the highest/lowest forecast temps in the hourly data.

**Comment by greg-does-weather** [comment]
Closed by #1319
