### ISSUE TITLE
Remove "WFO name" label from WFO promo

### ISSUE THREAD

**Issue by partly-igor** [weather-gov/weather.gov#1156]
### Description
Currently the WFO promo displays the field label "WFO Name" in addition to the value. That is, it reads "WFO Name \<office name>" rather than just "\<office name>". We should remove the label and only keep the value

![Screenshot of the current WFO name with the unnecessary field label text](https://github.com/weather-gov/weather.gov/assets/150970973/6f4bbbab-6200-4cd0-8e32-f8df1457b539)

### Acceptance criteria
- [ ] The text below "Your Local Forecast Office" displays the name of the office but not the literal text "WFO name"
- [ ] Changes have been tested for accessibility

**Comment by greg-does-weather** [comment]
@partly-igor What environment are you seeing this in? It's not showing up [in beta](https://beta.weather.gov/point/36.166/-86.779#daily), and the config we have in git should prevent it. If it's your local environment, can you try `make import-config` and see if the label goes away?

**Comment by colinmurphy01** [comment]
Assigned to @partly-igor. If not an issue then close.

**Comment by partly-igor** [comment]
confirmed this isn't an issue once the config is updated so I am closing this issue. Thanks @greg-does-weather
