### ISSUE TITLE
Content Strategy: Clarify value/purpose between Weather Story vs. AFDs vs. Other Forecaster text products

### ISSUE THREAD

**Issue by kmranjo** [weather-gov/weather.gov#1169]
Acceptance criteria

- [x] Document proposed content strategy outlining the different goals, audiences, etc. for each content type
- [x] NWS review 
- [x] Team alignment
- [ ] Discuss with POs how to get buy-in from above to promote this approach

[Draft strategy document for forecaster content](https://docs.google.com/document/d/1JD0lLGEEPUtgBsgqpFsIEOTn1ec9EAdga1T4cs127MM/edit?usp=sharing)

For background, original sitewide [content strategy draft doc](https://docs.google.com/document/d/1OmzqsbsEN8XPmVVyabPkhKSlFE4KUFgFft3Nhz6N4-Y/edit?usp=sharing)

**Comment by kmranjo** [comment]
Outlined an initial approach above. In doing so, running into the gaps for forecaster-created content types we haven't dug deep into yet (blogs, custom webpages, newsletters, etc) so am digging a little deeper into that assessment by looking more closely at all the office-specific content on the site. Will try not to let it be too much of a diversion, but I think more background on the content being created in these areas will help inform our conversations going forward.

**Comment by kmranjo** [comment]
@colinmurphy01 I have this fleshed out to a point, but there are a few topics that would need more discovery around them to make an informed recommendation. The biggest one is the event recaps and storm damage reports, which are manually built by forecasters now. Is that an area we want to include in this now, or should we just note it as something to get to a bit later?
The other slightly smaller one is the manual writeups of historical data trends and norms, so its a blend of climatology and local weather info.

**Comment by kmranjo** [comment]
Removed editorial content from this one as discussed, and otherwise refined and updated the approach. I think it's ready for review by the team and POs whenever we want.

**Comment by kmranjo** [comment]
Depends what others bring to it, but I think so?

**Comment by colinmurphy01** [comment]
@partly-igor Consideration for PO / Design Sync this week

**Comment by kmranjo** [comment]
@colinmurphy01  I feel like we've completed the first few items on the task list for this one based on our convos last week, but the last one is something we haven't gotten to yet. Since this work specific to AFDs is kind of getting wrapped into larger tickets like #1293 do we still want to do that as part of this one, or should we close this out as done and work on artifacts and feedback in those newer tickets only?

**Comment by colinmurphy01** [comment]
Yea let's close this one out and use new tickets.
