### ISSUE TITLE
Precipitation tables not expanded or centered with expansion of hourly forecast details

### ISSUE THREAD

**Issue by shadkeene** [weather-gov/weather.gov#1189]
When a user expands the hourly forecast details, the precipitation amounts table is not expanded with it.  It should probably be expanded.  If not intended to be expanded, it could be centered.  I just want to make sure this layout is intended.

![image](https://github.com/weather-gov/weather.gov/assets/139174561/3100dcd3-babb-47ca-8499-95dad758d1fc)

This should be coupled with #1145

**Comment by colinmurphy01** [comment]
Let's discuss in PO review

**Comment by colinmurphy01** [comment]
This design was intentional, even if it seems unintentional.

Could explore alternatives.

From product's perspective, this is not urgent

**Comment by shadkeene** [comment]
Product thinks that if low level of effort, can have 5 rows in precipitation table per day, to ensure it captures all periods of the day's forecast. (6am-6pm), even if the next day shows the same information (can have duplicates).

**Comment by colinmurphy01** [comment]
Coupling with #1145

**Comment by colinmurphy01** [comment]
With #987 completed. This is what it now looks like on desktop.

![Image](https://github.com/user-attachments/assets/a6cc31ad-f79e-452e-ac12-b2d6e6d7d1e8)

Is this the preferred layout to resolve this issue?

**Comment by colinmurphy01** [comment]
@partly-igor following up on the above / status?
