### ISSUE TITLE
Config change from edit weather story to create weather story

### ISSUE THREAD

**Issue by kmranjo** [weather-gov/weather.gov#1194]
Update permissions in all environments to grant Create permissions to the Content Editor role for the Weather Story content type only.

This can be done by anyone with system admin permissions in the CMS. 
It can be tested with a Content Editor user in the Design environment. 

Complete this config change in: 
- [x] Design
- [ ] Staging
- [ ] Beta

**Comment by colinmurphy01** [comment]
This will need to be in git (yaml update) so it doesn't get overwritten.

**Comment by kmranjo** [comment]
Made the change and tested it in the design environment. It's working, so eng team is going to pull that into a PR for the other enviros.

**Comment by loganmcdonald-noaa** [comment]
This will be accomplished in #1241
