### ISSUE TITLE
I want the CMS to know my primary WFO

### ISSUE THREAD

**Issue by kmranjo** [weather-gov/weather.gov#1195]
### Background
Each WFO-based user of the CMS is going to have permissions at some level for multiple WFOs to provide emergency backup to their neighboring offices if/when needed. However, those instances will be rare, and their day to day operations will simply involve updates to their primary WFO. 

### Current state
Using the taxonomy structure of Region > WFO and the Workbench Access module we have the ability to: 
- Associate content with a single WFO
- Grant users permission to access content for multiple WFOs
However, there is no distinction made between a user's primary WFO and the neighboring offices they have permissions for. 

### Future state 
Whether through changes to the existing taxonomy or through other means, we want the ability for the system to understand that each user may have access for multiple WFOs, but most will have one primary WFO. Making this distinction will allow us to organize and display content based on a user's primary WFO (work captured in another ticket). 

One idea discussed would be to update user profiles to allow system admins to assign a primary WFO to each one.

**Comment by colinmurphy01** [comment]
Not possible with workbench, if this needs to be done at a more fundamental this might challenge our current access control tooling. 

We might be able to explore additional ways to fix, but will take work.

**Comment by loganmcdonald-noaa** [comment]
I think what we can do is define this as part of the user profile as a setting users can set. We can then use this setting to add a filter for what the user can see in their content dashboard.
