### ISSUE TITLE
Increase size of uploaded image

### ISSUE THREAD

**Issue by kmranjo** [weather-gov/weather.gov#1199]
### Current state 
Right now when a user creates a Weather Story and uploads a file to the Forecaster Image section, the preview of that image upon upload is quite small, which could make it difficult for the user to verify that they have uploaded the correct image. 

![Image](https://github.com/weather-gov/weather.gov/assets/127144183/4d55ae5f-6c15-4f0a-ae09-6a98b440e792)

### Acceptance criteria 
When a user uploads an image to the Forecaster Image section, the preview is large enough to distinguish some amount of detail so that the user can more easily verify the image.

**Comment by loganmcdonald-noaa** [comment]
How's this for size? 

![Image](https://github.com/weather-gov/weather.gov/assets/142825699/46a4e0bd-f354-4e9b-882d-ed776c1f8d22)

**Comment by kmranjo** [comment]
I think that works! We just need it to be big enough to see the detail and distinguish from other files they might have.
