### ISSUE TITLE
What new information have we learned from the post - midpoint on users, stakeholders, etc?

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#12]

**Comment by sarahmhgov** [comment]
Katrina started a [mural](https://app.mural.co/t/gsa6/m/gsa6/1685550345856/817e3440c48d4a0163db36f3f2b243dfd35a2b64?sender=u61b531faf98169a303ef4628) here, I will take a pass at putting into a deck

**Comment by sarahmhgov** [comment]
https://docs.google.com/presentation/d/11aGN3MjEvti0amqn10BdZxhhTQ76pUUZuMzjy5wCfac/edit#slide=id.g24d738ce323_0_920
