### ISSUE TITLE
On preview page, add publish capability

### ISSUE THREAD

**Issue by kmranjo** [weather-gov/weather.gov#1201]
### Current state 
When a user creates or modifies content, they are able to select the Preview option. 
This directs them to a page on which they can see the authored content exactly as it will display on the published page. The only action that they are able to take from this preview page is to return to editing. 

![Image](https://github.com/weather-gov/weather.gov/assets/127144183/0b024e45-1c77-4c5a-ac31-9543f3d7eba3)

To publish the item that they have previewed, they have to return to the editing page first, and then publish. Feedback from users is that this is a clunky user flow with more steps than they would expect. 

### Acceptance criteria 
When a user selects the Preview option, they are directed to the preview page where they can view the content as it will display on the published page. 
From this page, they are able to either publish that content OR return to the editing page. 

Note that currently the publish option only exists once a user has saved the content. Ideally, a user would be able to publish directly from preview, and this would trigger a workflow to both save and then publish that content.

**Comment by colinmurphy01** [comment]
@greg-does-weather are you working on this now?

**Comment by greg-does-weather** [comment]
We're closing this one as... either impossible or very difficult. We discussed at design/dev sync today. While having the save and publish buttons on the preview page would be ideal, it's not really practical for us right now.

We may look into whether we can get an embedded preview on the edit page and that would resolve the issue very nicely, but that's a nice-to-have for now.
