### ISSUE TITLE
Update timezones within Drupal

### ISSUE THREAD

**Issue by kmranjo** [weather-gov/weather.gov#1202]
### Current state 
The default time zone options for any configuration within Drupal reflect a long list of locations, but not the standard time zones that users are used to seeing. 

### Acceptance criteria
Default time zone options within Drupal should reflect the most frequently used options: 
- Coordinated Universal Time (UTC)  (aka Zulu time)
- Alaska (UTC-8)
- Aleutian (UTC-9) 
- Arizona Mountain Standard (UTC-7)
- Central (UTC-5)
- Eastern (UTC-4)
- Hawaii (UTC-10)
- Mountain (UTC-6)
- Pacific (UTC-7)
- Samoa (UTC-11)

Source: [time.gov](https://www.time.gov/)

**Comment by eric-gade** [comment]
@kmranjo Do we want to display the UTC offsets in the dropdown list? I ask because depending on the time of year, these are going to be different. For example, Alaska is currently in Alaska Daylight Time (UTC-8) but later on will be in Alaska Standard Time (UTC-9)

**Comment by kmranjo** [comment]
Dangit, I totally forgot about daylight savings (as I usually do). I think
if we CAN include the UTC offsets then thats helpful to the user, but it's
a nice-to-have and not necessary. I think generally they'll know what time
zone they need to be selecting based on where they are publishing for/from,
so the specific UTC offset is maybe just a reminder when we do hit DST.


*Katrina Ranjo* (she/her)

Content Design, 18F

Technology Transformation Services
