### ISSUE TITLE
Streamline save and publish process

### ISSUE THREAD

**Issue by kmranjo** [weather-gov/weather.gov#1205]
### Current state 
To publish content, a user must: 
- Create or modify the content in edit mode 
- Click Save from edit mode and be directed to a static view of the content (not the more useful actual preview) 
- Use the navigation to return to the Manage Content screen
- Select the Edit option for that content from the Manage Content screen and be directed to the Edit view for that content
- From the Edit view, scroll down to select Publish 

This is a convoluted flow with some unnecessary steps. 

Related: #1201

### Acceptance criteria 
To publish content at a later date, a user must: 
- Create or modify the content in edit mode
- Click Save from edit mode. They remain on the page in edit mode, but see a banner that confirms the content was saved. 

AND

To publish content, a user must: 
- Create or modify the content in edit mode
- Click Publish from edit mode and trigger a workflow that automatically saves and then publishes the content 

### Steps to complete
- [x] Design to confirm the desired user flow for these actions
- [x] Eng to confirm the desired flow is possible 
- [ ] Updates made to the process

**Comment by kmranjo** [comment]
Discussed with design last week, and aligned on approach. However, its description would change a little based on the other workflow items being discussed in #945. Should we move forward with this now and update the process twice? Combine these changes all in one? 
@colinmurphy01  I'm not sure if these are product questions or eng questions.

**Comment by colinmurphy01** [comment]
Let's chat with engineering on this to see how they'd like to break this work up into chunks. Both are equal priority and important iterations to implement in this round of CMS improvements.

**Comment by kmranjo** [comment]
Moving this to Doing because design has been working on it for over a week now (sorry, will keep better track of tickets!) 
Flows and their changes are outlined [in this doc](https://docs.google.com/document/d/1kVa7uiDI8hzdWdD80IL-DwjSIoeGDArVUVYHxhxgvQ8/edit?usp=sharing) and we'll be creating more tickets based on that soon.

**Comment by kmranjo** [comment]
I think the original intent of this ticket (which moved around a couple times through all the workflow convos) is satisfied by #1266. Should we close this one?
