### ISSUE TITLE
Create "owner" role and adjust "system admin" role

### ISSUE THREAD

**Issue by kmranjo** [weather-gov/weather.gov#1216]
Decisions coming out of the last conversation with partners about the system admin role uncovered the need for a higher role in the system to allow greater oversight of the system admin team, and ensure that system admins don't have access to anything that they shouldn't. 
[Notes captured here ](https://docs.google.com/document/d/1EFFY5OOL89vBD7T4DSQ58DXqCfcC0hmXLB2wWjY_1Iw/edit?usp=sharing)

### Current state 
Full outline of current roles is captured [in this document](https://docs.google.com/document/d/1cqM9sU6O2fbAONCDbv8cAmzCm262F5jUR-r_CwN2vQ0/edit?usp=sharing)

Currently the System Admin role is simply a renaming of the default Admin role. They have access to all actions and all items, both content and configuration. 

### Updates needed coming out of that meeting 

1. The current System Admin role should be renamed as Owner. This is still the default role in the system that has all access. 
2. A new role should be created called User Admin (previously System Admin, but changed because this could be misleading). This role should be able to: 

- Assign users to any role _except_ System Admin and Owner
- Assign users to editorial sections 
- Run system reports 
- Access the Files Overview page 
- Delete any file 
- Use the Basic HTML text format
- Use help pages
- Administer meta tags 
- Perform actions for node content (View, Create, Delete, Publish, Unpublish, Schedule, Modify, Revert)    
- Access the Content Overview page 
- View all content, regardless of publication status 
- Perform all actions related to taxonomy 
- Use the toolbar

**Comment by loganmcdonald-noaa** [comment]
I've created the role in design, and we should go through and together make sure all the permissions are appropriate for the role and then export everywhere and do an audit of current users.

**Comment by kmranjo** [comment]
@loganmcdonald-noaa I've updated the permissions for that role in Design. If it looks good to you, then I think its ready to export.

**Comment by loganmcdonald-noaa** [comment]
Thanks! I've updated a PR with all the configuration changes you've made: https://github.com/weather-gov/weather.gov/pull/1377

**Comment by loganmcdonald-noaa** [comment]
This is done (merging into staging) - we will likely iterate on the permissions for these roles over time but the base roles are setup.
