### ISSUE TITLE
All project documents have been successfully transferred over to NOAA Drive

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#1219]
- [x] Engineering - @greg-does-weather 
- [x] Design
  - [x] Content - @kmranjo 
  - [x] Product - @igorkorenfeld  
- [x] Research
- [x] Product - @colinmurphy01 
- [x] Project - @colinmurphy01 

`Process`
- Provide your NOAA account access to the GSA Doc
- Using your NOAA account, duplicate the doc (and host it within the [Core Team folder](https://drive.google.com/drive/u/0/folders/1oWHi4hdNdfsq_6TF4jtE_xWyK4hCGPOq) or any subfolder in the NOAA drive 
- Confirm the doc was successfully created by your NOAA account
- Using your GSA account
    - edit title of doc with `ARCHIVE` in the front
  - copy/paste [this archive front matter](https://docs.google.com/document/d/1uRGtN5YWBHYPqQzZL3u7ekeFyvdlSTSXk73-_7GRXus/edit#heading=h.xpp46xdc0nte) at the top of the document
  - Save it as a `custom building block` (insert > building block > create custom) for future use
- Once everything is done move the old file into this [Archive Folder](https://drive.google.com/drive/folders/12Jn6wjLZeV37rw4DOmM2DFQMkF_YOClQ?usp=drive_link) where everyone's permissions are view only

**Comment by kmranjo** [comment]
Content documents have been moved over to the noaa drive

**Comment by colinmurphy01** [comment]
@greg-does-weather who is taking the lead with transitioning engineering documentation?

**Comment by colinmurphy01** [comment]
Once docs have been successfully copied over. 

Instead of moving them into `trash` move them into this [Archive Folder](https://drive.google.com/drive/folders/12Jn6wjLZeV37rw4DOmM2DFQMkF_YOClQ?usp=drive_link) where everyone's permissions are `view only`
