### ISSUE TITLE
Scope: Visualizations

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#1236]
- [ ] Draft doc with context
- [ ] Brainstorm with design, product type of visualizations / use cases
- [ ] Prioritize use cases

https://docs.google.com/document/d/17tRHNkKxBU2Dy28SzjSbYWd6DsqFm_jpbMak4mKyuag/edit

**Comment by sarahmhgov** [comment]
@colinmurphy01 Realized never chatted about this - this is ready for an initial product review / conversation when the team is ready.

**Comment by colinmurphy01** [comment]
@sarahmhgov @partly-igor can we add this to our Design/Product review agenda (today or tomorrow)?

**Comment by sarahmhgov** [comment]
sure!

**Comment by sarahmhgov** [comment]
Reviewed initial draft with product 8/1, pulling back into doing to add some details to the scope
