### ISSUE TITLE
Design: AFDs

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#1238]
Example: https://api.weather.gov/products/f1e486ae-c001-491a-80f3-0cc6b4d5cca6

**Comment by colinmurphy01** [comment]
Recommendation for design from product

- We would ignore anything after the $$
- We should accommodate the tables for now, but look into policy/content strategy suggestions there

**Comment by coreypieper** [comment]
@partly-igor, here is the "main" AFD directive (section 2): https://www.weather.gov/media/directives/010_pdfs/pd01005003curr.pdf

CR supplement: https://www.weather.gov/media/directives/010_pdfs/pd01005003c102023curr.pdf
ER supplement: https://www.weather.gov/media/directives/010_pdfs/pd01005003e102004curr.pdf

**Comment by partly-igor** [comment]
Ready for implementation, added #1475 for engineering
