### ISSUE TITLE
Prototype: Satellite

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#1240]
- Using GOES, WFO WCA images https://www.star.nesdis.noaa.gov/GOES/wfo_index.php
- Place under radar on `Current` tab

**Comment by colinmurphy01** [comment]
Assigning to us in product to get this clarified with NESDIS

**Comment by colinmurphy01** [comment]
[Slack thread](https://gsa-tts.slack.com/archives/C05DU11D4J2/p1718653753820449)

- I think we just need to know which WFOs are serviced by GOES18 and which are GOES16
- Which products we should start with, based on NESDIS recs

**Comment by colinmurphy01** [comment]
Email sent

**Comment by colinmurphy01** [comment]
@greg-does-weather did we meet with NESDIS last week?

**Comment by greg-does-weather** [comment]
No. We've got an email thread started with them and an invitation to schedule time, so maybe we can do it next week.

**Comment by colinmurphy01** [comment]
@greg-does-weather is this unblocked now?

**Comment by greg-does-weather** [comment]
I guess we can use the JSON to figure out whether to use GOES16 or 18 which resolves the original blocking issue, but I'm not sure there's anything to prototype. It seems like satellite is ready for research/design/product?

Noting here so I don't lose the URL in the future, those JSON files use a lowercase WFO code, like so for MPX:
https://cdn.star.nesdis.noaa.gov/WFO/catalogs/WFO_02_mpx_catalog.json
I'm not sure which field(s) in there tell us explicitly whether to use 16 or 18, but in the worst case we can figure it out by parsing one of the static image URLs, or we could ask the satellite team to include a link to the gif.

**Comment by colinmurphy01** [comment]
@partly-igor @shadkeene @coreypieper Greg has a good point that this should be ready to design and build. There isn't much more to learn from an engineering perspective.

My question to you all is, would it be beneficial or an issue if we shipped Greg's prototype to production (updated with the added logic)?

**Comment by shadkeene** [comment]
heck yes!!! go for it!  @colinmurphy01 @greg-does-weather @coreypieper @partly-igor

**Comment by partly-igor** [comment]
@greg-does-weather would you mind deploying it to your env (or design) before we release? I want to take a look from design perspective

**Comment by greg-does-weather** [comment]
@partly-igor https://weathergov-greg.app.cloud.gov/point/44.998/-93.156?

Note that it currently only works for the parts of the country served by GOES 16, so if you go to other locations and see nothing, that could be why.

**Comment by greg-does-weather** [comment]
@colinmurphy01 @shadkeene From just an engineering perspective, yes, I think we can.
