### ISSUE TITLE
Metrics plan and PRA considerations

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#1250]
- Finalize goals and metrics plan
- Identify new public questions in order to pursue PRA approval

Dependency #1298

**Comment by coreypieper** [comment]
Need some clarification on this one.

**Comment by colinmurphy01** [comment]
I'm not able to get started on this yet. Let's move this back to the backlog for next sprint. 

CC @shadkeene @coreypieper

**Comment by colinmurphy01** [comment]
Dependency #1298

**Comment by sarahmhgov** [comment]
@colinmurphy01 confirming next steps are: 

- Email PRA folks for transparency / to confirm we can use the questions in our proposed way
- Implement in touchpoints

**Comment by colinmurphy01** [comment]
@sarahmhgov yeppers

**Comment by colinmurphy01** [comment]
Documented recommendation in [this spreadsheet](https://docs.google.com/spreadsheets/d/16IXMjLwqRC2Tx_VnFCR6UGzh91Ym5QYAnfdhp5XO-Us/edit?resourcekey#gid=2106559186)

**Comment by colinmurphy01** [comment]
@sarahmhgov CC me on the email to the PRA folks when you get around to it

**Comment by sarahmhgov** [comment]
PRA team is cool with it

**Comment by colinmurphy01** [comment]
@colinmurphy01 will find time to share out and align.
