### ISSUE TITLE
Add additional weather variables to current conditions 

### ISSUE THREAD

**Issue by partly-igor** [weather-gov/weather.gov#1252]
### Description
As part of #975 we discussed other weather variables to add to current conditions to provide users with additional information about the current weather.

The variables that should be displayed are:
Wind (mph and rotated icon)
Gusts (mph)
Humidity (%)
Dewpoint (°F)
Visibility (miles)
Pressure (in. and mb)

[Documented design](https://www.figma.com/design/0dSABt9zCqoknaKua6DHmP/NOAA---Weather.gov?node-id=6045-63587&t=OcaqUGLQywzuqngk-1) 

### Acceptance Criteria
- [ ] Variables are added to current conditions
- [ ] Gusts row displays only when data is available
- [ ] If data is not available for any other variable display "N/A"
- [ ] Implementation follows visual design for mobile and tablet+

**Comment by greg-does-weather** [comment]
closed by #1285
