### ISSUE TITLE
WFO / Org comms and engagement strategy

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#1283]
- How can we clarify the short-term and long-term questions
- When and How can we engage all NWS offices to make sure they feel heard (considering all of the other things happening)
- How can we earn good will / support

**Comment by colinmurphy01** [comment]
Blocked by #1304

**Comment by shadkeene** [comment]
Are we still blocked here?  I think webinars will help move these goals forward.

**Comment by colinmurphy01** [comment]
I think this is `done`?
