### ISSUE TITLE
Assess remaining hazard products as candidates for dynamic safety info

### ISSUE THREAD

**Issue by kmranjo** [weather-gov/weather.gov#1286]
Generated from #1082

Products still to be assessed are listed as TBD in [this spreadsheet](https://docs.google.com/spreadsheets/d/1vVtI5lARcPPscvm2BgTLXguHwEScSytJsafa9JHhFHU/edit?usp=sharing)

Acceptance criteria:

- [ ] Determine which products make sense to have dynamic safety info in the CMS
- [ ] Group the selected products by type
- [ ] Create tickets for each group to create dynamic safety content for them

**Comment by colinmurphy01** [comment]
@kmranjo is this work still open?

**Comment by kmranjo** [comment]
Yes, we have assessed all the main products but haven't started to take on some of the other categories (like Marine) or types (like statements)

**Comment by colinmurphy01** [comment]
I'll close this then.
