### ISSUE TITLE
Design: WFO Page

### ISSUE THREAD

**Issue by kmranjo** [weather-gov/weather.gov#1287]
Generated from #1169

Primary purpose: Humanize the NWS staff and their role in their communities 
Secondary purpose: Provide a consistent, reliable and centralized space for contact information and resources from a WFO

[Content model & governance](https://docs.google.com/document/d/1s6bAjY1wwyOst3O2mlb2u-WCz4WnoRKruiybVFImYmc/edit?usp=sharing)

Open questions: 
Does the new ops model impact how we’re thinking about WFOs and how products and other content is currently distributed by CWA?

Acceptance criteria: 
- [x] Address open questions 
- [x] Outline content strategy for initial version of these pages
- [x] Design WFO page template 
- [x] Product review
- [x] ENG review
- [x] Create tickets for build

**Comment by colinmurphy01** [comment]
Blocked by #1293

**Comment by kmranjo** [comment]
@colinmurphy01  I think we have enough of #1293 done for this one, but the ticket as a whole is still waiting on direction for the other content types. Does that sound right?

**Comment by colinmurphy01** [comment]
For V1 we should descope:

- Decision support materials until we get a sense of NWS Connect / DSS Builder timeline
- Upcoming events are also their own thing and moreso align with #1239 for public events and NWS Connect for partner events

**Comment by partly-igor** [comment]
We decided this was going to be the ticket for designing the page after feedback and that wireframes would be part of #1341

**Comment by partly-igor** [comment]
Ready for implementation, broken up into a few tickets:
#1469 
#1470 
#1471 
#1472 
#1473 
#1474
