### ISSUE TITLE
Scope translations prototype

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#1289]
We need to understand:

- Highest priority products and copy to translate
- Get access to Lilt's services and endpoints for the test
- Design a test in order to control and assess cost (by time, location)

**Comment by loganmcdonald-noaa** [comment]
Noting that Lilt has this integration: https://support.lilt.com/kb/drupal

It leverages this module: https://www.drupal.org/project/tmgmt

**Comment by colinmurphy01** [comment]
https://docs.google.com/document/d/1wlqjabosLPVsaskvHIZ48Ics8FdHeO4eXjvrVXwyLTs/edit

**Comment by loganmcdonald-noaa** [comment]
Is this still blocked? Are we good to close with the new plan?

**Comment by colinmurphy01** [comment]
Yes, thank you

**Comment by colinmurphy01** [comment]
Near-term work:
- #1346 
- #1347 
- Discussion with API team

Long-term:
- Mod to test Drupal integration with Lilt
- Translations + API
