### ISSUE TITLE
Identify path for including enhanced wording/details for thunderstorms in shortText (and maybe hourly too?) Connected to #1160

### ISSUE THREAD

**Issue by shadkeene** [weather-gov/weather.gov#1290]
As a follow-on to #1160, in the current forecast.weather.gov, intensity/severity wording is including in the icon description like the image below. 
![image](https://github.com/weather-gov/weather.gov/assets/139174561/63cd6d3e-cf52-4bfe-abe7-575406e8f02d)

In the API, this type of wording, at least for thunderstorms, is not included.  For things like "snow" heavy is appended, so the shortForecast shows "heavy snow" but for thunderstorms, it just describes as below, for the same point where "severe thunderstorms" is used in forecast.weather.gov.  
![image](https://github.com/weather-gov/weather.gov/assets/139174561/14e05154-03a0-4824-bd2b-46c915617074)

Forecasters can add lots of detail (manually or automated via forecastbuilder), like "thunderstorms" + large hail or "thunderstorms" plus damaging winds or "thunderstorms" plus heavy rain, and we'll want some of this detail to be included in the shortText that accompanies the hourly or AM/PM forecast.  There are a several things we need to do:
1. Identify all potential enhanced wording options for thunderstorms.
2. Prioritize what wording should be included in shortText and perhaps investigate current logic in forecast.weather.gov.
3. Determine how many characters can/should be included in shortText (hourly too?)  so it fits with beta.weather.gov design.

**Comment by colinmurphy01** [comment]
Is this related to #1160

**Comment by shadkeene** [comment]
Yeppers.  It is.  It's kind of the next steps, actions, for the 1160 observation.  I'll add 1160 to the description.

**Comment by colinmurphy01** [comment]
Roger. When you add those details please close this out.

**Comment by colinmurphy01** [comment]
@shadkeene following up on this. I see we have #1160 documented and in `blocked` while we confirm next steps with API team.

Should we close this or is this a separate task for the API team?

**Comment by shadkeene** [comment]
closing this and ensured part of this content put in 1160.
