### ISSUE TITLE
Content Strategy: Feedback Wireframe

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#1293]
Once #1169 and #1292 done, let develop a site map / content model to demonstrate the organization and flow of our content strategy in order to get feedback from Forecasters, Regions, and other Stakeholders

[Mural has artifacts for review](https://app.mural.co/t/gsa6/m/gsa6/1718740968145/1ac9d1f4d0604802e9be39f09f8bd56a0d3aaa1f?sender=u577f2fee72a47ad519ae8698)
Includes: 
- Content strategy for 4 content types to support forecaster expertise epic 
- Expanded sitemap 
- Content models for 2 of those content types

**Comment by kmranjo** [comment]
Pieces of this are ready for review - the only gaps are around the historical content, which may be addressed in tomorrow's meeting. Will discuss the ready pieces in PO/ENG sync today

**Comment by kmranjo** [comment]
@colinmurphy01  We have several tickets coming out of this: 
#1238 
#1291 (which might be a duplicate of #1287) 
#1231 
#1234 
#1295 

Is that everything? I think the only pieces that don't have clear steps outlined are the event recaps - we still need more information on these, unclear if we have alignment on them coming out of that meeting. Should I just keep that under the umbrella of this ticket for now?

**Comment by colinmurphy01** [comment]
This will be for the Figma prototype, when it's `done` and ready for R6.

**Comment by colinmurphy01** [comment]
I believe this is `done`
