### ISSUE TITLE
Add expand button to radar map

### ISSUE THREAD

**Issue by partly-igor** [weather-gov/weather.gov#1309]
### Description
Through Touchpoints and individual conversations we've heard that users can get stuck scrolling the radar when they want to scroll the page on mobile devices. This is because the radar and the site both allow scrolling, and the map can takes up the entire screen at certain points. To resolve the issue we've decided to:
1. Change the starting height (and thereby the aspect ratio) 
2. Add a button to expand/shrink the radar map 

[Figma Prototype](https://www.figma.com/proto/w2QI2uTgaTWUPLHLi40mm1/Weather.gov-%E2%80%93-v0.2?page-id=8510%3A184114&node-id=8530-192779&viewport=882%2C468%2C0.2&t=ZshdVhXSZjHA3GZG-1&scaling=scale-down&starting-point-node-id=8530%3A192779)

[Documentation](https://www.figma.com/design/w2QI2uTgaTWUPLHLi40mm1/Weather.gov-%E2%80%93-v0.2?node-id=8735-44604&t=W3iiiU3sNhTv1h0E-1)

Note that there is currently no USWDS icon for map zoom-in, only zoom-out. I've created the [icon](https://drive.google.com/file/d/1hz-pATlz9JTBiYzTcZseALS4KlkPpNSK/view?usp=drive_link) we should use in the expanded state (the collapse/zoom-in icon). 
### Acceptance Criteria
- [ ] On mobile the map takes up the full container width, and starts with an aspect ratio of 6/4 (width/height)
- [ ] On mobile the map  takes up the full container width and expands to an aspect ratio of 3/4 
- [ ] On tablet+ the starting ratio is 3/2. 
- [ ] On tablet+ the expanded ratio is 1/1
- [ ] The tablet+ width of map stays as is now – taking up the full container on tablet, and limited to 8 columns on tablet-lg. 
- [ ] The expand/collapse button follows the styling for the different states outline in the documentation 
- [ ] The expand/collapse button is sticky

**Comment by colinmurphy01** [comment]
Related/Blocked by #1345

**Comment by greg-does-weather** [comment]
This seems small and portable enough to be worth pursuing now, so we're gonna.
