### ISSUE TITLE
As a developer, I can make changes in Github that are reflected on the site (and I fully understand this process)

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#133]
Acceptance criteria
- [ ] Document and implement a developer experience for CI/CD pipeline for prototyping

Related ticket #98

**Comment by colinmurphy01** [comment]
Trying to clean up tickets, what should we do with this one?

#98 is the ADR, do we use that as the main ticket and close this? We likely will spin up smaller ADRs.

**Comment by greg-does-weather** [comment]
I wonder if we want to change this issue to something like, "As a dev, I can make changes in GitHub that are reflected in a (test|staging) environment." That'll cover the CI/CD work we can do today, and we can address the production part whenever we settle on a production environment. What do you think? The body of the issue already looks good, though.

**Comment by colinmurphy01** [comment]
Closing. We understand the process as is CF push. We'll clarify when we have a prototyping org setup in cloud.gov.
