### ISSUE TITLE
Add gusty winds icon in daily/hourly forecast when winds reach a certain threshold.

### ISSUE THREAD

**Issue by shadkeene** [weather-gov/weather.gov#1338]
This ticket is probably related to #1290, in that we want either icons or wording to key in on severity or key message, pending what conditions are in the forecast.  For this case, someone providing feedback noted that winds were gusting to 30 mph but there was no "windy" icon in beta.weather.gov.  We need logic to identify when to use the "windy" icon. There will be many other cases for this too.   

User story: I want to quickly identify a windy day/hour based on a windy icon showing up when a certain wind threshold is met.

Considerations:
- This icon should show up in hourly
- This icon may or may not need to show up in daily

Dependency
- Why aren't we consistently receiving gusts

_Feedback ID: 5853420. I see gusty winds up to 30 mph in the upcoming forecast for Monday, however there is no windy icon to go along with the sunny icon. There is also no mention of windy conditions in the hourly forecast. Hopefully this will be added soon._

**Comment by colinmurphy01** [comment]
Wind gusts seems to be working, but there is discussion around adjusting icons to better communicate conditions.

We will monitor feedback this and reprioritize if needed.

**Comment by coreypieper** [comment]
I did notice a little something about the wind ones.  It doesn't look like we differentiate sky cover in windy icons. For example, when the API has "https://api.weather.gov/icons/land/day/wind_few" ("few" attempting to ID the sunny conditions accompanying the wind) as an icon, we use "spritesheet.svg#new_windy_cloudy". So we should do some work to align the sky cover noted in the api's windy icons.

**Comment by colinmurphy01** [comment]
I think we need to revisit this in API sync next week.

Rereading this and realizing it's less about seeing gusts in hourly and more about the gust icon showing up.

**Comment by colinmurphy01** [comment]
This ticket can be closed. This is performing as expected.

CMS has default settings and a place where WFOs can configure forecast thresholds for copy/icons

Sustained defaults:

- Windy = 30 mph
- Very windy = 45 mph

Gusts default:

- At least 18mph, w/ 3mph difference for gusts to be noted

CMS configurations across WFOs are very different, examples:

- Great falls has 30, 45, 3mp difference
- Billings 26, 42, 5mph difference (minimum is 35)

https://docs.google.com/spreadsheets/d/1aXmBqXtAMGYISZP1Ld6KiVLL0oFyKp5TRZvcBFZB1mI/edit?gid=1149500459#gid=1149500459
_Red means varies from default value_

To-do: API team will add a row noting which columns impact the API

In legacy they support a glossary for weather terms/definitions/thresholds
