### ISSUE TITLE
Github Documentation: Research Summaries

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#1395]
Goal: be able to better communicate what we are learning, what type of research we're doing, top insights

Audience: Internal NWS, GSA leadership

For each research study: 

- [ ] When 
- [ ] Description of what the research was, who we engaged with
- [ ] What we learned

No need for links to outputs

https://docs.google.com/document/d/1oeJ7w2nBBKY7QHFe8IyYou9F4bUnM2NBfMLlqzNGkmQ/edit#heading=h.n0mlbya2g5vq

**Comment by sarahmhgov** [comment]
https://github.com/weather-gov/weather.gov/pull/1566

**Comment by colinmurphy01** [comment]
Add suggestions to PR and approved

**Comment by sarahmhgov** [comment]
Made updates, I think its done

**Comment by colinmurphy01** [comment]
Agree and I think we should ship it. 

One last thought would be to add the color indicators to the internal research round as well.

I updated the PR's branch. When you're ready, go ahead and merge.
