### ISSUE TITLE
Manual save of favorite locations. 

### ISSUE THREAD

**Issue by coreypieper** [weather-gov/weather.gov#1399]
This ticket is meant to track desires expressed in external (TouchPoints) survey feedback to have the ability to manually save favorite forecast locations (like old mobile.weather.gov site).

**Comment by greg-does-weather** [comment]
I think this will cover what's in #815 as well.

**Comment by colinmurphy01** [comment]
Moving this to `Next` not a priority for the next couple milestones, but would likely be batched into a V2 Search Epic / Milestone

**Comment by colinmurphy01** [comment]
duplicate of #815
