### ISSUE TITLE
Addition of wind direction acronym/abbreviation to hourly table

### ISSUE THREAD

**Issue by coreypieper** [weather-gov/weather.gov#1400]
A number of external comments have requested the addition of wind direction abbreviations alongside the arrows (e.g. SSE).

**Comment by shadkeene** [comment]
Consider changing arrow to one with a longer stem.

**Comment by coreypieper** [comment]
like this: 
![Screenshot 2024-07-03 at 12 51 13 PM](https://github.com/weather-gov/weather.gov/assets/4570239/8ba8a6c8-306d-4c10-82a4-3a994374b0dc)

**Comment by colinmurphy01** [comment]
We will also look into changing the arrow icon as part of this.

**Comment by partly-igor** [comment]
Design has been reviewed, and ready for implementation. Ticket #1445 for engineering.
