### ISSUE TITLE
Displaying distance to and elevation difference of observation and forecast location

### ISSUE THREAD

**Issue by shadkeene** [weather-gov/weather.gov#1403]
Feedback from a user: _I liked that as I travel to locations and look at weather (Denver, Florida, etc), elevation is important for hiking and understanding oxygen levels._

If clear to the user, it is often helpful important to display the elevation of the forecast a user is looking at AND the elevation of the observation that is displayed.  This is especially important in mountainous areas.  It will be a challenge to make sure the user understands (if we are showing two elevations) which elevation is for the forecast point and which elevation is for the observation location.  We did explore earlier the "learn more about this observation" to show metadata, like elevation, for observations.  

Considerations:
- Show actual elevation of observation
- Show distance between observation point and Forecast point (find my location or average in zip code)

Implementation consideration:
- Consider signaling approximate distances

**Comment by colinmurphy01** [comment]
Confirmed that elevation data is available for:
- Observation station
- Grid (Forecast)

Consideration for design:
- Display observation elevation
- Display forecast elevation
- Display difference in elevation from observation?

**Comment by coreypieper** [comment]
In addition to elevation, **distance** to the observation location is desirable for the same reasons.

**Comment by colinmurphy01** [comment]
Chat with MC about this for thoughts.

**Comment by colinmurphy01** [comment]
We should consider adding tool tip or help text. @kmranjo

**Comment by partly-igor** [comment]
Implementation ticket #1831  added for engineering
