### ISSUE TITLE
Trouble splitting counties in hazard map/Inland and Coastal Harris County TX example

### ISSUE THREAD

**Issue by shadkeene** [weather-gov/weather.gov#1409]
We received some detailed feedback about a hazards that was showing up as partial county coverage (likely a forecast zone that is just part of a county), and beta.weather.gov hazard map didn't show any of the county as being affected by the hazard.  Harris County is shown here: 
![image](https://github.com/weather-gov/weather.gov/assets/139174561/26f797ef-25de-4f3d-b483-b7ba437d18d6)
Here's what the partial county looked like (look at the Houston area).
![image](https://github.com/weather-gov/weather.gov/assets/139174561/37c43cb0-9f74-4f3a-9314-765fa3ad7b1c)

And here's what beta showed.
![image](https://github.com/weather-gov/weather.gov/assets/139174561/3f8dfe89-bfef-46b6-91a1-4a9c8d66be04)

The person sharing the feedback thought it was odd because beta seems to be handling another "partial county" in that only "Northern Liberty" county was being displayed, and this was correct on beta.

**Comment by greg-does-weather** [comment]
[bundle_1720195119717.zip](https://github.com/user-attachments/files/16111742/bundle_1720195119717.zip)
