### ISSUE TITLE
Tropical cyclone icon is "spinning" in the wrong direction. 

### ISSUE THREAD

**Issue by coreypieper** [weather-gov/weather.gov#1410]
From SME: "I was looking at the beta site this evening now that hazards have been issued for Beryl.  I noticed that the symbol you are using for tropical storm/hurricane implies turning in the wrong direction for the Northern Hemisphere.  See the attached screenshot from the beta site versus the typical [tropical storm symbol](https://www.istockphoto.com/vector/whirlwind-sign-tornado-hurricane-hurricane-storm-white-background-vector-illustration-gm972710244-264760539) for the Northern Hemisphere."

I've attached a screenshot from beta illustrating the issue.
<img width="564" alt="Screenshot 2024-07-05 at 9 53 44 PM (1)" src="https://github.com/weather-gov/weather.gov/assets/4570239/3464c82c-9692-48d4-ba79-47af9fd757a0">

**Comment by colinmurphy01** [comment]
We'll replace the current cyclone file with a mirrored icon.

Note: American Samoa may have use cases where a cyclone is spinning in the opposite direction, but we believe that those use cases are small and the cyclone icon will still communicate the necessary information.

**Comment by igorkorenfeld** [comment]
Updated Icon
![hurricane-counter](https://github.com/user-attachments/assets/5956f506-b293-4895-9913-2148979dc6b8)

**Comment by partly-igor** [comment]
Counter clockwise icon

![hurricane-counter](https://github.com/user-attachments/assets/b280199f-763a-42f5-bf15-32d67487834b)
