### ISSUE TITLE
Research: Reusable WFO content

### ISSUE THREAD

**Issue by kmranjo** [weather-gov/weather.gov#1422]
Coming out of the conversation in #1414, the team aligned on doing a research spike to look into solutions for reusable content, specifically for the WFO information. 

It's understood that the solution will likely impact the current WFO promo, and the team is open to doing the rework for that component/content type. 

### Desired public experience

A user coming to the website can see information about a given WFO display consistently across different locations on the site. They can also see the WFO page load seamlessly with much of that information included in it. 
Example: 

1. I go to my point forecast page. At the bottom of the 7-day forecast, I see the WFO promo for my office and it includes the office phone number. 
2. I click on the link in that component and am directed to the WFO page. There, I can see a lot of information about the office, including the same phone number I saw before. 
3. I click on the county finder, and use it to find my county. 
4. I'm directed to the county page. I see county-specific information there, as well as a promo for my WFO with the same phone number. 

### Desired authoring experience 

A stakeholder in charge of maintaining the content for a WFO is able to author all information about a WFO in one place, regardless of where it may appear on the site. 
Example: 

1. The phone number for my WFO has changed. I log in to the CMS and navigate to the set of information for my WFO.
2. I update the phone number, and save and publish the change. 
3. When I view that phone number on the front-facing site, on the point forecast page, WFO page, county pages, or other locations, I can see that all spaces it appears are displaying the updated phone number. 

Acceptance criteria
- Documented strategy
- Implementation tickets

Ideally preserving content within beta right now, would be ideal

**Comment by loganmcdonald-noaa** [comment]
This looks good! Thanks for putting together.

**Comment by colinmurphy01** [comment]
Might bleed over into next sprint with the translations work still in progress

**Comment by eric-gade** [comment]
[Link to the figma with the potential data sections](https://www.figma.com/design/w2QI2uTgaTWUPLHLi40mm1/Weather.gov-%E2%80%93-v0.2?node-id=9942-4943&t=vX6pzHVfmYJxkin4-0).
  
These appear to include:
* All WFO promo fields
* About text
* Local expertise links (dynamic list)
* An image
  
The rest of the items on that page (forecaster discussion, map, etc) can be retrieved dynamically and are not directly authored anyway

**Comment by eric-gade** [comment]
The following tickets stemming from this issue have been created:
* https://github.com/weather-gov/weather.gov/issues/1469
* https://github.com/weather-gov/weather.gov/issues/1470
* https://github.com/weather-gov/weather.gov/issues/1471
* https://github.com/weather-gov/weather.gov/issues/1472
* https://github.com/weather-gov/weather.gov/issues/1473

**Comment by greg-does-weather** [comment]
With the creation of the subsequent issues, this one is now closed.
