### ISSUE TITLE
Touchpoints button covers up links on mobile

### ISSUE THREAD

**Issue by partly-igor** [weather-gov/weather.gov#1424]
### Description

When scrolling to the very bottom of a page the touchpoints button covers up the last few links in the identifier/footer on certain mobile devices. You cannot scroll any further to see them. See the screenshot below taken on an iPhone 14

![Screenshot of touchpoints button covering up links in footer](https://github.com/weather-gov/weather.gov/assets/150970973/26c37271-6eee-43a5-be14-ba5115e1b0e7)

- [ ] Touchpoints button doesn't cover up any links at the bottom of the page. 
- [ ] Tests have been implemented or modified to capture the bug
- [ ] Changes have been tested for accessibility

**Comment by colinmurphy01** [comment]
Add 3 units of padding at the bottom to accommodate.

**Comment by greg-does-weather** [comment]
Closed by #1464
