### ISSUE TITLE
Add a Home button to the alerts.weather.gov page

### ISSUE THREAD

**Issue by swallace100** [weather-gov/weather.gov#1432]
### Description
As a user, I would like a Home button on the alerts.weather.gov page so that I can easily navigate back to the homepage once I am done looking up alerts.

### Questions and Considerations
Right now when a user goes to the alert.weather.gov page, there is no clear way to return to the home page without pressing the browser back button. I was conducting heuristics testing as part of a school assignment and discovered that users become stuck on this page once clicking on it. A Home button would be a simple way to solve this problem.

### Acceptance Criteria
- [A Home button is on the alerts.weather.gov page]

**Comment by greg-does-weather** [comment]
Hi @swallace100! Thanks for this feedback. This repo is for a new weather.gov so we'll make sure to keep this in mind as we build the new site. In the meantime, we'll pass this along to the team that maintains alerts.weather.gov.
