### ISSUE TITLE
Radar zoomed out by default

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#1438]
### Description

With #1426 closed it seems in staging 
- the map is zoomed out by default
- the marker is not present 

![Screenshot 2024-07-15 at 4 57 11 PM](https://github.com/user-attachments/assets/3c97dc35-9d9d-4c8a-ae54-c7616318f3b5)

### Acceptance criteria

- [ ] map is zoomed to corresponding location
- [ ] map marker is present
- [ ] Tests have been implemented or modified to capture the bug
- [ ] Changes have been tested for accessibility

**Comment by greg-does-weather** [comment]
Blocked pending conversation with @scadergit. We previously hacked together a way of getting the map to mark a location by forcibly using the CMI store's `dispatch("markLocation", [point])` method, and while I can see that is still being dispatched, it doesn't seem to be causing anything to happen.

Additionally, the `settings.map.zoom` and `settings.map.center` options don't seem to be working anymore. Presumably these changed in the last big CMI release, so we'll need to coordinate with Jared to understand how that works now.
