### ISSUE TITLE
Document methods to improve dependency handling and comms with NWS components

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#1446]
When major releases are deployed across our dependent NWS libraries or services, we don't have awareness of the changes to expect and they are often forced on us right away.

There are common practices that an mitigate this problem, we'd like to document those recommendations and bring them to the various teams as commitments that systems must uphold.

**Comment by greg-does-weather** [comment]
Draft: https://docs.google.com/document/d/121ljYPqKMH-HFuWHzLYXTx78T3B5tbuIOyAVInrUaeA/edit. Getting feedback from other engineers before sharing widely

**Comment by greg-does-weather** [comment]
I dropped the ball on this. Anyway, I'm not sure where it should go next. Who exactly was I writing this for? 😂

**Comment by colinmurphy01** [comment]
I'll give this some thought today.

**Comment by colinmurphy01** [comment]
Sent email for feedback. 

After that, will likely bring it to George and Jason to discuss next steps since this is outside of our area of authority.

**Comment by colinmurphy01** [comment]
Followed up on email thread to get a sense of next steps

**Comment by colinmurphy01** [comment]
We're starting to socialize this and figure out the owner of this.

I'm going to close this
