### ISSUE TITLE
Revisit logging in NewRelic for obs station errors

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#1447]
- Is it still running?
- Is it running for OCONUS locations?
- Are we able to calculate the distance from the person's location to the successful obs station? (if not we may spin up a new ticket)

**Comment by colinmurphy01** [comment]
@eric-gade where are we with this.

Last I heard is we found this was broken and needed to be fixed. We identified a fix but needed support, is that still true? Is this blocked?

**Comment by eric-gade** [comment]
I need to ask a new colleague a question about it once I can get my environment set up to deal with NR locally again. There has been no movement on this issue otherwise

**Comment by jamestranovich-noaa** [comment]
I have a fix at https://github.com/weather-gov/weather.gov/pull/1720 for the NR timestamps. Can't guarantee it fixes everything with NR but it should move us forward.

**Comment by jamestranovich-noaa** [comment]
OK. I know why the NR errors are happening and I have a PR for the interop branch. https://github.com/weather-gov/weather.gov/pull/1767 

I confirm that 

- NR is broken in prod, still, but should be fixed when we deploy the api interop layer (we're removing the relevant PHP code from Drupal)
- We are able to calculate the distance from the person's location to the successful obs station (and log if we can't find any valid nearby observation stations)
- We are **not** able to query OCONUS -- but I believe this is unrelated to NR. This seems to be a bug in the api interop layer. Filing a separate issue.

**Comment by jamestranovich-noaa** [comment]
I _think_ we can close this now because https://github.com/weather-gov/weather.gov/issues/1591 (interop layer) is the relevant epic and that branch now has all the NR fixes and logging. 

Was there anything else we needed to do here?

**Comment by eric-gade** [comment]
I agree, we can close it
