### ISSUE TITLE
Explore GHWO and better understand it, with potential connection to beta.weather.gov

### ISSUE THREAD

**Issue by shadkeene** [weather-gov/weather.gov#1449]
GHWO may feed into risk/threat levels in beta.weather.gov.  We need to know about the current process for creating GHWO and the future of it, including any GIS service that's being developed.

**Comment by colinmurphy01** [comment]
[Notes Doc](https://docs.google.com/document/d/1g8W4SF0q5B2JkOyhcFEW7rYLHY3BIPo6eiT05oSkeWs/edit)

Shad followed up in an email.

Will discuss next steps with design/eng in leads sync

**Comment by shadkeene** [comment]
Wondering if we're ready to close.  We've definitely explored this, but we probably need to outline and write tickets for next steps before closing.

**Comment by colinmurphy01** [comment]
Tracking scoping work in #1536
