### ISSUE TITLE
Export english translations to Spreadsheet or CSV

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#1457]
After reviewing [this file](https://gsa-tts.slack.com/archives/C05DU11D4J2/p1721156745407489?thread_ts=1721154708.755439&cid=C05DU11D4J2) with the translations lead, a couple things will be helpful for a proper translation:

- Replacing clauses with variables and instead adding examples with complete content (10 has been referenced as an ideal set)
  - I'm still unsure, what we do from there
- Exporting into a format that can be used within Excel (I'm assuming CSV is best, if we can't support an XLS file)

Note: It's likely that most of these phrases have been translated before and therefore won't cost additional credits

**Comment by colinmurphy01** [comment]
Discussed that we'd get the phrases exported into a CSV and then assigned to me to manually clean it up and add the necessary examples.

**Comment by colinmurphy01** [comment]
Need to submit via [this form](https://docs.google.com/forms/d/e/1FAIpQLSeq3Zpb5lDL1QNGcHd2qqZ9lWFJaQOdfPx3-giktFHpfmgAvw/viewform)

Updated to XLS file to add comments for translation

[beta.weather.gov_copy_072524.xls](https://github.com/user-attachments/files/16383703/beta.weather.gov_copy_072524.xls)

I could use a second pair of 👀 to review this for spelling, grammar before it gets submitted. @eric-gade can you help me out?

**Comment by colinmurphy01** [comment]
Also need to note the following abbreviations upon submission:
- SSO
- dBz
- X (social media)
- HTTPS

**Comment by eric-gade** [comment]
@colinmurphy01 The sheet looks good to me!

**Comment by colinmurphy01** [comment]
Translations have been submitted. Used 7/31 as a reasonable due date.
