### ISSUE TITLE
[WFO-CMS-Data] Initial WFO page template and routing

### ISSUE THREAD

**Issue by eric-gade** [weather-gov/weather.gov#1470]
### Description
**NOTE**: #1469 is a prerequisite to this work
  
This issue stems from #1422, which sought to create tickets for WFO data entry and display.
  
The purpose of this ticket is to spin up the initial scaffolding for a WFO page template and the corresponding Drupal routing. The primary task is to simply display WFO data on a custom template (styling and formatting does not matter yet), and to be able to access that page at a predictable URL.

### Questions and Considerations
* What should the URL be for WFO pages? We can change this later, and it might be good for now to start with `/office/<code>`, where `<code>` is the three-letter WFO code, like `OKX` for New York.
* We will __not__ be including any dynamic parts of the page yet, such as local expertise links or the WFO map

### Acceptance Criteria
- [ ] We have a predictable URL which Drupal can successfully route to a (bare bones) WFO page
- [ ] The WFO page template can load field data from the WFO Information content type that was modified in #1469 
- [ ] Do __not__ include any dynamically generated portions of the page, such as the WFO map or the local expertise links

**Comment by greg-does-weather** [comment]
Closed by #1517
