### ISSUE TITLE
[WFO-CMS-Data] Add WFO map to WFO page template

### ISSUE THREAD

**Issue by eric-gade** [weather-gov/weather.gov#1472]
### Description
#1469  and #1470 are __prerequisites__ to this ticket.
  
Implement the WFO map with its geography outlined as designed in the [Figma file](https://www.figma.com/design/w2QI2uTgaTWUPLHLi40mm1/Weather.gov-%E2%80%93-v0.2?node-id=9942-4943&t=vX6pzHVfmYJxkin4-0).

### Questions and Considerations
* Which mapping library should we use? Probably want to crib what we did for Alert maps

### Acceptance Criteria
- [ ] The WFO page template now displays a map with the WFO geometry outlined, per the designs

**Comment by greg-does-weather** [comment]
This s done in #1539
