### ISSUE TITLE
WFO Page template

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#1474]
Using the following [Figma file](https://www.figma.com/design/w2QI2uTgaTWUPLHLi40mm1/Weather.gov-%E2%80%93-v0.2?node-id=9942-4943&t=vX6pzHVfmYJxkin4-0) implement the front-end styling for the WFO page.

**Comment by colinmurphy01** [comment]
Likely a duplicate to #1470, @partly-igor will confirm.

If so, please close and archive this ticket.

**Comment by partly-igor** [comment]
confirmed
