### ISSUE TITLE
AFD template

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#1475]
We are ready to implement the first version of AFDs. At the start AFD should be a standalone page, with a set of control inputs and a content area that gets dynamically updated based on the input selection (i.e. is reactive).  

[Documentation](https://www.figma.com/design/w2QI2uTgaTWUPLHLi40mm1/Weather.gov-%E2%80%93-v0.2?node-id=10253-207539&t=hVXoEEK2XrCDWG5w-1)

[Mobile prototype](url)

Artboard with [mobile](https://www.figma.com/design/w2QI2uTgaTWUPLHLi40mm1/Weather.gov-%E2%80%93-v0.2?node-id=10118-197954&m=dev&t=hVXoEEK2XrCDWG5w-1), [tablet](https://www.figma.com/design/w2QI2uTgaTWUPLHLi40mm1/Weather.gov-%E2%80%93-v0.2?node-id=10253-208736&m=dev&t=hVXoEEK2XrCDWG5w-1), [desktop](https://www.figma.com/design/w2QI2uTgaTWUPLHLi40mm1/Weather.gov-%E2%80%93-v0.2?node-id=10054-197480&m=dev&t=hVXoEEK2XrCDWG5w-1)

Note that there are a few new components that will need to implemented here (they are also noted in the documentation in figma):
1. A combobox for WFOs
2. A dropdown with AFD versions
3. In page navigation/anchor links

As discussed with @eric-gade in the initial implementation we can make the WFO selector a simple dropdown, and then have a separate ticket for creating the combobox version. I can create the followup ticket if engineering decides to go with that approach. 

Priorities:

1. Parsing with most recent one
2. Later versions (Bonus, or next sprint)

**Comment by colinmurphy01** [comment]
URL Structure would ideally be /afd/office issued + queries for the specific AFD

For a page that doesn't have queries, the initial state would have selectors not preselected (users can then select the office). 

For first round - dropdown menus may not work.

**Comment by eric-gade** [comment]
Breaking out into separate tickets to be done in order:
https://github.com/weather-gov/weather.gov/issues/1525
https://github.com/weather-gov/weather.gov/issues/1526
https://github.com/weather-gov/weather.gov/issues/1527
https://github.com/weather-gov/weather.gov/issues/1528
https://github.com/weather-gov/weather.gov/issues/1529
https://github.com/weather-gov/weather.gov/issues/1530

**Comment by greg-does-weather** [comment]
Closing this in favor of the individual tickets
