### ISSUE TITLE
Prototype Visualization

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#1477]
Get a sense of chart and style of charts we want to create. What needs to be visualized and where.

Additional consideration for the future will be probabilistic visualizations ([slack thread](https://gsa-tts.slack.com/archives/C05DU11D4J2/p1723037348849989)). We are not prioritized for this version of visualizations, but keep it in the back of your mind.

**Comment by partly-igor** [comment]
Designed a number of charts for the various weather variables, testing out their placement in the layouts. Still more exploration to do.

**Comment by colinmurphy01** [comment]
I think this is `done`

[Figma documentation](https://www.figma.com/design/w2QI2uTgaTWUPLHLi40mm1/Weather.gov-%E2%80%93-v0.2?node-id=11028-255552&m=dev&t=yrI9IMUri5KRaKev-1)

[Context](https://www.figma.com/design/w2QI2uTgaTWUPLHLi40mm1/Weather.gov-%E2%80%93-v0.2?node-id=10757-238038&t=yrI9IMUri5KRaKev-4)
