### ISSUE TITLE
[WFO-CMS-Data] Remove WFO Promo content type

### ISSUE THREAD

**Issue by eric-gade** [weather-gov/weather.gov#1486]
### Description
This ticket is part of the work described in #1422.

### Questions and Considerations
**Should only be done after all other `[WFO-CMS-Data]` tickets have been completed.

### Acceptance Criteria
- [ ] The WFO Promo content type and any associated content are removed from the config / system

**Comment by colinmurphy01** [comment]
Is there any promo content we want to preserve?

No. There are 3-4 in there now, not hard to redraft.
