### ISSUE TITLE
Discovery: Outlook products

### ISSUE THREAD

**Issue by kmranjo** [weather-gov/weather.gov#1512]
Outlook products have been coming up in several different parts of our work, so it would be helpful to learn a bit more about them. 

The goal of this timeboxed discovery will be to document: 
- What outlook products exist
- Which part of NWS issues them
- What format they take (text, image, etc) 
- What data is available on the use of these products

[Discovery document here](https://docs.google.com/document/d/1S1gs53zOQHHc5ewtNbmDqod4fefAsBFzcYT2CmoTfoY/edit?usp=sharing)

[Raw data here ](https://docs.google.com/spreadsheets/d/15tgAFpE-nYUhBVxAwO6KA7kF-khfk82B8-ztbvo966U/edit?usp=sharing)

**Comment by kmranjo** [comment]
@colinmurphy01  does this reflect what we talked about yesterday? If so, I think I can get started on it today

**Comment by colinmurphy01** [comment]
Can you pull analytics for them as well?

**Comment by kmranjo** [comment]
I can try. They aren't all as straightforward as 1 product on 1 page. Most of the ones I've found have them grouped together a bit confusingly, and a lot of them are embedded on the site instead of directing users to the source. But I'll give it a shot.

**Comment by kmranjo** [comment]
Moving this to review - ready to chat about it whenever there's time in one of our review meetings. 
Recommended next steps would be to discuss w/ Design how we might incorporate HWOs into the site, since they seem to be the primary value add, at least until we get to the centers.

**Comment by colinmurphy01** [comment]
[Slack convo about HWOs](https://gsa-tts.slack.com/archives/C05DU11D4J2/p1723056706139559)

**Comment by coreypieper** [comment]
Email sent to SME for an update on HWO consideration timeline. They're on leave until Aug 12.

**Comment by coreypieper** [comment]
SME's current though as that, because the GHWO is still a few years (maybe 1-3) from being fully operationalized, any full discontinuation of the HWO is likely 2-5ish years off.

**Comment by kmranjo** [comment]
Conversation with product is captured in the notes toward the end of [the doc](https://docs.google.com/document/d/1S1gs53zOQHHc5ewtNbmDqod4fefAsBFzcYT2CmoTfoY/edit?usp=sharing). 
Aligned on these as next steps: 
1. Deprioritize HWO entirely 
2. Deprioritize tropical for now, we can look at revisiting in the spring 
3. Prioritize SPC convective outlooks as part of discovery around the national/center milestones

**Comment by coreypieper** [comment]
Regarding SPC outlooks, these data may come in handy:

- Convective outlooks geometry in the API: https://api.weather.gov/products/26a7884a-cc96-484c-8859-1070651112c0 (product is PTS)
-- JSON too: https://www.spc.noaa.gov/products/outlook/day1otlk_cat.nolyr.geojson
- Text from the outlook in the API (product is SWO): https://api.weather.gov/products/8b7971cf-9970-479b-bee8-83fca7597ed8
