### ISSUE TITLE
Prepare for webinars

### ISSUE THREAD

**Issue by shadkeene** [weather-gov/weather.gov#1522]
- Align slides with talking points
- Ensure plenty of room for Q&A
- Align on spicy pepper responses

**Comment by colinmurphy01** [comment]
We have a working [deck](https://docs.google.com/presentation/d/1xcrXpe4p5cLaEvgDUG2UP-JRsJ3kpaihMezz1P5rpIw/edit#slide=id.g279b2f27970_0_2246) for this type of shareout.

We can use this as a starting place if it's helpful for a broader shareout.

**Comment by colinmurphy01** [comment]
I think this is `done`!
