### ISSUE TITLE
[AFD-Template] Parse AFD text into desired markup

### ISSUE THREAD

**Issue by eric-gade** [weather-gov/weather.gov#1526]
### Description
This is a part of the work outlined in #1475 
  
It should be done after #1525 
  
We need to parse the raw AFD text and return markup per the description outlined in [this Figma file](https://www.figma.com/design/w2QI2uTgaTWUPLHLi40mm1/Weather.gov-%E2%80%93-v0.2?node-id=10253-207539&t=pUfyChLhxBuElTRp-0).
  
Specifically, per @partly-igor:
* > Each AFD I looked at starts with this sort of header: 
3 lines of codes, followed by 3 lines of Title, Publishing WFO, and date stamp
* > If possible, we should parse headers. From the sample I looked at H2 headers always start with an period (.) before the text.  Note that we are using a different style of headers for the AFD
* > We should eliminate the single line breaks throughout AFD body paragraphs. Currently there is a break at <= 66 chars for each line. 
* > If possible we should also parse H3s. These often start and end with an ellipses

### Acceptance Criteria
- [ ] Raw AFD text is now presented in a parsed, custom markup (via some kind of parsing utility)
- [ ] The header portions of the AFD are parsed into a separate markup, per the Figma
- [ ] H2 headers are parsed from the text and given a styling similar to the markup
- [ ] There are no superfluous line breaks as exist in the raw text (at 66 chars per line)
- [ ] We _attempt_ to parse H3 headers from those that start and end with ellipses

**Comment by greg-does-weather** [comment]
AFD formatting directive: https://www.weather.gov/media/directives/010_pdfs/pd01005003curr.pdf - section 2.5 in particular is about AFD formatting.

**Comment by colinmurphy01** [comment]
I believe this is `done`
