### ISSUE TITLE
[AFD-Template] Style page according to design, v1

### ISSUE THREAD

**Issue by eric-gade** [weather-gov/weather.gov#1527]
### Description
This is part of the work outlined in #1475 

It should be done after #1526 
  
We need to style the AFD template according to the [Figma design](https://www.figma.com/design/w2QI2uTgaTWUPLHLi40mm1/Weather.gov-%E2%80%93-v0.2?node-id=10253-207539&t=pUfyChLhxBuElTRp-0).
  
See:
[Documentation](https://www.figma.com/design/w2QI2uTgaTWUPLHLi40mm1/Weather.gov-%E2%80%93-v0.2?node-id=10253-207539&t=hVXoEEK2XrCDWG5w-1)

[Mobile prototype](https://github.com/weather-gov/weather.gov/issues/url)

Artboard with [mobile](https://www.figma.com/design/w2QI2uTgaTWUPLHLi40mm1/Weather.gov-%E2%80%93-v0.2?node-id=10118-197954&m=dev&t=hVXoEEK2XrCDWG5w-1), [tablet](https://www.figma.com/design/w2QI2uTgaTWUPLHLi40mm1/Weather.gov-%E2%80%93-v0.2?node-id=10253-208736&m=dev&t=hVXoEEK2XrCDWG5w-1), [desktop](https://www.figma.com/design/w2QI2uTgaTWUPLHLi40mm1/Weather.gov-%E2%80%93-v0.2?node-id=10054-197480&m=dev&t=hVXoEEK2XrCDWG5w-1)
   
**NOTE**: For this initial pass, we will not be using the combobox USWDS/custom component for the dropdowns. Instead, these should be put in as plain selects. We will revisit the comboboxes in a subsequent ticket

### Acceptance Criteria
- [ ] The AFD page conforms to the Figma designs, with the exception of the combobox dropdowns
- [ ] A list of WFOs is provided to one of the select elements
- [ ] Select elements are not fully functional comboboxes yet

**Comment by colinmurphy01** [comment]
Noticing this is in `to-do` but not assigned. @eric-gade is this on your list this sprint?
