### ISSUE TITLE
[AFD-Template] Front-end component for retrieving past versions and navigating WFOs

### ISSUE THREAD

**Issue by eric-gade** [weather-gov/weather.gov#1529]
### Description
This is part of the work outlined in #1475   
  
It should be done adfter #1528 
  
Building upon the async routes created in #1528, this work should build a custom frontend component that is able to respond to changes in the select menus and asynchronously swap markup for the selected AFD.
  
Additionally, the we need to switch the select elements and transform them into full-fledged combobox components, where:
* Selecting a different WFO from the WFO dropdown will update the AFD selection dropdown options, retrieving information about some set number of most recent AFDs;
* Selecting a specific AFD from the AFD dropdown will fetch and update the markup for the selectd AFD, swapping out what is currently displayed

### Acceptance Criteria
- [ ] Select menus are now comboboxes
- [ ] Selecting a WFO updates the AFDs listed in the AFD combobox
- [ ] Selecting an AFD from the AFD combobox asynchronously fetches the markup for that AFD, then swaps it with what is currently displayed

**Comment by greg-does-weather** [comment]
Closed by #1587
