### ISSUE TITLE
Scope: Risk Summary / GHWO

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#1536]
Document the following

- User need
- GHWO mentions
- Technical considerations
- Must, Should, Won't priorities

Discuss amongst product and design

**Comment by colinmurphy01** [comment]
From previous convos: #1449

**Comment by colinmurphy01** [comment]
@colinmurphy01 to provide example

**Comment by colinmurphy01** [comment]
Examples can be found in this folder - https://drive.google.com/drive/folders/115wmW9nweCxHdaFfVJWNa8qmzS_-A9Of

**Comment by coreypieper** [comment]
I've gotten a decent start on this. Would love 30 min next week to work out the remainder. https://docs.google.com/document/d/1pAnrIrMUhmg2_FJPUjTrPEwZNhotQDQsfkGSMs6FhXo/edit

**Comment by colinmurphy01** [comment]
Nice maybe we can shoot for wednesday's po/design sync to review?

**Comment by shadkeene** [comment]
I will be reaching out to folks about the technical aspects of this product.

**Comment by colinmurphy01** [comment]
My biggest scope concern here is replacing rsync. 

This might be the use case that forces us to replace the integration between WFOs and the public internet for image files.

**Comment by colinmurphy01** [comment]
I believe this is `done` as sarah is moving forward with #1372
