### ISSUE TITLE
Scope: WWA Map

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#1548]
We need to scope the core features of the WWA map in order to inform #1415 

NWS has feelings about how it functions and "plays by it's own rules". This will require conversations with various SMEs to assess the drama.

Research and recommendations are captured in [this scoping document](https://docs.google.com/document/d/1IekL1r7pZS_oBcFL1ic7bWsxz-yXP2IdN6iBK0r9xrk/edit?usp=sharing).

**Comment by colinmurphy01** [comment]
@sarahmhgov Assignging this to you for this sprint (I believe you raised your hand).

If not, I'd be happy to take this over.

**Comment by colinmurphy01** [comment]
Never mind we're deprioritizing this for now, and instead:
- Waiting to design and build county pages and then hear from people if anything's missing
- This might be more applicable to just national users and something we can pick up later in that phase, if it's not really needed for county/state

**Comment by kmranjo** [comment]
Ready to review in design coworking on Tuesday and PO review on wednesday

**Comment by colinmurphy01** [comment]
🍿

**Comment by kmranjo** [comment]
Reviewed with product and got approval to move forward with prototype
