### ISSUE TITLE
Hazard story

### ISSUE THREAD

**Issue by janelx** [weather-gov/weather.gov#155]
We are dramatically simplifying this feature

### Supported user stories
E4 … As a member of the public or a partner, I would like to understand the possibility, severity, and impact of a hazard
E4.3 …I want to understand at-a-glance what, where, and how bad the threat/impact level is of a hazard for a specific location 
E4.4 … I would like to know what to expect for the length of the hazard (could be more?) for a specific location
E4.5 … I want to understand the actions or steps I could take to save my life or property at my location
E.9 As a forecaster I want to be able to write a unique weather story for a specific hazard that is separate from my WFO weather story, in order to communinate relevant details to people experiencing the hazard.

Considerations:
- How do we ingest hazard products into the CMS?
- Is there a Hazard ID we can use?
- How can a forecaster link a story to a hazard in the CMS?
- Can a forecaster correlate a story to multiple hazards?
- When should the hazard story be published or unpublished?

Hypotheses: 
- By displaying hazard-specific content only to those impacted by the hazard, we can deliver high value without adding confusion or alarm to other users. 
- Content in the hazard story provides a complement to the hazard product itself. 

Acceptance Criteria

- [ ] 

----- Delete below? -------

### User acceptance criteria
As a member of the public or partner, I understand the conditions, timing, impact and severity of a hazard for my specific location, and the actions I need to take to protect life or property from that hazard. 

### Design (define/discovery)
**Purpose**
Provide an open space for forecasters to communicate the what/when/impacts of an impending weather hazard for a specific area, and safety guidance needed to advise those in that area how to protect life and property. Serves as a complement to the hazard products and weather data. 

**Format**
Text with the option to include supportive imagery
Text would need basic styling options (bold, italic, underline, add links, etc) 
Image formats are TBD 

### Examples 
**Wind advisory in effect tonight**
Expect strong northwest winds tonight up to 50 mph, ending Friday morning. 
Winds will be strong enough to blow away unsecured items, and make driving difficult for high profile vehicles. 
**Take action**
Secure loose items like outdoor furniture, and use caution if outdoors, especially driving. 

**Severe thunderstorm warning** 
A severe thunderstorm has been spotted in McDonough County, moving east. 
Expect winds over 50 mph, heavy rain, lightning, and quarter-sized hail, which is likely to damage vehicles. 
**Take action**
Move indoors immediately. Move to an interior room on the lowest floor, and avoid large windows.

### Component acceptance criteria
A forecaster should be able to: 
- Create a new hazard story 
- Write and format the text as desired
- Associate the story with a specific hazard product (or multiple hazard products) 
- Tag the story with the hazard type 
- Upload an image file (or multiple) to the DAM
- Author alt text or a caption for each image
- Add images (up to 3)
- Publish the story 
- Unpublish the story 
- Edit an existing story (both updating the text and/or removing or updating the image) 
- View all hazard stories created within a given WFO, regardless of publication status, and search by hazard type tag 
- View the change log of a story (date/time of change, type of change, person who changed it, etc) 

A forecaster should not be able to: 
- Inject code into the component 
- Write more than 500 words in the text field 
- Add more than 3 images 

An end user should be able to: 
- Navigate to any page displaying the hazard product and see the hazard story paired with it
- Read the text up to 300 words 
- If text is longer than 300 words, see a clear invitation to expand it in full 
- Expand and collapse the expanded text  
- See when the story was last published
- View the image
- If multiple images are present, swipe and/or click through each one 
- Read the alt text or caption for each image 
- Expand each image and return it to previous size 

The system should be able to: 
- Automatically include a date and timestamp when the story is published 
- Automatically include the name of the WFO it is associated with 
- Include the component on the page only if the linked hazard product applies to that location 

### Exploration needed
Stakeholder user testing: Is the limit of up to 500 words enough to meet the need?

End user testing:
- Is the guidance of 100-200 words (with room for up to 500) enough to meet the need? If full length, does it negatively impact the experience?
- What type of images add value to the weather story for the user? 

**Notes**
- Currently offices differ: 1 product to multiple zones or WSW for each zone and add timing

----
```[tasklist]
#### Review: design, function and flow:
- [ ] POs - org alignment and vision review
- [ ] Eng - feasibility review and right size stories
- [ ] UX - what and how to test
```

```[tasklist]
#### Story details
-  [ ] Reviewed designs (must be attached)
-  [ ] Acceptance criteria define (added to this story)
```

**Comment by colinmurphy01** [comment]
@kmranjo Please update this by EOW.

**Comment by kmranjo** [comment]
I'm afraid I haven't worked on this one yet at all - limited on time this week. I do think that once we have the weather story ticket fleshed out, it will heavily inform this one, so I've been prioritizing work on that first. It's ready to be discussed with design and product.

**Comment by kmranjo** [comment]
@janelx  Updated this story to reflect the concept we talked about of this as a version/view of a weather story. I added a couple examples based on past hazard-based stories, but it might be a bit before I can grab some images to go with them because I'll need to wait for new ones or use wayback machine to find some that match. 
With that missing piece in mind, does this otherwise reflect what we talked about? Is anything different or missing?

**Comment by colinmurphy01** [comment]
@kmranjo can you do two things: 

- confirm that I've updated this to reflect the capability we're testing in the prototype?
- Review the content from the older ticket (below Delete this?) and determine what's relevant to keep?

**Comment by kmranjo** [comment]
@colinmurphy01  I updated the info above to include the hypothesis I think we are testing, but want to confirm with @partly-igor and @sarahmhgov  that this looks correct. 
I also updated the info below the "delete" line to be a bit closer to the concept we're considering, but a lot of it is very specific to implementation and I don't think we're there just yet. Not sure if it is valuable to keep all that since we might need it eventually (even if edited), or if it woudl be cleaner to delete it all and get the design fully where we want it before looking at that level of detail for how the component will work. Thoughts?

**Comment by partly-igor** [comment]
The hypotheses look good to me. 

Agree that some of the implementation details in the AC below the delete line is a little early, and may change based on feedback we hear next week. Wondering if we refine this ticket after the round of research?

**Comment by colinmurphy01** [comment]
@kmranjo @sarahmhgov I think we are holding on this feature for a while now. I'm going to close this ticket.
