### ISSUE TITLE
Local Outlooks component iterations

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#1552]
Prior to picking up #1473, @kmranjo and I discussed the followong:
- Instead of just having a limited set of hyperlink text fields in a list, can we support Title, Description, Link fields for each so that forecasters are encouraged to write why the resource is valuable in stead of just the name of the product
- Renaming the component because they are not all "local" or "outlooks"

**Comment by colinmurphy01** [comment]
Because #1548 got deprioritized, I chatted with @partly-igor and @sarahmhgov this would be helpful for you to pick up and wireframe/design to some extent.

I'll assign to you for now, but you all should sync on it tomorrow and then confirm if this is something you can lead. If not, move it back to `backlog` and unassign.

**Comment by sarahmhgov** [comment]
Added some thoughts and clarification to this doc: https://docs.google.com/document/d/1880yFJmWSgcHbI262o60CEANcRHCkkTB-OQJRPuBOBI/edit

@igorkorenfeld happy to mock up if needed, but didn't want to poke too much at figma before aligning on the changes themselves (and I think the design changes are pretty straightforward)

**Comment by colinmurphy01** [comment]
With the conversation around outlooks from the other day (yesterday, wed, shrug), I'm wondering if building this component is premature and should be reconsidered once we figure out our strategy for outlook products? 

When I think about it, I think we should still move forward with this component and essentially give WFOs a space to have 5 links of things that are relevant to their WCA. But I'm not as confident as I was earlier, so I'm open to hearing your thoughts.

**Comment by sarahmhgov** [comment]
Hm trying to follow, may need convo. 

I think it's pretty important to give WFOs a space to have links to things. My understand has been that in the short term the intent is this will be links to existing outlooks/products, and WFOs will have to adapt as some outlooks get incorporated/ moved over. I don't think anything has changed w outlooks conversation in my mind, but happy to chat through.

**Comment by colinmurphy01** [comment]
Roger, then let's move forward.

When there is updated designs and #1473 is updated reflecting the new fields.

**Comment by sarahmhgov** [comment]
Ok - @partly-igor do you want me to update the designs, or is this mostly blocked by #1473?

**Comment by colinmurphy01** [comment]
I actually think this ticket blocks #1473.

**Comment by sarahmhgov** [comment]
@partly-igor would you like me to pick up the tiny bit of design work on this one? Basically mocking up having up to 4 resources with Hyperlink, Text field, Description per doc.

**Comment by partly-igor** [comment]
That sounds good to me!

**Comment by sarahmhgov** [comment]
Added some wireframes, I think this is good to review, pretty straightforward. If eng needs CMS mockup I could add that as well. https://www.figma.com/design/w2QI2uTgaTWUPLHLi40mm1/Weather.gov-%E2%80%93-v0.2?node-id=11827-2&node-type=canvas&t=flr7RygmkUdGQnEN-0

**Comment by colinmurphy01** [comment]
Looks great. Can you add it to #1473 and weigh in on the questions listed in the description?

**Comment by sarahmhgov** [comment]
Ah! Yep, on it.
