### ISSUE TITLE
Spike: Hazard - Generic safety info and local resources

### ISSUE THREAD

**Issue by janelx** [weather-gov/weather.gov#156]
### Supported user stories
- 4.5… I want to understand the actions or steps I could take to save my life or property at my location

### Acceptance Criteria

- [x] Document what the problem we're trying to solve
- [x] Proposal for how we're solving it
- [x] BONUS: Alignment from the team (based on calendars)

### Dynamic Safety Information
**Problem statements:**
- It is a challenge for forecasters to create content new each time during the pressures of a weather hazard, especially when time is short 
- Safety guidance featured in the weather story is often limited to the most widely applicable situations, which means users outside of those situations may not receive the most valuable or applicable guidance. 

**Proposed solution:** 
Use the CMS to create a database of safety guidance that can be automatically populated throughout the website as needed based on the hazard type. 

[Detailed proposal linked here](https://docs.google.com/document/d/1rw6eCqSYQFSNbQs02dH-dAmSPCqmmDKNE4k7fsCC3Os/edit?usp=sharing)

### Local Resources
**Problem statements:** 
- Forecasters are very familiar with locally-relevant challenges and resources, but don’t currently have any avenue through which they can connect users to them. Since they have to communicate to the full WFO, information is limited to that level. 
(example: Tune in to your local weather radio station for updates) 
- Some safety guidance may be very important, but too vague to be actionable by itself. This puts users in the position of having to look up more information before they can take action. 
(example: Not knowing my local weather radio station, I then have to go look up what station that would be for me.) 

**Proposed solution:** 
Use the CMS to create a database of locally-relevant safety resources for each WFO that can be automatically populated throughout the website as needed based on the active hazard type and selected location.

[Detailed proposal linked here](https://docs.google.com/document/d/1uluZQP3vzvxKmM8oKkARAiBkjvacffvGXUWEpIZdpIo/edit?usp=sharing)

**Comment by colinmurphy01** [comment]
Before tackling this, meet with David Johnson to discuss efforts for rewriting and organizing safety info in weather.gov

**Comment by kmranjo** [comment]
Updated the details above, will plan to discuss with design in our next meeting. 
@partly-igor  @sarahmhgov  feel free to take a look beforehand if you like.

**Comment by kmranjo** [comment]
Both features discussed during design crit on 12/21, ready to review with product.

**Comment by colinmurphy01** [comment]
From product review

- Dynamic Safety
  - Feasibility = high
  - Product = good, but when
  - Next steps: 
    - Follow up with @coreypieper for more feedback
    - Create ticket and add to prioritized backlog for next sprint's consideration
- Local Resources
  - High value
  - Feasibility = medium, low
  - Product = high, but want more validation
    - We do this in hazard products - tripcheck.com, air quality, etc.
  - Next steps: 
    - Create ticket and add to prioritized backlog for next sprint's consideration - design the process for managing content and get feedback on operational feasibility from Nashville Forecaster/WFO, then design/build

**Comment by kmranjo** [comment]
@colinmurphy01  I am moving this to done since all next steps have been taken except the conversation with Corey. We'll tackle that next week when everyone's back in office, and I noted that in the ticket for that component as well.
