### ISSUE TITLE
Hazard - Local resources

### ISSUE THREAD

**Issue by janelx** [weather-gov/weather.gov#157]
[Full details are captured here](https://docs.google.com/document/d/1uluZQP3vzvxKmM8oKkARAiBkjvacffvGXUWEpIZdpIo/edit?usp=sharing)

### Supported user stories
- 4.5 … I want to understand the actions or steps I could take to save my life or property at my location

### Design Considerations 
- View resources I can use specific to my location that will help me to protect life and property 
- Some resources may be text only, others may include links to internal or external webpages 
- Users view these resources only on their location page, and only when hazards are present 

### Implementation Considerations
- Content is created by forecasters, with information gathered in partnership with local EMs
- Content creator needs to be able to associate each piece of content with a location (county) AND one or multiple hazard types ("event") 
- When a hazard product is issued, the system automatically detects any applicable local resources and displays them alongside the hazard product on the location page. 
Applicable in this case means the content is tagged with the same event type, and with the county that the user-selected location sits within
- When the hazard expires, the local resources no longer display. The content never needs to be unpublished, since the display conditions are set by the presence of the paired hazard product.

### Out of scope for now 
- Consideration of overlapping resources (crossover of locations) 
- Resources applicable to any location more granular than a county 
- Implementation for more than one WFO, or any edge cases in which a county is covered by more than one WFO

### User feedback
- EM partners appreciate seeing this content on the page and are eager to assist forecasters with creating/maintaining it 
- Forecasters see the value of this content on page, but do have questions about the workload of creating/maintaining it

**Comment by janelx** [comment]
For wireframing, needs some high-level content examples. How does it differ from "safety" info. We started with the idea that this would be a place to link to useful places to stay up to date with hazards and emergency info. 

For testing/continuous discovery:
- Usefulness and relevancy of info 

@kmranjo

**Comment by kmranjo** [comment]
Not at all an exhaustive list, but a few examples I had created so far include: 
- Listing the radio station that they could tune into for updates
- Linking to the contact info for the local power utility to report outages
- Linking to the local DoT to report downed trees on roads, traffic lights out, etc.
I think the location context is key here, because it'll be hard to point users to resources without that being defined. If the context for the page is the entire area for which the hazard applies (either a full WFO or substantial part of it) then resources would be tough. But if we can get it down to county level once we know their location, that seems more doable. So maybe this component makes more sense on the location page?

**Comment by janelx** [comment]
Thanks. I was thinking the radio station too. 
Don't know if this helps, but there are 2 flows. Location known (browser remembers it) and location not know, in which case yea, would need to investigate if state level or county level provides relevant and helpful info. 

I still need to add a way to add location and get to point location.

**Comment by kmranjo** [comment]
@partly-igor I updated this at a high level based on the conversation last week, but am wondering if we want to get more specific about what details need to go into a ticket like this? In this case, there are some design-related questions that still need to be tackled (for instance, what is the header for this content, or what is the max number of items). Should those kinds of specific questions be included in the ticket itself, or the details just added when they are worked out as part of hte design process?

**Comment by partly-igor** [comment]
I like the idea of having an  "outstanding questions" / TBD section in the ticket so that we can note that we have thought about this item but are still figuring it out.

**Comment by kmranjo** [comment]
@partly-igor I wrote up more specific details [in the word doc here](https://docs.google.com/document/d/1uluZQP3vzvxKmM8oKkARAiBkjvacffvGXUWEpIZdpIo/edit#heading=h.rnv2ravwu5ya). It's long, but does include some of the open questions. Would you want to see all of this in the ticket itself?

**Comment by partly-igor** [comment]
I think between the doc and the ticket it's all covered no need to copy over.

**Comment by partly-igor** [comment]
[Designs here](https://www.figma.com/file/0dSABt9zCqoknaKua6DHmP/NOAA---Weather.gov?type=design&node-id=1988%3A15388&mode=design&t=KHJMkpZmnhOYEmrN-1), reviewed with PO & Engineering
