### ISSUE TITLE
Consider adding time reference to satellite imagery section

### ISSUE THREAD

**Issue by shadkeene** [weather-gov/weather.gov#1570]
Not many users know what Z time is, and those are the time stamps on our satellite imager that we're using now.  One simple fix could be to add a time reference in the heading, such as "Past 7 Hours", which is how long the current animated gif satellite loops are.  This would provide context for long the loops are for, and it would suggest to the user that this is past data, not modeled/future data.

![Image](https://github.com/user-attachments/assets/1e91905f-faa2-4979-b2da-395a442b040c)

[Slack thread](https://gsa-tts.slack.com/archives/C05DU11D4J2/p1724681301472639)

**Comment by coreypieper** [comment]
Greg has concluded that the JSONs like [this](https://cdn.star.nesdis.noaa.gov/WFO/catalogs/WFO_02_mpx_catalog.json) contain times we can use. Format is:
4-digit year, 3-digit day of the year, time in UTC. 

_Example:
20242391330 is 2024, 239th day of the year, and 1330UTC._
