### ISSUE TITLE
e4.v1 Alert details

### ISSUE THREAD

**Issue by janelx** [weather-gov/weather.gov#158]
### Supported user stories

- 4.3 … I want to understand at-a-glance what, where, and how bad the threat/impact level of a hazard for a specific location
- 4.4 … I would like to know what to expect for the length of the hazard (could be more?) for a specific location

### As a user, I can: 
- Clearly see the hazard product details (e.g. what, where, when, impact, safety)
- Understand the timing of the hazard (when it is expected to arrive, pass) 
- See how up-to-date this information is (when was the hazard product issued) 
- Navigate between multiple hazards

[Figma board](https://www.figma.com/file/0dSABt9zCqoknaKua6DHmP/NOAA---Weather.gov?type=design&node-id=1336-19052&mode=design)
[Prototype](https://www.figma.com/proto/0dSABt9zCqoknaKua6DHmP/NOAA---Weather.gov?page-id=915%3A1056&type=design&node-id=1336-19384&viewport=760%2C-2982%2C0.16&t=8MRcYGAOfUF81eCv-1&scaling=scale-down&starting-point-node-id=1336%3A19384&show-proto-sidebar=1&mode=design) 

### Implementation Considerations

- The hazard product data combines the data and separate with things like \n\n, we will need to parse this and render it for better visibility
- We'll need to parse out "..." based on designs
- As a user I can share a "deep link" to a specific hazard detail
- This is related to #154 

Goals, content, styling, behavior and more are captured [in this document](https://docs.google.com/document/d/1aKfbnZV0FiO5qwELeUczNB63eKZ2I8fmFEni6fGiS5c/edit?usp=sharing)

### User feedback

- TBD

**Comment by colinmurphy01** [comment]
Confirmed with @shadkeene last sprint that the anonymized view (no zip/location) is not a risk at this time and totally feasible for MVP.

**Comment by colinmurphy01** [comment]
Deprioritizing for Sprint 3.3 based on milestone discussion.

**Comment by colinmurphy01** [comment]
Regroup next week

**Comment by kmranjo** [comment]
[Document with this writeup](https://docs.google.com/document/d/1aKfbnZV0FiO5qwELeUczNB63eKZ2I8fmFEni6fGiS5c/edit?usp=sharing) is ready for review by the rest of design. I'll update the ticket above once we have alignment. 
@partly-igor @sarahmhgov  Flagging this for review but don't expect us to get to it until after the holidays.

**Comment by kmranjo** [comment]
Design huddled on this today, it is ready to move ahead to product and eng review

**Comment by kmranjo** [comment]
That's correct - the design team reviewed it, but that's it.

**Comment by kmranjo** [comment]
Reviewed with Product, next steps are to discuss with Eng how to break into implementation tickets. Meeting with Eric to chat tomorrow and will capture outcomes here.

**Comment by kmranjo** [comment]
Met with Eric today, he's tackling the breaking up of the work into multiple eng tickets. The document can be the "one stop shop" but info can be copied into the relevant tickets as well, once they exist.

**Comment by eric-gade** [comment]
@colinmurphy01 yeah that's the idea

**Comment by colinmurphy01** [comment]
Closing and tracking with Eng tickets
- #583 
- #589  
- #590 
- #591 
- #592 
- #570
