### ISSUE TITLE
UI: Switch between languages

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#1581]
I want to switch between languages. Currently supported

- English
- Spanish
- Chinese

Considerations:
- Automatically select language based on browser settings (priority order)

Pair this with #1030

**Comment by colinmurphy01** [comment]
Considerations:
- USWDS components
- Built in Drupal module for this capability

**Comment by partly-igor** [comment]
Ticket #1985 added for engineerings
