### ISSUE TITLE
View weather on a map

### ISSUE THREAD

**Issue by janelx** [weather-gov/weather.gov#159]
### Supported user stories
- 3.7 … I want to understand when and where weather is developing according to my location (example developing precipitation in my area)
- 4.6 … I'd like to know when and where the hazard is in order to see if the hazard is approaching me or near me/specific location

### Story details: As a member of the public 
- I want to see my location
- I want to see place names and streets
- I want to zoom in an out
- I want to navigate to other parts of the map
- I want to see other unique layers that are relevant to the forecast (wind, smoke)
- I want to see radar
- I want to see a timestamp
- I want to see it animate over time

### [User Feedback](https://docs.google.com/document/d/1PX7SPyvBVDP5JAh0P3Cv-1Bmp7ZRbRE1Jzly8bzbdr8/edit)
**Users are looking for predicted storm path in a radar / GIS product** Multiple users were interested in zooming into radar to be able to read more easily, pinpoint location, and timestamps to know what time period they are looking at. Users also noted a desire to see additional information, such as radar velocity and wind direction, in a more comprehensive radar tool.

“I wasn’t sure if radar was for now, or for future, felt like it was for future and that timing should be described on the page.”

“So as my eyesight isn't the greatest, I would definitely want to expand this map just so I could get a better sense if it is my County that's affected or it's not here I can see. All right, so it's the east side of Nashville. Okay, but yeah, it would be helpful if I could get in there if I could, make it larger. So it's easier to read.”

Recommendations: 

- Show radar of future radar
- Show timestamps of last updated
- Allow users to zoom in to see legible fonts
- Show pinpoint location based on phone GPS location
- Allow users to go to more comprehensive radar / gis tool, or expand to see more layers

**Comment by colinmurphy01** [comment]
Duplicates #633
