### ISSUE TITLE
Page: view hazard info - Wireframe

### ISSUE THREAD

**Issue by janelx** [weather-gov/weather.gov#160]
**Supports flow:** [Hazard](https://www.figma.com/file/FKZbKMvnwMCOahfEIH7wfJ/sprint-2.5-%2F-MVP-flows?type=whiteboard&node-id=94-813&t=Fzwsxj2peOszEf8X-4)

### Components:
- #158 
- #154 
- #155 
- #156 
- #157 
- #159 
- #162 

**Supports user stories:** 
- E4 As a member of the public or a partner, I would like to understand the possibility, severity, and impact of a hazard
  - 4.1 As a member of the public who got a hazard alert through their weather app, I want to click a link and see the full WWA hazard
  - 4.2 … I want to be made aware of any hazards for a specific location
  - 4.3 … I want to understand at-a-glance what, where, and how bad the threat/impact level of a hazard for a specific location
  - 4.4 … I would like to know what to expect for the next 24 hours (could be more?) for a specific location
  - 4.5 … I want to understand the actions or steps I could take to save my life or property at my location
  - 4.6 … I'd like to know when and where the hazard is in order to see if the hazard is approaching me or near me/specific location

Other stories supported
- E.7 As a member of the public, I want to share info with others

Design (define/discovery):
- HMW display important hazard info in a way that is easy to understand at-a-glance to help members of the public get reliable info quickly?

### Support needed:
- Components and conditions to display

### Acceptance criteria

[will be added with design]

----

### Needed next steps:
- design/define layout details

```[tasklist]
### Review: design, function and flow:
- [ ] POs - org alignment and vision review
- [ ] Eng - feasibility & right size stories
- [ ] UX research - what and how to test
```

```[tasklist]
### Story details
-  [ ] Reviewed designs (must be attached)
-  [ ] Acceptance criteria define (added to this story)
```

**Comment by colinmurphy01** [comment]
@janelx I assume you're taking the lead with this?

**Comment by janelx** [comment]
[PD notes ](https://docs.google.com/document/d/1ZvPxmVEi8M7_P2P2_vd797W1veBHY-onlOs73UGkQ4E/edit)from partner research sessions to help inform design/define wireframes

**Comment by colinmurphy01** [comment]
Moving this to done as we incorporate this into our research materials
