### ISSUE TITLE
R7 iterations (tabs, layout)

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#1616]
### Design implementation tickets
- [x] https://github.com/weather-gov/weather.gov/issues/1918
- [x] https://github.com/weather-gov/weather.gov/issues/1925
- [x] https://github.com/weather-gov/weather.gov/issues/1926
- [x] https://github.com/weather-gov/weather.gov/issues/1928

### Bugs to fix
- [x] https://github.com/weather-gov/weather.gov/issues/1916
- [x] https://github.com/weather-gov/weather.gov/issues/1917

Related #1374

**Comment by colinmurphy01** [comment]
Blocked by #1373

**Comment by colinmurphy01** [comment]
@colinmurphy01 will schedule a catch up with @partly-igor and you all on this work, so that we can chunk out the design and eng tickets together.

This work is prioritized to be done and in beta by 10/18

**Comment by partly-igor** [comment]
Updated with documentation/designs for the Today tab

**Comment by eric-gade** [comment]
Starting a checklist of related implementation tickets. First is the today tab changes

**Comment by colinmurphy01** [comment]
Do you want this to be the "by 10/18" ticket?

**Comment by colinmurphy01** [comment]
@partly-igor will infish creating UX tickets and link them here + assign to @eric-gade to be reassigned if necessary.

**Comment by partly-igor** [comment]
I believe I've now added all the implementation tickets with their respective documentation. If anything is missing please let me know.
