### ISSUE TITLE
Links to AFD pages

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#1617]
Once we complete AFDs, we need a means for people to find them.

Right now in [the mockup](https://www.figma.com/proto/w2QI2uTgaTWUPLHLi40mm1/Weather.gov-%E2%80%93-v0.2?page-id=9111%3A11215&node-id=9111-18585&viewport=278%2C40%2C0.27&t=0SiMoDewy4Co2OYQ-8&scaling=scale-down&content-scaling=fixed&starting-point-node-id=9111%3A11217&show-proto-sidebar=1&hide-ui=1) it’s only visible within a weather story, we don’t account for the current use case of there are no weather stories (which is right now). 

**^Update:**
We can display the link in the space where Weather Stories live, even if there is no weather story. For now that means that the link will the first item on the 7 days page, but that will be updated once #1616 is implemented. 

The other space we would like to include a link to the the AFD is on the WFO page. Note the technical consideration below. 
[Figma mockup](https://www.figma.com/design/w2QI2uTgaTWUPLHLi40mm1/Weather.gov-%E2%80%93-v0.2?node-id=9942-4962&t=Stc9X7inHUwgMRMr-4). 

Technical consideration:
- The AFD page will need to know what WFO WCA you're coming from in order to render the correct AFD for that user (based on convo with @eric-gade)

**Comment by partly-igor** [comment]
The link to the AFD could live within the space dedicated to the weather story, but can be separate from the story itself, so that even if there isn't a story the links can show.  This will be true once we implement #1616 as well.
