### ISSUE TITLE
Scope -  Find

### ISSUE THREAD

**Issue by janelx** [weather-gov/weather.gov#162]
### Supported user stories

- Flows / User story - design details
- 4.6… I'd like to know when and where the hazard is in order to see if the hazard is approaching me or near me/specific location

### Story details: As a member of the public 
- View a hazard on a map relative to a specific location

### Design (define/discovery)
- HMW automate an accessible and reliable way to let people know if a hazard is approaching a specific location?

### Support needed
- Radar map of a location
- Define/discovery needed: 
  - Other relevant maps and conditions to display

### Acceptance criteria
[will be added with design]

----
### Needed next action: design & define
- Design view
- Collab/consult w/Kari on best assets to use for different hazards [events] 

```[tasklist]
### Review: design, function and flow:
- [ ] POs - org alignment and vision review
- [ ] Eng - feasibility review
- [ ] UX - what and how to test
```

```[tasklist]
### Story details
-  [ ] Reviewed designs (must be attached)
-  [ ] Acceptance criteria define (added to this story)
```

**Comment by colinmurphy01** [comment]
Duplicate #568
