### ISSUE TITLE
Plan/Recruit: R8 - Unmoderated Visualization Usability test

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#1620]
- [x] Submit to use usertesting.com
- [ ] Write up scenarios

**Comment by sarahmhgov** [comment]
I've submit and got approval to use usertesting.com the week of Oct 8th

**Comment by sarahmhgov** [comment]
Started this doc to start thinking about task https://docs.google.com/document/d/1BkKtu37TYcmWdMRFg9bcmWb_OjDk5MD_qfRskrq5q3g/edit

**Comment by colinmurphy01** [comment]
Mobile round
