### ISSUE TITLE
WFO page session alert showing?

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#1626]
I got a weird bug when looking at my local WFO's page

![Image](https://github.com/user-attachments/assets/2d89cb87-7fca-498a-aa20-3ff3ff36ee5d)

URL: https://beta.weather.gov/offices/CLE#

**Comment by greg-does-weather** [comment]
Were you previously logged in?

**Comment by colinmurphy01** [comment]
I haven't logged in a while (days, maybe weeks).

**Comment by colinmurphy01** [comment]
Unable to reproduce today. Closing and monitoring.
