### ISSUE TITLE
Explore disconnect between what observation data is in MADIS and what's in API

### ISSUE THREAD

**Issue by shadkeene** [weather-gov/weather.gov#1627]
Will need to dig in to MADIS and API connection to see if there is low-hanging fruit/changes that could support API receiving more observational data (coverage/types/ob frequency).

MADIS map: https://madis-data.ncep.noaa.gov/MadisSurface/

**Comment by colinmurphy01** [comment]
Added to API agenda tomorrow

**Comment by colinmurphy01** [comment]
Discussed in API Sync:
- API team will add ticket to query all stations based on location
- Will also provide station metadata (in order to differentiate between ASOS, CWOP, etc)

**Comment by shadkeene** [comment]
added station metadata ticket in JIRA. closing now.
