### ISSUE TITLE
Migrate research insights airtable to google sheets

### ISSUE THREAD

**Issue by sarahmhgov** [weather-gov/weather.gov#1636]
Migrate research insights airtable to google sheets

**Comment by sarahmhgov** [comment]
Google sheets: https://docs.google.com/spreadsheets/d/1NMqDTz5w5ZCmOAK_sZ8iRO67AqL3anJLDJVkesMo9MY/edit?gid=0#gid=0 

from airtable: 

https://airtable.com/appNGZfrPxwyV6AbL/tblutnbY1mIGLa5ck/viwecI9D0k2g2XBQ3?blocks=hide

**Comment by colinmurphy01** [comment]
Is this something LANTERNs can also help with in the future?

**Comment by sarahmhgov** [comment]
Potentially - I suppose there's some similarity in basically coding/ categorizing feedback and research insights.
