### ISSUE TITLE
Doc: Monitoring needs

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#1641]
Considerations for documentation
- What's moving us up to NewRelic subscription
- What options are in the market 
- Buy vs. Host

**Comment by colinmurphy01** [comment]
Once reviewed across the team we'd take this proposal to the Chris for review and next steps - ideally not getting too caught up on pursuing a perfect solution for the org and one that can maintain our velocity without causing long-term issues.

**Comment by colinmurphy01** [comment]
@jamestranovich-noaa can you review the open comments and see if ay can be resolved. We can then send this over, this sprint.

**Comment by jamestranovich-noaa** [comment]
Updated document and resolved comments. I would like to get an update on where we are in terms of budget and then we can send it over?

**Comment by colinmurphy01** [comment]
Follow on #2034

**Comment by jamestranovich-noaa** [comment]
@colinmurphy01 @mel-keene-gsa i'd like to close this ticket -- which was really about writing up our monitoring needs -- and open new issues when we have concrete next steps for monitoring. Right now it seems to be an ongoing conversation. thoughts?

**Comment by colinmurphy01** [comment]
Agree, this can be closed. I'll leave you to it.
