### ISSUE TITLE
Doc: Github (public), Gitlab (deployment) proposal options

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#1642]

**Comment by jamestranovich-noaa** [comment]
drafted a rough [proposal](https://docs.google.com/document/d/1RE7RUdO37Uk30et7pqFj0V5QuQuM_UD4Y5xpJThuDfc/edit) -- comments welcome.

**Comment by jamestranovich-noaa** [comment]
What do I need to do here to close this ticket? :thinking:

**Comment by colinmurphy01** [comment]
- I'll find time so you can brief the team on the proposal and next steps. 
- In the meantime, can you document the chunks of work into however many tickets make sense
- Close this ticket

**Comment by jamestranovich-noaa** [comment]
Perfect. I've broken up phase 1 tickets into Github issues; phase 2 tickets should be Gitlab (!) issues so I've made a catch-all for phase 2 (see below).

Phase 1:
- #1707 
- #1708 
- #1710 
- #1712 
- #1713 

Phase 2:
- #1714 

We can add more to phase 1 or phase 2 as we continue conversations with the team (I see that we have a meeting next Tuesday). I'll close this for now -- feel free to reopen if there's still something else we need to do here.
