### ISSUE TITLE
CI page load tests often fail 

### ISSUE THREAD

**Issue by jamestranovich-noaa** [weather-gov/weather.gov#1654]
### Description

We have a recurring issue where page load tests often fail (as a Github workflow: `page-load-time-tests`). Sometimes they are just barely passing ([100ms difference](https://github.com/weather-gov/weather.gov/actions/runs/10582158091/job/29322373875?pr=1650)) but we would like to look at this problem holistically, since the API shouldn't be part of the timings (or at least should be a finite time) so we can get more precise timings.

### Acceptance criteria

- [ ] Tests have been implemented or modified to capture the bug
- [ ] Changes have been tested for accessibility

**Comment by colinmurphy01** [comment]
I think this is related or a duplicate for #1675. Can you confirm?
