### ISSUE TITLE
Document compliance workflows and processes

### ISSUE THREAD

**Issue by jamestranovich-noaa** [weather-gov/weather.gov#1662]
### Description

We should document, even if it is just an internal document, how we track compliance progress, as well as how the compliance process itself works. Especially if others want to be involved, we need to keep track of what controls need to be implemented, revised, updated, etc.

### Acceptance criteria

An internal document of some sort?

**Comment by colinmurphy01** [comment]
When do you think we should pick this up?

**Comment by colinmurphy01** [comment]
@jamestranovich-noaa can you provide an update with this ticket? Have you picked this up?

**Comment by jamestranovich-noaa** [comment]
This is still in progress. Latest update: SSP is delayed due to the discovery of older cloud.gov rev4 controls in the CRM; it's on my plate now to submit a FedRAMP package access request.

**Comment by colinmurphy01** [comment]
Should we move this to `blocked` then?

**Comment by jamestranovich-noaa** [comment]
Done. https://docs.google.com/document/d/1XhU7R3qCjYstcjdCz2V7TUhdTnD3WRRDkIlJbMgjnU0/edit?tab=t.0
