### ISSUE TITLE
AFD for Alaska.

### ISSUE THREAD

**Issue by coreypieper** [weather-gov/weather.gov#1681]
There is an issue with the forecast discussion link on the beta site for locations within the WFO Anchorage CWA. This is likely due to confusion with the dual domains they have. So they have dual GFE domains which have identifiers of (ALU and AER). However, products that cover their entire CWA, like the AFD, still utilize their overall WFO identifier AFDAFC. 

The link to the AFD on the beta site currently is: https://beta.weather.gov/afd/AER. This of course returns an error because AFDAER does not exist.

Consideration
- Could this be done in twig via urls

**Comment by eric-gade** [comment]
Note to self that we also need to handle the 404 case here in such a way that the whole site doesn't break

**Comment by jamestranovich-noaa** [comment]
I think the 404/500 is related to https://github.com/weather-gov/weather.gov/issues/1729

**Comment by coreypieper** [comment]
At [this page](https://beta.weather.gov/point/61.217/-149.9?#daily) for Anchorage, the AFD link above the forecast doesn't work, and there is no Your Local Forecast Office link below the forecast.
