### ISSUE TITLE
Oct 1, 2024 WWA priority/product changes

### ISSUE THREAD

**Issue by coreypieper** [weather-gov/weather.gov#1697]
Here are the changes upcoming for the WWA priority order (Oct 1).
https://www.weather.gov/help-map/
https://www.weather.gov/media/nws/WWA_Changes_10124.pdf
https://www.weather.gov/media/notification/pdf_2023_24/scn24-75_wwa_map_priority_changes_aaa.pdf 

There are a number of changes noted in the SCN.

Implementation:
- Update alert priorities
- Names
- Would need to be done in interop layer as well

Create PR and then wait till Oct 1 to deploy to staging/cut a release to beta as well

**Comment by greg-does-weather** [comment]
In addition to the priority changes, which are pretty easy to follow, can I clarify what I think I see in the PDF?

* `Wind Chill Warning` is removed entirely
* `Hard Freeze Warning` is removed entirely
* `Hurricane Local Statement` is renamed `Tropical Cyclone Local Statement`
* `Wind Chill Advisory` is removed entirely

Are these correct?

**Comment by colinmurphy01** [comment]
@coreypieper to review and confirm

**Comment by coreypieper** [comment]
One change and two additions to @greg-does-weather's list noted below.

- `Wind Chill Warning` is removed entirely
- `Hard Freeze Warning` is removed entirely
- `Hurricane Local Statement` is renamed `Tropical Cyclone Local Statement`
- **CHANGE:** `Wind Chill Advisory` is renamed `Cold Weather Advisory`
- **ADDITION:** `Hard Freeze Watch` is removed entirely
- **ADDITION:** `Wind Chill Watch` is removed entirely

**Comment by greg-does-weather** [comment]
Closed by #1802
