### ISSUE TITLE
Draft a doc for a QASP/OTE

### ISSUE THREAD

**Issue by mgwalker** [weather-gov/weather.gov#17]
Get that in front of Bert (OPPSD) as a working doc we can refine over the next 3 months

**Comment by cannandev** [comment]
See Slack conversation https://gsa-tts.slack.com/archives/C04TCUMF2TF/p1685120870888479?thread_ts=1684948137.818679&cid=C04TCUMF2TF

**Comment by colinmurphy01** [comment]
To-dos

- Draft of standards
- Propose and get feedback with Warrick's team
- Finalize and share amongst core team

**Comment by colinmurphy01** [comment]
@greg-does-weather can you add the doc to this ticket?

Status: I think we had alignment on the code quality standards and some questions that can be clarified from Bert. The System requirements were things we should document and address - that's a to-do for Warrick's team and could be documented for ATO or an SLA-type doc.

**Comment by greg-does-weather** [comment]
The doc itself is authored in #203. The notes from the conversation are here: https://docs.google.com/document/d/1yVPG2XV1HhlsQ8p4upZwWjJ4H5-0qEmaFSihldAu_jc/edit#bookmark=id.4cuk6npnw1ir

At sprint planning, we can prioritize updating the QASP based on Bert's feedback and then get it merged. We can continue to update it, but I'd like to get it into the repo soon. There are multiple things we'll need to address, and the QASP only covers a subset (code and pipeline **_quality_**, not processes).

**Comment by colinmurphy01** [comment]
That sounds good to me. Let's make sure the QASP has that purpose statement included.
