### ISSUE TITLE
Set chart widths dynamically

### ISSUE THREAD

**Issue by greg-does-weather** [weather-gov/weather.gov#1702]
### Description

In the first implementation of our charts, they are fixed at the width of their containers and all of the available data is smooshed into the charts. For charts showing longer periods of time, this can make the chart difficult to read.

Instead of fixing the chart's width to its container, we would like to dynamically determine the chart's width based on two factors:
- an explicit width for the hours on the X axis
- the number of hours being displayed

The chart container should clip the horizontal part of the container that extends beyond the container itself, and the container should support scrolling. Scrolling will also be accompanied by scroll buttons similar to the hourly details table.

The width of a single hour on the X axis should be variable based on which screen width break points we're currently in, and per type of chart. As a result, when the screen crosses break point thresholds, the chart width needs to be recomputed and the chart needs to be redrawn accordingly.

#### Chart widths
|Chart type|mobile|mobile-lg|tablet|tablet-lg|desktop|
|---|---|---|---|---|---|
|line|720|720|940|951|951
|bar|720|720|940|951|951

### Acceptance criteria

- [ ] Charts are sized appropriately according to the descriptions above
- [ ] Changes have been tested for accessibility

Related #1766

**Comment by greg-does-weather** [comment]
tbd: we'll figure out what the widths should be and fill those in

**Comment by partly-igor** [comment]
I have tested out different widths for the chart and believe that setting the chart width itself may allow us to achieve this effect. After manually testing out different options I have come with the set that I've added to the top of the ticket. This allows for the following number of visible hours at the smallest (hours min) and largest sizes (hours max) within a breakpoint. (Hours may be off by 1 :) )


Viewport Size | Breakpoint | Chart width | #Hours  Min | #Hours Max
-- | -- | -- | -- | --
Mobile | 0 | 720 | 9 | 13
Mobile-lg | 480 | 720 | 15 | 21
Tablet | 640 | 940 | 15 | 23
Tablet-lg | 880 | 951 | 21 | 25
Desktop | 1024 | 951 | 25 | 25

**Comment by partly-igor** [comment]
Completed via #1858
