### ISSUE TITLE
Create uploader user on beta.weather.gov

### ISSUE THREAD

**Issue by jamestranovich-noaa** [weather-gov/weather.gov#1718]
### Description

As a one-time step, we want to create an `uploader` user that remains on beta.weather.gov and will not be wiped out by any changes. The username/password should be generated randomly (via `uuidgen`) and stored via cf environment variables.

### Acceptance criteria

- [ ] we have an `uploader` user for external uploads

**Comment by colinmurphy01** [comment]
Is this part of DSSBuilder integration?

**Comment by jamestranovich-noaa** [comment]
Done. But we still have upload issues, that should be a separate issue though.
