### ISSUE TITLE
Styling and Imagery: Weather for a location

### ISSUE THREAD

**Issue by janelx** [weather-gov/weather.gov#174]
**Supports flow:** [basic weather](https://www.figma.com/file/2bDju7teT0H71ldhCkYORF/Weather.gov-2.0-MVP-Flow-%2F-Share-doc?type=whiteboard&node-id=1-197&t=MAvYDAGQ62WFG0Pf-4)

### Components
- #175 
- #177  
- #178  
- #179  
- #180  
- #181  
- #3.v7 weather on a map (might be similar to #159  )
- #154  (used on 3 layouts - conditional for with location and without location)
- #299 

**supports user stories:** 
- E3 As a member of the public or a partner, I can understand basic weather information for a specific zip code/area
  - 3.1 … I want to understand that the weather information I'm seeing is relevant to my specific location
  - 3.2 … I want to view current conditions
  - 3.3 … I want to view short and longer term weather forecasts
  - 3.4 … I want to read a summary of the weather trends and impact 
  - 3.5 … I want to understand when the information was last updated so that I know it’s relevant and not stale
  - 3.6 … I want to know who created the forecast in order to trust that the person is familiar with this location and its unique needs/culture
  - 3.7 … I want to understand when and where weather is developing according to my location (example developing precipitation in my area)

Other stories supported:
- 4.2 … I want to be made aware of any hazards for a specific location

### Support needed:
- Browser location 
- Browser remembering location (second visit)
- Define/discovery needed: 
  - conditionals for hazard alerts to show

### Acceptance Criteria 
[will be added with design]

----
### Needed next steps:
- Design/define layout details

```[tasklist]
### Review: design, function and flow:
- [ ] POs - org alignment and vision review
- [ ] Eng - feasibility & right size stories
- [ ] UX research - what and how to test
```

```[tasklist]
### Story details
-  [ ] Reviewed designs (must be attached)
-  [ ] Acceptance criteria define (added to this story)
```

**Comment by colinmurphy01** [comment]
Deprioritized for this sprint because there is more substantial work here to be done.

@janelx for next sprint, I do like the idea of partially executing this with a wireframe to help the devs. For sprint planning next week, consider that in prioritization and maybe break that off as a ticket?

**Comment by janelx** [comment]
That sounds good. Will do.

**Comment by colinmurphy01** [comment]
Updated title to reflect the styling/imagery work identified that we'll take on later.

#248 will reference the wireframing work.

**Comment by colinmurphy01** [comment]
Closing this and tracking this work with #377. So that this can referenced for posterity and not edited.
