### ISSUE TITLE
Flag vulnerabilities for pull requests

### ISSUE THREAD

**Issue by jamestranovich-noaa** [weather-gov/weather.gov#1750]
### Description

Let's use https://github.com/actions/dependency-review-action for flagging vulnerabilities during PR reviews too, and not just when they are merged into `main` (Dependabot only scans `main`). 

Relevant GH docs: https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/about-dependency-review#dependency-review-enforcement

This action also optionally checks for incompatible licenses.

### Acceptance criteria

- [ ] We flag vulnerable libraries automatically as part of PR reviews

**Comment by colinmurphy01** [comment]
This feels important. Is this something we should consider doing soon? Or should we wait to do this till we migrate to Gitlab?

**Comment by jamestranovich-noaa** [comment]
I think we should do it now, it's a simple lift and we're running into this periodically since we have long lived branches (such as the interop api layer work). And we definitely should have the same (or better) on Gitlab. You can  assign this issue to me.

**Comment by colinmurphy01** [comment]
that detail helps. I'll mark it as `high` for next sprint
