### ISSUE TITLE
Add extra fields to our WFO PDF upload Drupal content type

### ISSUE THREAD

**Issue by jamestranovich-noaa** [weather-gov/weather.gov#1752]
### Description

We have a [sample DSS packet](https://www.weather.gov/source/eax/dsspacket.xml) and a [sample PDF](https://www.weather.gov/media/eax/DssPacket.pdf) for reference. 

Looking at this, and also comparing fields with the Weather Story ([sample](https://www.weather.gov/source/pih/WxStory/WeatherStory.xml)) we want to add these extra fields and mark them as optional:

- `StartTime` (Unix epoch time)
- `EndTime` (Unix epoch time) 
- `Order` (integer)
- `FrontPage` (boolean)
- `Title` (CDATA string)
- `Description` (CDATA string)

We believe (but cannot verify) that the only tags that are used are `StartTime`, `EndTime`, `Title`, and `Description`. But until we can verify, I would err on the side of gathering more data than we strictly need.

Questions to consider: 

- if we get extra data in the payload, what happens? Can we capture these somehow?
- should we also broaden the file type to accept pngs and whatever kinds of images that WeatherStory might have? can we repurpose this content type to accept WeatherStory data as well?

### Acceptance criteria

- [ ] `wfo_pdf_upload` content type fields above are added and optional
- [ ] Outside test that confirms that we can upload with extra fields

**Comment by colinmurphy01** [comment]
Is this a duplicate to #1887 @jamestranovich-noaa?

**Comment by jamestranovich-noaa** [comment]
Yes! Thank you for the catch. Closing this one in favor of #1887
