### ISSUE TITLE
Visualization datapoint labels cut off. 

### ISSUE THREAD

**Issue by coreypieper** [weather-gov/weather.gov#1766]
When values on the bar graphs that top out at 100% have data close to 100, the labels are cut off. 
![IMG_6757](https://github.com/user-attachments/assets/104e6c78-85fb-4067-93ec-5ae190229535)

Additionally, sometimes x axis values are not showing up at all on iphone SE and Android/Pixel 7a. We were only able to reproduce when bars are ≥95%.  

![image](https://github.com/user-attachments/assets/d23fad9f-0f9e-4228-aece-9e52ec36dc1e)

**Comment by colinmurphy01** [comment]
@igorkorenfeld and @eric-gade do you have capacity to look into this when you pick up #1702?

**Comment by colinmurphy01** [comment]
Hurricane this week might have conditions that can be used for testing.

**Comment by partly-igor** [comment]
Noting that #1858 helped but didn't totally get rid of the issue for x-axis. 

The pattern I am seeing is that the x-axis labels disappear only for the "Today" bar charts whenever the first hour is odd numbered (for example 3pm, 5pm, etc..). Notably we skip labels for odd hours on the bar graph, and it may be somehow related to that. The x-axis labels do display when the first hour is even-numbered, so it doesn't seem like the chart width being too narrow is the issue, but perhaps specific chart widths do create that problem.

**Comment by greg-does-weather** [comment]
To clarify, the thing where the labels on the chart itself were being cut off is resolved, right? The remaining issue is the X axis labels?

**Comment by partly-igor** [comment]
That's right – and cool, I forgot we only did it for temperatures so that sounds like a good plan!
