### ISSUE TITLE
e3.v2 short term forecasts (hourly)

### ISSUE THREAD

**Issue by janelx** [weather-gov/weather.gov#177]
Product flow (in figma): [From weather.gov](https://www.figma.com/file/2bDju7teT0H71ldhCkYORF/Weather.gov-2.0-MVP-Flow-%2F-Share-doc?type=whiteboard&node-id=1-197&t=4fI7ZiRfDaM0r8hF-4)

### Supported user stories
- 3.3 … I want to view short ~~and longer~~ term weather forecasts 
  - long term forecast story is here #178 

### Story details: As a member of the public 
- I am able to understand what the basic weather will be for each hour for the next 4 hours

### Design (define/discovery)
- Completed during prototype phase

### Support needed
- Weather API (forecastHourly, forecastGridData)
- Weather icons
- Speech to text for summaries (need to discuss between PD, eng, and PM if part of this issue)

### Acceptance criteria
[Criteria outline in figma](https://www.figma.com/file/0dSABt9zCqoknaKua6DHmP/NOAA---Weather.gov?type=design&node-id=345-2238&mode=design)
**As a member of the public I can easily understand:**
- [ ] what the weather will be for each hour for the next 4 hours for a specific location
**Additional UX research/continuous discovery**
- [ ] Qualitative experience of accessibility:
  - [ ] Screenreader experience of listening to the weather components
  - [ ] Experience of navigating weather data for screenreader, select, keyboard shortcuts
- [ ] Are we showing the most accurate and useful data?
  - [ ] For is it accurate/useful information to show PoP in the contents of the weather icon? API response examples.
- [ ] Is it easy to understand? Is the understanding accurate (enough to make a decision)?

----
### General
- [ ] Responsive
- [ ] USWDS friendly
- [ ] Section 508 compliant

### Short term forecasts >= tablet  - 12 col grid

<kbd><img width="583" src="https://github.com/weather-gov/weather.gov/assets/93934808/7801252c-a78a-4616-a1eb-9b80d29a387b.png"></kbd>

**Hour title (12 PM, 1 PM, etc)**
- [ ] h3
- [ ] hourly beginning with next hour. Ex. If it is 11:01 to 11:59 show for 12 PM, 1 PM, 2 PM and 3PM (four hours)
- [ ] time zone is relative to the forecast location not browser location

**Conditions (icon and description)**
- [ ] NOAA weather icons - max height: 64px or max width: 72px
- [ ] Icon description from Icons api
- [ ] text: 'body'

**Chance of precipitation:**
- [ ] Probability off precipitation as a percentage [probabilityOfPrecipitation]
- [ ] 12 px / gray-cool-50

**Temperature** 
- [ ] temperature in Fahrenheit, [temperature], [temperatureUnit]
- [ ] font-size:32 (or nearest utility class) 
- [ ] degree f font size: 12

**Mobile**
<kbd><img width="225" alt="image" src="https://github.com/weather-gov/weather.gov/assets/93934808/5d8a5ba7-4258-4997-86ed-5919c5ac1271">
</kbd>

### Review: design, function and flow:
- [x] POs - org alignment and vision review
- [x] Eng - feasibility review
- [x] UX - what and how to test

### Story details
-  [ ] Reviewed designs (must be attached)
-  [ ] Acceptance criteria define (added to this story)

**Comment by janelx** [comment]
summary/reflection from conversation on showing probability (conversation in slack and meetings):

**hypothesis:** it is useful for people to at-a-glance
1.  understand the probability of precipitation and the type of precipitation
2. understand the probability of certain weather conditions (ex. thunderstorm, blizzard, rain, etc)

**Questions:**
- Can I design a uncluttered view that accurately displays both? (i will try next week)
- Are there probability data points for other weather conditions like blizzards, tropical storms, etc? Are there useful correlations with prob of precip or any other data points?

**Assumptions**
- We are not tackling display/indicators of  intensity or associated WWAs in this story - but will in the hazard alert stories - this may slightly adjust layout
- There will likely need to be a detailed view of weather, where we can display lower priority data -> maybe future iteration

**Challenge**
- What is a lean design/build to begin learning from?
- Viewing/testing the diversity of data, contexts, and possible correlations

**Comment by colinmurphy01** [comment]
I think this has been through some mix of Design, Eng, and PO Review. 

When the outcomes of the discussion (above) are addressed, I'm assuming this shouldn't need to go through review again? Or should go through async review? What are your thoughts @janelx? I'm trying to use this as a precedent for managing reviews in the future.

**Comment by janelx** [comment]
@colinmurphy01 it's needs at least PO review when the above is sussed out.

**Comment by janelx** [comment]
Update on review status: posted options for displaying PoP vs Chance on slack for @shadkeene to review. Reviewed with design this morning, and reviewing w/engineers this afternoon.

**Comment by janelx** [comment]
[Link to outline](https://drive.google.com/file/d/1s6Va3_YyJ3t5C6wlXEKlNYxPvSUzKq6j/view?usp=drive_link) of pros/cons using PoP vs Chance

**Comment by shadkeene** [comment]
@janelx @colinmurphy01  Design a) approved from PO perspective.  Had good tagup with Janel on this.  Few key things we need going forward are to be able to view multiple sites at once during development for q/c in different weather situations...and to understand what numbers/words show up in API when there are 2+ precipitation types.

**Comment by janelx** [comment]
+ added under ux research/continuous discovery - want to measure the usability and accuracy of using this diplay and datapoints (Chance/PoP). This isn't a blocker - it's just to make sure we are accounting lower confidence pieces of the design we just won't know till we are able to look at more combinations of weather types and corresponding data. Also, maybe able to get some useful insight from HazSimp researchers.

**Comment by colinmurphy01** [comment]
I think this is ready for dev for this sprint, I'm going to move this to to-do and tag it as **Eng**

**Comment by greg-does-weather** [comment]
We currently don't have a convenient way to get the timezone information for a WFO grid point.

What we'll have to do for now, I think, is use the WFO grid coordinates to hit the API's `/points` endpoint a second time, because that does return timezone information.

**Comment by colinmurphy01** [comment]
Claire to-dos for w/o 11/06:
- Now: Stubbed Desktop and Mobile version (will have PR for that)
- Next: Design review
- Next: Design fixes
- For greg upon return: Integrating with API
