### ISSUE TITLE
Investigate uploads on beta.weather.gov

### ISSUE THREAD

**Issue by jamestranovich-noaa** [weather-gov/weather.gov#1778]
### Description

PDF uploads seem to be different when we upload them via beta.weather.gov. Needs some investigation as to why the beta environment is different.

### Acceptance criteria

- [x] Tests have been implemented or modified to capture the bug (outside tests)

**Comment by jamestranovich-noaa** [comment]
Yes, I'm also fixing this bug for this sprint! Also because I want to demo this feature next Friday!

**Comment by jamestranovich-noaa** [comment]
Fixed: https://beta.weather.gov/node/93

Outside tests for this particular bug coming soon.

**Comment by colinmurphy01** [comment]
Moving this to `doing`
