### ISSUE TITLE
Plan funding for FY25 for Weather.gov 2.0 and associated efforts

### ISSUE THREAD

**Issue by shadkeene** [weather-gov/weather.gov#1779]
Plan funding for all efforts associated with Weather.gov 2.0.  Much already done but need to finalize numbers for FY25.

**Comment by colinmurphy01** [comment]
How's this going? What are the next steps?

**Comment by colinmurphy01** [comment]
Is this `done`?

**Comment by colinmurphy01** [comment]
Is this `done`?

**Comment by shadkeene** [comment]
I think the unknowns are very minor at this time, but yep, we're constrained by what we've already discussed, so let's close this.
