### ISSUE TITLE
e3.v4 content last updated (ref: flow)

### ISSUE THREAD

**Issue by janelx** [weather-gov/weather.gov#179]
### Supported user stories
- Suspect that this just needed for current conditions for a location #175 vs layout view

### Story details: As a member of the public 
- 

### Design (define/discovery)
- 

### Support needed
- 

### Acceptance criteria
[will be added with design]

----
### Needed next action: design & define

```[tasklist]
### Review: design, function and flow:
- [ ] POs - org alignment and vision review
- [ ] Eng - feasibility and right-size
- [ ] UX - what and how to test
```

```[tasklist]
### Story details
-  [ ] Reviewed designs (must be attached)
-  [ ] Acceptance criteria define (added to this story)
```

**Comment by colinmurphy01** [comment]
Will this be included in individual components (like current conditions, weather story) or is it it's own feature?

**Comment by janelx** [comment]
Currently it's displayed once. Need to discuss with engineers to determine what makes the most amount of sense, depending on what it returns.
