### ISSUE TITLE
Update weather story component

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#1793]
Placeholder Eng ticket for #1739 and blocked until then

Dependency - #1921 

This would require:
- Acting as DSS Builder, get the XML file from the specific office from prod ([example](https://www.weather.gov/source/lmk/wxstory/wxstory.xml))
- Image size compression is done for demo
- Priority for demo
  - Show placement on page
  - Show hierarchy of content within component
  - Show styling (BONUS, not required)
  
[Figma documentation](https://www.figma.com/design/w2QI2uTgaTWUPLHLi40mm1/Weather.gov-%E2%80%93-v0.2?node-id=13112-306091&node-type=frame&t=kqQsalojRQcyos73-11)
[Context/designs](https://www.figma.com/design/w2QI2uTgaTWUPLHLi40mm1/Weather.gov-%E2%80%93-v0.2?node-id=13113-313079&node-type=frame&t=kqQsalojRQcyos73-11)
[New icon for AFD](https://drive.google.com/file/d/1hCqhutIOZ-UrYubOhKqLMzSvepU8efxz/view?usp=drive_link)

**Comment by colinmurphy01** [comment]
This is work that's been prioritized for 10/18.

**Comment by colinmurphy01** [comment]
@colinmurphy01 to add detail for delivery by 10/18, likely without DSS builder integration completed.

**Comment by colinmurphy01** [comment]
@eric-gade I think you were working on the desktop layout and changes @partly-igor had in [this slack thread](https://gsa-tts.slack.com/archives/C05DU11D4J2/p1729791044250799)

**Comment by colinmurphy01** [comment]
Now that we've moved the AFD link within this component, we'd like for the AFD link to be present on the page even if there isn't a weather story.

**Comment by greg-does-weather** [comment]
Closed by #2027, #2004, #2017, #2057
