### ISSUE TITLE
IOC User Journey / Content Strategy Deck

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#1794]
As a complement to [this deck](https://docs.google.com/presentation/d/1xcrXpe4p5cLaEvgDUG2UP-JRsJ3kpaihMezz1P5rpIw/edit#) it'd be helpful to have content models/wireframes in order to demonstrate the type of information that will be available to a user. 

Example narrative, playing off of `How we're expanding the site` and `what's going to change`:

As a new coach of the Shaker Heights High School soccer team (forgive using my local area)
- I am able to view my local, active alerts/outlooks, conditions, and forecast for the day and week (looking for precip and heat risk in particular)
- I am able to understand the forecast because it's in my preferred format:
  - Graphics/Written summary `weather story via DSS builder`
  - Data `table`
  - Graphs `graphs`
- If I'm interested, I read further details `AFD via AWIPS/API`
- If a hazard is developing or active:
  - I'm able to view the hazard, on a map, with actionable safety tips `hazard in beta`
  - I'm able to read more into safety information for this hazard - `wireframe of national safety page`
  - I'm able to come back and monitor conditions as it gets closer to practice `screengrab radar and satellite via radar.weather.gov and NESDIS`
- I want to know who and how the forecast is made, and if I can reach out with questions - `wireframe of WFO page and note Center, Program pages in future`
- I may not know and want to know the seasonal weather/hazard trends for Ohio (especially if I'm knew or visiting) - `wireframe of state weather/safety pages + future tag` 
-  I am able to view and explore risks and relevant information across my county, state, or the country in order to see what else is happening or could be coming `wireframe of county page`
- In addition to this user, we will also support the most important needs of :
  - users monitoring weather across regions and the entire US (public and general partners)
  - marine and coastal users (public and general partners)

**Comment by kmranjo** [comment]
I've got the first full draft of this built out in the deck (slides 45-62) and ready for review

**Comment by colinmurphy01** [comment]
Love the journeys and the way everything is threaded together. I added some notes. Has this been reviewed by Design?

**Comment by kmranjo** [comment]
Not yet, just finished it this morning. I can bring it to design coworking tomorrow.

**Comment by colinmurphy01** [comment]
@kmranjo can you write up the alternative EM persona to Thomas and then we can call this done?

**Comment by kmranjo** [comment]
Sure - where did we land on the scenario? I think I had proposed a hospital admin and winter weather, but not sure I got confirmation on it.

**Comment by colinmurphy01** [comment]
Let's roll with winter weather for now. It'll be relevant for the next 6 months

**Comment by kmranjo** [comment]
Ok, updated it with that scenario. Take a look and if it's all good then this can be closed out

**Comment by colinmurphy01** [comment]
Moved into it's own deck so it's easier to find for future presos: https://docs.google.com/presentation/d/1mKUrKNce_G1RSTBdHshWFyJ6zHvKRAn2z5wLwD1fBQc/edit?usp=drive_link
