### ISSUE TITLE
[interop layer] Add AFD parsing and tests to interop

### ISSUE THREAD

**Issue by eric-gade** [weather-gov/weather.gov#1796]
### Description
We need to rewrite the AFD parser in JS and add to the interop layer. Additionally, we should transliterate the corresponding parser tests.

### Acceptance criteria

- [ ] AFD parsing is handled by the interop layer
  - [ ] the bug identified in #1830 is addressed
- [ ] Tests within the interop layer capture the same capabilities as the current tests
- [ ] PHP-side templates / classes are updated to use parsed markup from the interop, rather than creating markup themselves

**Comment by colinmurphy01** [comment]
@eric-gade we're temporarily assigning this you for this sprint, we can regroup when you're back.

**Comment by colinmurphy01** [comment]
@eric-gade assigning this to you for this sprint, let us know if you have questions or concerns.

**Comment by greg-does-weather** [comment]
Closed by #2030
