### ISSUE TITLE
e3.v5 weather story

### ISSUE THREAD

**Issue by janelx** [weather-gov/weather.gov#180]
### Supported user stories
E3 … As a member of the public or a partner, I can understand basic weather information for a specific zip code/area
E3.4 … I want to read a summary of the weather trends and impact

### User Acceptance Criteria
As a member of the public or partner, I understand the upcoming weather trends and how they will impact me. 

### Design (define/discovery)

**Component name:** Weather story

**Purpose**
Provide an open space for forecasters to communicate expected weather trends, timing and impacts for the coverage area in a narrative summary, serving as context for (and a complement to) the datapoints on the page. This would be the case during regular weather as well as when hazardous conditions are present or approaching, and the amount of detail and timeframe it covers would all be up to forecaster discretion. (hazard scenario covered in greater detail in #155 )

**Use**
For MVP, “Coverage area” will be defined as the WFO coverage area, with the ultimate goal of scaling that down to the smallest actionable location. We acknowledge that this use of the component may not fully deliver the intended value to the targeted user stories, but it does lay the groundwork for future iterations. 

**Format**
Text with the option to include supportive imagery
Text would need basic formatting options (bold, italic, underline, add links, etc) 
Image formats are TBD 

### Sample text (regular weather only) based on recent stories from OHX
1) We will have to get through a few more warm days early this week, but a cold front will bring a chance of light rain to the area late Thursday into Friday, and we should see some fall-like temperatures by the weekend. 

2) Cooler air this weekend may lead to areas of frost Sunday morning. Areas east of I-65 and south of I-40 are most likely to see temperatures falling below 40 degrees. Those along the Cumberland Plateau are much less likely to see temperatures near freezing. 

### Acceptance criteria
A forecaster should be able to: 
- Create a new weather story 
- Write and style the text as desired
- Associate the story with a specific location (post MVP: multiple locations) 
- Upload an image file to the DAM
- Author alt text or a caption for the image
- Add the image to the weather story 
- Publish the story 
- Unpublish the story 
- Edit an existing weather story (both updating the text and/or removing or updating the image) 
- View all weather stories associated with a given location within the system, regardless of publication status 
- View past versions of a published story 
- View the change log of a story (date/time of change, type of change, person who changed it, etc) 
- Save draft

A forecaster should not be able to: 
- Inject code into the component 
- Write more than 300 words in the text field 
- Add more than one image 

An end user should be able to: 
- Navigate to their location page and see a weather story on page if one is published to that location
- Navigate to their location page and not see a gap if no weather story is published to that location 
- Read the text 
- See the name of the WFO the story is attributed to
- View the image
- See when the weather story was last published
- Read the alt text or caption for the image 
- Expand the image to fullscreen and return it to previous size 

The system should be able to: 
- Automatically include a date and timestamp when the story is published 
- Automatically include the name of the WFO it is associated with 
- Include the weather story component on the location page only if a published weather story associated with that location exists 
- If there are multiple published weather stories for a specific location, display only the most recently published. 
- For CMS users, provide a list of locations for which no published weather stories exist (post MVP?)

### Support needed/ dependencies identified
Technical
- Method to associate a weather story with a specific WFO
- Mechanism by which to connect a specific user location to a specific WFO, and serve the content associated with it 
- Image management and support 
   - Preferred file formats and sizes
   - Folder structure and/or DAM system
   - Image renditions or scaling options
- Out-of-the-box rich text editor (I think?) 

### Exploration needed
Technical: 
- For images, what file size and format would be best to use? (considering source, ease of use, and site performance) 
- What tools are easiest for forecasters to use to create images? Or can we provide them preset images to select from? Or both?

Stakeholder user testing:  Is the guidance of 100-200 words (with room for up to 300) enough to meet the need?

End user testing:
- Is the intended value of the component still delivered if the geographic scope covered is at the WFO level and not a specific location? 
- Is the guidance of 100-200 words (with room for up to 300) enough to meet the need? If full length, does it negatively impact the experience?
- What type of images add value to the weather story for the user? 

To explore post-MVP: 
Would it be feasible to redefine the coverage area to a smaller-scale location? This would mean writing multiple weather stories for the area covered by one WFO so that each can be more specifically relevant to a user’s location.

----
### Needed next action

- [x] Design Review
- [x] Eng Review
- [ ] PO Review

**Comment by colinmurphy01** [comment]
@kmranjo Please update this by EOW.

**Comment by kmranjo** [comment]
@colinmurphy01  I've added what I had so far when it was stuck in a word doc, but I would definitely consider it to be a draft. Would love to talk about this with the group since I haven't done one with this structure before, and am not sure I'm matching expectations.

**Comment by janelx** [comment]
@kmranjo this looks good! I'm assuming that #155 will be less restrictive? We learned from Forecaster research on hazards that a main pain point was only being able to publish 1 hazard story, difficulty of updating headlines to make them more relevant, limitations of images and need re-usable graphics. 

For this one, the only thing I'd suggest is the ability to set publish/unpublish date so they don't need manually manage it. If are able to add some user centered acceptance criteria, that'd be great. If not, I can add it real quick when I have moment!

**Comment by kmranjo** [comment]
@janelx  I've updated the above based on our conversation yesterday, so I think the only piece it still needs is the example with an image that you mentioned. Other than that, does this look ok to bring to PO review? Anything I've missed?

**Comment by kmranjo** [comment]
@shadkeene This is the weather story ticket mentioned in PO sync today. It doesn't have a visual with it yet, but the details of what it will do and how are all above if you want to take a look. Let me know if you have any questions.

**Comment by janelx** [comment]
For testing w/users there is an opportunity for us to test actual forecaster provided content and for them to receive feedback (if of interest to forecasters). I think this will be more effective than testing with our canned content. It's an opportunity to help authors to improve communications via user feedback, while refining our understanding how we might improve the component based on forecaster and user needs.

**Comment by kmranjo** [comment]
Confirmed in Design Crit we are good on design review, ready to move on to product and eng review

**Comment by janelx** [comment]
@kmranjo does this capture everything that should be shown? Also, what should the headline be? I didn't see it as something that they should be able to change.


![Image](https://github.com/weather-gov/weather.gov/assets/93934808/5560e7d7-72b5-483d-a5f3-034673efcd4a)

**Comment by janelx** [comment]
Let me get back to you on number 1. This is kind of an older practice and I want to see what Drupal has out of the box along with best practices. 

Alt text with will be on the CMS side. Here is with a caption.
<img width="298" alt="image" src="https://github.com/weather-gov/weather.gov/assets/93934808/0f85957f-42ec-46a9-8584-71390950dadf">

**Comment by colinmurphy01** [comment]
Confirm PO review with @shadkeene onsite

**Comment by janelx** [comment]
@colinmurphy01 and @kmranjo we need to update these specifications based on our convos. Here is the updated screen.

![Image](https://github.com/weather-gov/weather.gov/assets/93934808/d73cb670-eb35-43b9-bf8e-c9eae64fc5ec)

**Comment by colinmurphy01** [comment]
I think we should and then later on reconsider bringing word count and image restriction back in once we see Forecasters use it. @kmranjo? I think you felt that we should keep them, would love to hear why.

**Comment by kmranjo** [comment]
I think we could start without character limits if we need to, but I think we'd be missing out on a passive way to shape the communication. These limits are already decently long, and we could make them longer if we are concerned. In my experience, if people know there is a limit, they'll self-edit to make sure they can communicate their points concisely. If it's wide open, they may still do that, but they may not. In fact I believe we heard exactly that feedback from at least one person about another component....I think the urgent headlines? That there's a character limit that they're used to and it encourages them to include just the most necessary info? That was from one of the virtual forecaster sessions we did not too long ago. 
I think the location scaling (which I know right now is not necessarily part of it) would also lead to less space being needed because you aren't having to speak to as wide a range of conditions. 
The other reasoning would just be to encourage the best user experience. A block of long text is tough to parse. 

On the multiple images, I don't know that we've heard the need for that yet, especially for a non-hazard scenario. Multiple images has been mentioned, but in context of the current state, not in context of this use of the weather story. I'd love to learn more about what they'd create for one image in a non-hazard scenario, and then if additional needs come up we could address those.

**Comment by janelx** [comment]
I agree @colinmurphy01 we should pilot and see how it's really being used and iterate from there.  

For the restrictions: This is where we differed during prototyping phase. I still recommended: Remove enforce word count limit and restriction to images. This could be dangerous to limit especially in times of hazards and would just force forecasters to use other communication channels. Word count isn’t really a problem with forecasters that I've seen. 

Instead focus on providing best practices. Adapted from prototyping stage to include recent research. Suggested CMS side with help text and in-context of what they will be writing. This is something Claire and I talked about in proto phase:
- Example text but should: add audience and goal of the weather story/AFD for summary (what would be shown on the page) and detail view (what's clicked into)
- Add resources tools to encourage best practices

In one drupal block
<img width="249" alt="image" src="https://github.com/weather-gov/weather.gov/assets/93934808/8a4f1ba7-df53-419f-b974-54697014527c">

A little more usability and easier to update across content-types
<img width="267" alt="image" src="https://github.com/weather-gov/weather.gov/assets/93934808/99086ea5-9f55-4e68-af91-82624af90e3b">

**Comment by janelx** [comment]
Been thinking about this. It sounds like the word count solution and other restrictions, initially proposed, might be coming from low confidence in forecasters being able to write concise and plain language suitable for this field. 

If that is the concern, I'd like to propose, postponing building out these solutions till we get more understanding of the usability for current content and how it might be improved. I propose we get user feedback for the AFD summaries shown on point location page (particularly during and for anticipated WWAs) and perhaps see if HazSimp team has done any research that touches on it that we could learn from. 

Choosing AFDs as a place to start b/c from partner feedback, it sounds like AFD are useful, would require less writing, and could help to influence improving AFDs. Perhaps in the future, if feasible, they could serve the need AFD summary and details, streamlining forecaster workflow and building consistency in communication.

**Comment by kmranjo** [comment]
While encouragement to write in concise and plain language is certainly a benefit here, my main concern is more to present information that end users are able to quickly and easily understand, knowing that large blocks of text can be an obstacle to that goal. 
I think the versions of content I'm pulling and creating might help illustrate this, and I hope to have those completed in the next couple of days to share around. I'm including screenshots of the AFDs for each scenario, so we'll be able to take a look at those as well and that should give us a fuller view of all possible options.

**Comment by janelx** [comment]
Sounds good. When you share we can update/create new wires for testing. For
now we'll keep the word count. During our design convo there was an
expressed desire for hazards to match capability so I'll add the criteria
to match on the Hazard wireframes and component ticket.

**Comment by colinmurphy01** [comment]
Since we're building this out. Going to update this to done for now. As we get feedback from hazard testing, we'll scope out iterations as needed
