### ISSUE TITLE
Ingest Weather Story XML files from DSS Builder

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#1808]
@colinmurphy01 to add acceptance criteria for this ticket and regroup with @jamestranovich-noaa and size.

Related: #1793

**Comment by colinmurphy01** [comment]
@colinmurphy01 to update the details (including XML metadata)

**Comment by jamestranovich-noaa** [comment]
We ingest all details for the weather story now into drupal content types -- one per image. Only office, title, description, and full image are required. The rest of the attributes are optional.

**Comment by jamestranovich-noaa** [comment]
Yup, I've let them know, with the caveat that this isn't in beta yet. But, soon!
