### ISSUE TITLE
Make scripts more robust

### ISSUE THREAD

**Issue by jamestranovich-noaa** [weather-gov/weather.gov#1809]
### Description

We have some scripts that need cleaning up and sanitizing; [shellcheck](https://www.shellcheck.net/) is a good tool to check common scripting errors. In addition I'm also seeing some copy-and-paste errors from `cisa-dotgov` that really shouldn't be there. 

### Acceptance criteria

- [ ] `shellcheck` passes all scripts cleanly (and/or exceptions are clearly documented)
- [ ] run `shellcheck` as part of a github action?

**Comment by colinmurphy01** [comment]
Give me a read on priority/timing?

**Comment by jamestranovich-noaa** [comment]
Sanitizing scripts is a small lift -- `shellcheck` tells you exactly how to fix these warnings/errors -- so we can do anytime, and the work would take less than 30m -- we don't have _that_ many scripts. This work is not urgent (although I'd like to remove the `cisa-dotgov` references sooner rather than later).

**Comment by jamestranovich-noaa** [comment]
I went ahead and did a PR for the `shellcheck` warnings but I don't think its worth it to add as a github action (yet). I think we should (in general) stay away from deploy scripts because they are rather fragile for extending environments.
