### ISSUE TITLE
e3.v6 wfo attribution

### ISSUE THREAD

**Issue by janelx** [weather-gov/weather.gov#181]
### Goal
Provide a quick introduction to the WFO responsible for the forecast, with a quick path to contact the office or learn more about it.

### Supported user stories
1.1 - I want to know how NWS serves my priorities
1.2 - I want to know who creates forecasts and hazards, and how they create them
6.1 - As a partner, I want to know who and how I can reach out to someone when I need to

### Dependencies 
CMS needs the ability to map a geographic location to a specific WFO based on coverage area

### Content 
All content is authored in the CMS
- WFO shortcode  (required, but may be auto populated, eng TBD)
- WFO name  (required, but may be auto populated, eng TBD)
- URL to WFO page  (required)
- WFO phone number  (optional)  
- Short intro text (required, 150 characters)
- URL to WFO Facebook page  (optional) 
- URL to WFO Twitter account  (optional)
- URL to WFO YouTube account  (optional)

WFO Name is an H2
Intro text is plain text only, no styling elements needed 

### Behavior
- Display conditions: For any location page, the system detects which WFO covers that location and populates the corresponding instance of this component 
- Any optional fields not authored do not appear in the published component 
- For social media links, the icon for the platform appears only if the URL for that platform is authored 
- The component cannot be published if required fields are not authored 
- Only one instance of the component can exist for each WFO 

[Example in document here](https://docs.google.com/document/d/1_BzB1kA8jrzfVrXYoiq2juyEzKaTBWtmjetmDJzw7T0/edit?usp=sharing)

### Acceptance criteria
Site users should be able to: 
- Navigate to their location page via search or direct link
- View the component on the page
- Read the text (heading, WFO name, intro, phone number, social media promos) 
- View the images (social media icons) 
- Click the phone number to call from any call-capable device 
- Click the WFO name to navigate to the WFO page 
- Click any social media icon to navigate to the social account for that office 

Content creators should be able to: 
- Open the WFO promo component tagged for their WFO
- Author content within the component 
- Publish the component 

Content admins should be able to: 
- Create a new WFO promo component 
- Tag the component for a WFO (or select from menu) 

----

### Review: design, function and flow:
- [ ] POs - org alignment and vision review
- [ ] Eng - feasibility and right-size
- [ ] UX - what and how to test

**Comment by colinmurphy01** [comment]
Prioritized for Sprint 3.3. 

This will be included in #248 based on MVP WFO recommendation from #165:

![Image](https://github.com/weather-gov/weather.gov/assets/24654605/4136b56b-3a26-4c9b-b9f7-2f511ea65413)

**Comment by janelx** [comment]
@colinmurphy01 I think we might need an additional user story as this one doesn't really match the attribution one. BUT updated weather story covers attribution. Here is what I was thinking the value of showing this on the page, if we don't have something from the from trust and authority exercise

**Value:**
- Show NWS has physical offices with specialist monitoring weather for their state
- More inviting to the public and increase access to public participation
- Prepare for future state where people can learn more, or if link is included
  - Access point to learning more public education events 
- Sense of place, reinforce forecaster's familiarity of how weather affects the location

**Comment by colinmurphy01** [comment]
Closing this as it's being stubbed in Greg's work implementing the point location page #248.

The refinements noted above will be considered in #461

**Comment by kmranjo** [comment]
Updated to reflect latest recommendations based on content models and user feedback. I believe next steps are: 

- [ ] Design review to get alignment on approach
- [ ] Eng review to flag the technical dependency
- [ ] Update and add visual designs to the ticket (this would make it ready for eng?) 
- [ ] Build

**Comment by colinmurphy01** [comment]
Should this be added to today's co-work agenda, or wait till Igor's back?

**Comment by kmranjo** [comment]
It's pretty basic so we could maybe chat about it briefly during cowork and then he could look at it when he's back? It does still need his alignment, but I don't expect any surprises with this one.

**Comment by kmranjo** [comment]
@colinmurphy01  So for this one since we have alignment does it go straight to eng with a build ticket? And am I right you don't want to repurpose this ticket for the build, but I should make a new one with all this info in it but tagged for eng? Sorry, still getting a feel for the ticket progression.

**Comment by colinmurphy01** [comment]
Yes please do that to just get in the habit of closing tickets and opening eng tickets as the last step.

Since it's EOD, you can do that Monday AM.

**Comment by kmranjo** [comment]
Opened #597 for next steps, moving this one to done
