### ISSUE TITLE
Prioritize alert types with `evacuation` included

### ISSUE THREAD

**Issue by jamestranovich-noaa** [weather-gov/weather.gov#1841]
### Description

We are getting `Unknown alert type: Evacuation - Immediate` errors from the interop layer. Note that we expect `evacuation immediate`. There's a few other unknown alert types, as well.

Since last week, we've gotten the following unknown alerts:

- Unknown alert type: Evacuation - Immediate
- Unknown alert type: Local Area Emergency Warning
- Unknown alert type: Tropical Cyclone Statement
- Unknown alert type: Evacuation Immediate Warning

To grab an updated list in NR, the NRQL query is `SELECT uniques(message) FROM Log WHERE message LIKE '%Unknown alert type: %' SINCE 1 week ago`

### Acceptance criteria

- [ ] Tests have been implemented or modified to capture the bug

**Comment by greg-does-weather** [comment]
The interop layer already preserves unknown alert types: https://github.com/weather-gov/weather.gov/blob/api-interop-layer/api-interop-layer/data/alerts/index.js#L70

If it comes across an alert type it doesn't know about it, it marks it as a land hazard with the lowest possible priority and sends it on to the frontend. It also logs it to NewRelic.

Ultimately, this is an upstream problem. None of those four alerts are canonical. NGITWIS is not using the proper names. The list of canonical alerts is here: https://www.weather.gov/help-map/. The API ingests the data from NGITWIS and passes it straight along, I believe, so it's not an API problem - it's upstream even of that.

**Comment by jamestranovich-noaa** [comment]
I agree, and at the same time we have to deal with the data we've given. I'll leave it to product to prioritize (or not) but my feeling is that we should special case any alert with the word "evacuation" in it, at least.

**Comment by jamestranovich-noaa** [comment]
Well, the easiest way to special case is probably to check if the unknown alert type has the word "evacuation" in it, and if so, map the alert to `evacuation immediate`. (We'd still log the unknown alert type though!)

Generally I am thinking that over time we can build up a list of unknown alert types and decide if we should remap these at IOC/launch.

**Comment by colinmurphy01** [comment]
@shadkeene and @coreypieper (CC @kmranjo because she's observed stuff over time) how do we feel about updating our hazard prioritization logic for beta to prioritize hazards with the mention of `evacation`.

My ONLY concern is that these areas are probably getting pummeled with more and more alerts, but I do think we can assume a locally-generated alert like this is likely the most important thing they want their community to see.

**Comment by colinmurphy01** [comment]
Deprioritizing since beta is not actively used.

Will also split into two tickets:
- implementing `evacuation` logic
- reviewing logs of unknown alerts for mapping consideration (later)

**Comment by colinmurphy01** [comment]
Created #1891 to evaluate the logs prior to IOC.

**Comment by colinmurphy01** [comment]
@jamestranovich-noaa should we repurpose this ticket for the new `evacuation` logic for alerts or create a new ticket and close this?

**Comment by jamestranovich-noaa** [comment]
We can repurpose this ticket, sure. Edit away!

**Comment by colinmurphy01** [comment]
@coreypieper @shadkeene where should we prioritize the external alerts that include the phrasing `evacuation` in the title amongst [the other NWS hazards](https://api-weathergov-greg.app.cloud.gov/meta/alerts)?

**Comment by colinmurphy01** [comment]
@coreypieper can you weigh in on the above comment?

**Comment by coreypieper** [comment]
Right now "Evacuation Immediate" is priority 14 on [the list](https://www.weather.gov/help-map/), and I think it would make sense to group all products with "Evacuation" in the title in that priority space too.
