### ISSUE TITLE
Wind gust point style not matching wind gust legend style

### ISSUE THREAD

**Issue by shadkeene** [weather-gov/weather.gov#1845]
### Description

The wind gust point style on the wind gust graph is red and does not match the blue point style that is on the legend.  This may be connected to the JS bundling or lack of bundling?  

![image](https://github.com/user-attachments/assets/ebc42118-b5ce-405b-b259-fbc710dafc6e)

### Acceptance criteria

Wind gusts point style in the graph and legend will match.

- [ ] Tests have been implemented or modified to capture the bug
- [ ] Changes have been tested for accessibility

**Comment by colinmurphy01** [comment]
![image (14)](https://github.com/user-attachments/assets/d2215235-3d86-44cf-8c9b-7a0ed32cb90c)

wind gusts showing up fine now in staging.
