### ISSUE TITLE
[Interop layer] Investigate the logic for how we determine "overnight" periods

### ISSUE THREAD

**Issue by greg-does-weather** [weather-gov/weather.gov#1852]
### Description

See https://github.com/weather-gov/weather.gov/pull/1823#discussion_r1785166989. The logic we use for determining whether we have an overnight period is incorrect. I suspect there is a simpler way to do this:

1. build the full list of calendar days
2. for the first calendar day...
  - one period, that period is night time
  - two periods, the first is day time and the second is night time
  - three periods, the first is overnight, the second is day, and the third is night

☝️ That should be guaranteed based on how we split the days around local midnight instead of around weather days. 

### Acceptance criteria

- [ ] We determine if the logic is correct
- If not...
  - [x] Tests have been added to capture the bug
  - [x] The bug is fixex

**Comment by mgwalker** [comment]
I was gonna, but those lingering issues in staging are my priority for now. I'll move it to to-do, and hopefully pick it up later today.

**Comment by greg-does-weather** [comment]
That is to say, I will do those things.

**Comment by greg-does-weather** [comment]
fixed, closed
