### ISSUE TITLE
outside tests will sometimes fail with a 503 -- server unavailable error

### ISSUE THREAD

**Issue by jamestranovich-noaa** [weather-gov/weather.gov#1857]
### Description

We have some kind of file system locking contention when running outside tests repeatedly, because we upload files again and again: 

```
120	03/Oct 18:59	php	Error	Symfony\Component\HttpKernel\Exception\HttpException: File "public://2024-10/test-upload_27.png" is already locked for writing. in Drupal\jsonapi\Controller\FileUpload->handleFileUploadFor
```

I'd like to fix the fundamental issue here, but if we can't address the root cause, the next best thing is to randomize the file upload names. 

### Acceptance criteria

- [ ] Outside tests can be run repeatedly in sequence without failing

**Comment by colinmurphy01** [comment]
This feels important to fix prior to turning on the DSS integration?

Will randomizing file names impact the user experience?

**Comment by jamestranovich-noaa** [comment]
Great question. This particular issue is (I believe) an odd Drupal/Docker interaction issue with tests. 

But good catch regarding user experience. I filed a separate ticket for figuring out a better way to handle upload of files with very similar names: https://github.com/weather-gov/weather.gov/issues/1870

**Comment by colinmurphy01** [comment]
@jamestranovich-noaa has this been resolved?

**Comment by jamestranovich-noaa** [comment]
Yes! Good catch. Closing
