### ISSUE TITLE
User "typed-in" location doesn't save as "typed-in" location

### ISSUE THREAD

**Issue by shadkeene** [weather-gov/weather.gov#1864]
If I search for Mount Ashland, Oregon, it sends me to the forecast location for ~7000 ft elevation (70 degree high with 80s in the valleys).  But it shows the location as "Ashland, OR" which can be confusing for the user, especially when there's no reference map or elevation for the forecast point.  We received feedback about this via touchpoints.

![image](https://github.com/user-attachments/assets/bd6b6879-9aa6-4270-a7b1-23b8b781bde2)

![image](https://github.com/user-attachments/assets/ed5ff915-f23c-4672-88e7-f52399ae62f3)

Additionally, it shows "Ashland, OR" as a recent location vs. the mountain location of "Mt Ashland, OR".  

![image](https://github.com/user-attachments/assets/4e400645-e68c-40b6-9923-b4eeb08dd07c)

Now when I search for the actual valley location of Ashland, OR, I get the warmer temperatures.

![image](https://github.com/user-attachments/assets/f73678e5-1a89-46bb-bd21-1ff9b31c4448)

Now, for recent locations, I actually have to "Ashland OR" locations saved, one for the mountain and one for the valley.  
![image](https://github.com/user-attachments/assets/bdd07a64-fec4-416c-b1e6-7fcc1f37e05e)

I'm not sure what the best solution is, but it feels like we could use the actual "searched for" location as the forecast location.

**Comment by shadkeene** [comment]
Multiple more comments in touchpoints feedback.  We probably need to prioritize this in next several sprints, especially as we head into winter @colinmurphy01 @coreypieper

**Comment by colinmurphy01** [comment]
upgraded to `high`

**Comment by colinmurphy01** [comment]
Other examples Haleakala, HI

**Comment by colinmurphy01** [comment]
Assigning to eric to investigate the problem space, not solve.

**Comment by colinmurphy01** [comment]
@sarahmhgov will help make a doc of how we go about doing this now

**Comment by colinmurphy01** [comment]
Chatted in Des/Eng sync ([notes](https://docs.google.com/document/d/16qm1xuKg-lpCwUp7o_0uoHewaCXwFAQOPD4l1ZH4QCs/edit?tab=t.0#heading=h.vgvp3txecvs2))

Ideas:
- The way we save "recent locations" we might be able to do a similar technique
- Other solutions are bigger ideas

**Comment by colinmurphy01** [comment]
In order to close this, let's identify the best solution (even if it's short-term/temporary) and then document it into an `engineering` ticket. @sarahmhgov can you own that?

**Comment by sarahmhgov** [comment]
We discussed with this document, see option 2. https://docs.google.com/document/d/1o-1Qk5_hZuUfQKXzAT2b22l3OWMJwNQsnTlbgef_D30/edit?tab=t.0

**Comment by colinmurphy01** [comment]
So glad it wasn't **option 3**

**Comment by colinmurphy01** [comment]
@sarahmhgov Can you make it into an eng ticket and add it to our `Now` list with a `High` priority

**Comment by sarahmhgov** [comment]
Ticket here: https://github.com/orgs/weather-gov/projects/2/views/4?pane=issue&itemId=88204873
