### ISSUE TITLE
Rebasing interop branch and deplyoing to beta

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#1877]
Once the interop layer has been deployed to staging, we should test that environment for any inconsistencies across all data fields, content, components, on a variety of locations.

Targeting deploy Wednesday 10/23

**Comment by colinmurphy01** [comment]
@greg-does-weather please add in the description any particular use cases we should be 👀 during manual review in staging.

**Comment by colinmurphy01** [comment]
this is `done`?

**Comment by jamestranovich-noaa** [comment]
Yep!
