### ISSUE TITLE
Automatically increment Drupal libraries on deployment

### ISSUE THREAD

**Issue by greg-does-weather** [weather-gov/weather.gov#1878]
### Description

If any Javascript or CSS we deploy to the frontend changes, we must also update the `*.libraries.yml` files for the themes that use those files. It's pretty easy to forget to do that, so we added a bot that looks for those script changes and notifies us if the libraries file is not also updated. However, this is still cumbersome and creates noise.

An easier approach would be to automatically update the version information in the libraries file whenever we deploy.

### Acceptance criteria

On any deployment to any environment, we update all of our theme `*.libraries.yml` files with versions based on the timestamp of the deployment.

**Comment by colinmurphy01** [comment]
Moving to backlog for next sprint.
