### ISSUE TITLE
[Interop layer] Refactor alerts module to move top-level code into a function

### ISSUE THREAD

**Issue by greg-does-weather** [weather-gov/weather.gov#1881]
### Description

The alerts module has top-level code that immediately loads alerts and sets up the timer to refresh them every 30 seconds. As a result of this top-level code, the alerts module is slightly more difficult to test. The top-level code should be moved into a function and that function should be called by the main script.

### Acceptance criteria
- [ ] Alerts initialization and updating are wrapped in a function
- [ ] The main script calls the init/check function
- [ ] Alert module tests are updated accordingly
- [ ] Module tests that dynamically import their modules because of the top-level alert function are modified to use static imports

**Comment by colinmurphy01** [comment]
Is this something you want to do prior to staging deploy?

**Comment by greg-does-weather** [comment]
Nah. It's debt, but it's not critical.
