### ISSUE TITLE
Chart tooltip: hide interaction

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#1883]
Current
https://github.com/user-attachments/assets/3e6a496c-3bbe-466f-966d-3abc4b8887f2

On mobile, once I activate a tooltip in a chart I'm unable to hide it.

**Comment by colinmurphy01** [comment]
Is #1896 the solution for now?

**Comment by partly-igor** [comment]
Good question – I think it may have been, but can you let me know if what's on staging has resolved the original issue you were seeing?

**Comment by colinmurphy01** [comment]
I think this solves it and we can monitor.

My preference however would be for it to be a little more sensitive, as-in If I tap anywhere outside of a bar or tooltip it disappears (vs. the fix is anywhere outside of the chart). I also dont know if this resolves it for accessibility purposes - do we need a deliberate close button?
