### ISSUE TITLE
DSS Builder PDF upload parity changes with Weather Stories

### ISSUE THREAD

**Issue by jamestranovich-noaa** [weather-gov/weather.gov#1887]
### Description

We have made a lot of changes to Weather Story upload content types that should be copied over to PDF uploads as well. 

- [ ] Optional attributes
  - `StartTime` (Unix epoch time)
  - `EndTime` (Unix epoch time) 
  - `Order` (integer)
  - `FrontPage` (boolean)
  - `Title` (CDATA string)
  - `Description` (CDATA string)
- [ ] Filesystem upload locations (after #1886 goes in)

### Acceptance criteria

- [ ] Outside tests for optional attributes
- [ ] Changes have been tested for accessibility

**Comment by colinmurphy01** [comment]
Moving to the backlog for consideration next sprint.

**Comment by colinmurphy01** [comment]
Is this `done`?

**Comment by colinmurphy01** [comment]
@jamestranovich-noaa is this `done`?

**Comment by jamestranovich-noaa** [comment]
Not yet. I need to finish up weather stories, and then we can circle back to this. I've been holding off on parity for PDF uploads until we get the newer DSS workflow settled in (particularly overwriting of uploaded files).
