### ISSUE TITLE
Install USWDS and dependencies

### ISSUE THREAD

**Issue by cannandev** [weather-gov/weather.gov#189]
Install US Web Design System according to [developer instructions](https://designsystem.digital.gov/documentation/getting-started-for-developers/) using Node Package Manager (npm). 
Incorporate compilation of SASS/SCSS style files into our developer workflow.

**Comment by cannandev** [comment]
Related to #188

**Comment by colinmurphy01** [comment]
Interesting delivery process use case here. 

Since this is more foundational architectural work... should this go through Des, Eng, PO review prior to DONE or just Eng? @greg-does-weather interested in your take?

**Comment by greg-does-weather** [comment]
I think this can just be engineering. How we _use_ USWDS should go through design and product review, but just for getting it installed and setup, there's not really much to review outside of engineering.
