### ISSUE TITLE
[Interop layer] Configure deployment to beta cloud environment

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#1895]
Description
The interop layer is a new Node.js app that needs to be deployed to our cloud environments on all deployments. Sandbox and Staging were handled in #1731, this one is for beta.

Furthermore, networking needs to be configured so as to allow the weathergov* app to access the interop layer and for the interop layer to reach the public internet. If the configuration is reasonably straightforward, it might also be ideal not to expose the interop layer process to the internet.

Acceptance criteria

- [x]  deploying to the beta environment also deploys the latest interop layer
- [x]  networking configuration is documented
- [ ]  deployment and infrastructure diagrams are updated
- [x]  remove `nodemon` from prod usage

**Comment by colinmurphy01** [comment]
@jamestranovich-noaa are you taking the lead with this for deployment this sprint?

**Comment by jamestranovich-noaa** [comment]
Yes. We also want to remove `nodemon` as that is really for dev usage only. Adding to list above.
