### ISSUE TITLE
Event recaps: complete content models

### ISSUE THREAD

**Issue by kmranjo** [weather-gov/weather.gov#1901]
Generated from #1545

With alignment on the approach to create separate event recap content models for each event type, we completed 2 in the scope of initial modeling (tornado, winter storm). 
Captured in [this mural](https://app.mural.co/t/gsa6/m/gsa6/1718119936446/419e4314179ba9c3829e492427f271a1dd3b4cf2?wid=0-1718627874201&outline=open)

The scope of the remaining work is to:
- [x] Determine how many event types we will need to cover
- [x] Create a model for each event type, and document (not just in mural)
- [x] Run at least one real example through each model 
- [x] Capture any additional questions we will need to answer in the longer-term 

Out of scope: 
- Connecting cross-state events
- Implementation details
- Governance 

With running examples through the model(s) and some helpful input from Corey, this has circled back around to be one larger, more flexible content model, [documented here](https://docs.google.com/document/d/1kk9zKJ2mgoJ6JjMpiTrFHdMuqMqesrNUxzJwIQSCUqI/edit?usp=sharing).

**Comment by colinmurphy01** [comment]
I think you made progress on this last week, is this now `done` and ready for design? If so, please mention the ticket in a comment here.

**Comment by kmranjo** [comment]
Its done, but I got the impression you wanted to run it by the content champs group as well? If not, then it's ready for design.

**Comment by colinmurphy01** [comment]
Yes, I think we're aiming to talk this through with those champions on Dec 12.

**Comment by kmranjo** [comment]
Went over this in today's content champs meeting and got great feedback. The only real note on the model was concern around word count for the summary, but we agreed on trying it out and seeing how it works with real info.

**Comment by colinmurphy01** [comment]
Sweet so I'll take that as approval to design/develop for now?

**Comment by kmranjo** [comment]
Yes, this is good to go to design.
