### ISSUE TITLE
[Interop layer] Missing tests

### ISSUE THREAD

**Issue by greg-does-weather** [weather-gov/weather.gov#1904]
- Alerts
  - [x] Alerts with only forecast zone(s) get the correct polygon
  - [x] Alerts with only fire zone(s) get the correct polygon
  - [x] Alerts with only county zone(s) get the correct polygon
  - [x] Alerts with only county SAME code(s) get the correct polygon
  - [x] We only return land alerts
  - [x] We do not return past (ended or expired) alerts

- Hourly forecast
  - [ ] We do not show gusts if they are less than 8mph more than sustained winds (***not even implemented***)
  - [x] ~"Feels like" temperature is properly derived from heat index, wind chill, or actual temperature (***not even implemented***)~ Non-issue. We use the `apparentlyTemperature` value from the API.

**Comment by colinmurphy01** [comment]
Moving this to `doing` since you're working on it in #1907
