### ISSUE TITLE
additional site content

### ISSUE THREAD

**Issue by janelx** [weather-gov/weather.gov#191]
Related issue: #161 

All NOAA sites and gov't site should include the links to the following content specific to weather.gov
- About
- Privacy policy
- Accessibility
- Media inquiries: decided for this to go to NOAA media inquiries for MVP
- Site Index: A HTML page that lists all website pages (use placeholder - need to add to site)

## Recommendations
About page: 
- For MVP, link to existing page at https://www.weather.gov/about/ 
- For long term, page content can be updated to reflect site focus as well as org priorities (contingent on #280 ) 

Privacy Policy: 
- For MVP, link to existing page at https://www.weather.gov/privacy
- NOAA is currently working on updates to this policy, so further updates should wait until that guidance is available. 

Accessibility: 
- For MVP, link to existing NOAA page at https://www.noaa.gov/accessibility  
- NOAA is also currently working on updates to this content, so further updates should wait until that guidance is available. 

Media inquiries: (TBD, Corey to send) 

Site index: 
- Create a new page that reflects high level structure of the site, linking to new pages where possible and to current state when not possible. Update as the site is migrated. 
- Tracking in #271 

## Acceptance Criteria

- [ ] Pages have been created to reflect content that should be migrated
- [x] Pages that should be linked out to other sites are documented
- [x] An interim strategy for pages/content that doesn't exist is determined (e.g. <nolink> vs. hidden vs. ???)

## Status

- [x] Design Review
- [ ] PO Review
- [x] (not needed) Eng Review
- [ ] Ready for Build

**Comment by colinmurphy01** [comment]
Discuss with @kmranjo that if she has capacity she can pull this into this sprint.

Added acceptance criteria.

**Comment by kmranjo** [comment]
@colinmurphy01  Does this reflect what we talked about today? These are based on convos with Shad, Kari, and Corey P.

**Comment by colinmurphy01** [comment]
I believe site index is blocked by #271

**Comment by colinmurphy01** [comment]
Add this proposal to Design Review today and then we can review with Shad onsite. 

I don't believe Eng needs to review, but we can check with @cannandev on getting #326 set up so we can implement ourselves?

Then we can get this implemented.

**Comment by colinmurphy01** [comment]
This has been reviewed and approved by Design.

@shadkeene this just needs your approval for how we deal with footer links for MVP.

**Comment by colinmurphy01** [comment]
Approved by Shad
