### ISSUE TITLE
Show precipitation amounts graph and table when no rain is in forecast for that day

### ISSUE THREAD

**Issue by shadkeene** [weather-gov/weather.gov#1916]
### Description

If there is no rain accumulation predicted for that day, there is no precipitation amount graph or table.  This could be misleading, and there is often a slight chance for precipitation with no expected measurable precipitation forecast, and the user could find this beneficial that no accumulation is predicted.  I don't think this is intentional.

### Acceptance criteria

Precipitation amount graph and table should show up each day, regardless if there is rain or snow accumulation in the forecast or not. 

- [ ] Tests have been implemented or modified to capture the bug
- [ ] Changes have been tested for accessibility

------

Moving into separate ticket for design later
>We can discuss how best to summarize "no rain or snow accumulation is forecast", as a simple statement like this when no rainfall or snowfall accumulation is predicted could save room and prevent any confusion.

**Comment by colinmurphy01** [comment]
>no rain or snow accumulation is forecast

Is that the correct grammatical sentence?

Is it valuable to have the graph show up with 0s first as an eng fix, then we design how the sentence is displayed as a separate ticket to complete after 10/18?

**Comment by greg-does-weather** [comment]
Closed by #1919
