### ISSUE TITLE
Nashville Travel Authorizations

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#192]
We are planning to be onsite in Nashville

- Thursday, Nov 2: 10am - 4pm CST
- Friday, Nov 3: 10am - 4pm CST

Include our Project Name + Tock Code 1879 in the Authorization Title

**For Duty Location use Mt. Juliet, TN** 

**For Booking a Hotel**
Book the [Holiday Inn Express, Mt. Juliet](https://www.ihg.com/holidayinnexpress/hotels/us/en/mount-juliet/bnamj/hoteldetail)

- [x] Claire (driving from ATL)
- [x] Colin
- [x] Katrina
- [x] Sarah
- [x] Shad

I'll book a rental car for us to use.

**18F submission considerations:**

- FY24 billable code
- Submissions for approval:
  - Djemila McCray - review
  - Your supervisor - approval

**Comment by colinmurphy01** [comment]
Need to get estimations across 18F people first and get approval prior to submitting authorizations.

**Comment by colinmurphy01** [comment]
Email of estimates sent to Carrie for approval. Once approved we can submit authorizations.

**Comment by colinmurphy01** [comment]
As of Friday, we have approval to submit authorizations

**Comment by shadkeene** [comment]
Yes, all good on my end.

**Comment by kmranjo** [comment]
I did....but I haven't heard anything about the auth moving forward, so I'll check with the travel folks today

**Comment by sarahmhgov** [comment]
Catching up on this, what is the auth code?
