### ISSUE TITLE
Special Weather Statements with no ending time?  Intentional or working with what we have?

### ISSUE THREAD

**Issue by shadkeene** [weather-gov/weather.gov#1939]
From touchpoints feedback spreadsheet, row 362, Oct 2, 2024, a user states "When does the Special Weather Statement for my area end? It just says "In effect from 3 PM on Wednesday." It's for overnight fog. How late tomorrow morning will there be fog?"

When I look at a current special weather statement, it does have an ending time.  Are we carrying an ending time in the headline for all Special Weather Statements, or how does that work?  I don't think we have an end time on some.  I may need a refresher on this, so won't designate as a bug.   I do document a special weather statement below that seems to be in effect on Friday (tomorrow) but the headline says it ends today (Thursday).  

![image](https://github.com/user-attachments/assets/6d304f06-002c-413c-b67a-d5063c5899ef)

![image](https://github.com/user-attachments/assets/34e3bc2f-4cc6-46a1-9fb1-c7a641c236ed)

**Comment by greg-does-weather** [comment]
I was able to capture the special weather statement in Chama, and the end time is indeed missing. The 5pm in the alert box comes from the expiration (17:00:00-06:00).

![image](https://github.com/user-attachments/assets/f2553733-05bc-4323-9b0c-9445b71a4838)

**Comment by colinmurphy01** [comment]
@kmranjo can you weigh in on this?

**Comment by colinmurphy01** [comment]
Roger, so this is a non-issue and if end times are not showing up that's on the Forecaster.

@shadkeene feel free to weigh in or if you agree, please close.

**Comment by colinmurphy01** [comment]
Duplicate to #2042

**Comment by colinmurphy01** [comment]
We're going to close and monitor these to see if they continue to be an issue for others.
