### ISSUE TITLE
satellite imagery not fitting in viewport

### ISSUE THREAD

**Issue by shadkeene** [weather-gov/weather.gov#1945]
### Description

Satellite imagery movies don't seem to be fitting in viewport of mobile devices.  Is this expected behavior?  This was brought up during one of the unmoderated user feedback sessions, and I'm experiencing this on my mobile device.  I believe animated GIFs did fit on the page.  So there is some accessibility concerns if someone has to scroll over to see the whole image.

### Acceptance criteria

Satellite imagery fits on screen of any device, with ability to perhaps pinch and zoom into areas.

- [ ] Tests have been implemented or modified to capture the bug
- [ ] Changes have been tested for accessibility

**Comment by colinmurphy01** [comment]
I think this was fixed in the recent release.
