### ISSUE TITLE
Design/ Prototype: County level aggregations of alerts 

### ISSUE THREAD

**Issue by sarahmhgov** [weather-gov/weather.gov#1951]
Design / prototype to satisfy following user needs: 

- I need to see what alerts / hazards are occurring across the county
- I need to be able to "drill into" specific alerts / hazards

Notes: 
- that there is an initial design for county level aggregations, it should be updated to match designs for state level in terms of dealing with high volume alerts
- This likely will include design of a map / visual of alerts and some way of seeing actual list of alerts. Initial prototyping should explore these ideas to help scope. 

We'll build with county in mind and then test across a state area

**Comment by colinmurphy01** [comment]
Focusing the scope of this on County for now.

**Comment by partly-igor** [comment]
Done for county as part of #1363
