### ISSUE TITLE
Advocate for Rain equivalent QPF datapoint along side ice and snow

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#1956]
The "water" equivalent visualization is still confusing to most users. We've explored many alternate solutions to this problem, but fundamentally having a "rain" equivalent data point will be the best  solution. 

Let's chat with the folks that manage QPF data to assess the feasibility of that datapoint.

**Comment by coreypieper** [comment]
We've learned from the Severe, Fire, Public, and Winter Weather Services Branch that, in short, rainfall amount grid/field is unlikely in the foreseeable future. Here is [a pdf](https://drive.google.com/file/d/1EEk4HdLVAKzhkPsML7Zejb49SZ95hYki/view?usp=drive_link) of the email thread.

**Comment by colinmurphy01** [comment]
Closing, and will monitor as we test.
