### ISSUE TITLE
Identify WFO criteria and candidates for content build

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#1959]
Looking for states and WFOs across each region, ideally representing the widest possible array of geographic features (coast, mountain, etc), common weather hazards, and combinations of WFOs per state. 

Some considerations presented to content champs when considering contributor candidates: 
- Bandwidth (especially in spring)
- Openness to new initiatives
- Writing and/or web skills

**Comment by kmranjo** [comment]
Moving to Review because technically this is just waiting on the next content champs meeting

**Comment by kmranjo** [comment]
Wrote up a [brief template](https://docs.google.com/document/d/1xAMQ1D6C6V2-SdqMMVvdu2WHVI3wfdu26V6aA3hKfO8/edit?usp=sharing) for content champs to pull from when messaging their WFOs. 

Also created the [deck for the next content champs meeting](https://docs.google.com/presentation/d/1L7tI2ZisV_xuybEGrXzcgIYHD4W6EX3ldTDErQKay6o/edit?usp=sharing) on 11/14 

Actual selection will happen at that meeting, but the prework is all complete so should we close this ticket out?

**Comment by colinmurphy01** [comment]
yep can you add those materials to #2065?
