### ISSUE TITLE
Finish UX Changes (desktop tabs, accordions)

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#1967]
Our plan is to implement the quick forecast and updates to the day forecast item incrementally – this ticket is for the second version of these components. The new version will change the quick forecast on mobile and table to act as an accordion, and as a set of tabs (or buttons) on tablet-lg and desktop. 

Mobile
[Figma documentation](https://www.figma.com/design/w2QI2uTgaTWUPLHLi40mm1/Weather.gov-%E2%80%93-v0.2?node-id=13538-178393&node-type=frame&t=11ZH72DCjsHUttWh-11)
[Context/Design](https://www.figma.com/design/w2QI2uTgaTWUPLHLi40mm1/Weather.gov-%E2%80%93-v0.2?node-id=13538-175875&node-type=frame&t=11ZH72DCjsHUttWh-11)

Tablet-lg/Desktop
[Documentation ](https://www.figma.com/design/w2QI2uTgaTWUPLHLi40mm1/Weather.gov-%E2%80%93-v0.2?node-id=13538-174248&node-type=frame&t=11ZH72DCjsHUttWh-11)
[Context/Design](https://www.figma.com/design/w2QI2uTgaTWUPLHLi40mm1/Weather.gov-%E2%80%93-v0.2?node-id=13538-174279&node-type=frame&t=11ZH72DCjsHUttWh-11)

**Comment by colinmurphy01** [comment]
Igor to fill out with documentation prior to planning

**Comment by colinmurphy01** [comment]
Note that currently when I click on the today "tab" in the 7-day quick forecast desktop view it does not jump down to Today.

However I assume when we implement the ideal user experience this bug will be moot.

**Comment by shadkeene** [comment]
Do we need to add the helper text about "water" in the charts section too, for consistency?
_"Water" refers to the amount of water that is present in the precipitation. The precipitation may actually fall in solid form such as ice or snow, in liquid form as rain, or a mix of both._

**Comment by colinmurphy01** [comment]
Considering onboarding next week, likely won't be done by end of the sprint and we cannot break up the desktop and mobile updates - tey have to be done at the same time.

CC @shadkeene and @coreypieper

**Comment by eric-gade** [comment]
Closed by #2095
