### ISSUE TITLE
New Relic monitoring for upload functionality

### ISSUE THREAD

**Issue by jamestranovich-noaa** [weather-gov/weather.gov#1974]
### Description

We have a number of PDF uploads happening every day, now. The vast majority are successful. However, checking the cloud.gov logs, it appears that we are getting some 422s and it's not clear why -- we need more monitoring/logging around this to determine the issue.

### Acceptance criteria

- [ ] New Relic logs 422 server responses (we'd like to know why exactly they fail)

**Comment by colinmurphy01** [comment]
@jamestranovich-noaa should we pick this up soon?

**Comment by jamestranovich-noaa** [comment]
Yes. With the caveat that I looked into this already and I don't know if we can actually track these errors. I do not have access to the APM in New Relic (for convoluted reasons, only an "owner" does and I am but a mere "admin"). I'll poke around a bit more but this is one of our big monitoring gaps currently.

**Comment by jamestranovich-noaa** [comment]
I set up a dashboard panel to monitor these. This is good enough for our purposes; we can close now. 

![image](https://github.com/user-attachments/assets/8e1db4bb-805b-4586-b45c-895667918d99)
