### ISSUE TITLE
Remove/Hide "Forecaster's Report" component

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#1981]
The old weather story component is still available and visible in beta. With the new UX updates, this should be removed or commented out.

![Image](https://github.com/user-attachments/assets/84dc57fb-a89e-4b67-9afd-fad77772f3aa)

**Comment by partly-igor** [comment]
We should also remove the link to the AFD here since it's going to live with the weather story

**Comment by colinmurphy01** [comment]
I'm hesitant to do that until we're supporting weather stories across all WFOs.

**Comment by partly-igor** [comment]
We could still show the AFD link even if we don't show the weather story – I don't think we have to couple their visibility

**Comment by colinmurphy01** [comment]
ok that'd be nice. I'll add that to #1793
