### ISSUE TITLE
Daily chance of precipitation inconsistent with hourly chance of precipitation

### ISSUE THREAD

**Issue by shadkeene** [weather-gov/weather.gov#1982]
### Description

When a user sees the daily chance of precipitation, seemingly after day 3, it can be 0% even though the icon suggests precipitation is expected.  The hourly can be a high percentage, but the daily percent seems to be zero around Day 4 onwards.
https://beta.weather.gov/point/42.327/-122.872?#daily

Daily precip chance for Monday 0%
![image](https://github.com/user-attachments/assets/0dadaf50-b548-4c82-952e-5f28e67fddfa)

Hourly precip chances very high for Monday
![image](https://github.com/user-attachments/assets/598e969a-d78a-43f4-b756-7108404f2efb)

### Acceptance criteria

Daily precip chance should be consistent with hourly precip chances in general.

- [x] Daily POP should be calculated by taking the highest hourly POP of the day and rounding to the nearest 5%.
- [x] The AM/PM POPs should be calculated the same way, by taking the highest hourly POP of that 12-hour period and displaying that for the day/night POPs, rounding to the nearest 5%.
- [x] Tests have been implemented or modified to capture the bug
- [x] Changes have been tested for accessibility

**Comment by coreypieper** [comment]
This is what the API has for Sunday:
![Screenshot 2024-10-30 at 12 45 20 PM](https://github.com/user-attachments/assets/402df968-f975-41d9-9bd6-9e43ff321bf8)

The PoP is 11% at that location:
![Screenshot 2024-10-30 at 12 54 35 PM](https://github.com/user-attachments/assets/5078f43f-002e-4e31-b25f-8a30afdb0cfd)

So, perhaps we're getting NULL not because there is missing data, but perhaps because the API is not showing PoP lower than 15% (which is the low end of "Slight Chance")?

**Comment by shadkeene** [comment]
Updating this here.  It seems that only parts of the country are not showing the daily pop beyond day 4 or so.  Seattle, WA consistently is showing 0% chance daily POP but in hourly, you can see there are significant chances of precipitation.  So, a couple things we learned:

- Daily POP, which seems to be the highest hourly POP rounded to the nearest 10% for that 24 hour period, is showing as 0% when it's null in the API, even though there is actually higher POP occurring for that day in the hourly POP.  This is occurring for parts of the country, but not everywhere.
- The AM/PM POPs in the more-detailed weather section below the 7-day forecast are just not being displayed when there is a null.  

And steps forward in near-term:

- Daily POP should be calculated by taking the highest hourly POP of the day and rounding to the nearest 5%.
- The AM/PM POPs should be calculated the same way, by taking the highest hourly POP of that 12-hour period and displaying that for the day/night POPs, rounding to the nearest 5%.

Steps in longer-term:

- Figure out why some daily and AM/PM POPs are not making it from the forecast to the API...and showing up as null in the API.
