### ISSUE TITLE
Remove extra padding/overflow on mobile

### ISSUE THREAD

**Issue by partly-igor** [weather-gov/weather.gov#1989]
### Description
On devices smaller than a tablet (<640px wide) there is extra white space on the right side of the page for the Today tab, which adds an unnecessary horizontal scroll to the page. 

This seems to be caused by some combination of the `grid-gap-lg` class on the three main rows of that tab, and the other margin and padding setting.

![Screenshot of the extra space](https://github.com/user-attachments/assets/ec3520f7-8ab7-4505-a535-e6ffdff7a45e)
  

### Acceptance criteria
- [ ] The gap on the right side has been removed
- [ ] Containers take up full width

**Comment by colinmurphy01** [comment]
@partly-igor to check

**Comment by colinmurphy01** [comment]
@partly-igor has this been addressed?

**Comment by partly-igor** [comment]
Can confirm this was fixed
