### ISSUE TITLE
[Interop] Use uncaught exception handler to gracefully restart

### ISSUE THREAD

**Issue by greg-does-weather** [weather-gov/weather.gov#2001]
### Description

The interop layer currently has a handler for exceptions that are not caught elsewhere. Its behavior is to log the error and continue running. However, because unhandled exceptions necessarily indicate a previously unknown error state, we cannot be certain that the interop layer's internal state is consistent and we should not trust it to keep operating correctly. Indeed, the [Node.js documentation](https://nodejs.org/api/process.html#warning-using-uncaughtexception-correctly) makes this exact argument.

Instead, we should consider a very slim launcher application whose whole job is to monitor for unhandled exceptions in the interop layer, gracefully shut it down, and relaunch it.

### Acceptance Criteria
- [ ]

` Tag the related milestone to this story`

**Comment by colinmurphy01** [comment]
It's hard to grok the impact or priority of this work. @eric-gade would be interested in your thoughts, moving to `backlog` for consideration.

**Comment by jamestranovich-noaa** [comment]
I still plan on doing this, with the caveat that my priority is still finishing up weather stories though.

**Comment by eric-gade** [comment]
@colinmurphy01 let's prioritize this I think it's a good idea
