### ISSUE TITLE
Update new "today" template to display errors

### ISSUE THREAD

**Issue by jamestranovich-noaa** [weather-gov/weather.gov#2003]
### Description

With the new layout, we need to update the error message(s). If we go to a site that fails catastrophically (e.g., Pago Pago) the resulting "today" page looks odd. We show errors properly, but the CSS seems off. Example:

![image](https://github.com/user-attachments/assets/2d2fc92c-a24e-4b0f-a171-94d9c666b1f4)

### Acceptance criteria

- [ ] Tests have been implemented or modified to capture the bug
- [ ] Changes have been tested for accessibility

**Comment by partly-igor** [comment]
Updated designs and opened #2094 for engineering.
