### ISSUE TITLE
Safety page list

### ISSUE THREAD

**Issue by kmranjo** [weather-gov/weather.gov#2026]
Based on #1923 we have a design ticket ready (#2011) but will also need a list of the actual pages to be created for this section. 
In conversation with the POs, we found that what constitutes a "weather hazard type" will not be as simple as using the list of hazard types they have in the navigation or safety section menu. Several types are buried within pages that are more like categories, so we need to think through which actual pages to create. Since it would probably be good to get alignment on this before writing begins, this can be prioritized anytime in the next few weeks. 

### Recommendation

**Create a safety section landing page, and one page for each of the following hazard types:** 
- Air quality (includes ash)
- Avalanche
- Beach hazards (rip currents, sneaker wages, high surf)
- Cold (includes windchill, polar vortex)
- Drought
- Dust storms
- Flood (all types except storm surge) 
- Fog
- Heat 
- Hurricane (includes tropical storm, storm surge)   
- Lightning
- Marine hazards (gales, small craft)  
- Space weather
- Thunderstorm
- Tornado
- Tsunami
- Wildfire/fire weather 
- Wind
- Winter (snow, ice, blizzard) 

**Pages in the current safety section that will not be included** 
- Survivor stories
- Fatalities
- Bios
- Educational materials (activities, curriculums, etc) 
- History 
- Medical information
- Photo galleries
- Safety campaign pages or materials

Current site page count for this section: 249
Estimate page count for beta: 20

### Open question for product
Should we preserve any of the content that is education/science focused for future sections? Unclear when we will focus on education, or make a decision about moving that information back to weather.gov

**Comment by shadkeene** [comment]
I think we're missing storm surge and coastal flood type of stuff.  For flooding there are lots of subcategories (debris flow, flash flooding, river flooding, areal flooding).  And for storm surge, that should probably go in hurricane.

**Comment by kmranjo** [comment]
Great feedback, thank you! I've updated the list above to reflect that the "flood" category will include all types except for storm surge, and that one will go under "hurricane".
