### ISSUE TITLE
Create csv export of CMS safety tips

### ISSUE THREAD

**Issue by shadkeene** [weather-gov/weather.gov#2028]
STI would like to have a csv export of all CMS safety tips so they can do some initial work with them.

**Comment by colinmurphy01** [comment]
Sorry, what do you mean by do some work with them?

CC @kmranjo @coreypieper

**Comment by colinmurphy01** [comment]
Katrina will look to see if we can currently do it via CMS. If not, build a spreadsheet using word docs.

**Comment by kmranjo** [comment]
As far as I can tell, this isn't an action that the CMS can do. There IS an option to export content, but it only does so in a .yml file format. I checked the configuration options for content export, and there doesn't appear to be any option to change that format. 
With that in mind, @colinmurphy01 if you can send me an example of the file you used with the translations group before, I'll create one that matches that structure and input the safety info.

**Comment by colinmurphy01** [comment]
[Example](https://docs.google.com/spreadsheets/d/1WgQ0XWfRZrzK5OWMSVuBatElAZGnlxcW/edit?usp=drive_link&ouid=106015952511420309231&rtpof=true&sd=true)

**Comment by colinmurphy01** [comment]
Assigning to @shadkeene

**Comment by shadkeene** [comment]
Sharing with Monica.
