### ISSUE TITLE
Prototype: WWA Map

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#2031]
Based on #1548 

The full scoping document is **[linked here](https://docs.google.com/document/d/1IekL1r7pZS_oBcFL1ic7bWsxz-yXP2IdN6iBK0r9xrk/edit?usp=sharing)**

The prototype will be a map that displays active alerts, color-coded by the tier of alert (W/W/A).
Icons on the map can display what type of alert it is. These should indicate the category of alert, not the specific product type. 
Categories: 
- Rain (encompasses rain, flooding, etc) 
- Snow (encompasses all snow-related types)
- Wind (all wind-related types that don't fall into other categories)
- Thunderstorm (Severe storms, lightning, etc)
- Tornado 
- Heat
- Cold (include frost)
- Hurricane
- Fire weather (red flag, etc) 
- Visibility (fog, dust, ash)

The final version could be viewable at county, state or national view, but TBD which view we want to start with for the prototype. 
- At national view, you can only see the visuals (colors, icons) and select a state
- At state view, you can only see the visuals and select a county 
- At county view, you can see the visuals and the full list of alerts, prioritized by severity. Clicking the map opens the relevant alerts. Clicking the alerts highlights the relevant areas on the map. 

Open design questions: 
- How do we want to handle overlapping hazards? 
- Can we include timing in the map to reduce overlap? (like a tabbed approach for today, tomorrow, next day) 
- How do we want the user flow to work? 
- Should we include the full list of alerts at state level? 
- How can we provide alternatives to the map clicking for navigation?

**Comment by partly-igor** [comment]
This work has been reviewed for county, but wondering how want to track this work. Do we want to have any follow up tickets for this, or just keep a long running ticket?

The separate pieces of design and prototyping work will  be:
- Thinking about how the WWA map work on the state and national levels. 
- Creating icons for the categories above

**Comment by colinmurphy01** [comment]
I'd like to make those into tickets and track those separately vs. leaving this open while we go through a round of testing.

**Comment by partly-igor** [comment]
Created tickets for state and national level, and for the icons.
