### ISSUE TITLE
The text on the current conditions component (e3.v1) is not translation-ready

### ISSUE THREAD

**Issue by greg-does-weather** [weather-gov/weather.gov#204]
Introduced in #196.

We cannot address this bug until we build out the infrastructure for supporting translations. I think that should be pretty straightforward with Drupal and its built-in language modules. Once we know how we're going to do translations in general, we can come back and fix this component.

On this one in particular, the displayed text is combined from different sources, so that may introduce additional complexity. We'll evaluate once we get there, but noting here because we may need a little design help.

**Comment by claire-skies-noaa** [comment]
The translation module t() is pretty straightforward in Drupal. The simplest way is to pipe your text through |t. You can use placeholders for dynamic text.
