### ISSUE TITLE
Considering end time display for hazards when available

### ISSUE THREAD

**Issue by coreypieper** [weather-gov/weather.gov#2042]
In attached screenshot, it shows that the expiration time of the high wind warning not displaying in the dropdown header OR the product itself (which I don't think is intended). User feedback has indicated that this is desired. 

One consideration is that they could be referring to listing day of week instead of actual date

[bundle_1730756636838.zip](https://github.com/user-attachments/files/17624139/bundle_1730756636838.zip)
![Screenshot 2024-11-04 at 3 44 14 PM](https://github.com/user-attachments/assets/9a5d4f40-ca18-4bf7-b929-3bf11e474760)

**Comment by colinmurphy01** [comment]
@kmranjo how do you feel about this?

**Comment by kmranjo** [comment]
I'm confused...I agree the end time isn't in the banner up top (as intended) but I see it mentioned twice in the hazard product itself, both in the "in effect from" section and the "when" section. 
Are we talking about the expiration as something entirely different from the event end time? Is that what folks are asking for, and if so, do we know why?

**Comment by colinmurphy01** [comment]
We're going to close and monitor these to see if they continue to be an issue for others.
