### ISSUE TITLE
Tonight’s low in the wrong column

### ISSUE THREAD

**Issue by coreypieper** [weather-gov/weather.gov#2044]
The tonight’s low is in the “High” temperature column in the Quick Look at the top of the page. It’s rightly listed as the Low lower on the page. 

![IMG_8232](https://github.com/user-attachments/assets/c66af678-642a-4c35-9369-a0c16ca7ba20)
![IMG_8233](https://github.com/user-attachments/assets/c2c87ec0-24fb-4cfb-bb82-b30586fbd68e)

**Comment by coreypieper** [comment]
Looks as though now the low is in both columns the first period (and maybe is should say “Tonight”?)
![IMG_8278](https://github.com/user-attachments/assets/6d3e2efd-9c7c-4df8-9289-ad757053894c)

**Comment by colinmurphy01** [comment]
What time did you see this occurring?

**Comment by eric-gade** [comment]
Closed by #2140
