### ISSUE TITLE
The "feels like" temperature is not correct in the current conditions component (e3.v1)

### ISSUE THREAD

**Issue by greg-does-weather** [weather-gov/weather.gov#205]
The "feels like" temperature is currently taken exclusively from the API `heatIndex` value. However, there is also a `windChill` value, and it's possible for both of these values to be empty.

We'll need product input to help us understand what those values mean and how we should use them. E.g., if one of them is populated, should we use that? If they're both absent, do we use the current temperature as the "feels like"? Etc.

Bug introduced in #196

**Comment by greg-does-weather** [comment]
Proposed in the linked pull request:
* if the heat index is set, use the heat index
* if the heat index is empty and the wind chill is set, use the wind chilld
* if both are empty, use the current temperature

**Comment by colinmurphy01** [comment]
Questions for SMEs (Kolly/NCO and Kim McMahon):
- When are both set? Is this a use case we need to manage or the API already handles it?
- Is it dependent on location and time? (like April might require heat index for NO, but windchill for MSP)
- What's the default (likely heat index)? Wet build global temperature vs. heat index
