### ISSUE TITLE
Map weather story images to the right WFO

### ISSUE THREAD

**Issue by jamestranovich-noaa** [weather-gov/weather.gov#2060]
### Description

The weather stories need to be mapped to the appropriate WFO code in order to show up on the daily forecast page. Unfortunately the `Office` field in the XML seems to be inconsistent and even varies over time. Example: the weather story XML documents for `TAE` sometimes lists the `Office` field as `Tallahassee, FL` -- which makes sense -- and at other times as the generic `National Weather Service` -- which, I suppose, is correct but not accurate at all. Some `Office` fields are prefixed with "NWS Forecast Office", such as `NWS Forecast Office Medford, OR`, but some are not (as in `Old Hickory, TN`). In other words, there's a great deal of variance here in the XML data.

For a first pass, let's see how much we can disambiguate based on the `Office` field. Or maybe form a heuristic based on other fields: if the `Office` does not match anything (e.g., the generic "National Weather Service"), the `cwa_center_*` latitude and longitude fields might be workable. 

### Acceptance criteria

- [ ] We have a way to reliably map the XML attributes to the right WFO
  - [ ] _Or_, if not, we request DSS Builder to make changes so that we know how to associate the weather story image with the right WFO
- [ ] We have a test for mapping XML attributes to WFO codes

**Comment by colinmurphy01** [comment]
Does Jeremy know of this issue? This feels like something they should fix on the DSS Builder side, no?

**Comment by jamestranovich-noaa** [comment]
For now, here is the best heuristic I've come up with:

- regexp match against `Office`: `^(NWS Forecast Office )?([^,]+)` and look it up via our taxonomy
- if that fails, regexp match against `WebURL`: `^http://www.weather.gov/([a-zA-Z]+)/?$`
- if that fails, regexp match against `WebURL`: `^/([a-zA-Z]+)/$`
- if that fails, regexp match against `WebURL`: `^/FXC/wxstory.php\?wfo=([a-zA-Z]+)$`
- if that fails, give up.

This gives me ~92.14% error rate, which is the best I can do without making the heuristic more complicated. I'll go ahead and implement this for matching while we wait for a reply or better solution (if any) from the DSS builder team.

We also might need to modify our taxonomy a bit: currently, "Charleston" and "Jackson" have the same name and we need to disambiguate. So there's a bit of taxonomy work to do as well.

**Comment by colinmurphy01** [comment]
@coreypieper @shadkeene are you okay with this success rate for now?

I agree that we shouldn't put more complexity into our logic if the true fix is on the DSS Builder side and this should get good coverage across the site for the time being.

CC @mel-keene-gsa

**Comment by jamestranovich-noaa** [comment]
split off taxonomy work: https://github.com/weather-gov/weather.gov/issues/2079
