### ISSUE TITLE
In the current conditions component, the temperature unit should be top-aligned with the temperature

### ISSUE THREAD

**Issue by greg-does-weather** [weather-gov/weather.gov#207]
The "&deg;F" text is currently bottom-aligned instead of top-aligned:

![image](https://github.com/weather-gov/weather.gov/assets/142943695/cfb2bdcf-c480-426e-be1f-4efff5419d72)

Introduced in #196. See #175 for design artifacts

**Comment by colinmurphy01** [comment]
Can be picked up when #174 is ready for dev

**Comment by greg-does-weather** [comment]
Replaced by #330
