### ISSUE TITLE
Complete NOAA security compliance training

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#2071]
- [x] Miatta
- [x] Mel
- [x] Seamus

**Comment by colinmurphy01** [comment]
@shadkeene will provide a link

**Comment by colinmurphy01** [comment]
@sspj-does-weather and @Miatta18F have you compeleted training yet?

**Comment by Miatta18F** [comment]
I just got access to CLC this morning so I'll finish it today.

**Comment by colinmurphy01** [comment]
@Miatta18F following up, did you complete?

**Comment by Miatta18F** [comment]
Yep, finished it last week.
