### ISSUE TITLE
Date on 7-day forecast incorrect

### ISSUE THREAD

**Issue by shadkeene** [weather-gov/weather.gov#2073]
### Description

If a user is looking at beta.weather.gov in the evening of 11/11, they currently see the date of 11/12, and they see the words "Today" instead of "Tonight", and they see the high temperature and low temperature instead of only the low temperature.  

![image](https://github.com/user-attachments/assets/a47b1bda-4e59-4bc3-9538-1309ded1ed42)

### Acceptance criteria

A user should only see the current date.  If it is nighttime, the descriptor should read "Tonight" instead of "Today", and we should explore/discuss only showing the overnight low temperature instead of equal high and low temperatures.

- [ ] Tests have been implemented or modified to capture the bug
- [ ] Changes have been tested for accessibility

**Comment by colinmurphy01** [comment]
Related #2044

**Comment by eric-gade** [comment]
Closed by #2140
