### ISSUE TITLE
Automate accessibility testing

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#219]
Acceptance Criteria

- [x] Explore options below
- [x] Document within #201 
- [x] Runs on push
- [ ] Branch protections (#232)

**Comment by colinmurphy01** [comment]
Considerations from refinement

- pa11y or axe-core, maybe built into cypress tests instead of an additional tool
- Cypress might have its own thing?

**Comment by claire-skies-noaa** [comment]
* We'll use pa11y as a local developer tool and add it to our onboarding doc.
* We'll use Cypress axe-core as GitHub Action. Set to WCAG 2.1 AA Standard (which is the Cypress default for now)

**Comment by loganmcdonald-noaa** [comment]
Fixed by #295
