### ISSUE TITLE
Data categorization for compliance

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#220]
Acceptance Criteria

- [x] _Colin to work with @loganmcdonald-noaa to see how we can chunk out this work/goals by sprints_

**Comment by colinmurphy01** [comment]
Will clarify in 1:1

**Comment by loganmcdonald-noaa** [comment]
Here is my notes on data categorization: https://docs.google.com/document/d/1ml38XLWNSOsDjGHRY3MsP55gstu9ouumayyJ-87N3yo/edit

**Comment by colinmurphy01** [comment]
Tagged @shadkeene in the document where your opinion + examples will help.

**Comment by loganmcdonald-noaa** [comment]
The work on this is complete, but we should have some items come out of this moving forward.

**Comment by shadkeene** [comment]
@loganmcdonald-noaa @colinmurphy01 Shared the FIPS doc with Jason/George, as they wanted this to go to higher levels of leadership.

**Comment by colinmurphy01** [comment]
@shadkeene I might suggest amending the doc with your perspective (taking the thoughts out of comments and adding them under each category).

**Comment by loganmcdonald-noaa** [comment]
I think we can close this and just track #339
