### ISSUE TITLE
Updates to Header

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#225]
Alternatives identified in PO Review
- ~~NWS logo. Site title: National Weather Service. Subtitle: NOAA~~
- NWS logo (with red text). Site title: Weather.gov Subtitle: National Weather Service
  - NWS logo without the text (maybe with red lines)
- ~~NWS logo. Site title: Weather.gov Subtitle: [slogan] Weather ready nation~~

![NWS_Original_Logo_Vector](https://github.com/weather-gov/weather.gov/assets/93934808/843b45eb-7365-45f3-8dfe-e61f292bf0ca.svg)

**Comment by colinmurphy01** [comment]
@janelx POs will discuss this in PO Sync and prioritize against other work.

**Comment by colinmurphy01** [comment]
After discussion amongst POs, we'd like to move forward with 1 option instead of testing 3 for now. 

The one we advocate for is option 2
"NWS logo. Site title: Weather.gov Subtitle: National Weather Service"

The main reason is that it is a mental shift for the org to make weather.gov serve the public vs. the org needs. This option does that, but if we find in testing it's confusing then we can revert to option 1.

**Comment by janelx** [comment]
@shadkeene are you able to get a vector file (SVG) of the logo?

**Comment by shadkeene** [comment]
Yes, here are the vector files.  They must not have reached you and got stuck along the way.  Sharing via Slack.

**Comment by janelx** [comment]
@colinmurphy01 I've attached an SVG of the logo to be swapped out.

**Comment by janelx** [comment]
@shadkeene @colinmurphy01 I've also added an option with a logo without text. Best practice is remove the text from image and have it has readable text (like in the header) if possible. But It also feels like a different logo without the red. Let me know which you prefer.

![Image](https://github.com/weather-gov/weather.gov/assets/93934808/5c565318-7917-444e-9ec7-11c904830f80)

![Image](https://github.com/weather-gov/weather.gov/assets/93934808/7eb1682e-9bd5-46f0-b2f4-5a584c749b29)

**Comment by colinmurphy01** [comment]
@shadkeene and/or Kari let us know which logo to move forward with and then we can get the header updated.

**Comment by shadkeene** [comment]
95% sure we want text around the logo. Too much right now to try for new
logo design.

**Comment by colinmurphy01** [comment]
Awesome, moving this to to-do and leaving unassigned.

This might need an engineer to pick up since we don't have access to Drupal yet. CC @claire-skies-noaa or @loganmcdonald-noaa

**Comment by loganmcdonald-noaa** [comment]
Just to clarify - even if you had access to Drupal, this would be blocked by an engineer. All content is pushed _up_ at the moment, there is not a process to pull it down and sync it from our "stable" deployment.

**Comment by colinmurphy01** [comment]
Good point

**Comment by loganmcdonald-noaa** [comment]
For review @janelx @colinmurphy01 @claire-skies-noaa https://weather.app.cloud.gov/

**Comment by colinmurphy01** [comment]
Looks good to me. We'll have to observe how many times people on mobile mistakenly tap the NWS link when they mean to go to the homepage
