### ISSUE TITLE
Point beta.weather.gov to our MVP environment

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#228]
## Acceptance Criteria
- [ ] Cloud.gov agreement is signed (#230)
- [x] use https://weather.app.cloud.gov/ for the time being
- [ ] Setup on cloud.gov ([guidance](https://cloud.gov/docs/management/custom-domains/))
- [x] File request to NCO
- [ ] Define naming conventions for various environments

**Comment by shadkeene** [comment]
@colinmurphy01 @loganmcdonald-noaa please let me know if I need to help prep a ticket now or do anything on my end to expedite this process once cloud.gov usage is formalized.

**Comment by colinmurphy01** [comment]
@shadkeene submitted request to NCO

**Comment by loganmcdonald-noaa** [comment]
Follow up: https://github.com/weather-gov/weather.gov/issues/372
