### ISSUE TITLE
Onboarding documentation - I'm new and I want to get up to speed on the most critical parts of the org

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#23]
- [ ] Documentation for new team members
- [ ] Proposal for first 2 weeks
- [ ] Sceduling for first 2 weeks

**Comment by colinmurphy01** [comment]
Sarah started this doc: https://docs.google.com/document/d/1JIagnghg3xYNm4zdr_BtxWOwmifUaxjSCeybsaoqExE/edit

**Comment by sarahmhgov** [comment]
Julia shared in a crit session this example from guides and methods! https://docs.google.com/document/d/1Y3tGTFq5oGaQU4CAmKqP4VCIaJNE5H_bqAiZFKPGIDg/edit#

**Comment by sarahmhgov** [comment]
Oo also this one from amanda. I know you have examples too, just sharing https://docs.google.com/document/d/1mHQVPhCSiKzJyPg6an4b-t26uuAyUU2ToeBkjvFIGBY/edit#heading=h.ut4cheuqf23t
