### ISSUE TITLE
Utility-first CSS ADR

### ISSUE THREAD

**Issue by claire-skies-noaa** [weather-gov/weather.gov#233]
https://designsystem.digital.gov/utilities/

**Comment by cannandev** [comment]
@greg-does-weather I didn't use the ADR issue template to create this. How do I delete/close it?

**Comment by greg-does-weather** [comment]
As long as it doesn't have the `ADR: accepted` label, just closing it is fine. If it did have that label, closing it would kick off an automation that creates a PR to formally add the ADR, so we could just close that PR instead of merging it. 🙂
