### ISSUE TITLE
Export basic pages as SCS config files

### ISSUE THREAD

**Issue by claire-skies-noaa** [weather-gov/weather.gov#235]

**Comment by colinmurphy01** [comment]
@cannandev let's discuss these issues in our next 1:1

**Comment by greg-does-weather** [comment]
I'm not sure what this one is referring to either. If I was to guess, it'd be that we should export the standard, static pages and make them part of the repo so we can ensure they're always available in every deployment. In that case, I think we've decided not to import content into environments anymore, but will document the process for doing it manually in #518.

**Comment by colinmurphy01** [comment]
Should we close this then?

**Comment by greg-does-weather** [comment]
Let's do it.
