### ISSUE TITLE
Investigate heat index and wind chill values from the API

### ISSUE THREAD

**Issue by greg-does-weather** [weather-gov/weather.gov#244]
### Description

We want to show users the most relevant information, including an appropriate "feels like" temperature. To do that, we need to better understand the options available to us and how they work.

### Questions and Considerations

- Does the API ever set both values? If so, when?
- What is the NWS policy for what value to use and when?
  - Does the API already implement this policy, such that only one value will ever be set?
- Is the NWS policy based on location and/or time?
- What should we use as a default?
  - Heat index?
  - Wind chill?
  - Wet bulb global temperature?

### Acceptance Criteria
- [ ] We understand what value we will display to users.

### Tasks
- [ ]

**Comment by colinmurphy01** [comment]
Paraphrasing from Brian and Becky:
It’s VERY likely that the WFOs manage when to use heat index vs. wind chill based on the conditions for their locations (via an apparent temp grid). So they are responsible for that logic when the data is created."

Recommendation to consider: Neither the API nor us should manage that logic and we likely shouldn’t plan for a use case of them both showing up.

**Comment by colinmurphy01** [comment]
The above is based on forecast "feels like temp", not observed.  I think we're looking for observed?  So I think I need to still get that answer.  I don't know why that occurred to me last night and not during our discussion.  I don't believe observations go through the WFO, into the grids, and then back out to the web.  It's a more straightforward process from observation to web.

**Comment by shadkeene** [comment]
It was suggested that we use the words "Heat Index" and "Wind Chill" vs. "feels like" temperature.  The concern was that it's too close to Accuweather's RealFeel temperature, which is trademarked.  Thoughts?

**Comment by shadkeene** [comment]
Also, I think this ticket can be closed, per the meeting today.  What do you think @greg-does-weather and @colinmurphy01 ?

**Comment by greg-does-weather** [comment]
Yep, I think we can close this!

I'll spin up a separate ticket for changing the text to "heat index" or "wind chill" and we can carry that conversation over there.
