### ISSUE TITLE
Wireframe: Weather for a location

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#248]
Related to #174 

- [ ] [In figma marked as engineer ready](https://www.figma.com/file/0dSABt9zCqoknaKua6DHmP/NOAA---Weather.gov?type=design&node-id=588-3231&mode=dev)
- [ ] Flow: From weather.gov [figma](https://www.figma.com/file/2bDju7teT0H71ldhCkYORF/Weather.gov-2.0-MVP-Flow-%2F-Share-doc?type=whiteboard&node-id=1-197&t=luRus8dTXwOo0QjL-4)

![Image](https://github.com/weather-gov/weather.gov/assets/93934808/0b332e29-572e-4253-930e-3f3f7a1c4d51)

As the engineers are developing the individual components listed below they are deploying them to a testing environment where we can progressively show and test our work. However they're being rendered without a layout and instead being stacked ontop of each other.

IN lieu of not having a final design for the page, we'd like to have a wireframe of a location page that developers can implement and use to organize components so that stakeholders and users can see:
- hierarchy
- the components individually

This will not tackle
- how imagery is used on the page
- additional page styling

Components
https://github.com/weather-gov/weather.gov/issues/175
https://github.com/weather-gov/weather.gov/issues/177
https://github.com/weather-gov/weather.gov/issues/178
https://github.com/weather-gov/weather.gov/issues/179
https://github.com/weather-gov/weather.gov/issues/180
https://github.com/weather-gov/weather.gov/issues/181
https://github.com/weather-gov/weather.gov/issues/3.v7 weather on a map (might be similar to https://github.com/weather-gov/weather.gov/issues/159 ) - created a unique component ticket #299 
https://github.com/weather-gov/weather.gov/issues/154 (used on 3 layouts - conditional for with location and without location)

Reviews
- [x] Design 
- [ ] PO
- [ ] Engineering

**Comment by janelx** [comment]
@colinmurphy01 i created a new ticket for the weather map component. I must have missed it. [It's here](https://github.com/weather-gov/weather.gov/issues/299)

**Comment by colinmurphy01** [comment]
Based on milestone discussion this will provide wireframes for the following components:

- [ ] #175 
- [ ] #177 
- [ ] #178 
- [ ] #179 
- [ ] #180 
- [ ] #181 

These wireframes should provide layout, placement, and basic content recommendations in order to enable dev.

Not included because they will require their own design exploration:

- #299 
- #154

**Comment by janelx** [comment]
@colinmurphy01 @shadkeene one thing we talked about during our eng/design sync was the URL for a point location page. Basically like a readable vanity url like "weather.gov/nashville". Just noting this here so it doesn't get lost, but @greg-does-weather knows the possible options.

**Comment by colinmurphy01** [comment]
PDF used for Nashville feedback ([figma](https://www.figma.com/file/0dSABt9zCqoknaKua6DHmP/NOAA---Weather.gov?type=design&node-id=523-702&mode=design))

[Point location layout - desktop - sketch - v2.pdf](https://github.com/weather-gov/weather.gov/files/13227788/Point.location.layout.-.desktop.-.sketch.-.v2.pdf)


![Image](https://github.com/weather-gov/weather.gov/assets/24654605/c20862e4-f3b3-4844-8aff-a15a5888ed1b)

**Comment by colinmurphy01** [comment]
@janelx If you haven't done so, I'd suggest reviewing this with Claire tomorrow in Des/Eng sync.

Then when/if it's Ready for Eng the current process is to update labels to tag "Eng" and take off "Design" and drag it back into to-do and leave as unassigned. If Claire has bandwidth this sprint she can decide to pick it up or not.

**Comment by colinmurphy01** [comment]
Tagging @greg-does-weather for eng review

**Comment by greg-does-weather** [comment]
Looks good to me. I think we can pick up implementing the page right away, with placeholders for the remaining components.

**Comment by colinmurphy01** [comment]
@greg-does-weather I believe you were working on this last week. Is this still on your list for this sprint? 

Do we want to track this work with this ticket or a separate one?

**Comment by mgwalker** [comment]
The implementation is in #439. I think I didn't move this one because I wasn't sure if there was more to it. But I think it'd make sense once #439 is merge, if you and Shad and maybe Igor want to look at staging and see if it satisfies the requirements here, then we could close this one?

**Comment by colinmurphy01** [comment]
That sounds like a plan.

I don't currently see this in your dev environment [within Nashville](https://weathergov-greg.app.cloud.gov/local/OHX/50/57/Nashville). Am I missing something?

**Comment by mgwalker** [comment]
I don't think it's deployed anywhere right now. I can put it there if y'all want to look at it before it's merged, or it'll be in staging after Eric finishes his review and I fix any issues or questions he has.

**Comment by greg-does-weather** [comment]
Boy I just really bounce between accounts, don't I?

**Comment by colinmurphy01** [comment]
Dont sweat deploying it to dev, we can review in staging.

For some reason I thought that was automatically when a PR is cut.
