### ISSUE TITLE
Establish role-based tokens for our fonts

### ISSUE THREAD

**Issue by claire-skies-noaa** [weather-gov/weather.gov#256]
USWDS lets us customize the values of [type](https://designsystem.digital.gov/design-tokens/typesetting/font-family/#type-based-tokens) and [role](https://designsystem.digital.gov/design-tokens/typesetting/font-family/#role-based-tokens) family tokens with available [font](https://designsystem.digital.gov/design-tokens/typesetting/font-family/#available-fonts) tokens in our project’s [settings configuration](https://designsystem.digital.gov/documentation/settings/).

Acceptance criteria

- [ ] Have fonts for font-roles in our settings file

**Comment by colinmurphy01** [comment]
Let's follow up with claire on this to better understand

**Comment by greg-does-weather** [comment]
We already have some type- and role-based tokens specified in our sass:

- theme-font-type-sans
- theme-font-role-heading
- theme-font-role-body
- theme-font-role-code

(from https://github.com/weather-gov/weather.gov/blob/main/web/themes/new_weather_theme/assets/sass/_uswds-theme.scss)

@partly-igor Should we specify the remainder of the type- and role-based tokens to ensure we're getting consistent fonts everywhere?

**Comment by partly-igor** [comment]
@greg-does-weather that's a good idea, I think we can do that after we decide on a style direction.

**Comment by greg-does-weather** [comment]
@partly-igor I'm still a little fuzzy on this, but did some of the work you did recently also address a bit of this? Do we want to keep this ticket open for it?

**Comment by partly-igor** [comment]
Yeah I think it should mostly be covered by the changes to our theme file. We can close. Thanks for catching!
