### ISSUE TITLE
Location page: Title for Nashville is confusing and verbose

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#258]
### Description
For Nashville, the title "Nashville-Davidson metropolitan government (balance)" text is coming from the weather.gov API.
- Why? 
- How common is this?
- What are other locations that might create confusion?
- Is it possible to get a simplified title for Nashville?

### Acceptance criteria - research spike

- [ ] We understand the reason?
- [x] We understand the impact?
- [ ] We have a potential solution?

## Screenshots (if appropriate):

<img width="447" alt="image" src="https://github.com/weather-gov/weather.gov/assets/142943695/55e9e397-4af8-4bf2-80bd-82bf3c50cabb">

**Comment by colinmurphy01** [comment]
From Brian
"In this case for place names. I would guarantee this is not the only location that is like this. Specifically for this location we should be able to change it fairly quickly in the database used for the API, but finding and changing other places would take longer." ([source](https://gsa-tts.slack.com/archives/C04UJTTH2NT/p1696540146801859))

**Comment by greg-does-weather** [comment]
Issue #335 also somewhat speaks to this. The forecast.weather.gov JSON endpoint includes a place name that is more aligned with what we want.

**Comment by colinmurphy01** [comment]
We've tested several solutions to improve place names.
