### ISSUE TITLE
WCM recruitment

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#284]
Using the relationships at the WFO level, use the WCMs to reachout and recruit partners (EMs and such).

- [x] Outreach materials drafted (summary of project and involvement + form for WCMs to fill out)
- [x] Form is tested and pulling into main spreadsheet
- [x] Outreach materials have been sent to Brian
- [x] Brian has sent note to WCM network

**Comment by colinmurphy01** [comment]
@sarahmhgov tested the form.

- It's being ingested into the form well
- The only thing to tweak would be to add a note at the top of the 5 contact submission "pages" – "if you don't have 5 total candidates, hit next at the bottom and then submit"

**Comment by sarahmhgov** [comment]
Thanks Colin!

I can do that,

Sarah

**Comment by colinmurphy01** [comment]
Brian sent out comms on 10/31
