### ISSUE TITLE
Nashville Onsite Prep

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#289]
Agenda outline: https://docs.google.com/document/d/1PgPEdUirJYESJSkpDbLlctSUjU0dhzTezOB4LsS7eJ8/edit#heading=h.j2c2nhsjkof3

Tasks

- [ ] Confirm agenda with Team
- [ ] Identify and confirm activities
- [ ] Develop materials

**Comment by sarahmhgov** [comment]
I'm still working on this [doc](https://docs.google.com/document/d/1PgPEdUirJYESJSkpDbLlctSUjU0dhzTezOB4LsS7eJ8/edit)


WIP activities - given in person, going to translate to an in person 
[Forecaster Mural](https://app.mural.co/t/gsa6/m/gsa6/1697837323155/d5128efa17d1e672de1cad5c7fce493152559b8c?sender=u61b531faf98169a303ef4628)

[Partner engagement Mural](https://app.mural.co/t/gsa6/m/gsa6/1697838561419/faff640e468a1b0e8e34982540fb67629a3c97c7?sender=u61b531faf98169a303ef4628)

**Comment by colinmurphy01** [comment]
Scheduled a team prep meeting on Friday 12-1pm EST
