### ISSUE TITLE
Setup Cloud.gov and deployment environments

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#293]
Considerations

- [x] developing our deployment strategy for various environments
  - [x] Policy for production (beta) - access to SSH, deployments, constrain?, main automatically deploy? 
- [x] creating developer sandboxes
- [x] Automate deployments
- [x] Ability to spin up and down cloud.gov infrastructure
- [x] documentation

Need:

- There are potential needs to deploy 2 different things at the same time and show them (possible for 1-off situations)

**Comment by loganmcdonald-noaa** [comment]
Can close with #389
