### ISSUE TITLE
Our ADR automation eats code blocks in Markdown

### ISSUE THREAD

**Issue by mgwalker** [weather-gov/weather.gov#304]
### Description

The ADR automation we use is supposed to copy content wholesale from the ADR issue, but it appears to lose code blocks. I suspect it's something to do with the backtick. In any case, ADR 0007 lost a substantial bit of its content in the translation from issue to file.

### Acceptance criteria

The ADR automation preserves the original text exactly.

**Comment by colinmurphy01** [comment]
@greg-does-weather this is probably something we need to fix sooner than later so that we don't continue to create more doc debt.

I'm going to move it to the backlog so we can pick it up when we have extra capacity.

How long will this take?
