### ISSUE TITLE
Create a new weather story

### ISSUE THREAD

**Issue by greg-does-weather** [weather-gov/weather.gov#306]
### Supported user stories
- #180

### Story details: As a forecaster...
- I want to be able to create a new weather story
- I want to be able to write and style the text as described
- I want to associate the story with my WFO
- I want to be able to publish stories
- I want to be able to unpublish the stories
- I want to edit an existing story

### Acceptance criteria
A forecaster should be able to:
- [x] Create a new weather story
- [x] Write and style the text as desired
- [x] Associate the story with a specific location (post MVP: multiple locations)
- [ ] Save draft
- [ ] Autosave
- [x] Publish the story
- [ ] Unpublish the story
- [x] Edit an existing weather story (both updating the text and/or removing or updating the image)
- [x] Authors cannot inject code
- [ ] The field is limited to 300 words
- [x] The timestamp of when the story is published is automatically captured

**Comment by colinmurphy01** [comment]
Added save acceptance criteria

**Comment by colinmurphy01** [comment]
How do we want to handle the admin interface, Drupal is OVERWHELMING (even for testing)

#180 some early sketches of CMS view

Assigning to Igor and Greg to discuss how to unblock eng, knowing #443 is the priority

**Comment by greg-does-weather** [comment]
The weather narrative creation form UI in the Claro theme, which is a built-in that is the default for admin views:

![Screenshot 2023-11-28 at 12-33-42 Create Weather narrative Weather gov](https://github.com/weather-gov/weather.gov/assets/142943695/e1b4ce3a-2908-4e65-9b2e-237fa023fc0d)

**Comment by colinmurphy01** [comment]
Solution to explore for CMS interface for this iteration:

- Upon login present a button that says "create weather story"
- User is directed to "Create weather narrative page"
- Create accounts for nashville WFO peeps, un/pw

OOS
- Simplify the "Create weather narrative page" to
  - Headline
  - Text box
  - Add image
  - Default WFO to Nashville
  - Authoring capabilities (publish and unpublish date/time)

**Comment by greg-does-weather** [comment]
How do you want to handle this? We've implemented the exploratory thing (except for creating accounts; that is its own mini-hurdle for eng to clear) for now. Is that enough for now, or do we want to go ahead and start looking into admin theming? Looking at the board, it seems like the only thing that might compete for attention this sprint is prototyping around embedding radar on the location page. I think if we also wanted to spend some time playing around with admin themes, we *might* have the bandwidth for both, but the images work that Eric is picking up may balloon into a monster (and it might turn out to be super easy; we'll see!).

**Comment by colinmurphy01** [comment]
I'm favoring focusing on the map and radar exploration #299 and waiting on CMS theme exploration / calling this done.

**Comment by colinmurphy01** [comment]
@greg-does-weather this is in the `to-do` column?

**Comment by greg-does-weather** [comment]
I guess it should actually be `done`.
