### ISSUE TITLE
The weather story authoring UX should default to the forecaster's WFO

### ISSUE THREAD

**Issue by greg-does-weather** [weather-gov/weather.gov#312]
### Supported user stories
- #180

### Story details: As a forecaster
- I want my WFO to be selected by default when I create a new weather story

### Acceptance criteria
- [ ] The WFO field defaults to the logged in user's WFO.

**Comment by greg-does-weather** [comment]
This is blocked by authentication. It may or may not be blocked by ICAMS.

Right now we don't have users in our system at all. We need to figure that piece out and how to associate users with WFOs first. Once we do that, then we can do this.

**Comment by colinmurphy01** [comment]
@kmranjo for your reference as well

**Comment by kmranjo** [comment]
Knowing that some users will be associated with multiple WFOs, and that the likely path we will be taking is that weather stories are not created new but simply updated, this may be less important now.

**Comment by colinmurphy01** [comment]
Closing this and we'll monitor in testing if this is something to revisit
