### ISSUE TITLE
Should we say "feels like" or "wind chill"/"heat index" next to temperatures?

### ISSUE THREAD

**Issue by greg-does-weather** [weather-gov/weather.gov#318]
> It was suggested that we use the words "Heat Index" and "Wind Chill" vs. "feels like" temperature. The concern was that it's too close to Accuweather's RealFeel temperature, which is trademarked. Thoughts?

(from https://github.com/weather-gov/weather.gov/issues/244#issuecomment-1769009543)

I suspect we want to better understand where that suggestion is coming from, and also how users think about those words. And as a single data point, the standard weather app on macOS and iOS uses "feels like."

**Comment by klsheets** [comment]
Who suggested "Heat Index" and "Wind Chill" - I thought NWS was moving away from that.  I think the preferred scientific term currently is "Apparent Temperature" which can be interchanged with "Feels Like"

Accuweather patents a lot of things so they may have RealFeel patented, but I don't think we're precluded from using "Feels Like" which works for both hot and cold scenarios.

At some point we discussed apparent temperature and it was confirmed that a specific location wouldn't have a heat index and a wind chill on the same day so mapping to Apparent temperature for both of those fields (it is the name of the ndfd field)  would work.

**Comment by colinmurphy01** [comment]
@klsheets I'm thinking we close this for now?

We can retackle this when we pick up #368.
