### ISSUE TITLE
Solidify content sync strategy

### ISSUE THREAD

**Issue by claire-skies-noaa** [weather-gov/weather.gov#322]
Context:

## When we say “content”, we mean all the Drupal entities:

- Nodes (for example, /node/1  – About us page)
- Content types (think of a bucket; for example, Footer menu)
- Content type items (think of the thing in the bucket, for example, Privacy Policy link)
- Taxonomy
- Users
- Drafts
- Roles
- Permissions
- DAM/assets

Per conversation with Katrina and engineers:

## Future

Stable **"pull down"** approach where changes are made to our beta and pulled down as needed by developers to their local machine. The need for latest content to be synced across other environments is TBD. 

## Now

During build MVP phase, engineers have a **"push up"** approach to both content and code. Since we're still figuring out environments, layouts and components, any text is considered temporary and can be wiped away at any time. Please provide any **static text that should persist** to the engineers.

**Comment by loganmcdonald-noaa** [comment]
This can be closed after Greg's update to documentation.
