### ISSUE TITLE
Setup SAML communication with ICAM IdP

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#324]
This  is done when we can test and confirm the communication between the ICAMS IdP and our SP is working. There will be followup work to ensure that users can login to Drupal using this communication. 

- [x] Choose a SAML solution for Drupal
- [x] Generate certificate and metadata, #435 
- [x] Send XML with metadata to NOAA accounts team
- [x] Receive relevant information from the identity provider
- [x] Test that the communication works

**Comment by loganmcdonald-noaa** [comment]
Authored #337, we should use https://git.drupalcode.org/project/samlauth

**Comment by loganmcdonald-noaa** [comment]
This had been blocked on setup of our cloud.gov environments but we are now ready with the environments to send our metadata, will do early next week. Also #390 will give us the relevant modules we need.

**Comment by loganmcdonald-noaa** [comment]
This is currently blocked by a requirement for a third party signed certificate from a CA like DoD. I am working to either get access to DoD's CA or find another to meet the requirement.

**Comment by loganmcdonald-noaa** [comment]
Blocked on #435

**Comment by loganmeetsworld** [comment]
Set this up with samltest.id and it is working great, just need to swap out metadata information with icam once they have accepted it. 

![Image](https://github.com/weather-gov/weather.gov/assets/10510566/00bdd330-15e0-4584-b495-08e244ce4853)
