### ISSUE TITLE
Draft our needs for hosting and platform services

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#325]

**Comment by colinmurphy01** [comment]
Will link in our [long-term acquisition doc](https://docs.google.com/document/d/1OlFc1AnfpT6DJMAYXENmt-fDR2CC8XNvMDPWovOqCqE/edit) as well.

**Comment by loganmcdonald-noaa** [comment]
Needs drafted in acquisition doc - up next, chatting with COR.

**Comment by colinmurphy01** [comment]
Chatting with COR will be tracked in #127
