### ISSUE TITLE
Create Drupal admin accounts for core team members

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#326]

**Comment by colinmurphy01** [comment]
@loganmcdonald-noaa is this blocked?

**Comment by loganmcdonald-noaa** [comment]
I think it depends on what the accounts are needed for at the current moment. We can either make them today using basic auth or wait until we can access them with NOAA accounts. But when I asked if this was blocking anything, no one from design said it was a blocker for review.

**Comment by colinmurphy01** [comment]
Correct.

The only thing it would block is #191 which is not a priority

**Comment by claire-skies-noaa** [comment]
During this build phase, any content should be pushed up by devs. We'll hold off creating drupal accounts for the rest of the team until we have a stable environment.
