### ISSUE TITLE
Handle error cases in the current conditions component

### ISSUE THREAD

**Issue by greg-does-weather** [weather-gov/weather.gov#327]
### Description

There are a variety of error cases that the current conditions component can experience, as we're learning. We need to decide what we want to do in those situations and then... do it!

Some example cases:

- The observation station presented first by the API returns nothing
- The observation reported by the selected station returns only invalid data

On the data side, we also need to address how we pick which observation station to look at. The API returns a list and we're currently just taking the first item off the list. But that's not always appropriate – for example, if a station hasn't updated in 3 hours, it's not really useful to us.

### Acceptance criteria

- [ ] We have researched our options, and made some choices
- [ ] We have designed a UX for error states
- [ ] Tests have been implemented or modified to capture the bug
- [ ] Changes have been tested for accessibility

**Comment by greg-does-weather** [comment]
Related: #333

**Comment by greg-does-weather** [comment]
Blocked until we can find out from SDB how the API is filtering/sorting observation stations.

**Comment by colinmurphy01** [comment]
We believe this might be solved for now with #511 and #514
