### ISSUE TITLE
Draft and Submit FIPS199 (Determine FISMA Level)

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#339]
Current doc: https://docs.google.com/document/d/1ml38XLWNSOsDjGHRY3MsP55gstu9ouumayyJ-87N3yo/edit#heading=h.aji7qfaikov4

**Comment by colinmurphy01** [comment]
Blocked until we get further approval from George or other champions?

**Comment by loganmcdonald-noaa** [comment]
Blocked until we are on the same page about who the AO is.

**Comment by colinmurphy01** [comment]
Tagging @shadkeene in this so he can continue to monitor categorization approvals on the NWS end

**Comment by colinmurphy01** [comment]
We have approval to submit this with FISMA Moderate - @loganmcdonald-noaa

**Comment by loganmcdonald-noaa** [comment]
This has been "submitted" and moderate has been approved. We have the green light to move to control selection.
