### ISSUE TITLE
Configure Drupal to use SAML attributes to allow users to login

### ISSUE THREAD

**Issue by loganmcdonald-noaa** [weather-gov/weather.gov#348]
Edit the Drupal configuration to use SAML attributes to broker messages with our ICAM IdP (NOAA accounts). Enable the correct configuration and document how to set this up in future environments.

**Comment by loganmeetsworld** [comment]
Set this up with samltest.id and it is working great, just need to swap out metadata information with icam once they have accepted it. 

![Image](https://github.com/weather-gov/weather.gov/assets/10510566/00bdd330-15e0-4584-b495-08e244ce4853)
