### ISSUE TITLE
MVP Persona documentation

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#352]
We've learned a lot about our various users, let's articulate that better in our documentation and explain who are the core "decision makers" we're focusing on now vs. later. 

I'm envisioning these to be simple personnas we can point to. Rough outline:

## Personna title
- Example of job titles
- Weekly duties
- Responsibilities during hazards
- Decisions they make
- Technographics

**Comment by colinmurphy01** [comment]
@sarahmhgov this is a lingering ticket I've had for a while. 

With the recent rounds of research I feel like this is a low effort thing that could be good for this next sprint. Thoughts?

**Comment by sarahmhgov** [comment]
working on getting into github here: https://github.com/weather-gov/weather.gov/blob/8bb83a797adbaa8e2278cc4bc27becc7ba1e8e5d/docs/user-types.md

**Comment by colinmurphy01** [comment]
Added some comments / suggestions to the PR.
