### ISSUE TITLE
Scope - Detailed weather information

### ISSUE THREAD

**Issue by janelx** [weather-gov/weather.gov#368]
… I want to view an expanded hourly forecast of conditions over the next 72 hours
... I want to view more granular data and details that are relevant right now

**Comment by janelx** [comment]
User goal questions: 
1.) Why are people looking at extended hourly? i.e. do they want to know what the weather will be for a specific time? Are they looking at trends?
2.) Is there any additional weather information that they would like to see? (does "expanded" mean more info?)

**Comment by colinmurphy01** [comment]
@kmranjo @igorkorenfeld @sarahmhgov I'm tagging this one with `product` to say that we need to scope this based on our findings.

**Comment by sarahmhgov** [comment]
Started an initial draft for a detailed hourly requirements https://docs.google.com/document/d/1tPOxuJog3oPFVDhhrywlIQzRir-vwvpwWvLFezXDVBU/edit

**Comment by colinmurphy01** [comment]
@sarahmhgov was this reviewed by design?

**Comment by sarahmhgov** [comment]
Based on conversation with POs, this work is broken into sub-tickets. 

Temperature is being prioritized first.

**Comment by colinmurphy01** [comment]
@igorkorenfeld and @sarahmhgov I believe the only thing left here is for @shadkeene's review and approval right?
