### ISSUE TITLE
e4.v8 hazard page styling

### ISSUE THREAD

**Issue by kmranjo** [weather-gov/weather.gov#378]

**Comment by colinmurphy01** [comment]
@igorkorenfeld when do you want to tackle styling?

Do you want to do it in this Milestone (next two sprints) or do it all together later?

**Comment by partly-igor** [comment]
I am leaning toward pushing it a little later, but can give you a better answer after figuring out how much we want need to adjust for the next round of research.

**Comment by colinmurphy01** [comment]
Closing as this is not relevant anymore. We may reconsider this later.
