### ISSUE TITLE
Follow up with FEMA for user recruitment

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#381]
- [x] Send Bianca a summary of project, how people will help us, time investment, and screener link
- [ ] Support outreach to LTRGs and National groups

**Comment by sarahmhgov** [comment]
Doc here: https://docs.google.com/document/d/1rPagesmuwhz2wT-RpCn57yCywNInYRwXPv7gXV4mEIw/edit

**Comment by sarahmhgov** [comment]
@colinmurphy01 are you good with this?

**Comment by colinmurphy01** [comment]
Yep

**Comment by colinmurphy01** [comment]
Put in touch with the External Affairs person and she is acting as our point person for outreach. This is the survey being used: https://docs.google.com/forms/d/e/1FAIpQLSeD0-i-rytACvinNehGHRWKQv1JpjfwDNDthXjl6kQ2xV2cbg/viewform?usp=send_form
