### ISSUE TITLE
User Research breakdown and prioritization

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#382]
Question to be answered: As we get into planning for usability testing we have limited capacity and bandwidth how should prioritize testing across our user groups?

**Comment by colinmurphy01** [comment]
Discussion is scheduled for next Wednesday

**Comment by sarahmhgov** [comment]
Included in research plan https://docs.google.com/document/d/1xiNoSVLHpCbr5QaUhEwpqlT44Y6QT5VS8H3J-JVF_50/edit#heading=h.j2c2nhsjkof3
