### ISSUE TITLE
Clean up user database spreadsheet

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#383]

**Comment by sarahmhgov** [comment]
spreadsheet is not as much of a mess! 

Note process is: 
- go through the raw screener data
- copy into the master tab ('All public / partner')
- make all rows that have been copied grey
https://docs.google.com/spreadsheets/d/1zFkbQQb5qLRHnLY2bGtdknHj3RvSDL1sA31X9l_Vfms/edit#gid=1858561965
