### ISSUE TITLE
Weather story framing doc

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#399]
Document how we want to frame weather stories in order to brief (and get feedback from) forecasters

[First draft here](https://docs.google.com/document/d/1sj_Yuy1bYlDVPtaWu4t-HmmzhIQG4BVV3VfrRU9wcLI/edit?usp=sharing)

For this sprint
- [ ] Initial draft of purpose of weather story, what to include, how to write it

OOS
- [ ] Tweak based on build
- [ ] Tweak based on user feedback (public/partner research)

**Comment by kmranjo** [comment]
@colinmurphy01  Added the link to a first draft doc above. I think this reflects how we've been talking about both weather and hazard stories so far. Wasn't sure how prescriptive to get, so these are fairly high level and open ended with lots of examples. It does not include the "how" in terms of the tool itself, but we can add that once the process is more established. Does this meet what you were looking for? 
Also want to give @sarahmhgov  and @partly-igor the opportunity to take a look and weigh in to keep me honest with the framing.

**Comment by colinmurphy01** [comment]
I'll review monday, thanks!

**Comment by colinmurphy01** [comment]
@kmranjo revisiting this as we think about #458. Can you help me remember where we landed with Hazard Stories?

**Comment by kmranjo** [comment]
I don't think we've made a final determination on hazard stories yet - it still needs to be looked into for eng feasibility, and we wanted to confirm that even just the weather stories are workable for forecasters before expanding the concept, so #458 would not include hazard stories. Does that sound right, @sarahmhgov ?

**Comment by sarahmhgov** [comment]
I think a conversation would be good, but my take is that there are needs for stories at the hazard level both short term (gap filling) and long term (real time updates), but agree that need more conversations on feasbility and wouldn't be blocking CMS testing on having it built so the framing might be an add on.

**Comment by colinmurphy01** [comment]
If there is time in Design Cowork today, can we chat about this?

**Comment by colinmurphy01** [comment]
Based on yesterday's convo, this should be assigned to @sarahmhgov and incorporated into our discussion guide/briefing materials for #458.
