### ISSUE TITLE
Content modeling

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#401]
[Mural](https://app.mural.co/t/gsa6/m/gsa6/1699474006598/7a5ad4f53d5f1e15f1a82b1addc3a47c22ff3393?sender=u577f2fee72a47ad519ae8698) (where I map out possible content layouts to figure out what a model might need) 
[Spreadsheet](https://docs.google.com/spreadsheets/d/1dmbd8fPU9lH5FHQy06fGBS97sxyVSFh_gawPERuhVi4/edit?usp=sharing) (where the actual model lives. Full disclosure, if we decide to use content models, airtable would probably work better but only going build one if it's worth it for the team) 

- [x] Draft a content model by page (point forecast default + hazard, hazard page)
- [x] Share out internally for feedback
- [x] Determine next steps

**Comment by kmranjo** [comment]
Just an end-of-week update that this is in a decent place, still working on some of the hazard-related content elements, but ready for a convo about this either Monday or once we are past Thanksgiving.

**Comment by kmranjo** [comment]
Worked through this for the WFO attribution/promo component, and shared with design. We determined it may be a useful tool but we don't need to make it a formal thing. I'll just keep using it as part of my process and sharing out if/when it might be helpful. Closing this ticket out.

**Comment by colinmurphy01** [comment]
I do like the spreadsheet as a method to collect our content types and to inform our styling/content governance. I would like for that to persist as we design/build so that when we tackle styling we have an inventory to work from?

**Comment by kmranjo** [comment]
Yup, the spreadsheet will definitely still be a thing - I need it as a way to organize and categorize pieces of information anyway. If it's intended for use beyond just me, we can chat about how best to organize/format it for that purpose. Right now I'm cleaning it up a bit to have each tab reflect a type of information instead of a page, and then will have the actual models listed on their own tab.
