### ISSUE TITLE
Use real location-based content for Hazard prototype testing

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#405]
- Example of hazard based content vs. location based content
- Once the user provides location, provide more location-specific content

**Comment by colinmurphy01** [comment]
Iteration based on feedback

**Comment by kmranjo** [comment]
Content has been created in [this mural](https://app.mural.co/t/gsa6/m/gsa6/1699452608538/fcb4654d4f51366b3320cfa29d17513253725eb1?sender=u577f2fee72a47ad519ae8698), and Igor is adding it to the wires.

**Comment by colinmurphy01** [comment]
Roger, then let's call this done? and then one-off requests can be handled as needed.
