### ISSUE TITLE
Move the point-location-prototype to beta.weather.gov

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#409]
Right now the point-location-search prototype requires access to the direct link to view. POs would like to socialize beta.weather.gov across the NWS and so since we don't have a homepage or navigation setup it'd be great to have that prototype available on the first page.

**Comment by mgwalker** [comment]
I would suggest this be prioritized *after* #370, because that bug feels ***very*** breaking to me.

**Comment by greg-does-weather** [comment]
This is now in staging. It's ready for product review and then a beta deploy!
