### ISSUE TITLE
Document the SAML modules we use and how we use them

### ISSUE THREAD

**Issue by greg-does-weather** [weather-gov/weather.gov#410]
### Description

SAML modules were introduced in #390. They were only installed and enabled in that PR, though. But once we start using them, we need to document what they are and how we're using them.

### Acceptance Criteria
- [x] We have listed the SAML modules we're using, with links to their origins
- [x] We have explained how we're using the modules

**Comment by colinmurphy01** [comment]
@loganmeetsworld Have you done this already?

If not, do you want to do this next sprint, while it's fresh or later?
