### ISSUE TITLE
Categorize all relevant NIST 800-53 controls

### ISSUE THREAD

**Issue by loganmcdonald-noaa** [weather-gov/weather.gov#417]
Take the v8.1 security matrix and categorize all controls by these attributes: 

- Applicability to weather.gov 2.0
- Who is responsible for implementing the control (infrastructure platform/provider, NOAA/NWS operations, application development team)
- Possible implementation details if we are responsible

**Comment by colinmurphy01** [comment]
Is this something that can be done in 1 sprint? Is there a way to break this up maybe by your bullets: this sprint = Applicability to weather.gov 2.0? Next is Who is responsible for implementing the control? OR by control groups?

**Comment by loganmcdonald-noaa** [comment]
I think it can be done in one sprint as an overview, for sure.

**Comment by loganmcdonald-noaa** [comment]
Controls have been categorized by implementation responsibility, now we can break them down and document implementation suggestion/detail.
