### ISSUE TITLE
setup noaa email for Igor

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#418]

**Comment by shadkeene** [comment]
igor.korenfeld@noaa.gov has been set up and I asked Igor to call 855-673-3751 to get his password and finalize it.

**Comment by shadkeene** [comment]
can leave open until @partly-igor confirms it's all ready to go.

**Comment by colinmurphy01** [comment]
@partly-igor and @eric-gade heads up that if you don't log into your NOAA email addresses every 30 days, you get reported to the principal's office.

**Comment by partly-igor** [comment]
Was able to log in and did the training
