### ISSUE TITLE
The location search box sometimes doesn't do anything

### ISSUE THREAD

**Issue by greg-does-weather** [weather-gov/weather.gov#425]
### Description

When you type in the location search box, sometimes nothing happens.

### Acceptance criteria

- Typing in the location search box should always do something.

**Comment by eric-gade** [comment]
I have seen situations where the JS for the search box loads before the input element is present in the DOM, which throws an error (and prevents any subsequent location-izing).
  
The first thing to try would be to wrap the binding of the LocationSearch instances in a `DOMContentLoaded` event handler, ie:
```javascript
document.addEventListener('DOMContentLoaded', () => {
  // Do all the existing stuff in here
}
```
  
Another solution might be to have that JS add an event listener at the `document` level for `input`/`change` events, then check that the target element of the event has the specific `id` or other attribute for the search bar elements.

This way we can guarantee that the element we care about is not only parsed but loaded into the DOM before attempting to set up the eventing for it.
  
Another option would be to wrap this as a web component / custom element.
