### ISSUE TITLE
The location page is not responsive

### ISSUE THREAD

**Issue by greg-does-weather** [weather-gov/weather.gov#429]
### Description

Per @loganmcdonald-noaa, the location page is wonky on mobile. This is likely due to how I implemented the grid and I didn't use the mobile responsive classes.

![IMG_0089](https://github.com/weather-gov/weather.gov/assets/142943695/87c6790c-33cc-4bce-a407-3d2571cc8717)

This page has not yet been designed, but we still ought to make a reasonable effort to make it work reasonably well for users. We can dig into the weeds of how it ought to behave permanently when we get to designing the page, but for now, just spreading the current conditions across the width of the page is probably good enough.

### Acceptance criteria

- The location page works reasonably well on mobile.

**Comment by greg-does-weather** [comment]
The note about the page not being designed is incorrect. It's designed in #248

**Comment by colinmurphy01** [comment]
This is in review. Does this mean it's being worked on/done or should we move this back?

**Comment by greg-does-weather** [comment]
It's in review in PR #439. That PR closes a few different issues (which is a bad practice and I shouldn't have done it...), including this one.
