### ISSUE TITLE
As a person about to go about their day, I want to know the most important weatger conditions in the forecast so I can prepare

### ISSUE THREAD

**Issue by greg-does-weather** [weather-gov/weather.gov#431]
### Description

We currently map icon paths returned by the API into a set of new NOAA icons and short description text. However, the API sometimes returns an icon that simultaneously represents two conditions. For example:

![rain now and partly cloudy later](https://api.weather.gov/icons/land/day/rain/bkn)

This shows rain followed by partly cloudy skies. In this situation, we want to prioritize between the two conditions and only show the user the higher priority of the two. In order to do that, we need to prioritize them so our users can be prepared.

### Questions and Considerations

We will need a definitive list of icons from the API. We've already mapped the icons we know about to NOAA icons and text descriptions, but we need to be sure we have them all.

### Acceptance Criteria
- [ ] We have a list of all the single-condition icons we should expect from the API
- [ ] We have put those conditions into a priority order

**Comment by colinmurphy01** [comment]
Lol we created 3 tickets for this. Closing and tracking in #513
