### ISSUE TITLE
Hazard Flow Prototype for Testing

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#443]
In this next round of research we'd like to test the end to end user experience for a member of the public in two scenarios (hazard is developing and in a hazard).

Using #242 as a foundation, we need to:

- [x] Decide on our hazard and location page hypothesis
- [x] Mock up mobile and/or desktop pages to support testing
- [x] #405 
- [x] Discuss and align as a team (PO, Eng, Design)

**Comment by colinmurphy01** [comment]
@partly-igor can you update this ticket? I believe this is either done or very close?

**Comment by partly-igor** [comment]
Created prototypes for two scenarios:

[Scenario 1](https://www.figma.com/proto/0dSABt9zCqoknaKua6DHmP/NOAA---Weather.gov?page-id=915%3A1056&type=design&node-id=1430-7039&viewport=477%2C-14508%2C0.58&t=Mbi5ddiNwKm6d7AR-1&scaling=scale-down&starting-point-node-id=1430%3A7039&show-proto-sidebar=0&mode=design)

[Scenario 2](https://www.figma.com/proto/0dSABt9zCqoknaKua6DHmP/NOAA---Weather.gov?page-id=915%3A1056&type=design&node-id=1430-7797&viewport=477%2C-14508%2C0.58&t=Mbi5ddiNwKm6d7AR-1&scaling=scale-down&starting-point-node-id=1430%3A7797&show-proto-sidebar=0&mode=design)
