### ISSUE TITLE
Investigate public/browser caching

### ISSUE THREAD

**Issue by greg-does-weather** [weather-gov/weather.gov#450]
### Description

We may need to look into public and browser caching to make sure our assets are cached in a way that's valuable for our users. For example, fonts should be aggressively cached because they're not likely to change very often. We want to make sure that public caches and user browsers don't need to pull duplicate data down very often because that's a waste of time and bandwidth.

Should we spend some time tweaking our Apache settings (via local `.htaccess` files, maybe?) to get the caching behavior we want? Should we look into putting a reverse proxy cache (e.g., Varnish) in front of Apache? Etc.

- Related to/derived from #260

### Acceptance Criteria
- [ ]

**Comment by eric-gade** [comment]
What do we need to look into for the public part? Should we check with cloud-gov to see what the current options are for asset caching?
