### ISSUE TITLE
Update daily and hourly forecasts to use API short descriptions

### ISSUE THREAD

**Issue by greg-does-weather** [weather-gov/weather.gov#455]
### Description

Currently, both components use a mapping from API icons to condition descriptions. This is, from the words of NCO, a "no-go." (For a lot of reasons, not least that those icons will never give us as nuanced results as actual text will.) We should instead use the short description provided by the API.

Because the text descriptions from the API may be significantly longer than the ones in our mapping, we may need to also pair up with design to tweak things accordingly.

> [!NOTE]  
> We know that the API returns different short forecast text than the legacy point forecast page does. This is a concern, but Brian is tracking that and we can come back and adjust when we know what we need to do, if anything.

### Acceptance criteria

- [ ] Tests have been implemented or modified to capture the bug
- [ ] Changes have been tested for accessibility

**Comment by colinmurphy01** [comment]
Can be picked up after #439 is merged.

**Comment by greg-does-weather** [comment]
There's a draft PR #472 for this. I don't remember why I put it into draft rather than marking it ready for review – I think maybe there was still some discussion about whether this is really what we wanted to do?

**Comment by colinmurphy01** [comment]
From a PO perspective, @shadkeene were pretty clear that we should leverage shortForecast. (also validated by Brian)

**Comment by greg-does-weather** [comment]
Well then! I'll put that PR in review.
