### ISSUE TITLE
Identify roles and permissions for the site

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#457]
Details on current state and initial thoughts on future state [being drafted here](https://docs.google.com/document/d/17TTaY2MF_taotKaunoeX2HwoCqiYzomDbStxBAHkdeo/edit?usp=sharing)

Propose the following
- [x] What are the current roles of the site?
- [x] What are the ideal roles for the site moving forward?
- [x] What are the permissions necessary to uphold security and compliance?
- [x] What permissions necessary to do their work?

**Comment by greg-does-weather** [comment]
@kmranjo Now that we can both get into Drupal, want to pair up sometime to go through the list of permissions and decide what shapes of users will need each one?

**Comment by colinmurphy01** [comment]
🍿 

I also started to think about his in [this mural](https://app.mural.co/t/gsa6/m/gsa6/1683818432520/54128f16c12b6200373d7f8c3351f04f3f7fb879?wid=0-1701788236546)

**Comment by kmranjo** [comment]
Oooo yes please! I had ideas around this that I documented waaaayyy back towards like the end of the PA that I can dust off and see if they still stand up to what we know now.

**Comment by colinmurphy01** [comment]
This will require product and org discussion.

Start with some fundamental roles and permissions, but will certainly need more nuanced ones when we define the site more and rollout to regions/WFOs

**Comment by kmranjo** [comment]
Current state has been captured in the doc linked above. 
An initial draft of a proposed permissions structure is also in that same document and ready for review. Since this is not quite the same as other tickets I've worked on, I'm not sure who needs to review it? @colinmurphy01

**Comment by colinmurphy01** [comment]
I'd suggest
- [ ] Design Review
- [ ] PO Review

**Comment by kmranjo** [comment]
Ok cool, @partly-igor @sarahmhgov maybe we can chat about this one during coworking tomorrow? Shouldn't take too long.

**Comment by colinmurphy01** [comment]
Might also be good to chat with @loganmcdonald-noaa about it from a security controls perspective and develop a hypothesis for #523?

**Comment by loganmcdonald-noaa** [comment]
No qualms from security/compliance perspective. I would like to chat about this at eng sync today as a first look. #523 is likely pretty separate.

**Comment by colinmurphy01** [comment]
@kmranjo are you able to join I think it's 4-5pm EST?

**Comment by loganmcdonald-noaa** [comment]
I think it's fine to have the initial conversation amongst just engineering.

**Comment by kmranjo** [comment]
I wouldn't be able to join (hard stop at 4 on Mondays) but the questions in #523 are more about the mechanisms than the people part of the process, so I'm not sure I'd be able to help much anyway. Agree with Logan, it's more for the eng folks.

**Comment by loganmcdonald-noaa** [comment]
To be clear, I don't think our conversation will be about #523 yet, which I believe is sort of a process/org/product question at the beginning at least. It's definitely a separate question to this anyway, and much more compliance/security informing than this.

What I think we need to chat amongst engineering about is this local/WFO vs. national tiers setup for access control and how that would (or would not) work in our current setup at a high level to start.

**Comment by colinmurphy01** [comment]
Notes from PO review

- Good to geaux
- Write out the interim solution for regional and one-off use case for lanterns, for comms purposes?
- Regroup after #558 (how will local be administered? How easy will it be to create a regional tier, if needed)
- We will continue to build out roles/permissions as we build out the site

**Comment by kmranjo** [comment]
@colinmurphy01  I added a note to the doc about the regional and one-off cases. Moving this to Done.
