### ISSUE TITLE
Plan: Weather Story Test - Nashville

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#458]
Once the weather story component is built #180, we'd like to observe how it will be used on a day by day basis. Including

- What content is included?
- What images are included?
- How much effort it takes to write one (compared to current state)?
- Are there any issues (generating images and uploading to CMS)?

Reviews

- [ ] Design
- [ ] Product
- [ ] Engineering (inform, not review)

**Comment by sarahmhgov** [comment]
draft of research plan here: https://docs.google.com/document/d/1CKFj_a28ouSb-7gIQshghJjrWPDaJVufFsuIN_4LuBs/edit#heading=h.j2c2nhsjkof3

**Comment by colinmurphy01** [comment]
Adding a checklist for review.

Should this be added to design co-work today?

**Comment by colinmurphy01** [comment]
Closing and tracking prep #605
