### ISSUE TITLE
Executive Champions Presentation - w/o 2/8

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#460]

**Comment by colinmurphy01** [comment]
Proposed: 2/1 - 30 min

**Comment by colinmurphy01** [comment]
I think this was still proposed but not confirmed. @shadkeene assigning to you to confirm the date and amount of time.

**Comment by shadkeene** [comment]
@colinmurphy01 I'll check on this today.

**Comment by shadkeene** [comment]
Looks like we're a go for an extended 20-min demo and possibly strategic questions in early Feb.  Date shared.  Will collaborate on content for this and close after the demo/meeting is over.

**Comment by GrecoSorcerer** [comment]
I recently found this repo and about 18F while scrounging the weather.gov site and internet.

Are these presentations open to the public? I'm curious about the direction Gov services are going to be going in the new year and beyond.

Sorry for any intrusion.

Best,

**Comment by colinmurphy01** [comment]
@GrecoSorcerer no intrusion, it's cool to see people caring about our work.

We do not open up these meetings in particular to the public or record them.

However this space is regularly kept up to date with our work. We're working on better documenting our milestones as we go, so that should provide greater transparency.

**Comment by GrecoSorcerer** [comment]
> We do not open up these meetings in particular to the public or record them.

Unfortunate but understandable 😅 

> However this space is regularly kept up to date with our work. We're working on better documenting our milestones as we go, so that should provide greater transparency.

The documentations _is_ actually really appreciated. I know that documenting work and setting up tasks can be pretty time consuming.
Making use of the Projects board has made viewing the road map fairly straightforward as well. As far as an outsider's perspective on that goes anyway.

Thank you for the reply, 
Happy New Year!

**Comment by colinmurphy01** [comment]
Closing because it was scheduled.

Using #688 to track prep work
