### ISSUE TITLE
Create accounts in drupal admin for testing

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#463]

**Comment by greg-does-weather** [comment]
The product team now have accounts on staging.

Who should get accounts on beta? Right now Logan is the only person who has access, I think. And it feels right that not many of us should have access to it, if we want to simulate what production will be like. So one or two people who can manage other accounts, and our Nashville forecasters and ITOs?

**Comment by colinmurphy01** [comment]
> So one or two people who can manage other accounts

Like admin roles?

Yes to Nashville peeps. Can you also make sure Corey has an account as well?

**Comment by colinmurphy01** [comment]
We'll wait on reaching out to Nashville for account info until next week

**Comment by colinmurphy01** [comment]
Closing this as the team has admin access. There's more work to be done for setting up test accounts for Forecasters.
