### ISSUE TITLE
Testing page

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#475]
We should create a page that pulls in and renders data for multiple places so that we can observe and assess the data coming from the API.

Locations (shad to fill out):
- Crater Lake, OR
- Biloxi, MS
- Caribou, ME
- Cheyenne, WY 
- Centralia, WA

A page for each:
- Current conditions (across 3-5 locations)
- Daily forecast
- Hourly Forecast

Goals:
- Team can monitor for API errors or inconsitencies
- Team can view variances in weather conditions and copy length

**Comment by colinmurphy01** [comment]
@greg-does-weather what locations should we include to get a variety of weather conditions at any point in time.

**Comment by greg-does-weather** [comment]
The thing about the weather is that it changes all the time. By which I mean to say, there is no such list of locations. :trollface:

I think what I'd want to do for a test page would actually be to find different conditions and collect them into a set of mock API responses. That way we don't have to worry about the test page changing with the actual weather; it'd be a static set of conditions that we've identified and want to be able to look at. Going that route, we could also just make stuff up to test various scenarios, like one hour has a super short condition description ("snow") and the next one is super long("snow and fog and thunderstorms and maybe frogs"). We don't necessarily have to be reliant on actual results from the API for this page.

**Comment by colinmurphy01** [comment]
@greg-does-weather and @eric-gade I think I saw you toying with this in this sprint?

**Comment by greg-does-weather** [comment]
We're changing our approach. #509 updates our weather blocks so they are location-configurable, but we think the layout builder may be a more appropriate approach for the testing page.

So I think this ticket should now go back into the backlog.

**Comment by shadkeene** [comment]
@greg-does-weather @colinmurphy01 @eric-gade I've added 5 locations that hopefully give a diverse and abundant look at weather hazards through March at least.

**Comment by colinmurphy01** [comment]
Feedback from PO Review yesterday:

- Approved
- Deploy to staging not beta
- Add last updated timestamps for each component (daily and hourly).
  - only viewable on testing pages
- Add navigation between testing pages
