### ISSUE TITLE
Displayed icons in hourly forecast can create unexpected/misleading visualization

### ISSUE THREAD

**Issue by kmranjo** [weather-gov/weather.gov#483]
Within the hourly forecast, the icon for a given condition seems to be displayed even if that condition is not especially likely. Attached is an example where the icon would give the user the impression that it will rain all day, but looking at the percentage chance shows that it is actually not the most likely condition forecast for several of those hours. 

![Image](https://github.com/weather-gov/weather.gov/assets/127144183/f89f84f9-be08-4199-9962-cd742d456a18)

I'm not sure if this is a true bug, or an issue with the logic that determines when the icons are shown.

**Comment by colinmurphy01** [comment]
#455 #451 should start to fix this confusion by providing a more detailed forecast description. 

Once implemented we can revisit the topic of should we depend on the API for icons vs. add additional nuanced icons.

**Comment by colinmurphy01** [comment]
@partly-igor can you confirm the above based on what you're designing in #477

**Comment by partly-igor** [comment]
Yes, in the way you described in the previous comment, that our guess is that by providing the description and %chance, we can lessen the confusion.
