### ISSUE TITLE
Conducting and Synthesizing hazard research

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#488]
Accetance criteria

- [x] We conducted 10 interviews (8 user, 2 forecaster)
- [x] Identify priority and future usability issues based on testing
- [x] It's been synthesized in a doc or deck
- [ ] Feedback on components are documented in their github tickets
- [ ] BONUS: Video or audio

**Comment by sarahmhgov** [comment]
Research deck ready to share externally: https://docs.google.com/presentation/d/1u4oyQEZaMoOlp_uqRfsT2Ca4JA9G8YitbiSU5QUormA/edit#slide=id.g28ffbeb00ae_0_9

Internal doc with additional details: https://docs.google.com/document/d/1PX7SPyvBVDP5JAh0P3Cv-1Bmp7ZRbRE1Jzly8bzbdr8/edit
