### ISSUE TITLE
As a product owner, I want to be able to identify which pages people are visiting most often

### ISSUE THREAD

**Issue by greg-does-weather** [weather-gov/weather.gov#497]
### Description

As as a weather.gov product owner, I want to be able to view site analytics and understand which pages people are visiting most often at different times.

In the legacy point forecast, this is accomplished by putting latitude and longitude in the page title so that it will be captured by DAP.

The first step in getting web analytics for beta.weather.gov is to add DAP JS code tags to start collecting the data.  DAP is used for any public-facing page, so beta.weather.gov meets that criteria.  Full instructions can be found here: https://digital.gov/guides/dap/add-your-site-dap/.  There is the option of using locally-hosted code or centrally-hosted.  The centrally-hosted method essentially requires us to add this to the page's code, replacing "AGENCY" with "NWS".
```
<!-- We participate in the US government's analytics program. See the data at analytics.usa.gov. -->
<script async type="text/javascript" src="https://dap.digitalgov.gov/Universal-Federated-Analytics-Min.js?agency=AGENCY" id="_fed_an_ua_tag"></script>
```

Related to #496

### Questions and Considerations

- What are our options for passing data into DAP?
- What information do we want to be sure to capture?

### Acceptance Criteria
- [beta.weather.gov pageviews can be viewed on DAP's google analytics page]

**Comment by eric-gade** [comment]
Note that from an analytics perspective, we can put whatever information we want into `<meta>` tags for specific kinds of pages

**Comment by shadkeene** [comment]
@greg-does-weather I've updated this issue to provide instructions for how to allow DAP to start tracking beta.weather.gov, so we can start viewing things like "pageviews".  There's more to be discussed in terms of URL structure, so we can get the most insightful analytics possible, but this is a start.

**Comment by colinmurphy01** [comment]
Start with DAP

**Comment by colinmurphy01** [comment]
Doc for discussion: https://docs.google.com/document/d/1cbzbEsumFdvx4qWOG7Qxy33Db8iNTH9-NVpUCCMDzqU/edit#heading=h.hkpusizh85gi

**Comment by shadkeene** [comment]
I like what I'm seeing in DAP.  We can see tab clicks on this, we can see which lat/lon folks are visiting, etc.  DAP used to exclude URL parameters, but it doesn't seem to be doing so any more, so we can see tab clicks like daily, etc.  This can probably be closed, unless @coreypieper or others want to see other types of data.



![Image](https://github.com/weather-gov/weather.gov/assets/139174561/a10d2292-9b54-46cf-9604-c4e1b931d88f)
