### ISSUE TITLE
Forecaster testing - hazard prototype

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#502]
Two small group (2-3) convos, being conducted week of 12/11

1. Union reps
2. Nashville WFO leads

Goals:
- How would they feel about the two types of content
- Content tied to hazard
- Edge cases
- Where it lives

To-Dos
- [x] @colinmurphy01 to recruit and schedule
- [x] @sarahmhgov to write discussion guide

**Comment by colinmurphy01** [comment]
Sent out slack message for scheduling

**Comment by colinmurphy01** [comment]
@partly-igor Is this `done`? I'd assume so?

**Comment by partly-igor** [comment]
I thing this one is in progress as we are doing our testing this week 

The prototype itself was another ticket which I did move to done (though I can't find it anymore to reference it).
