### ISSUE TITLE
Enable Media Library for media handling

### ISSUE THREAD

**Issue by eric-gade** [weather-gov/weather.gov#506]
### Description
We want to enable the Media Library, and possibly the Media Types, for image uploads within the CMS. The first example to use is the "forecast image" upload for Weather Narratives.
  
Currently, the upload only permits the CMS author to upload a single image file, but not to view other previously uploaded files. Additionally, if the user attempts to upload the exact same file again, Drupal will indicate an error -- but there is not way to select the existing file. I believe that adding the Media Library component can resolve these problems.

### Questions and Considerations
- Do we need to define all media types explicitly now that we use the Media Library?

### Acceptance Criteria
- [ ] A user can upload an image and then view it in the media library
- [ ] A user can create a new Weather Narrative and select an already-uploaded image for display as the Forecast Image

**Comment by colinmurphy01** [comment]
Deprioritizing this until we pick up CMS UX in Milestone 3

**Comment by jamestranovich-noaa** [comment]
I think we can close this one?

**Comment by colinmurphy01** [comment]
yea we can until we find a use case for it.

there are also some other lingering CMS tickets in `later` that can be closed.
