### ISSUE TITLE
FEMA User Recruitment / Outreach

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#510]

**Comment by colinmurphy01** [comment]
last email sent was in Nov 17, need to follow up

**Comment by colinmurphy01** [comment]
Related: #561

**Comment by sarahmhgov** [comment]
I'm having trouble finding the email thread - any chance you know where it
is?

**Comment by colinmurphy01** [comment]
@sarahmhgov sent you an email that was as a reply

**Comment by sarahmhgov** [comment]
@colinmurphy01 somehow I'm not actually on that email, must have only seen via you forwarding. I'll just respond to the main thread I suppose.

**Comment by colinmurphy01** [comment]
Replied in email, they should have what they need. 🤞

**Comment by colinmurphy01** [comment]
FEMA email has been sent out: https://content.govdelivery.com/bulletins/gd/USDHSFEMA-387be19?wgt_ref=USDHSFEMA_WIDGET_EA
