### ISSUE TITLE
Spike: Research the Layout Builder module

### ISSUE THREAD

**Issue by greg-does-weather** [weather-gov/weather.gov#512]
The [Layout Builder](https://www.drupal.org/docs/8/core/modules/layout-builder/layout-builder-overview) is intended to allow content managers to configure different layouts for different content types or even for individual pages. If it works as advertised and isn't too complex, it could be a godsend.

**Comment by colinmurphy01** [comment]
@kmranjo do we have a use case in MVP for this type of capability? Do we want forecasters or admins to be able to create custom layouts?

**Comment by greg-does-weather** [comment]
To Katrina's point, we're interested in the layout builder module because it may help us create new content types and associated layouts more easily than we can do it right now. Our layouts are currently kind of a mess. This module could help. I think it's worth playing around with to see.

We weren't thinking about it as something for end users to use; we were thinking about it in the context of helping us build more quickly.

**Comment by colinmurphy01** [comment]
@eric-gade I _think_ this is `done` and we're going to test it out in #475?
