### ISSUE TITLE
Anchorage location not working on beta.weather.gov

### ISSUE THREAD

**Issue by klsheets** [weather-gov/weather.gov#517]
### Acceptance criteria

- [ ] Tests have been implemented or modified to capture the bug
- [ ] Changes have been tested for accessibility

**Comment by greg-does-weather** [comment]
The API is not giving us grid information for Anchorage (about [latitude 61.218, longitude -149.858](https://api.weather.gov/points/61.218,-149.858)). I remember from the PA that Alaska is "different" in a lot of ways; is this one of those? Does Alaska not use grids?

But legacy forecast is happy to [provide a forecast for those coordinates](https://forecast.weather.gov/MapClick.php?lon=-149.858&lat=61.218), so we know the data exists and it's probably available in the API, we just need to figure out how to get it.

**Comment by klsheets** [comment]
Alaska issues grids, but it’s different grids than the conusAK grids are polar stereo graphic projection and I think 1.25km, or at least some of them.Pacific region grids are also different.  I think there’s 1 fit Hawaii and 1 for the western pacific territories.  All use the Mercator projection and I’ve lost track of their standard resolution my guess is 2.5 or 1.25kmFor records sake.  Conus grids are lambert conformal projection and depending on element 1.35 or 2.5km I think.It’s been 15 years but the grids were part of my master’s project so I have lots of detailed grid attributes buried somewhere in my brain.Sent from my iPhoneOn Dec 7, 2023, at 7:44 PM, Greg Walker ***@***.***> wrote:﻿
The API is not giving us grid information for Anchorage (about latitude 61.218, longitude -149.858). I remember from the PA that Alaska is "different" in a lot of ways; is this one of those? Does Alaska not use grids?
But legacy forecast is happy to provide a forecast for those coordinates, so we know the data exists and it's probably available in the API, we just need to figure out how to get it.

**Comment by colinmurphy01** [comment]
@greg-does-weather add it to the API spreadsheet?

**Comment by greg-does-weather** [comment]
Added. The API is also not returning observation stations for points in Alaska.

**Comment by greg-does-weather** [comment]
The API has a known bug specifically for the Anchorage CWA. It's on the API's roadmap, but there's no proposed workaround for us in the meantime. #532 is for a short- to mid-term solution to at least let users know that we're aware of the problem.

**Comment by colinmurphy01** [comment]
Closing this issue:

- Short-term solve with #532 
- It's being tracked in [our API spreadsheet](https://docs.google.com/spreadsheets/d/18QuYevG_dNz8nKnW-jGmtBHNwafdqEx8XPRN4Kxlxck/edit?pli=1#gid=0)
