### ISSUE TITLE
Documentation: How to export content in one environment and import it into another

### ISSUE THREAD

**Issue by greg-does-weather** [weather-gov/weather.gov#518]
We expect content authors/managers may periodically need to export content from one environment (e.g., staging) and import into another (beta, or eventually, production). This could be, for example, content associated with new content types, where it can't be added to prod before the updates are released but forecasters etc. could be creating the content in staging in the meantime. Rather than ask them to either wait or duplicate effort, we have a way to export and import content, but it's not obvious. So, we need to document the process well so our users know what to do.

From #504

**Comment by colinmurphy01** [comment]
How should we prioritize this?

I added to `Debt/Bugs/Docs` milestone, so I'm assuming this can wait?

**Comment by greg-does-weather** [comment]
Yeah, that's fine.

**Comment by colinmurphy01** [comment]
@kmranjo @greg-does-weather  this has been hanging in review. What are the next steps for this?

**Comment by kmranjo** [comment]
I think I reviewed and approved a PR for it right before the holidays, but wasn't sure if that meant the ticket was ready to move forward...

**Comment by greg-does-weather** [comment]
Closed in #545. Thanks for the reminder!
