### ISSUE TITLE
Proposal: How are roles and permissions managed

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#523]
Once #457 have been clarified, we need to define the process for which these are managed, including how does...
   - [x] someone become admin
   - [x] admins grant permissions
   - [x] access get downgraded or revoked
   - [ ] etc

Related #650 

Questions coming out of last week's meeting are being addressed [in the doc](https://docs.google.com/document/d/1cqM9sU6O2fbAONCDbv8cAmzCm262F5jUR-r_CwN2vQ0/edit#heading=h.jl241rs3xqny), but some open questions will require a meeting with our primary NWS folks, so putting this in blocked until we have that time available.

**Comment by colinmurphy01** [comment]
@loganmcdonald-noaa we're thinking about deprioritizing this until Apr/May when we tackle CMS UX. Any reason not to? Is this blocking anything?

**Comment by loganmcdonald-noaa** [comment]
No that's fine. I will write up findings on Group and Permissions by Term to close out a proposal for how to handle this this week.

**Comment by colinmurphy01** [comment]
@kmranjo In drafting the easier use case #650 and the progress we're seeing with workbench, I think we'll be unblocked to start implementing this stuff.

However I'm curious to hear if you think we should start drafting more role administration/management workflows for the other 3 roles we've identified (WFO admin, National admin/contributor). I was originally thinking yes because it'll allow us to be extra confident in workbench as our tool, however I'd understand if it was premature to do now and we could close this ticket.

I'd love your opinion.

**Comment by kmranjo** [comment]
Updated the roles/permissions doc to reflect most recent conversations ([linked here](https://docs.google.com/document/d/17TTaY2MF_taotKaunoeX2HwoCqiYzomDbStxBAHkdeo/edit#heading=h.x9hkqn6hm1bb))

**Comment by colinmurphy01** [comment]
We are going to use the champions meeting next Thursday 1015-1050 to align on this and commit to a path forward.

**Comment by colinmurphy01** [comment]
Next Steps:

- Flesh out county, state, region use cases (can our system support assigning individuals to content that's specific to states, regions, or counties)
- Flesh out east palestine use case
- Identify options for who/where sys admins roles will live  
- Identify any other 24/7 use cases that might test the system

**Comment by colinmurphy01** [comment]
Scheduled time with SMEs to discuss follow-up questions on Thursday 1230-1pm EST

**Comment by colinmurphy01** [comment]
Created #893 as a follow up activity that can be picked up if there's bandwidth or after MVP?

**Comment by colinmurphy01** [comment]
I think this is `done` @kmranjo?

**Comment by kmranjo** [comment]
Yup, I think based on the convo last week where it sounds like we're aligned on approach, this is good to go.
