### ISSUE TITLE
V2 Current Conditions based on user research

### ISSUE THREAD

**Issue by greg-does-weather** [weather-gov/weather.gov#529]
- [ ]  Consider removing the plain language text description for sighted users
- [ ] Consider adding a label “current conditions” with the observation station to clarify the type of data
- [ ] Consider the hierarchy and space taken by current conditions, explore ways to collapse information to make it clearer that it is only referring to current vs forecasted.
- [ ] **Display observation station information** - We display the current conditions for a location based on the data from an observation station, but we do not display anything about the observation station itself, which may be several miles from the user. Do we want to show them that information? We can show them the name of the observation station, the observation station ID (3 or 4 letters; can't remember offhand), and maybe the distance from the location being viewed. Are these things relevant/interesting to users? If so, how should we display them? (related to #514)

**Comment by colinmurphy01** [comment]
This is a placeholder ticket for the refinements of our current conditions component. Design will figure out tomorrow what the refinements are and how to track them.

**Comment by colinmurphy01** [comment]
@igorkorenfeld @sarahmhgov @kmranjo did you all identify any other XS/S refinements you want to consider beyond this? If so, can you add them?

I feel like what we chunked out yesterday and today was the high priority stuff, but just checking.

**Comment by partly-igor** [comment]
From @sarahmhgov 's recommendations:

- [ ] Consider removing the plain language text description for sighted users
- [ ] Consider adding a label “current conditions” with the observation station to clarify the type of data
- [ ] Consider the hierarchy and space taken by current conditions, explore ways to collapse information to make it clearer that it is only referring to current vs forecasted.

**Comment by greg-does-weather** [comment]
The last bullet makes me wonder if the headers could be "Currently," "next 12 hours," and "next 5 days." Then it also removes the word "forecast" altogether, too.

**Comment by colinmurphy01** [comment]
Adding checklist to issue description

**Comment by colinmurphy01** [comment]
In the share out today, one of our forecasting testers repeated feedback she gave in her session.

- Clear labels of high/low temperature, whch relates to some of the other questions we've heard
- Rain/Snow accumulation is important (this may be another detailed data point to explore in #368) 
  - there are limitations to this dataset being available in the API, this might need to be considered for daily forecast

**Comment by colinmurphy01** [comment]
Once `done` please update #647

**Comment by colinmurphy01** [comment]
@partly-igor what is the status of this?

**Comment by partly-igor** [comment]
This is labeled design, but I think it's actually an engineering ticket that Eric has already implemented. Design is currently working on a V3

**Comment by greg-does-weather** [comment]
Concur with Igor, this is done in #678

**Comment by colinmurphy01** [comment]
Thanks @greg-does-weather
