### ISSUE TITLE
Competitive Analysis - IA/Content

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#53]
Review major competitors and/or similar sites in other countries to get an overall idea of how different sites break out/organize content, and what approaches they take to weather synopses

Analyzed:
- What content is included for the equivalent of a point forecast page
- How is it organized, treated, communicated

**Comment by kmranjo** [comment]
Raw findings are being stored here: https://docs.google.com/spreadsheets/d/1jL5ipGK6WwlS-YeyujV1JPFMRZ6B6KMx9pd-FJRgx-k/edit?usp=sharing 

I'm planning to get a few slides together to summarize/illustrate the high level takeaways, and dig into the text summaries more

**Comment by kmranjo** [comment]
Findings captured in the deck here: https://docs.google.com/presentation/d/1Xct6T6VMP9KoL-iJRM0d96jslojUyCuqbUuJBe4S_18/edit?usp=sharing 

Will share in demo next week if this is of interest.
