### ISSUE TITLE
Create static page for Anchorage locations

### ISSUE THREAD

**Issue by eric-gade** [weather-gov/weather.gov#532]
### Description

Currently, the API is unable to return grid (and therefore conditions/forecast) information for locations in the Anchorage wfo.
  
We should design and implement a static information page to display to users so that they know we currently cannot provide them this information.
  
From an engineering/cms perspective, this is simply a matter of creating a content page of some sort and capturing all requests to `/AFC/*`, redirecting them to this new page.

### Acceptance criteria

- [ ] There are designs and content for a static page describing how the forecast information is unavailable for the Anchorage area
- [ ] We have implemented this page within the CMS
- [ ] Any request to a URL that begins with `/AFC/` (the Anchorage wfo code) should display the static page we've designed and implemented

**Comment by colinmurphy01** [comment]
Related #327
