### ISSUE TITLE
Hazard - Generic Safety Information

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#548]
[Full details captured here](https://docs.google.com/document/d/1rw6eCqSYQFSNbQs02dH-dAmSPCqmmDKNE4k7fsCC3Os/edit#heading=h.q1j9om24zxvf)

### Supported user stories
- 4.5 … I want to understand the actions or steps I could take to save my life or property at my location

### Design Considerations
- Safety info for the applicable hazard type is displayed adjacent to the hazard product 
- Safety info is grouped by applicable circumstances, with the general default guidance appearing first, and any other labels grouped after (need to determine what the preset labels are, and in what order they display) 

### Implementation Considerations
- Content type created by location-agnostic content contributors
- Content creator would need to be able to associate each piece of content with one or multiple hazard types ("event" in CAP API) 
- Content creator would need the option to associate a piece of content with one of a set of pre-identified circumstances ("in a vehicle", "outdoors", etc) 
- When a hazard product is issued, the system automatically detects the applicable pieces of safety information (tagged with that event type) and displays them alongside the hazard product
- When the hazard expires, it no longer displays. The content never needs to be unpublished, since the display conditions are set by the presence of the paired hazard product. 

### User feedback
TBD

**Comment by kmranjo** [comment]
Updated ticket based on conversation last week, but we do still want to get some input from Corey before diving too far into design.

**Comment by kmranjo** [comment]
Vetted idea with Corey today, updated the document and now this is ready to be picked up whenever it's high enough priority.

**Comment by colinmurphy01** [comment]
This is ready for `Design`?

**Comment by kmranjo** [comment]
Yes, it's ready.

**Comment by partly-igor** [comment]
[Designs here](https://www.figma.com/file/0dSABt9zCqoknaKua6DHmP/NOAA---Weather.gov?type=design&node-id=2023%3A19696&mode=design&t=KHJMkpZmnhOYEmrN-1), reviewed with engineering

**Comment by colinmurphy01** [comment]
Once `done` fill out #649 for engineering

**Comment by partly-igor** [comment]
Design is close, need to figure out one more case of what to do when there is existing content

**Comment by partly-igor** [comment]
Based on our [slack conversation](https://gsa-tts.slack.com/archives/C05DU11D4J2/p1705952655623849), it seemed like we are leaning on this version of the [flow](https://www.figma.com/proto/0dSABt9zCqoknaKua6DHmP/NOAA---Weather.gov?page-id=1970%3A8152&type=design&node-id=2225-41493&viewport=426%2C91%2C0.11&t=AU40SdAMnKbK4hPL-1&scaling=min-zoom&starting-point-node-id=2225%3A41358&show-proto-sidebar=1) 

[Artboards](https://www.figma.com/file/0dSABt9zCqoknaKua6DHmP/NOAA---Weather.gov?type=design&node-id=2225%3A41358&mode=design&t=Kz2Y77cBmgQTBVH7-1)

**Comment by colinmurphy01** [comment]
@partly-igor @kmranjo can you update me on the status of this?

I thought this was in our most recent release?

**Comment by kmranjo** [comment]
It's definitely there in staging, not sure about beta - my access is funky today, cant get to the content management screens

**Comment by kmranjo** [comment]
@colinmurphy01  Access issues resolved, and I can confirm the option to create the content is there in beta. Not sure what our policy is in terms of pushing new authored content to beta, but if we want some of that content built out, I can do that easily.

**Comment by colinmurphy01** [comment]
Good question.

I'd love to do this but I'd like @coreypieper to weigh in on if **we** should be doing it or if we want to bring in an SME to do it with us? Corey might be that SME anyways, lol.

**Comment by colinmurphy01** [comment]
Created #777 to track the work of adding generic safety content to beta.
