### ISSUE TITLE
Dev research spike: Authorization options in Drupal

### ISSUE THREAD

**Issue by greg-does-weather** [weather-gov/weather.gov#558]
In order to understand what our options are with respect to the [roles & permissions doc](https://docs.google.com/document/d/17TTaY2MF_taotKaunoeX2HwoCqiYzomDbStxBAHkdeo/edit#heading=h.vf0n0782mell), we should spend some time investigating more deeply into Drupal's built-in authorization as well as existing modules that may extend it in ways that are beneficial to us.

Goals:
- Understand different ways users may be created. E.g.:
  - If anyone with a NOAA account can sign into the CMS, how do we then assign people the appropriate roles?
  - Should we require the user accounts to be created in the CMS first, and then linked to a NOAA account? (The SAML module we're using appears to support this.)
- Understand roles better.
  - Can we scope them to locations natively, or does that need additional functionality/modules?
  - Should we create one of each role per WFO? (E.g., "Forecaster: Nashville," "Forecaster: Birmingham," "Forecaster: Huntsville", etc.)
- Look into options for tying authorization to taxonomies
  - Can we limit which taxonomies a user is allowed to attach to the content types they're authorized to create?
  - Are local admins limited to only granting access to the taxonomies that they themselves have access to?

This isn't comprehensive, but the primary goal is being able to talk about the roles & permissions doc from an engineering perspective with more clarity.

**Comment by loganmcdonald-noaa** [comment]
We have decided to try out [Group](https://www.drupal.org/project/group) and see if it meets our needs and how content would be organized. Will open two follow up tickets: 

1. Spike on demoing Group with our current publishing setup
2. Research on how Group scales
