### ISSUE TITLE
Public Outreach Article (FEMA Distribution)

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#561]
Community outreach partners at FEMA are willing to share our survey in order to recruit members of the public and vulnerable communities.

They need a publicly accessible article describing weather.gov to do so. Here is some suggested copy we can use:

```
The National Weather Service, the government agency that provides weather forecasts and warnings to the US and territories, is redesigning Weather.gov to better serve the public. We are looking for people to provide honest feedback in order to make Weather.gov more inclusive, accessible, and easy to use for everyone. 

You don’t need to have used Weather.gov before to participate. You can remain anonymous and can opt out at any time.

Sign up for a chance to participate in an upcoming research session.
Signup form link (Google Forms): https://forms.gle/Fh8Nee3jUjaDvTYd9

Sincerely,

Weather.gov team
[weathergov.screener@noaa.gov](mailto:weathergov.screener@noaa.gov)
```

**Comment by colinmurphy01** [comment]
Example from another beta test: https://content.govdelivery.com/accounts/USDHSFEMA/bulletins/3776800

**Comment by coreypieper** [comment]
Passed the draft on to Shad (just a tweaked version of @colinmurphy01's suggestion). Once @shadkeene is good with it, I'll run it through NWS Comms for approval to create a page on weather.gov.

**Comment by coreypieper** [comment]
Here's the page: https://www.weather.gov/weathergovsurvey

Lemme know if/what kind of tweaks y'all want.

**Comment by colinmurphy01** [comment]
@coreypieper and @shadkeene in slack, @sarahmhgov and I were discussing using this copy instead - https://docs.google.com/document/d/1udXnXIZ8fJJrSP98GoV1lM99dJgd9dDwtKVnj3KPyvc/edit#heading=h.igahcuc4y3sp

What do you think?

**Comment by shadkeene** [comment]
@sarahmhgov @colinmurphy01 I love this!  Lots of detail and motivation behind what we're trying to do.  
@coreypieper What do you think?  Can you integrate this on to the web page?

**Comment by coreypieper** [comment]
I think that **[it](https://docs.google.com/document/d/1udXnXIZ8fJJrSP98GoV1lM99dJgd9dDwtKVnj3KPyvc/edit#heading=h.igahcuc4y3sp)** looks pretty good. @colinmurphy01, I posed a Q for you. Until I can get my GitHub notifications fixed up, just shoot me a chat or reply in doc with an @ to me.

**Comment by colinmurphy01** [comment]
Cool it looks like it's approved!

**Comment by colinmurphy01** [comment]
Article is live: https://www.weather.gov/weathergovsurvey

**Comment by colinmurphy01** [comment]
FEMA email has been sent out: https://content.govdelivery.com/bulletins/gd/USDHSFEMA-387be19?wgt_ref=USDHSFEMA_WIDGET_EA
