### ISSUE TITLE
Explore using config_split to manage our configuration

### ISSUE THREAD

**Issue by loganmcdonald-noaa** [weather-gov/weather.gov#562]
config_split allows us to create complete and partial splits for our configuration to use different configuration for different environments. It is probably handy at this point as we differentiate between local, prod, non-prod and want different modules for those environments. Ex: devel should be local only, samlauth should be cloudgov only, and in the future autologout should likely be partial (different settings for each)

**Comment by colinmurphy01** [comment]
I think you said you revisited this yesterday but still unsure if it's the right solution?
