### ISSUE TITLE
Daily/Hourly refinement

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#564]

**Comment by colinmurphy01** [comment]
Moving this back to our backlog so that it can be grouped with #584

**Comment by colinmurphy01** [comment]
@igorkorenfeld Is this incorporated with the designs for #477?

**Comment by partly-igor** [comment]
Yeah, that's right.

**Comment by colinmurphy01** [comment]
I'll close this one and we'll track progress on #477
