### ISSUE TITLE
CMS Flow for MVP roles, permissions, and weather story

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#567]
### Story
As a Forecaster or Admin logging into the CMS, what is the beginning of a forecast user experience to successfully find and navigate the functionality available to me.

[Initial thoughts/questions captured in this doc](https://docs.google.com/document/d/1UBysR2c7Jf798E7YJ-qZfi0qJgbGeSm8eN-pWKLzEIs/edit?usp=sharing)

[Mural sketches here ](https://app.mural.co/t/gsa6/m/gsa6/1704209170874/a425ef22c0c13bf5237124f4ab749b5e049c7cd3?sender=u577f2fee72a47ad519ae8698)

### Considerations
- navigation
- CMS homepage
- viewing my WFO
- viewing other WFOs
- creating a weather story
- managing weather stories (current and past)
- managing my profile and password

### Acceptance Criteria
- There's a clear hypothesis on the core CMS pages, flow, components
- Design has provided feedback
- Eng has weighed in on what's feasible
- Product has provided feedback based on Forecaster SME
- CMS tickets are broken out and ready to be shared/tested for feedback (OR ready for design/dev)

**Comment by kmranjo** [comment]
@colinmurphy01 I started to put together some thoughts about this (doc linked above), but am struggling with the amount of things unknown in terms of technical feasibility and product/org preference. I think a helpful next step would be to talk through these initial thoughts as a group.

**Comment by colinmurphy01** [comment]
For review, is it a lot of work to make a visual of your recommendations? Boxes, arrows, simple copy?

**Comment by kmranjo** [comment]
I don't have very fleshed out recommendations because there are so many different ways this can work and the determining factors are probably going to come down to those org and technical decisions. But I can sketch out some ideas and see if that helps with a conversation?

**Comment by colinmurphy01** [comment]
I get there are a lot of open questions, but it seems we all react well to a visual for discussion.

**Comment by colinmurphy01** [comment]
Adding to list of options to discuss in Friday's Team Hold.

**Comment by kmranjo** [comment]
@colinmurphy01  I was chatting with Igor today about the walls I'm hitting with this one, and he recommended writing up a list of the questions I'm getting stuck on and bringing those to a conversation with the team. I've copied the list below, and between that and the mural (which is a bit dead-ended at this point, but illustrates why the questions are important) I think we have enough to talk through this with the team to get it moving again. 

What mechanism will we use to associate a user with a WFO? 
Would we use the same method to associate a piece of content with a WFO? 
Can we create admin dashboards? 
Can they be pre-populated based on user permissions? Based on associated WFOs? 
Will weather stories be created new each time? 
Or will there be one for each WFO that gets constantly updated? 
If I have permission to author only for one WFO, and I create a new weather story, is it automatically associated with that WFO? 
If I have permission to author for multiple WFOs, and I create a new weather story but don’t finish authoring it and it is not yet tagged with a WFO, what happens to it? Who can finish authoring it, or publish it, if it isn’t associated with a WFO? 
To deal with some of the above issues, ideally a weather story cannot exist in a state where it is not associated with a WFO - is that something we can enforce? 
Do we need a change log with the metadata/attributes, or do we need to save the entire previous version’s content? 
How far back do those changes/versions need to be available? 
Do we have a way to display the content tree to users either as a whole or narrowed to a specific branch? 
If user permissions are in part based on location association via WFOs, and some content is based on location via county or other geographic definition, then how do we associate which users have access to that location-based content? (Use case is Local Resources) 
Would NWS prefer to author local resources as a set (fewer items, but more duplicate content), or individual items that can be compiled into a set (no duplicates, more items to manage)?

**Comment by colinmurphy01** [comment]
We are going to deprioritize this until Milestone 3 (Apr/May). 

At that point we will re-review this and align on an MVP CMS user experience.

**Comment by colinmurphy01** [comment]
@kmranjo do you suspect building out a flow for the CMS is going to be part of the work? Or should I close this?

**Comment by kmranjo** [comment]
I think we can close this out since most of the open questions have been addressed, and the pieces that still exist are tackled in the new tickets created during the scoping exercise
