### ISSUE TITLE
Scope - Find

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#568]
Based on user research we need to identify the features necessary to satisfy our MVP stories:
- 2.1 …I can get to a new weather.gov on the internet
- 2.2 … I want to know this is an official NWS and gov website
- 2.3 … I want to find a location that I’m interested in the weather for
- 2.4 … I want weather.gov to know my location

Currently we have identified:

- #185 
- #190 
- #271 

Acceptance Criteria
- We have a hypothesis for the flow, pages, components
- We have a sense of feasibility and risk
- We have alignment across the team
- We have feedback (if necessary)
- We have tickets representing the work, tagged with
  - Product - if it needs further clarification
  - Design - if it's ready for design
  - Dev - if it's ready for dev

[Scoping doc](https://docs.google.com/document/d/1h6jnisUqozGkW3N7OgOcu_QU1aCu3HqUKG-GbIz399w/edit?usp=sharing)

**Comment by kmranjo** [comment]
Flows and features are outlined in the doc linked above. Team discussion needed to more fully assess risks, challenges, technical capabilities, etc.
