### ISSUE TITLE
Location page loads take around 2 seconds, right at the upper limit

### ISSUE THREAD

**Issue by greg-does-weather** [weather-gov/weather.gov#571]
### Description

Our location page load times are long (around 2 seconds). This is considered to be about the maximum acceptable load time. We need to investigate our sources of latency and find some mitigations because the user experience is suffering. We should also identify a target page load time (Mozilla recommends ~1 second).

### Acceptance criteria

- [ ] Average location page load times are within our target time
- [ ] Tests have been implemented or modified to capture the bug – an e2e test that loads a handful of location pages in succession and averages the load time would be pretty cool

**Comment by elijah-wright** [comment]
I can't test this, but I think the latency issue is waiting on api.weather.gov to provide data back. if there's no other way to get the data quicker, caching may be necessary

**Comment by colinmurphy01** [comment]
@eric-gade is this still an issue. You mentioned that our caching strategy is starting to work.

Should we close this and continue to monitor or are there more substantial solutions we could explore that we could consider?

**Comment by elijah-wright** [comment]
would it be worth it to configure an external cache service (Cloudflare, Varnish) to cache the API with a TTL of 60 seconds? obviously there's apiCache but that's not a persistent cache.

**Comment by eric-gade** [comment]
@colinmurphy01 The caching branch has not been merged in yet ([the PR still open](https://github.com/weather-gov/weather.gov/pull/575) and has some testing errors failing, and we are waiting for @greg-does-weather to come back first)

**Comment by eric-gade** [comment]
Hi @elijah-wright -- Drupal has a built in cache capability that we are going to use initially, it's just that we haven't merged in those changes yet due to holiday lag
