### ISSUE TITLE
Add a cg space for Igor/design

### ISSUE THREAD

**Issue by partly-igor** [weather-gov/weather.gov#574]
The design crew would like to have a dedicated cloud.gov space for future rounds of user research so that we can add in specific scenarios and mock data. For example, we may want test an alert for an area that is not actually currently experiencing hazardous weather.  

@partly-igor might also use this space for styling changes down the line.

**Comment by colinmurphy01** [comment]
Interested to hear, how will this impact our cloud.gov costs

**Comment by loganmcdonald-noaa** [comment]
It should not impact our cloud costs but it should be a temporary
environment.

**Comment by colinmurphy01** [comment]
@igorkorenfeld and @sarahmhgov does this need to be created for #618?

**Comment by colinmurphy01** [comment]
Confirmed with @partly-igor  this is not important for this round. We will use figma for this next round.

**Comment by colinmurphy01** [comment]
We are standing up a temporary space in #825
