### ISSUE TITLE
Scope - CSN

### ISSUE THREAD

**Issue by sarahmhgov** [weather-gov/weather.gov#578]
Define core needs for CSN based on user research to date, document open questions and required research

**Comment by sarahmhgov** [comment]
Drafted initial CSN definition https://docs.google.com/document/d/1aH7wMdcDm3w8NJI5vYAP2Be-MBqH3legc6HqAEJEvQI/edit
next steps: align, flesh into basic flows

**Comment by colinmurphy01** [comment]
Adding to Friday's Team agenda.

**Comment by colinmurphy01** [comment]
Deprioritized from Friday's agenda to reduce distraction from hazards work.
