### ISSUE TITLE
Prototype - Detailed Weather (Temp/Wind/Precip)

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#584]
### Background
Blocked by #659 

Detailed Weather is complicated, there is an endless amount of weather variables and visualizations that could be built into beta.weather.gov to better serve partners.

We've identifed 3 areas where partners need more granular datapoints to effectively prep/plan:
- Temperature
- Precipitation
- Wind

Datapoints across these categories can be rendered at an hourly or daily level.

### Scope

The goal of this is to prototype 1-2 options for where we might put these datapoints so that it's easy to find and presents the necessary info partners need to make a decision.

This will enable us to:
- Evaluate the quantity of information
- What should vs. shouldn't require an "extra click" and how that looks
- get feedback and open the discussion with partners around what and how much detail do they need?

OOS:
- We do not need to explore options for visualization of data (on a plot, graph, color, etc)
- This will not be ready for dev after it's done, further design work will need to happen to get it ready for dev

**Comment by shadkeene** [comment]
@colinmurphy01 Thanks for adjusting this.  Perfect.  This can encompass things like "multiple precip types", etc, applying to hourly and daily, and not be locked down to hourly forecasts.
