### ISSUE TITLE
Monitoring tool Approval and License

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#586]
With the absence of sufficient monitoring software available within NWS to meet our needs, we've identified a tool that can help us in the short-term. We need approval to do so and need to consider getting a license.

- [x] Write up a 1-page proposal to overview our convos, assumptions, needs, recommendation and plan
- [ ] Socialize with champions and CIO for feedback and approval
- [x] Set up free account and consider paid license
- [ ] Consider procurement

**Comment by colinmurphy01** [comment]
Doc: https://docs.google.com/document/d/1UoWR2nUqr6pa_egnnQJTRtBo4tyAFd_4xpkliFyxB4M/edit

**Comment by colinmurphy01** [comment]
@shadkeene @coreypieper take a look at this and add thoughts in the doc.

**Comment by loganmcdonald-noaa** [comment]
We can close this.

**Comment by colinmurphy01** [comment]
Do we need a license for our use case?

**Comment by loganmcdonald-noaa** [comment]
We already have a license by signing up.

**Comment by colinmurphy01** [comment]
Clarification - do we need a paid license?

**Comment by loganmcdonald-noaa** [comment]
I don't think a paid license is necessary at this time.
