### ISSUE TITLE
Alert description field parsing

### ISSUE THREAD

**Issue by eric-gade** [weather-gov/weather.gov#589]
### Description
We need to parse out the raw text of a weather alert's `description` field for better displaying in the UI.
  
According to the [Alert Details document](https://docs.google.com/document/d/1aKfbnZV0FiO5qwELeUczNB63eKZ2I8fmFEni6fGiS5c/edit#heading=h.undl3hq54751), the `description` field can have several formats depending on the type of hazard in the alert and who is issuing the alert. However, many alerts have a consistent textual structure in this field. Specifically, they have the what/where/when structure outlined in the linked document.
  
Note that for this ticket we only want to deal with the [`descrption` ](https://docs.google.com/document/d/1aKfbnZV0FiO5qwELeUczNB63eKZ2I8fmFEni6fGiS5c/edit#heading=h.undl3hq54751)field parts of the "[field exceptions" portion of the Alert documentation](https://docs.google.com/document/d/1aKfbnZV0FiO5qwELeUczNB63eKZ2I8fmFEni6fGiS5c/edit#heading=h.undl3hq54751). Other field exceptions will be dealt with in subsequent tickets.
  
### Prerequisites
#583 should be completed and merged before starting work on this ticket
  
### Designs
[Figma board](https://www.figma.com/file/0dSABt9zCqoknaKua6DHmP/NOAA---Weather.gov?type=design&node-id=1336-19052&mode=design)
[Prototype](https://www.figma.com/proto/0dSABt9zCqoknaKua6DHmP/NOAA---Weather.gov?page-id=915%3A1056&type=design&node-id=1336-19384&viewport=760%2C-2982%2C0.16&t=8MRcYGAOfUF81eCv-1&scaling=scale-down&starting-point-node-id=1336%3A19384&show-proto-sidebar=1&mode=design)

### Example Data
You can find some example data of Alert responses with `description` fields [here](https://docs.google.com/document/d/1fp_kUTLF7pNb36sNwc6rvFThNPQ6lCWHIufck0Yf6iE/edit?usp=sharing). There are examples of alerts both with and without the what/where/when structure.

### Acceptance Criteria
- [ ] Unnecessary whitespace elements are removed from the description field, as outlined [here](https://docs.google.com/document/d/1aKfbnZV0FiO5qwELeUczNB63eKZ2I8fmFEni6fGiS5c/edit#heading=h.ekginlwxpntp).
- [ ] The `description` field is parsed when it can be, according to the what/where/when structure, and those headers are displayed as separate elements in the template (per the [Figma designs](https://www.figma.com/file/0dSABt9zCqoknaKua6DHmP/NOAA---Weather.gov?type=design&node-id=1336-19052&mode=design)).
- [ ] Parsed headers are styled [according to this structure](https://docs.google.com/document/d/1aKfbnZV0FiO5qwELeUczNB63eKZ2I8fmFEni6fGiS5c/edit#heading=h.ujjf3uvz0e0n)

**Comment by colinmurphy01** [comment]
Examples for parsing: https://docs.google.com/document/d/1fp_kUTLF7pNb36sNwc6rvFThNPQ6lCWHIufck0Yf6iE/edit?usp=sharing

**Comment by eric-gade** [comment]
Closed by #654
