### ISSUE TITLE
Alert areaDesc formatting

### ISSUE THREAD

**Issue by eric-gade** [weather-gov/weather.gov#592]
### Description
The `areaDesc` field of an Alert, if present, lists in plain text the areas impacted by the hazard. Depending on the type and location of hazard, the areas may be counties, cities, mountain ranges, or other types of location. 
  
They are presented in a list, separated by semicolons. 
  
Example: Hamilton; Inland Nassau; Northern Columbia; Atkinson; Pierce; Brantley; Inland Glynn; Echols; Clinch; Inland Camden; Northern Ware; Northeastern Charlton; Southern Ware; Western Charlton

### Prerequisites
#583 must be completed and merged before this work can begin.
  
### Designs
[Figma here](https://www.figma.com/file/0dSABt9zCqoknaKua6DHmP/NOAA---Weather.gov?type=design&node-id=1336-19052&mode=design).

### Acceptance Criteria
- [ ] Turn this text list into an unordered list
- [ ] Remove the semicolons
- [ ] Display the unordered list in a bulleted list 
- [ ] For counties effected - use a two column layout

**Comment by colinmurphy01** [comment]
From Des/Eng sync: For counties effected - use a two column layout
