### ISSUE TITLE
Draft FISMA approach

### ISSUE THREAD

**Issue by cannandev** [weather-gov/weather.gov#6]
Document link: [Understanding FISMA for weather.gov 2.0](https://docs.google.com/document/d/1-BR6AHTFD-HCXsNcwOWf7-dZyrwA4Lz9G4hCY0B7So4/edit#heading=h.7cgvyr8ta3q)

If we're not recommending a lower FISMA level for weather.gov, how does that affect the tools and services we're choosing to build? Let's have a plan in place.

**Comment by colinmurphy01** [comment]
Closing this as we proceed with #220, #339 and FIPS 200
