### ISSUE TITLE
R2 Usability Test - hazard Scenario

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#606]
For next round of research, want updates to the prototype and a new (maybe multiple) scenario - something that's severe or unfamiliar to folks. 

Discussed with Igor today, we landed on this for our target scenario: 
- Tornado Watch somewhere in the OHX coverage area (this product type doesn't usually include much information or any safety instruction, so will be best able to gage the value add of the new features) 
- Will not use the city of Nashville for our example, given recent events 
- Will select a location within a county that has enough applicable resources to test the Local Resources feature 
- Will use [this resource](https://mesonet.agron.iastate.edu/vtec/search.php) to use an actual Tornado Watch issued for the selected location sometime in the past 

Content needs:
- Hazard product
- Weather details
- Timing
- Safety info
- Local resources
- Radar/map
- WFO info

[Content captured in this document](https://docs.google.com/document/d/1ljxvYXLYBNumEFmvcPtBRHDMi9He916imBmJXxWxakg/edit?usp=sharing)

**Comment by kmranjo** [comment]
@partly-igor @sarahmhgov  Content for the scenario we outlined is [ready for review in this doc](https://docs.google.com/document/d/1ljxvYXLYBNumEFmvcPtBRHDMi9He916imBmJXxWxakg/edit?usp=sharing)
