### ISSUE TITLE
Document use case for "type of observation" metadata in API

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#610]
We identified a need for the API team to provide observation metadata so that we can filter out or identify the right data to use. 

The API team has requested a write up of the use case. Consider using their template if they have one. If not we can write up a simple description.

**Comment by colinmurphy01** [comment]
@shadkeene a reminder to think about this.

I don't believe this is a `high` priority for us or the API team, so if you want to deprioritize it - it's your call.

**Comment by shadkeene** [comment]
@colinmurphy01 Agreed--not a high priority.  Would like this ability by May though.  Will bring up in convo with Brian.

**Comment by shadkeene** [comment]
Use cases:

As a member of the development team, I'd like to be able to filter out certain types of observations that are less reliable than others.  For instance, CWOP observations do not have standardized maintenance and are owned by members of the public.  ASOS and RAWS have standardized maintenance plans.  Additionally, some observations have sky and weather conditions, whereas some don't, and filtering on these may be beneficial.

As a member of the development team, I'd like to be able to give the user an option to show certain types of observations, based on the types of data they're looking for.

**Comment by colinmurphy01** [comment]
Provided in spreadsheet and sent to brian.
