### ISSUE TITLE
Align on a monitoring plan, short-term

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#612]
We've drafted a recommendation for pursuing cloud-based application monitoring tools - https://docs.google.com/document/d/1UoWR2nUqr6pa_egnnQJTRtBo4tyAFd_4xpkliFyxB4M/edit#heading=h.vyi1z2jevb8d

18F can use NWS project funds to complete a short-term micro purchase with NWS approval.

Checklist
- [x] #615
- [ ] @loganmcdonald-noaa to get quote for services through September 30, 2024
- [x] @shadkeene and @coreypieper to get approvals 
- [x] If team wishes to use project funds, @colinmurphy01 to submit micropurchase request forms ASAP

**Comment by colinmurphy01** [comment]
Based on #615 it seems there is no cost.

I think next steps here would be to align on what we want/can monitor, for short term, and create an ADR?

**Comment by loganmcdonald-noaa** [comment]
I will write up an ADR to close this out!

**Comment by loganmcdonald-noaa** [comment]
#703 closed this out!
