### ISSUE TITLE
Add New Relic to all cloud environments

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#615]
Add our basic new relic account to all environments so we can monitor performance of the site. 

Follow up: 

- [ ] Github action for deployment tracking
- [ ] Add basic users to the account from the team
- [ ] Write synthetic API tests for external dependencies
- [ ] Alerts in Slack

**Comment by loganmcdonald-noaa** [comment]
Blocked on approval to use new relic with our app.

**Comment by loganmcdonald-noaa** [comment]
Got the go ahead to try out.
