### ISSUE TITLE
For end-to-end and accessibility testing, use deterministic data rather than hitting the live API

### ISSUE THREAD

**Issue by greg-does-weather** [weather-gov/weather.gov#619]
For our end-to-end and accessibility tests, we currently hit the live weather.gov API. This results in nondeterministic pages which can cause our tests to miss accessibility problems or bugs. Instead, we should replace the API data with well-known data for our tests so that we can have deterministic pages that fully test the various scenarios we expect to encounter.

**Comment by colinmurphy01** [comment]
Is this also related to #598 / [this thread](https://gsa-tts.slack.com/archives/C05DU11D4J2/p1704726502652899)?

**Comment by greg-does-weather** [comment]
lol. Wow, I forgot about it since ***yesterday***. Yes, it's the same thing. Gonna copy my comment over there and close this as a duplicate.
