### ISSUE TITLE
Plan / Prep - R3

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#627]
Included:

- Scenarios / Location
- Make Content
- Discussion guide / questions
- Profile / quantity of people

OOS

- Recruitment

**Comment by sarahmhgov** [comment]
Yep, Igor and I chatted about this as well. Sounds good.

**Comment by kmranjo** [comment]
Content for this is [outlined here](https://docs.google.com/document/d/1TeieNwJ-gZrUad6x27YqJubdZRvXW5mxR6bbl87Yj3U/edit?usp=sharing)
