### ISSUE TITLE
Scope - Dynamic Map and Radar

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#629]
Across all epics and user groups, a dynamic map is a critical feature people depend on to get more detailed weather information. 

We need to scope:

- User needs (and prioritize)
- Technical options available (based on our ##299) + pros/cons
- Accessibility strategies to consider

[Design brief](https://docs.google.com/document/d/16QfzH-2viPfBoWdpZ0O59qiz1u3qeGsoajq7lCIuArs/edit?usp=sharing)

### Acceptance criteria

- [ ] It’s documented (often in a “Design Brief”)
  - [ ] Specific and clear user stories that we should build now
  - [ ] Open questions or assumptions that need to be clarified
  - [ ] Options for solutions with feedback

### Out of scope for now, until the team is ready to discuss

- [ ] Team is aligned and has provided feedback
- [ ] The work is broken into groups that are similar/should go together and documented as Github Issues as needed:
  - [ ] Scopes for more detailed definition
  - [ ] Spikes for prototyping
  - [ ] Design or Engineering for delivery

**Comment by colinmurphy01** [comment]
@kmranjo in backlog refinement, we think reviewing and finalizing this as a team in the next sprint will be good for this work.

**Comment by kmranjo** [comment]
First draft of the design brief is linked above. Next step would be design review, though it's low in priority compared to other current items so it may just sit there for a while and that's ok.

**Comment by kmranjo** [comment]
Added the feedback that Brian passed along to the Notes section of the doc

**Comment by colinmurphy01** [comment]
Updated brief with product's priorities and synced in Design/PO today.

Updated #773 to reflect priorities, that should be ready for engineering.
