### ISSUE TITLE
Iterate - Detailed Weather

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#632]
Placeholder ticket for iterations coming out of #628 . This will likely be broken up into individual tickets for desing/eng to pick up.

**Comment by partly-igor** [comment]
The following tickets fall under this work
- #878 (Eng + Design)
- #969 (Design)
- #970 (Eng)
- #971 (Eng)
- #972 (Eng + Design)
- #973 (Eng) 
- #974 (Design)

**Comment by colinmurphy01** [comment]
Since we're tracking that work via the above tickets. I'm going to close this ticket.
