### ISSUE TITLE
Conduct - R4, Nashville CMS

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#641]
Targeting week of 4/22

[Pilot testing doc](https://docs.google.com/document/d/1c08m4XqhTEYz7L7kXL2cew35j7qWmku7XyqClKJn-6Y/edit#heading=h.ad4qkf2ij26f)

**Comment by colinmurphy01** [comment]
Nashville scheduled sessions Th-Mon, 11-12pm EST

**Comment by sarahmhgov** [comment]
In progress, guide here: 

https://docs.google.com/document/d/1bkRmvmGxSCHUcMCcq-kb88tZmTnacZ6QGtogWy0bS-M/edit?usp=drive_open&ouid=107981231857696325076
