### ISSUE TITLE
The current conditions narrative text sometimes jumps up into the same row as the "widget" view

### ISSUE THREAD

**Issue by greg-does-weather** [weather-gov/weather.gov#644]
### Description

At around 1020 pixels wide when the current conditions are no wind, the narrative portion of the current conditions will jump onto the same row as the widgets.

### Acceptance criteria

- [x] Tests have been implemented or modified to capture the bug

**Comment by greg-does-weather** [comment]
Not completely fixed. See https://github.com/weather-gov/weather.gov/pull/645#issuecomment-1898881383

**Comment by mgwalker** [comment]
I believe this was fixed in #650. Feel free to re-open it if you see it again!

**Comment by greg-does-weather** [comment]
Oops. I concur with myself.
