### ISSUE TITLE
Iterate Basic Weather components

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#647]
We have updated the designs for the basic weather components. Details for each of these changes are annotated in the Figma file. For daily and hourly we are incorporating the shortForecast as tracked in  #477  

- [x] #678
- [x] #679
- [x] #680
- [x] #681 
- [x] #696

**Comment by partly-igor** [comment]
@partly-igor to update description after finishing #477

**Comment by colinmurphy01** [comment]
Bigger chunk: Viewing hourly forecast within daily. Might need to be broken out and explored separately.

**Comment by greg-does-weather** [comment]
This ticket does not include the hourly details embedded in the daily forecast. Just everything else. 😄
