### ISSUE TITLE
Permissions: How is a user assigned to locations?

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#650]
Hypothesis: User is assigned to a WFO, WFO is associated to locations. This will then allow permissions to create content be established.

Related #523 

In focus:

- Role is able to post to a WFO (this will enable us to build local resources)

Out of focus:

- building out the CMS UX for each role (milestone 3)

**Comment by colinmurphy01** [comment]
Blocked by: #662

**Comment by colinmurphy01** [comment]
@kmranjo began drafting some workflows here: https://docs.google.com/document/d/1bXkfhvrqujVE0B7ffJLHxsL3TwCV5F2n7gS9kbJfXFU/edit#heading=h.srlqpjw10tkz

**Comment by greg-does-weather** [comment]
Is this substantially different from #523? If not, can we close that one and just keep this one?

**Comment by colinmurphy01** [comment]
Good question, I think this one was a specific blocker and the other is the start of a policy across all roles.

I'll regroup with Katrina on 523 this week to see if we should be drafting a policy now for the four roles and situations we know of, or do that later in expand.
