### ISSUE TITLE
Spike: Location page / daily view styling

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#655]
- Explore various (1-2) options for consideration
- Bring to team, get feedback

Included:
- Colors
- Type

Images (likely OOS)

**Comment by colinmurphy01** [comment]
After PO discussion with @klsheets @shadkeene @coreypieper + casual feedback from execs at AMS, there was alignment on Direction B – Serious, technical.

**Comment by colinmurphy01** [comment]
@partly-igor I believe this is `done`?

**Comment by partly-igor** [comment]
Agreed!
