### ISSUE TITLE
Apply USWDS component to hazard detail and banner

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#657]
## Hazard Banner
USWDS [alert component](https://designsystem.digital.gov/components/alert/), using the `usa-alert--slim` and `usa-alert--warning` variants. 
`usa-alert--slim` is already being used, but `usa-alert--info` should change to `warning` 

## Hazard details
- USWDS [accordion](https://designsystem.digital.gov/components/accordion/)
   - Should use the multi-selectable version because we want people to be able to expand/collapse multiple at once 
   - Use the bordered style variant (`usa-accordion--bordered`)
- Upon page load, first is expanded, rest are collapsed. This is assuming that the hazards are sorted by priority order (matching the order of the alert-banner), so we want the highest priority one expanded. 

## Other notes 
Can move forward with this without tabbed navigation
[Figma artboard](https://www.figma.com/file/0dSABt9zCqoknaKua6DHmP/NOAA---Weather.gov?type=design&node-id=1463%3A7684&mode=design&t=yIP6lGIIlNJ5M81N-1)

**Comment by eric-gade** [comment]
Closed by #663
