### ISSUE TITLE
Scope - Detailed weather - Precipitation

### ISSUE THREAD

**Issue by sarahmhgov** [weather-gov/weather.gov#658]
Product doc here: https://docs.google.com/document/d/1tPOxuJog3oPFVDhhrywlIQzRir-vwvpwWvLFezXDVBU/edit#heading=h.q3kaqu5iz4si

Precip: I need to know if the precipitation is rain, snow or freezing rain in order to make decisions ie whether the roads are safe
Weather hazard scenarios: 
Winter weather
Hurricanes
Ice
Sleet

Challenges
Data on probability and accumulation is structured by precip type (wx)
Accum is at the 6 hr level aggregated

**Comment by colinmurphy01** [comment]
Using #368 to track the scoping work
