### ISSUE TITLE
Parsing: Special Weather Statement

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#666]
We parse area effected, but in a special weather statement there is also "locations included"

![Image](https://github.com/weather-gov/weather.gov/assets/24654605/8292bcdc-3f04-445a-9082-51bf7d0b21ea)

**Comment by greg-does-weather** [comment]
The devil's issue.

**Comment by colinmurphy01** [comment]
We parse area effected, but in a special weather statement there is also "locations included"


![Image](https://github.com/weather-gov/weather.gov/assets/24654605/8292bcdc-3f04-445a-9082-51bf7d0b21ea)

**Comment by greg-does-weather** [comment]
Here's a capture of that alert, for future reference.

[active__status=actual&point=41.4729,-81.5464.json](https://github.com/weather-gov/weather.gov/files/13992797/active__status.actual.point.41.4729.-81.5464.json)

**Comment by greg-does-weather** [comment]
I don't think this is a debt issue. This is an iteration and will require design too.

**Comment by colinmurphy01** [comment]
Roger.

**Comment by colinmurphy01** [comment]
Another example


![Image](https://github.com/weather-gov/weather.gov/assets/24654605/16855f91-32d1-43a6-923a-9d3ba5b95923)


![Image](https://github.com/weather-gov/weather.gov/assets/24654605/e0612e2d-c59e-4598-895d-fbdf7abce0b2)

**Comment by colinmurphy01** [comment]
Current state for writing special weather statements:
- D2D has a standard format
- Other way is a text editor and do freeform

We will ensure we parse out the D2D format successfully. Product to find examples using D2D format and ensure that we're formatting it correctly. If not then scope updates.

**Comment by colinmurphy01** [comment]
@coreypieper do you have time today or tomorrow to confirm this?

> We will ensure we parse out the SPS D2D format successfully. Product to find examples using D2D format and ensure that we're formatting it correctly.

**Comment by colinmurphy01** [comment]
We successfully format D2D SPS. We will not parse and format GFE-based SPS. That will be need to be enforced via policy.

Will add to risk spreadsheet.
