### ISSUE TITLE
UX: Upon clicking a hazard banner, expand hazard details

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#667]
Upon clicking a hazard banner, I want to jump to the corresponding hazard details (current) AND have that accordion automatically expand (desired).

Current state video: first banner is automatically expanded (which is demoed and desired), but after clicking second banner it doesn't expand, and after collapsing first accordion and clicking again it doesn't expand.

https://github.com/weather-gov/weather.gov/assets/24654605/dc0d427e-992c-444a-a77c-d1bdbf803f35

**Comment by colinmurphy01** [comment]
@igorkorenfeld can you confirm that this is desireable?

**Comment by partly-igor** [comment]
I hadn't thought about that interaction before it was implemented, but yes you are right that's likely the interaction a user would expect – clicking the anchor link in the alert jumps down to an expanded text.

**Comment by greg-does-weather** [comment]
We can pick this up after #681. The code in there is already poking around the relevant DOM elements, so it should be fairly easy at that point.
