### ISSUE TITLE
Daily/Hourly view

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#677]
Related to: #647 

This focuses on viewing an hourly forecast within a daily forecast.

**Comment by eric-gade** [comment]
@colinmurphy01 No, this is not done. The hourly-in-daily is still going through design, per @partly-igor

**Comment by colinmurphy01** [comment]
Ahhh yes my mistake. 

I got confused from looking at the prototype last week.

**Comment by colinmurphy01** [comment]
Yes. Closing.
