### ISSUE TITLE
Iterate current conditions

### ISSUE THREAD

**Issue by greg-does-weather** [weather-gov/weather.gov#678]
## Current conditions  
[Annotated Mobile](https://www.figma.com/file/0dSABt9zCqoknaKua6DHmP/NOAA---Weather.gov?type=design&node-id=2196%3A31789&mode=design&t=bOEgGOPKzi4hAEyK-1)

[Annotated Desktop](https://www.figma.com/file/0dSABt9zCqoknaKua6DHmP/NOAA---Weather.gov?type=design&node-id=2203%3A38425&mode=design&t=bOEgGOPKzi4hAEyK-1)

[Reference (no annotation)](https://www.figma.com/file/0dSABt9zCqoknaKua6DHmP/NOAA---Weather.gov?type=design&node-id=2196%3A33525&mode=dev&t=bOEgGOPKzi4hAEyK-1) 

Component of #647

**Comment by eric-gade** [comment]
Closed by #692
