### ISSUE TITLE
Add tabbed navigation to basic weather

### ISSUE THREAD

**Issue by greg-does-weather** [weather-gov/weather.gov#681]
## Tabbed navigation
Only a couple of notes here, this one likely will surface a lot of questions, but would be happy to pair on this and answer questions as they come up. 

[Annotated artboard](https://www.figma.com/file/0dSABt9zCqoknaKua6DHmP/NOAA---Weather.gov?type=design&node-id=2196%3A31948&mode=design&t=bOEgGOPKzi4hAEyK-1)

Component of #647

**Comment by eric-gade** [comment]
Closed by #728
