### ISSUE TITLE
Prepare/Meet with Executive Champions and demo beta.weather.gov

### ISSUE THREAD

**Issue by shadkeene** [weather-gov/weather.gov#688]
Prepare what we want to share/demo with Executive Champions on Feb 8.  Be ready to answer any strategic-level questions from the group.  Ensure all are aware of status/progress of project.

**Comment by colinmurphy01** [comment]
Drafted deck: https://docs.google.com/presentation/d/1Jf94gWYcHM4X7WDTDMLYNlFcpDXH8DVbnEiVeMEo3ak/edit#slide=id.g26718f02b12_0_410
