### ISSUE TITLE
Refactor templates to use partials for consistency

### ISSUE THREAD

**Issue by greg-does-weather** [weather-gov/weather.gov#695]
### Description

Rather than hope we do things the same way in different places within our templates, we should make use of partials. We'll collect a list of things that should be partialized here.

- [ ] temperatures (the number with floating ℉; we currently implement it a few different ways, which is silly)
- [ ] gov banner (currently re-implemented in all of our index templates)

### Acceptance criteria

- [ ] To the best of our knowledge, all instances of the above have been replaced with template partials

**Comment by colinmurphy01** [comment]
Related: #930

**Comment by colinmurphy01** [comment]
Confirmed with @eric-gade this is done.
