### ISSUE TITLE
Investigating what's available in API for hourly data for use in details weather display

### ISSUE THREAD

**Issue by coreypieper** [weather-gov/weather.gov#705]
Looking for what variables are already available in API's hourly and gridpoint endpoints to help inform decisions as to what to include in detailed fcst and/or what to request from SDB for additions/modifications. 

https://api.weather.gov/gridpoints/FWD/67,100/forecast/hourly?units=us

- We need to determine if we should use [/gridpoints](https://api.weather.gov/gridpoints/MPX/108,72) over [/forecast/hourly](https://api.weather.gov/gridpoints/MPX/108,72/forecast/hourly)
- If we use /gridpoints how do we handle the multiple hour use case

**Comment by colinmurphy01** [comment]
For this ticket we don't need to list out all of the data in gridpoints, we'll do that when we implement detailed weather and determine where to get the data.

In regards to the second question /gridpoints tells us the duration of the variable, we will rely on that.
