### ISSUE TITLE
Parsing: Additional Details being cut off after first paragraph

### ISSUE THREAD

**Issue by shadkeene** [weather-gov/weather.gov#713]
### Description

When there are additional details that span more than one paragraph, either beta.weather.gov or API seems to be cutting off the second paragraph.  Images below show the difference.

### Acceptance criteria

beta.weather.gov shows entire "additional details" section for hazards.

- [ ] Tests have been implemented or modified to capture the bug
- [ ] Changes have been tested for accessibility
![additional_deets_full](https://github.com/weather-gov/weather.gov/assets/139174561/986b0e92-bd42-4e01-8603-1243d0a7d25b)
![additional_deets_partial](https://github.com/weather-gov/weather.gov/assets/139174561/9f8a925a-2768-4105-b935-9312983cdf92)

**Comment by shadkeene** [comment]
It does look like alerts API has both paragraphs
![alerts_fulldetails](https://github.com/weather-gov/weather.gov/assets/139174561/c1aec88b-3d05-4aa6-a3e8-3ddb3933e462)

**Comment by greg-does-weather** [comment]
That flood warning from the API:

[active__status=actual&point=37.7812,-122.4263.json](https://github.com/weather-gov/weather.gov/files/14090344/active__status.actual.point.37.7812.-122.4263.json)

**Comment by greg-does-weather** [comment]
Related to #712

**Comment by greg-does-weather** [comment]
Closed by #748
