### ISSUE TITLE
Explore impact graphic implementation

### ISSUE THREAD

**Issue by kmranjo** [weather-gov/weather.gov#719]
Design is interested in using the impact graphics to satisfy the user need of "view hazard on a map". 
- Using the entire graphic in weather story
- Taking only the map section of the graphic for use within the alerts/hazard details
- Using only the map section with the weather story
- Some combination of the above

In convo with engineering, discussed that if we have access to impact graphic through an endpoint(s), we could
1. Use the entire image
2. Use the entire image and use CSS to clip out the map (assuming the maps are always the same dimensions) 
3. Use the map part of the image directly
Options 1 and/or 3 are preferred, since option 2 might increase network traffic. 

However, all options are dependent on access to the impact graphic. Since the graphics come from a source outside of weather.gov/cloud.gov, we don't yet know how to set up that kind of file transfer. 

Next steps for this exploration are: 
- [x] Determine how file transfers work on cloud.gov 
- [x] Document options and risks

**Comment by kmranjo** [comment]
@colinmurphy01 @eric-gade @greg-does-weather Does this writeup reflect what we discussed this morning and what next steps should be? 

@partly-igor Just FYI, this is the ticket I mentioned

**Comment by colinmurphy01** [comment]
Related: #616

**Comment by greg-does-weather** [comment]
Yep, this captures it perfectly! Thank you!

**Comment by colinmurphy01** [comment]
Coming out of this research round and #629 we need to determine if the static impact graphic is the right solution before building it.

**Comment by loganmcdonald-noaa** [comment]
Questions for the impact graphics team: 

- [ ] Ensure that they can communicate over the open internet and providing a JSON API will work for them
- [ ] Ask what file types need to be supported - just images? 
- [ ] Ask what size of files they intend to send and if it is standardized
- [ ] Ask what cadence they send graphics - number of files per day/per hour

**Comment by eric-gade** [comment]
@loganmcdonald-noaa I'm hoping that the [media library ](https://www.drupal.org/docs/core-modules-and-themes/core-modules/media-library-module) ([ticket here ](https://github.com/weather-gov/weather.gov/issues/506))-- once integrated -- can give us permissions on whole directories/classes of images. We would likely need to pipe images into the media library using the core drupal media library api behind the scenes.

**Comment by loganmcdonald-noaa** [comment]
We got some answers via email from the impact graphics team. We are looking at images every 5 mins during active winter season but often less frequent other times. The graphics are PNG or JSON. The sizes are 100-300k px (I assume) per graphic.

**Comment by loganmcdonald-noaa** [comment]
We have all the information we need here to move forward when time comes to implement! The one thing I'll see is that the media module will help us derisking the UX on handling the incoming images a bit more so I'd prioritize that sooner rather than later.

**Comment by colinmurphy01** [comment]
We're going to make a decision on whether to move forward with this feature in tomorrow's Design/PO sync.
