### ISSUE TITLE
Recruit users for ongoing research (WRN)

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#73]
### Description
We need to recruit users from our 3 personas in order to test for user value and impact. The personas include:

- **Members of the public**
- **Partners at varying levels (national, state, local, community)**
- NWS Forecasters

### Considerations
- PRA Approval
- Compensation for testing (based on time and activity)

**Outcome: This is critical to assess impact on user-based outcomes**

### Justification
- Value: High
- Viability: Medium
- Alignment: High

```[tasklist]
### Work
- [ ] #25
- [ ] #72
- [x] Build form for screener
- [ ] Send outreach materials
- [ ] Gathering users in spreadsheet
```

**Comment by colinmurphy01** [comment]
I believe all 3 forms have been built, they are hosted [here](https://drive.google.com/drive/folders/13KyuR8Nr9rgNY8t7S5GKxSZ52egf15mj)

**Comment by colinmurphy01** [comment]
Waiting on OMB approval

**Comment by colinmurphy01** [comment]
To-Dos:
- [ ] - Tweet for Krissy to send out screener to the public
- [ ] - Follow up with Marcus and Doug at FEMA

**Comment by colinmurphy01** [comment]
WRN email (204 recipients) went out

**Comment by colinmurphy01** [comment]
Update:
- We have 8 respondents signed up from WRN so far, continues to trickle in ([sheet](https://docs.google.com/spreadsheets/d/1zFkbQQb5qLRHnLY2bGtdknHj3RvSDL1sA31X9l_Vfms/edit#gid=452906046))
- We discussed in the champions meeting who should be our priority candiates for MVP ([link](https://docs.google.com/document/d/1yVPG2XV1HhlsQ8p4upZwWjJ4H5-0qEmaFSihldAu_jc/edit#heading=h.yyfw6sry1fp8))
  - this may lead us to screen out some of our initial sign-ups from WRN

Next steps to consider:
- We should recruit via WCN partners (meeting with Brian next wednesday) - using WRN outreach materials
- We should send an email to WRN partners tagged as "non-profit" and "govt" (getting estimate from Doug)
- We could send a tweet out via Nashville channels (however it might be too broad)

**Comment by colinmurphy01** [comment]
After regrouping with Doug, we need to get back to him on:

- The profile and count of our ideal next round of outreach

Along with better documenting our outreach strategy.

**Comment by sarahmhgov** [comment]
Working on it right now

**Comment by sarahmhgov** [comment]
https://docs.google.com/document/d/1uMd9teC3GmvT-8cMvAMGYVLX37ObLwbEv7JQsy_LHrg/edit

**Comment by sarahmhgov** [comment]
Update - Doug sent out to the second batch of WRN folks Mon, Oct 23. Can close or keep open for now

**Comment by colinmurphy01** [comment]
1K emails have been sent this morning.
