### ISSUE TITLE
The new tabbed navigation needs to be accessibility tested

### ISSUE THREAD

**Issue by greg-does-weather** [weather-gov/weather.gov#733]
### Description

The tabbed layout introduced in #728 wasn't accessibility tested as part of the code review. (Blame GSA IT.) We need to do that sooner rather than later.

### Acceptance criteria

- [ ] Changes have been tested for accessibility

**Comment by eric-gade** [comment]
Additionally, per @partly-igor , we should ensure that we are using good ARIA attributes according to the [tab pattern described here](https://www.w3.org/WAI/ARIA/apg/patterns/tabs/). I think maybe we should add that as an AC to this issue.

**Comment by greg-does-weather** [comment]
Done in #753
