### ISSUE TITLE
Refactor layout around Twig templates for weather stories and WFO promos

### ISSUE THREAD

**Issue by greg-does-weather** [weather-gov/weather.gov#734]
### Description

When those two components first went in, they were side-by-side, so in order to put them on the same row, the row had to exist outside of both templates. Now that they're stacked vertically, however, that's not a concern anymore. We can clean up how they're being laid out and make it more consistent with the other components.

See https://github.com/weather-gov/weather.gov/pull/728#discussion_r1475135318

**Comment by colinmurphy01** [comment]
@greg-does-weather this feels like a `medium` priority and something we should do by end of May? Agree?
