### ISSUE TITLE
Adjust Weather Stories 

### ISSUE THREAD

**Issue by partly-igor** [weather-gov/weather.gov#739]
### Description
We heard from users during R2 that they were not sure what “Outlook” meant and it wasn’t something they seemed they placed a lot of value on in as compared with the other sections 

### Acceptance Criteria
- [ ] Evaluate what content if (any) lives in the current "Outlook" tab
- [ ] Come up with new title for the "Outlook" tab containing weather stories and the WFO promo

### Options
We’ve established the weather story as a space that forecasters can use to communicate whatever is most relevant that day. Because it is so flexible, it’s challenging to come up with a framing for it that feels accurate. 
Below are some options to consider, listed in order of preference. 

**Option 1 - Leans into the categories users are most used to seeing.** 
Make the label Today and move all today-related elements into it, including the weather story, day’s forecast and hourly breakdown. 
Pros: Presents a breakdown users are already familiar with, and reduces the need to go to multiple tabs for all info relevant to the current day. 
Cons: Weather Story can at times be relevant beyond the current day, though this is something stakeholders could control for. This solution also makes the tie to WFO promo less relevant, so we might need to reconsider where that lives if we go this direction.  

**Option 2 - Lean into NWS framing around forecaster voice**
Make the label Story, and include within the tab a subhead along the lines of “highlights from your local forecast office”. Present in next round of research and see how users react 
Pros: Puts the forecaster voice at the forefront and allows us to get user reactions to a more direct presentation of that voice. 
Cons: Its still a pretty vague term so will struggle to meet/create specific expectations for users. We’ve also heard less direct interest in the voice so much as the information it communicates.  

**Option 3 - Lean into the framing of location, since that's the primary tie between the items in that tab (story and wfo promo)**  
Make the label Area or Region and see how users react 
Pros: Reinforces the user’s location, clarifies the organization of content in a way that doesn’t require interpretation. 
Cons:  May be a less appealing/motivating label, which could lead to fewer users viewing what is technically critical information. Also has the potential to introduce confusion, since it takes a wider interpretation of location than the forecast itself does.

**Comment by kmranjo** [comment]
@partly-igor @sarahmhgov updated the ticket above with the options I mentioned in our meeting this morning

**Comment by partly-igor** [comment]
I'll wireframe these in Figma to help the conversation, let's have another conversation within design looking at them, and then can move to in-review so we can review with the team.

**Comment by colinmurphy01** [comment]
Confirmed the other day that this is `done` in #802
