### ISSUE TITLE
Iterate on Current Conditions 

### ISSUE THREAD

**Issue by partly-igor** [weather-gov/weather.gov#740]
### Description
Current conditions take up a fair amount of space in the current iteration. We heard in R2 that users find it somewhat helpful, but it is not the part they are most interested in. 

Because it takes up so much room it also means that users on the smallest devices will need to scroll down to see the tabbed content area

### Acceptance Criteria
- [ ] Find ways to reduce the vertical space taken up by current conditions
- [ ] Consider alternative placement
- [ ] Consider removing lat/long, minimizing remaining elements of obs station

**Comment by colinmurphy01** [comment]
@partly-igor I believe this is done?
