### ISSUE TITLE
Iterate on Tab Order

### ISSUE THREAD

**Issue by partly-igor** [weather-gov/weather.gov#741]
### Description
During R2 we heard from different users different preferences for what they would like to see first when looking through the information. It seems the current order does not match those preferences, though it will be harder to find an order that perfectly matches everyone's preferences. However should consider changing the current order of the tabs  (Alerts, Outlook, Hourly, Daily). 

### Acceptance Criteria
- [ ] Evaluate the current order
- [ ] Try a new ordering of the tabs that matches up with what users want or expect to see first

**Comment by colinmurphy01** [comment]
@partly-igor I believe this is done?
