### ISSUE TITLE
Add custom logging capability

### ISSUE THREAD

**Issue by eric-gade** [weather-gov/weather.gov#754]
### Description
We want to be able to log specific information from within Drupal, and have it display in `stdout` like other logs commonly do. This will allow us to grep the Docker / Cloud-gov log output.
  
We will probably want to use the [log_stdout plugin](https://www.drupal.org/project/log_stdout) (but be aware of [this open issue](https://www.drupal.org/project/log_stdout/issues/3339853))

### Acceptance criteria
- [ ] We can log custom information from within Drupal and have it display in Docker & Cloud-gov logs

**Comment by greg-does-weather** [comment]
Noting for reference, here's a thing we want to log: https://github.com/weather-gov/weather.gov/pull/751#discussion_r1483470745

**Comment by eric-gade** [comment]
Note: we are exploring options to pipe Drupal's own logging to newrelic. For the moment, we should implement our internal logging patterns just using the Drupal log

**Comment by colinmurphy01** [comment]
@eric-gade based on your work now, is this work still recommended? Is this a `low` priority in your mind or do you have a use case in mind that would make this a `medium` priority for MVP.

**Comment by eric-gade** [comment]
@colinmurphy01 I am just about to push a PR for #765 which is directly related to this issue (it's the thing I've been working on that whipped)

**Comment by colinmurphy01** [comment]
I believe we can close this?

**Comment by colinmurphy01** [comment]
With NewRelic this should be covered. As we want to measure/monitor ertain things we can scope that and discuss separately.
