### ISSUE TITLE
Engineer for case when gridpoints change for same location

### ISSUE THREAD

**Issue by shadkeene** [weather-gov/weather.gov#756]
Per John Sullivan who works in NCO/IDP: 

_Hi Corey & Shad,

Nice work on this project.  I took a look at [beta.weather.gov](http://beta.weather.gov/) and wanted to provide some technical feedback on something I noticed.  It appears that when I put my city, state into the search I am taken to a url that appears to include the API's gridX and gridY coordinates.  I.e., https://beta.weather.gov/local/TBW/75/60

One possible issue I see with doing that is that folks tend to bookmark their local forecast page.  I'm not sure how this works on the MVP backend, but those grids can change without notice under [api.weather.gov/gridpoints](http://api.weather.gov/gridpoints) if the WFO updates their GFE grid definition.  When that happens NCO OBT runs a realignment of the grid in the database, which will change the points (lat/lon) -> gridpoints (netcdf) alignment.  If a customer bookmarks that page, one day that grid could be for a different location, even become marine, or worse, no longer be valid.  Again, I'm not sure how a grid update would be handled by MVP url/code if a user attempts to use a grid that has been updated in [api.weather.gov](http://api.weather.gov/), but I thought it might be something to consider in the development efforts.

Please let me know if this makes sense.  Happy to hop on a meet and share screen to clarify.

John_

So we need to figure out a way for a user to bookmark a location for beta.weather.gov where that location will always remain the same, even if gridpoints change.

**Comment by colinmurphy01** [comment]
@greg-does-weather I believe we're switching over to using lat/long instead of gridpoints. Will that solve this issue?

**Comment by greg-does-weather** [comment]
Yep!
