### ISSUE TITLE
Observations: null icon

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#764]
### Description

Currently if there is no icon for observations, the default icon is 

![Image](https://github.com/weather-gov/weather.gov/assets/24654605/744fd5d1-52ba-4be6-b0a8-39bf2505b91f)

This can cause people to think there is a hazard in their area.

We should instead replace this with an icon (or no icon) that better communicates this error. 

### Acceptance criteria
- [ ] Tests have been implemented or modified to capture the bug
- [ ] Changes have been tested for accessibility

**Comment by colinmurphy01** [comment]
How do we feel about this icon?


![Image](https://github.com/weather-gov/weather.gov/assets/24654605/8badcfc8-5233-4473-a8f0-d5a88017eb81)

**Comment by greg-does-weather** [comment]
I honestly haven't paid attention. We can put it on the menu for tomorrow's API sync.

**Comment by colinmurphy01** [comment]
@partly-igor it was definitely a joke. But I appreciate the complement. Felt cute, will delete later.

**Comment by greg-does-weather** [comment]
@partly-igor They are computed separately, so one can have a value while the other is null.

**Comment by elijah-wright** [comment]
would a question mark work better? the file icon is cute but it's supposed to be serious

**Comment by partly-igor** [comment]
I explored a few different options for the icon, but I think the clearest option is actually to have no icon at all when it's null.

**Comment by colinmurphy01** [comment]
I believe this is unblocked now, so I'll move this into the backlog
