### ISSUE TITLE
Log Observation Stations

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#765]
Based on our current logic for gathering observation stations, if data is missing from the first, we go to the next station in the list, then the third station.

We want to log

- How many point location page results use the first obs station, second, or third
- What is the difference in **distance** from the point to the observation station location
- What is the difference in **elevation** from the point to the observation station location

This will allow us to evaluate the quality of observation data at scale.

**Comment by eric-gade** [comment]
Looks like #754 will be a prerequisite here
