### ISSUE TITLE
Add CWA shapefile to spatial data loading

### ISSUE THREAD

**Issue by eric-gade** [weather-gov/weather.gov#766]
### Description
In order to better facilitate GIS operations -- in particular #648 -- we first need to load the shapefile containing CWA/WFO boundaries.

### Questions and Considerations
The shapefile for CWAs, along with a description of the record metadata schema, can be found [here](https://www.weather.gov/gis/CWABounds).

### Acceptance Criteria
- [ ] Loading the CWA data into the weathergov gis database is a prodecure that is added to the load-spatial setup

**Comment by greg-does-weather** [comment]
Done in #767
