### ISSUE TITLE
Refactor pre-processing fetched data on the local point forecast page

### ISSUE THREAD

**Issue by eric-gade** [weather-gov/weather.gov#768]
### Description
In #720 we added the ability to preprocess fetching of certain bits of weather data from the API, so that we could know information ahead of time that would be relevant for rendering the overall page. For example, we needed to know if the point had corresponding alerts _before_ rendering the tabbed view, so that a page without alerts doesn't render the alerts tab at all.
  
Upon investigating what seemed like slower page load times, @greg-does-weather was able to determine that the preprocessing was not taking advantage of our site caching, and therefore adding upwards of 800ms to page load times ([slack thread here](https://gsa-tts.slack.com/archives/C05DU11D4J2/p1707514119130899)).
  
The gist: we need to find a way to fetch all WeatherDataService data for the location page ahead of time (like on page load), and then to make all of the data available to the templates. Instead of using Twig Tweaks to render each block on its own terms, we should try to pass this data to the blocks directly. Or even better: we should pass the data to each block's template file, including it as if it was a template partial.
  
The only way to find out is to try stuff.

### Acceptance criteria

- [ ] The page does not make multiple unnecessary calls to the same API endpoints for the same data
- [ ] We are still able to make determinations about the availability of alerts before we render the tabbed navigation view component

**Comment by greg-does-weather** [comment]
Guzzle (the HTTP library Drupal uses) can do parallel fetches, so if we're loading all the data up-front, we may be able to make some optimizations there as well.
