### ISSUE TITLE
Spike - Map and Radar

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#773]
We want to Prototype 2-3 options to help us determine which is the best tool to use based on our needs.

Use cases for MVP

- I want to view radar reflectivity over time to see how precipitation is forming around me
- I want to view an active hazard on a map to see if I'm impacted

Musts for MVP include:

- Can support radar reflectivity and hazard area
- Work on desktop and mobile (is there a bandwidth minimum required)
- Load quickly (determine time threshold)
- Display a marker for my location
  - Ideally based on browser location
  - In case of search, generic marker for location
- Automatically zooms and aligns location pin in the center of map (need to determine zoom level)
- Zoom
- Base Map must include
  - State borders
  - Names of cities and towns
  - Major roads
  - County borders (will this impact load)
- Supports animation
- Supports timestamp
- Supports a legend for defitions

Additional areas to investigate:
- Can the interface be customized with USWDS buttons or styled with font/color
- Can it support keyboard navigation for accessibility?

Should/Could/Won't features are included in the Design Brief below

[Design Brief](https://docs.google.com/document/d/16QfzH-2viPfBoWdpZ0O59qiz1u3qeGsoajq7lCIuArs/edit)

**Comment by colinmurphy01** [comment]
Coming out of design/product sync and po sync, CMI seems to be the favored near-term option.

Before we commit, can you confirm (as it's built right now) if we can we hide unwanted controls/features (menu, search)? @sarahmhgov I think we want to keep playback controls, correct?

If that's not possible, let's chat with SDB about how much time it'll take to move the controls into a separate library + in the cloud.

**Comment by greg-does-weather** [comment]
I'll ask about hiding the menu and stuff via configuration, but removing it ourselves is easy:

```js
document.querySelector(".cmi-radar-menu-container").remove();
```

**Comment by greg-does-weather** [comment]
Poking around the obfuscated code, I don't think the configuration supports hiding the menu, so we'll have to do it ourselves. Though, as noted, easy. 😄

**Comment by colinmurphy01** [comment]
I think we can call this `done` and move implementation into a separate ticket?

Related:
- #794 
- #886
