### ISSUE TITLE
Style Guide V1

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#774]
Intention is to begin documenting and implementing consistent styles:

- Fonts/Headers
- Colors

**Comment by partly-igor** [comment]
Initial guide [here](https://www.figma.com/file/0dSABt9zCqoknaKua6DHmP/NOAA---Weather.gov?type=design&node-id=3755%3A24279&mode=design&t=vC9KIRyWs22WD1O7-1) includes

Type scales
Colors
Font normalization values

**Comment by colinmurphy01** [comment]
@partly-igor is this `done` for now?

**Comment by partly-igor** [comment]
Yes! Thought I moved it, thank you!
