### ISSUE TITLE
Alert banner time zone is UTC instead of local

### ISSUE THREAD

**Issue by partly-igor** [weather-gov/weather.gov#780]
### Description

Our alert banner shows the the time a hazard is in effect with a UTC time zone label. This is likely not the time zones users expect or a familiar with, and we should adjust it to match the local time zone. Note that this ticket is related to #779 , which may  the copy that is displayed. 

![Screenshot of alert banner showing UTC timezones](https://github.com/weather-gov/weather.gov/assets/150970973/610296f3-6851-44eb-9d10-a6e81e9bc855)

### Acceptance criteria
- [ ] Local time zone code is displayed rather than UTC
- [ ] Tests have been implemented or modified to capture the bug
- [ ] Changes have been tested for accessibility

**Comment by greg-does-weather** [comment]
This should be fixed (incidentally) in #751 and up in staging.

**Comment by greg-does-weather** [comment]
Confirmed fixed
