### ISSUE TITLE
Spin up environment for R3 Testing

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#782]
- [x] Spin up a dedicated environment "test" (resource constraints?)
- [x] Use config split to not enable
- [x] Remove CMS from environment (use basic auth to support weather story)
- [ ] Adding bundler to a dev environment

**Comment by colinmurphy01** [comment]
Might need to split up API proxy into a separate ticket.

**Comment by loganmcdonald-noaa** [comment]
Made 822 since I believe it is a separate piece of work.

**Comment by loganmcdonald-noaa** [comment]
fixed by #825
