### ISSUE TITLE
[SPIKE] Research dynamic content loading options for location page

### ISSUE THREAD

**Issue by eric-gade** [weather-gov/weather.gov#785]
### Description
With the tabbed navigation and other proposed user-interactions that "reveal" content, we have the opportunity to dynamically load content only _during_ those user interactions. **Doing so allows us to load the page faster** (see [Time to Interactive](https://developer.mozilla.org/en-US/docs/Glossary/Time_to_interactive)), and also to potentially load more detailed information as the user interacts with the page.

### Questions and Considerations
- In the specific case of tabs, should we load hidden tab content from the client side immediately when the page has loaded, or wait until the user has activated the corresponding tab?
- What frameworks, if any, should we use for sending requests and updating the DOM from the client side?
- How can we set up Drupal to allow client-side requests, and do so securely? ([this docs article](https://www.drupal.org/docs/8/core/modules/rest/getting-started-rest-configuration-rest-request-fundamentals#configuration) might have some guidance)
- What are the accessibility implications of dynamically loading content based on user interactions?

### Acceptance Criteria
- [ ] A series of tickets for implementing any proposed solutions

**Comment by colinmurphy01** [comment]
Assessment critera

- Impact on percieved page load time from user
- Impact on architecture

**Comment by colinmurphy01** [comment]
As we prioritize #957 this will likely trickle into next sprint

**Comment by greg-does-weather** [comment]
Someone correct me if I'm wrong, but I believe this spike is finished. (See #1043, and [the report](https://docs.google.com/document/d/1jzFYsbHATATieUdbuYUtXfupwkktfeUxaZ4irnUXH3U/edit?pli=1#heading=h.p699yelunjyw)).

I believe the final recommendation from the sprint was for product to regroup to decide if it was worth the effort, and we chose to pursue smaller Lighthouse improvements first.

**Comment by colinmurphy01** [comment]
It kinda is done, but we haven't had time to discuss as a group the findings and lighthouse options. 

This has fell off my to-do list to schedule a meeting.

**Comment by colinmurphy01** [comment]
Scheduled time to discuss next week.

@eric-gade you mentioned wanting to prototype some improvements in stand up today. Move ahead at your discretion. That convo is to ensure we all have a solid understanding as to why the page load is long.
