### ISSUE TITLE
[SPIKE] Experiment with parallel/async API requests

### ISSUE THREAD

**Issue by eric-gade** [weather-gov/weather.gov#786]
### Description
When loading the location page, we make several API requests on the server before responding to the user's browser (so before showing them anything). Each of these requests has the potential to take a relatively long amount of time. And for the moment, they are executing _in order_.
  
We might be able to speed things up by calling certain API requests _in parallel_, and then acting on their responses. In plain language, this means not waiting for the response of a previous request before making the next request. The upshot is that this has the potential, in theory, to reduce load times.

### Questions and Considerations
- **biggest potential caveat**: How many of our API requests require information received during a previous API request? Such situations prevent us from taking advantage of async/parallel requests
- Code changes might be significant (or might not be).
- Drupal uses [Guzzle](https://docs.guzzlephp.org/en/stable/index.html) by default as its HTTP client under the hood, and Guzzle has [support for async requests built-in](https://docs.guzzlephp.org/en/stable/quickstart.html?highlight=async#async-requests).

### Acceptance Criteria
- [ ] A pull request that implements asynchronous API calls in `WeatherDataService`
- [ ] Possibly an ADR on this decision?

**Comment by colinmurphy01** [comment]
Draft PR, will review in eng sync today

**Comment by greg-does-weather** [comment]
@eric-gade This is long finished, right?

**Comment by eric-gade** [comment]
Correct
