### ISSUE TITLE
Where should the radar map live?

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#787]
In R2 research review, [a discussion](https://docs.google.com/document/d/1UMKzuTmWo_XJ2z-cMs-t6qugRrDP0Ywn2edJ29A9UvY/edit#bookmark=id.s7k89zvvvbh6) started around where and when we display radar.

Summary is that irregardless if there is a hazard, radar is a valuable tool for people and should be persistent. 

If that's the case where should it live persistently?

**Comment by colinmurphy01** [comment]
Related to #773

**Comment by colinmurphy01** [comment]
Closing #633 knowing that we're likely using the radar.weather.gov product for now, so additional design won't be needed.

**Comment by partly-igor** [comment]
We confirmed in design, we should place the radar under the "Current" tab. I think this is now done.
