### ISSUE TITLE
Spike: Investigate visualization libraries

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#789]
We'd like to determine what's best library to use for our visualization use cases including: 
- Temp and precip trends over time
- Precip levels
- Probabilistic data (future state)

and considering:
- Mobile/desktop capabilities
- Page load
- Effort/Time
- Capabilities to interact with graph (example: looking at specific point in time for temp or pop)

**Comment by elijah-wright** [comment]
Chart.js might be a good option to start with, for a bar chart we're not working with a lot of data and it seems more dependent on how the library chooses to render the chart

**Comment by greg-does-weather** [comment]
We'll sync up with design after deciding on the types of visualizations we want, and then engineering will pick an appropriate library.

**Comment by colinmurphy01** [comment]
Blocked by #1477 

Hopeful that we'll have use cases by EOW and this can be picked up week of 8/26.

**Comment by greg-does-weather** [comment]
Oops. We did this. It's Chart.js
