### ISSUE TITLE
Updating layout of Hourly to table

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#792]
![Screenshot of hourly table layout](https://github.com/weather-gov/weather.gov/assets/150970973/b23de56a-879b-4e91-9f23-4170d398e50a)

[Artboard](https://www.figma.com/file/0dSABt9zCqoknaKua6DHmP/NOAA---Weather.gov?type=design&node-id=3765%3A26081&mode=design&t=e8AR2Vxv9mFLeRgJ-1)

[Protoype](https://www.figma.com/proto/0dSABt9zCqoknaKua6DHmP/NOAA---Weather.gov?page-id=3765%3A26060&type=design&node-id=3765-26081&viewport=654%2C935%2C0.41&t=SpafpQ9QMYUhEIXW-1&scaling=scale-down&mode=design) - shows scroll, but not arrow click functionality. Let's talk about how to implement. 

[Annotated Component](https://www.figma.com/file/0dSABt9zCqoknaKua6DHmP/NOAA---Weather.gov?type=design&node-id=3765%3A26373&mode=design&t=e8AR2Vxv9mFLeRgJ-1)

What's included

- [x] Layout of hourly data should change from individual divs/items into a combined table
- [x] Includes time, temp, ~feels like~, condition, wind speed, ~gusts~, humidity, dew point
- [x] Columns are hours
- [x] Rows are weather data/values
- [x] If hazard is present, it will be visible in table across the hours it is in effect
- [x] Add right/left buttons to move table left and right (pair with igor on how much it would jump/scroll to)
- [x] First column is frozen as user scrolls right to left

Not included
- Gusts
- Apparent Temperature

Does adding multiple variables add significant complexity? Would it be easier if we used placeholder/dummy data for ay of these for testing? Would simplifying the variables down make it easier for now?

Separate:
- #795

**Comment by colinmurphy01** [comment]
Current API doesn't have gusts and apparent temperature, so we'd leave them out.

**Comment by eric-gade** [comment]
Closed by #847
