### ISSUE TITLE
Expand within Daily tab

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#793]
[Artboard](https://www.figma.com/file/0dSABt9zCqoknaKua6DHmP/NOAA---Weather.gov?type=design&node-id=4094%3A39444&mode=design&t=l3G8xVWs4HkEpIF3-1)
[Prototype ](https://www.figma.com/proto/0dSABt9zCqoknaKua6DHmP/NOAA---Weather.gov?page-id=&type=design&node-id=3470-33995&viewport=1474%2C1283%2C0.3&t=2JCjgMRdNqqgiCiq-1&scaling=min-zoom&mode=design)
[Documentation](https://www.figma.com/file/0dSABt9zCqoknaKua6DHmP/NOAA---Weather.gov?type=design&node-id=4094%3A42151&mode=design&t=l3G8xVWs4HkEpIF3-1)

What's included

- [ ] Within the first four days in the daily tab, include link to expand "See hourly details"
- [ ] IDEAL: Upon expand, display #792 with 6am - 6am timespan for that day
- [ ] BACKUP: Upon expand, include image of table as placeholder for testing
- [ ] When expanded, link copy changes to "hide hourly details" and upon click collapses 
- [ ] leverage proxy data from #782 

Not included
- Not connected to live data in API

**Comment by colinmurphy01** [comment]
The goal would be to have this done and deployed to beta by March 8.

**Comment by colinmurphy01** [comment]
To support R3, we'll make the API calls in our code for all of the days and we'll hit cached information (aka the dumb way).

**Comment by greg-does-weather** [comment]
@eric-gade This is closed by #877, right?
