### ISSUE TITLE
Add placeholder for radar

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#794]
[Radar GIF
](https://drive.google.com/file/d/12lhEaAmfJ_2KiAoN9LFsZcx_92pTafqC/view?usp=drive_link)

What's included:

- [ ] Include a static asset (jpeg or gif, screenshot of radar) for testing location
- [ ] It will only be implemented on the specific location for testing
- [ ] Placed within the alerts tab, below the alert accordions, as laid out in this [design](https://www.figma.com/proto/0dSABt9zCqoknaKua6DHmP/NOAA---Weather.gov?page-id=3451%3A14277&type=design&node-id=4086-40695&viewport=298%2C-706%2C0.21&t=8A8q9n6AsBtGAKt2-1&scaling=min-zoom&mode=design)

**Comment by partly-igor** [comment]
Blocked until design figures out scenario for next round (current in progress)

**Comment by colinmurphy01** [comment]
Blocked by #773

**Comment by colinmurphy01** [comment]
@partly-igor @greg-does-weather has this been assigned to someone?
