### ISSUE TITLE
Styling and Desktop / Tablet breakpoints 

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#798]
Blocked by #797 

- Today tab
- Daily (related #793)

**Comment by colinmurphy01** [comment]
We did get a request from NWS employees to allow the width of the `today` tab to expand wider for larger screens to reduce the need to scroll. 

Something to monitor in testing or consider in the future.

**Comment by partly-igor** [comment]
With saftey merged I think this is good. 

Regarding the wider "today", I ended up expanding the table width when I was implementing so hopefully that's ✅ , and yes we'll listen for it next week during testing.
