### ISSUE TITLE
Replace Alert List date/times with plain language

### ISSUE THREAD

**Issue by kmranjo** [weather-gov/weather.gov#809]
The current formula for what to display in the Alert List for any hazard product is: 
[event] in effect [onset] [time zone] - [ends] [time zone] 

This update will replace that formula with a series of new ones that are conditional based on the current time in relation to the "onset" time. 
[A full table displaying every option is available here](https://docs.google.com/document/d/1fSe3Qx3TPcDxBy-6KbbV3npN6PMfb5U5TU5J0bUpJ4o/edit#heading=h.3w5mxqgb80k)

This new formula would apply to any/all alerts, and should be tested with multiple alerts in a single place to see the full effect.

**Comment by colinmurphy01** [comment]
For the test, the options we dicussed were:
- Replacing timestamps with `now` in testing env
- Hardcoding banner copy for test in testing env
- Static times
- Do not implement for R3

**Comment by colinmurphy01** [comment]
@sarahmhgov @kmranjo I don't think this was picked up yet. So I don't know if it'll make it into our testing env.
