### ISSUE TITLE
Homepage (Find epic)

### ISSUE THREAD

**Issue by kmranjo** [weather-gov/weather.gov#813]
Coming out of the scoping work from #568 
Determine what should be present on the weather.gov homepage in order to serve the Find epic flows ([detailed here](https://docs.google.com/document/d/1h6jnisUqozGkW3N7OgOcu_QU1aCu3HqUKG-GbIz399w/edit?usp=sharing)).
The homepage serves flows 1 and 2 for MVP 

1: From homepage (no location) 
- User begins at weather.gov 
- Can see and understand use of the location search 
- Can input a location (address, city/state, zip) 
- Automatically directed to the correct location page 

2: From homepage (location detected) 
- User begins at weather.gov 
- Can see and understand use of the location search 
- Selects “Use my location option”
- Site popup requests location 
- User agrees to use of location 
- Automatically directed to the correct location page 

Any content or components that serve other epics are out of scope for this ticket, but the output of this work should keep in mind that other elements will eventually be incorporated on the homepage. 

Note this ticket is going to depend on the search component 

Acceptance criteria: 
Page template for homepage is designed and built

**Comment by kmranjo** [comment]
@colinmurphy01 Having a little trouble outlining the needs for this ticket since we know the homepage will eventually be more than this. Is this enough to go on? Is it even different enough from what we have now to merit its own ticket?

**Comment by colinmurphy01** [comment]
Good question. Maybe we call this persistent search (homepage and header)? That might end up getting split up into two?

**Comment by colinmurphy01** [comment]
Included in #814 closing this as a duplicate
