### ISSUE TITLE
Location search box & results

### ISSUE THREAD

**Issue by kmranjo** [weather-gov/weather.gov#814]
Coming out of #568
The Location Search box and its results serves [flows 1 and 5](https://docs.google.com/document/d/1h6jnisUqozGkW3N7OgOcu_QU1aCu3HqUKG-GbIz399w/edit?usp=sharing)

1: From homepage (no location)  
- User begins at weather.gov 
- Can see and understand use of the location search 
- Can input a location (address, city/state, zip) 
- Automatically directed to the correct location page 

5: Return visit (search)  
- In previous visit, location is detected or input
- User leaves the site
- New session at later date, user returns to weather.gov homepage
- User goes to location search, and the last searched location is displayed as the first option before any information is input

This ticket should focus primarily on Flow 1, as the memory elements of Flow 5 are captured separately.

This component should allow users to: 
- input locations
- view matching results 
- select a result and be directed to the location page set to that location 

For MVP, this component only needs to accept input of zip codes or city/state.

Acceptance criteria: 
- [ ] Component interactions are defined, including negative inputs and error messages 
- [ ] Design of the search box is complete
- [ ] Design of the search results is complete 
- [ ] Technical requirements/challenges are identified

**Comment by colinmurphy01** [comment]
Focusing on the component that lives in header and homepage.

**Comment by colinmurphy01** [comment]
@sarahmhgov based on your initial design/eng review, it seems you're thinking through all of the below: 
- #813 
- #816 
- #817 

Which is great. I'll close those and use this ticket to track them. Feel free to reopen if any of those need their own time/effort.

**Comment by colinmurphy01** [comment]
@sarahmhgov I moved this to blocked, but I'd wonder if this is actually `done` and ready for `eng` to explore as they build?

@greg-does-weather what do you think?

**Comment by greg-does-weather** [comment]
I think that's correct.

**Comment by colinmurphy01** [comment]
Created #914 for sprint planning.

@sarahmhgov can you add details to that ticket?

**Comment by colinmurphy01** [comment]
I believe this is `done` closing as we track dev work in #914
