### ISSUE TITLE
Location search - remembered results

### ISSUE THREAD

**Issue by kmranjo** [weather-gov/weather.gov#816]
Feature identified as part of #568  ([scoping doc](https://docs.google.com/document/d/1h6jnisUqozGkW3N7OgOcu_QU1aCu3HqUKG-GbIz399w/edit?usp=sharing))

Ability for the search box to retain the last input location and serve it as the first option of results when revisited

This feature supports flow 5: 
- In previous visit, location is detected or input
- User leaves the site
- New session at later date, user returns to weather.gov homepage
- User goes to location search, and the last searched location is displayed as the first option before any information is input

It is dependent on/tied to the Location Search component (#814) 

Acceptance criteria:
- [ ]  Component interactions are defined
- [ ]  Design of remembered search results is complete
- [ ]  Technical requirements/challenges are identified

**Comment by colinmurphy01** [comment]
Included in #814 closing this as a duplicate
