### ISSUE TITLE
Updates to page metadata

### ISSUE THREAD

**Issue by kmranjo** [weather-gov/weather.gov#818]
### Currently

![Image](https://github.com/weather-gov/weather.gov/assets/24654605/2fe09404-6868-40a4-8e3d-198663639a77)

### Updates
Updates to location page metadata:
- delete: Weather.gov 
- NWS logo
- Keep location and National Weather Service as is

Updates site metadata to:
- A new weather.gov is coming
- NWS logo

Acceptance criteria: 
- [x] Specific metadata fields are updated
- [x] Preview is generated in text (and in slack)
- [x] Technical requirements/challenges are identified 

Feature identified as part of #568 ([scoping doc](https://docs.google.com/document/d/1h6jnisUqozGkW3N7OgOcu_QU1aCu3HqUKG-GbIz399w/edit?usp=sharing))

**Comment by kmranjo** [comment]
It looks like in current state the title does get dynamically generated, which is good. It displays as: 
[location] | Weather.gov | National Weather Service 

There is no meta description as far as I can tell, so we should add that eventually, but I think this is good enough for beta. And when we do, I don't think there's any need for the meta description to refer to the fact that it's a beta. There are already enough cues for that on the page.

**Comment by colinmurphy01** [comment]
The only update then would be the logo to NWS.

**Comment by kmranjo** [comment]
These recommendations look good to me.
