### ISSUE TITLE
Setup for future SEO expansion

### ISSUE THREAD

**Issue by kmranjo** [weather-gov/weather.gov#819]
This work came out of #568 ([scoping doc](https://docs.google.com/document/d/1h6jnisUqozGkW3N7OgOcu_QU1aCu3HqUKG-GbIz399w/edit?usp=sharing)) 

It does not relate directly to any of the prioritized user flows, but will continue to direct search engines to the main weather.gov until beta is ready for a full rollout: 
- Beta is not being crawled by search engines, is not showing up in search results
- Beta is being set up to work well with search engines when ready

Acceptance criteria: 
- [x] robots.txt files are set up to ensure beta remains outside of search results for now 
- [x] standard metadata fields are identified for page templates so that SEO can be more easily implemented in future

**Comment by colinmurphy01** [comment]
Related: #639

**Comment by colinmurphy01** [comment]
I believe this is `done` #1065 and #1132
