### ISSUE TITLE
Scope - Forecaster Experiernce (CMS)

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#826]
### Background
E.9 As an NWS forecaster, ITO, comms lead (internal user), weather.gov MVP must support the ability to create, update, and manage this information consistently and easily.
- I want to log into weather.gov with my noaa account
- I want to view the area, content, and pages that I'm responsible for

OOS for now
- Information architecture and navigation
- Reporting within CMS

### Acceptance criteria

- [x] It’s documented (often in a “Design Brief”)
- [x] Specific and clear user stories that we should build now
- [x] Open questions or assumptions that need to be clarified
- [x] Options for solutions with feedback
- [x] Team is aligned and has provided feedback
- [ ] The work is broken into groups that are similar/should go together and documented as Github Issues as needed:
  - [ ] Scopes for more detailed definition
  - [ ] Spikes for prototyping
  - [ ] Design or Engineering for delivery

[Draft scoping doc](https://docs.google.com/document/d/1PsQEiGvb2_R57lndU9ZU8uz8P0nGEOCrTsv-B3SXINE/edit?usp=sharing)

**Comment by colinmurphy01** [comment]
@kmranjo please make sure admin/forecaster configuration stories are included in this ticket like #508. It'll be good to make a call if these are in MVP or not.

**Comment by kmranjo** [comment]
Very high level "now next later" framing of scope linked above, ready for initial conversations next week

**Comment by kmranjo** [comment]
All tickets from "Now" phase are created, and most urgent ones from "Next" as well. Ready to be prioritized and picked up as available.
