### ISSUE TITLE
R4 - Synthesis and Scope Iterations

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#830]
- [x] Synthesize feedback from CMS testing 
- [x] Create a deck for shareout
- [x] Discuss possible iterations, prioritize (must, should, could, wont yet)
- [x] Document into tickets (#831 is a placeholder)

**Comment by sarahmhgov** [comment]
Deck in progress: https://docs.google.com/presentation/d/1WLWpwrvi9-2S1W0lON0yemEqJCcBdhwPSgqvhM8FO4c/edit#slide=id.g27017597351_0_1483

figma exercise: https://www.figma.com/file/0w4ITEf0PyPesXVRI8homR/R4---Forecaster-CMS-synthesis?type=whiteboard&node-id=39-337&t=07wY0mVvjzbWz6sH-0

**Comment by sarahmhgov** [comment]
This deck is good from my pov, @colinmurphy01 would love a quick review. https://docs.google.com/presentation/d/1WLWpwrvi9-2S1W0lON0yemEqJCcBdhwPSgqvhM8FO4c/edit#slide=id.g27017597351_0_268

**Comment by colinmurphy01** [comment]
Provided comments in doc. Sorry it took me a bit.
