### ISSUE TITLE
Update end-to-end testing to capture backend code coverage

### ISSUE THREAD

**Issue by greg-does-weather** [weather-gov/weather.gov#842]
### Description

In order to make our tests more robust and reliable, our end-to-end tests should compute code coverage. Some prototyping around this work has been started in the `mgwalker/change-testing` branch. This will help us identify the test gaps that end-to-end testing should cover.

### Acceptance criteria

- [ ] End-to-end tests report code coverage
- [ ] The CI/CD code coverage reporter step properly integrates the coverage information from end-to-end tests

**Comment by colinmurphy01** [comment]
By the end of this sprint we'd close #843 and then have succeeding work clarified for closing additional gaps.
