### ISSUE TITLE
Provide weather story style guidance to the field.

### ISSUE THREAD

**Issue by coreypieper** [weather-gov/weather.gov#848]
In the development of an adaptive site, how NWS weather stories are generated becomes much more important when it comes to presentation - especially on mobile screens. The primary audience now is desktop users. As we roll out the CMS, providing guidance to the field regarding the best practices for generating graphical forecast information is important.

**Comment by kmranjo** [comment]
Draft document here: https://docs.google.com/document/d/1sj_Yuy1bYlDVPtaWu4t-HmmzhIQG4BVV3VfrRU9wcLI/edit?usp=sharing 
But could use an eng eye on the image recommendations

**Comment by kmranjo** [comment]
Currently getting some clarity on image requirements from Eric. 
Product could review in parallel, so going to update the ticket to reflect that. @coreypieper @shadkeene @colinmurphy01

**Comment by colinmurphy01** [comment]
Looks good, I added some considerations

**Comment by colinmurphy01** [comment]
I'm going to close this.

We'll revist this after we tackle the content strategy for forecaster products #1169
