### ISSUE TITLE
Hourly table - Hazards with no eventEndingTime

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#852]
Related to #847 

Open questions
- Are there alerts that don't have an expiration or end time?
- What to do with alerts in the hourly forecast table when they don't have an `eventEndingTime` field but do have an `expires` field?
- [Other examples](https://docs.google.com/document/d/1fp_kUTLF7pNb36sNwc6rvFThNPQ6lCWHIufck0Yf6iE/edit#heading=h.z2fxjtv200m8) 4,5,8

**Comment by coreypieper** [comment]
In the API, how do we use "ends" and "expires" for hazards?

**When "ends" has data in the API, use that. When "ends" has no data, use "expires."**

Why? The data for "ends" is taken from the VTEC code for products that use VTEC. The time/date in "ends" is therefore taken directly from what the forecaster has specified as when the hazard is expected to end.

The data in "expires" is meant to denote (mainly) when the text product itself is set to expire, and thus needs to be updated by the forecaster before that time. It's mainly meant to help remind forecasters to keep the information in the product fresh.

HOWEVER, in non-VTEC products, as there is no expiration data that can be garnered from the VTEC, the "expires" information is then essentially used to denote the expected end of a hazard.

**Comment by colinmurphy01** [comment]
Closing, this logic is currently implemented.
