### ISSUE TITLE
Product Inventory: Form and Insider Article

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#858]
We need to create a google form that's a slimmed down version of the inventory so that anyone across NWS can submit a product.

We will then send that out via an Insider Article.

We will also provide view-only access to our current inventory.

[Google form ](https://forms.gle/fLhUfEdN1EeG5wt39)
Spreadsheet of responses and previously logged tools ([link](https://docs.google.com/spreadsheets/d/1qgsTV6vqxHwjUYtYwH0BoaqeGdPTWGVh-2NhaEKwb4k/edit?usp=sharing)) 
**_Note that for both of these, you need to be signed in with your noaa.gov email_**

Suggested text (or starter text at least) for insider: 
The weather.gov 2.0 team needs your help! 
The team is currently trying to log all the custom tools, maps and visualizations created on the current weather.gov so they can be assessed for migration to the new site. With so many tools out there, we want to make sure we’re seeing them all. 
If you know of a custom tool built for weather.gov, use this form to let us know.

**Comment by kmranjo** [comment]
@colinmurphy01 I've got the form linked above and some text for Insider (just a guess, no idea what the requirements for it are). 
For the spreadsheet that we want to provide full visibility into, what are your thoughts on creating a copy of our working document and simplifying it? My main concern is that if it's still being used as a working document, various filters and etc. could be applied by users with edit access, and users with view only access may not have the context to know what they're looking at.

**Comment by colinmurphy01** [comment]
@kmranjo That makes sense to me.

**Comment by kmranjo** [comment]
Got all 3 pieces together (see above) so I think this is ready for review

**Comment by colinmurphy01** [comment]
Going out this AM in IT Insider
