### ISSUE TITLE
Use discussions section of the repo to better engage with other developers outside of writing issuse

### ISSUE THREAD

**Issue by joshchernoff** [weather-gov/weather.gov#860]
To help aid with better transparency and comprehension the admins should enable the discussion section of this repo

**Comment by colinmurphy01** [comment]
Adding this as a component to figure out in our ongoing rollout, comms, and feedback plan #836

**Comment by colinmurphy01** [comment]
Let's chat about this after a standup.

**Comment by colinmurphy01** [comment]
We're going to hold off on using Discussions right now to minimize the amount of forums we need to manage at this time. If there is an issue or question it can be logged as an issue.
