### ISSUE TITLE
Add testing data to test environment

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#866]
[Content for R3](https://docs.google.com/document/d/1TeieNwJ-gZrUad6x27YqJubdZRvXW5mxR6bbl87Yj3U/edit#heading=h.bsj9zz9riddq)
[Spreadsheet of weather data for R3](https://docs.google.com/spreadsheets/d/1B09J_NuBbNMyZG8_GW1MEJbjKWlNo3x2S2XB08mDowQ/edit#gid=1630835506)

**Comment by colinmurphy01** [comment]
@kmranjo @sarahmhgov @partly-igor can someone review the testing env today to ensure the data and content is correct and then close this?

**Comment by partly-igor** [comment]
Sounds good we'll all take a look
