### ISSUE TITLE
Add error logging

### ISSUE THREAD

**Issue by greg-does-weather** [weather-gov/weather.gov#871]
### Description

After discussion among the engineering team, we decided that we don't really need database error logging, per se. We haven't seen any database errors so far. But we also can't be sure because we have very poor error logging in general, so the first step should be to log our errors. Once we have that data, we may be able to determine whether we need more specific error handling.

We currently "eat" most of the exceptions we encounter. A small number are logged to Drupal Watchdog, but most are just caught and ignored. This mostly serves us fine, but when things go wrong, it can be hard to figure out _why_. We should instead catch and log these errors.

We will install the [log_stdout module](https://www.drupal.org/project/log_stdout) that redirects Watchdog logs to the standard out and error handles, where they will be captured by cloud.gov logging. This will also incidentally make them easier to access in local development.

We will also update our error handling so that caught errors are logged to Watchdog.

### Acceptance criteria

- [ ] Watchdog logs are sent to stdout and/or stderr
- [ ] stdout and stderr logs are captured by cloud.gov logging
- [ ] all caught errors are logged to Watchdog

---

Original description:

### ~Description~

~We have currently not experienced any database errors, but connection disruptions or (heaven forbid) data corruption could eventually cause them to happen. We should spend some time thinking about what we want to do in those situations. Currently any errors would bubble up to the blocks, which will quietly eat them and produce the more user-friendly error boxes, but we might want to think about fallbacks (e.g., if a database query fails, then perhaps we fallback to the API; or maybe we put in some wait-and-retry logic).~

### ~Acceptance criteria~

- ~We have determined how we should handle database errors~
- ~We have implemented database error handling~

**Comment by greg-does-weather** [comment]
I think I'd describe this as low-likelihood, high-impact. It's the sort of thing that if it's wrong, we probably have a bigger problem going on. It's more likely to be a symptom than a root cause. So catching it could be critical to recognizing that the bigger thing is happening.

If we have errors with the database, that could manifest in a few ways:
- can't correctly filter to the correct set of alerts, feels very bad
- can't fetch place names, feels like an annoyance more than anything
- can't correctly show CMS users the correct list of counties when they're authoring county-specific content, feels like a fine thing to punt for a while

**Comment by colinmurphy01** [comment]
Roger. Added to `Now` column for debt consideration.

**Comment by greg-does-weather** [comment]
@colinmurphy01 FYSA, we've changed this ticket from database error handling to general error logging. We should already be "catching" all of the database errors, but we're not doing anything with ***any*** error we catch. This PR is now to log those errors in a way that makes them easier to see so we can better understand if we need more specific error handling.
