### ISSUE TITLE
Accessibility: Update hourly forecast tables

### ISSUE THREAD

**Issue by greg-does-weather** [weather-gov/weather.gov#878]
### Description

The hourly forecast tables are currently pretty rough in assistive devices. Navigating through them on a screen reader, I'm not sure a table is the best layout. Some potential alternatives might be:

- ~instead of a row for each piece of information, collect it all into a single cell (using a card, perhaps?) so when a user lands in the cell, the reader announces the column header (the hour) followed by the hourly forecast details~
- ~hide the table from screen readers and implement an sr-only ordered list of the hourly forecast. This seems more appropriate to me than the first approach since the first approach essentially breaks the semantics of tables~
- ~reimplement the table as a flexbox, which could semantically be a list and thus 🪄 magically better for a11y~

See PR #877

### Acceptance criteria

Coming out of R3 a more ideal solution might be:

- Adding caption to the table
- Treating the times as column heads

Will confirm in Des/Eng sync today

- [ ] Implementation has been modified to work for all users
- [ ] Changes have been tested for accessibility

**Comment by colinmurphy01** [comment]
@greg-does-weather is a more detailed, manual accessibly review needed or is this ready for `eng`?

**Comment by colinmurphy01** [comment]
Will rescope after R3.

**Comment by colinmurphy01** [comment]
@sarahmhgov have we identified most of the accessibility issues in the current experience.

Do we need to do a manual review?

**Comment by colinmurphy01** [comment]
Coming out of R3 a more ideal solution might be:

- Adding caption to the table
- Treating the times as column heads

Will confirm in Des/Eng sync today

**Comment by colinmurphy01** [comment]
@igorkorenfeld Did we confirm this last week? I think so, but don't recall.

**Comment by colinmurphy01** [comment]
Something to explore - at celle level, my headings are X/Y.

This will allow a screen reader to announce both headers.

Test with WCAG/508 lead

**Comment by greg-does-weather** [comment]
As far as I can tell, aside from adding a caption, there's not much we can do to improve the screen reader experience here. The row and column headings are already identified as such, and in my (admittedly naive) testing, VoiceOver reads them out.

**Comment by colinmurphy01** [comment]
@igorkorenfeld any thoughts on what we should write as the caption?

**Comment by partly-igor** [comment]
How about "Detailed hourly weather data for <date>. The rows are weather variables, the columns are hours"

**Comment by greg-does-weather** [comment]
"for"? Is that supposed to be the day? "Today," "Thursday," etc.?

**Comment by partly-igor** [comment]
I don't know why that didn't paste correctly, sorry about that. It was supposed to say <date>

**Examples**
Detailed hourly weather data for April 9th. The rows are weather variables, the columns are hours
Detailed hourly weather data for April 10th. The rows are weather variables, the columns are hours

**Comment by partly-igor** [comment]
It happened again! I see what's happening: I am typing `<date>`, but I think the markdown editor is treating that as html

**Comment by greg-does-weather** [comment]
Got it! I'm on it.

Aside: GitHub strips out most HTML from comments. There's a list somewhere of the very limited set of stuff they permit. This one, perhaps: https://gist.github.com/seanh/13a93686bf4c2cb16e658b3cf96807f2

**Comment by greg-does-weather** [comment]
Closed by #1032
