### ISSUE TITLE
The wind direction arrows in the hourly forecast tables float above the row headings

### ISSUE THREAD

**Issue by greg-does-weather** [weather-gov/weather.gov#879]
### Description

When you scroll an hourly forecast table, the contents of the table are supposed to slide under the row headings. However, the wind direction icon floats above it.

https://github.com/weather-gov/weather.gov/assets/142943695/29c11555-3c07-4be3-98f1-18be992c4033

### Acceptance criteria

- [ ] Tests have been implemented or modified to capture the bug
- [ ] Changes have been tested for accessibility

**Comment by colinmurphy01** [comment]
I believe this has been addressed in #877
