### ISSUE TITLE
[SPIKE] Research weather API structures of other popular/successful met API services

### ISSUE THREAD

**Issue by eric-gade** [weather-gov/weather.gov#881]
### Description
In order to facilitate any future proposal to the API team about an ideal structure for WG2.0 API requests/responses, we should have well-rounded knowledge about how others in the world are shaping similar data. This ticket proposes an examination of other popular and/or successful Meteorological data API services in order to compare how they handle requests and what the shape of their response data is.

#### Which examples to look at? ####
This is not exhaustive, and we should add to it as needed, but off the top of my head here are some we might want to examine:
* [yr.no](https://developer.yr.no/) (the Norwegian service)
* [Pirate weather](https://pirateweather.net/en/latest/)
* [Open Meteo](https://open-meteo.com/)
* [Tomorrow.io](https://www.tomorrow.io/weather-api/)
* [UK Met Office DataPoint](https://www.metoffice.gov.uk/services/data/datapoint/getting-started) No longer officially supported, but still online and working until 2025. The replacement seems to me a paid/metered service :(

#### Criteria ####
We will probably want to have some kind of rubric or criteria for how we examine each of these.

### Acceptance Criteria
- [x] We have a document that summarizes the pros and cons of each service we choose to examine
- [x] Our document highlights overall interesting common features/trends that we'd like to include
- [x] Our document highlights any overall common pitfalls that we'd like to avoid
- [x] Our document highlights features these services have, but will just not be possible for us for whatever reason
- [x] Our document attempts to make some recommendation about an ideal API structure that we would like (but not necessarily in a field-by-field / request-by-response level of detail)

` Tag the related milestone to this story`

**Comment by colinmurphy01** [comment]
I'd be interested if someone from the API team would be open to doing this work?

**Comment by colinmurphy01** [comment]
@loganmcdonald-noaa this might be something to consider, even though it's out of our scope. This doesn't have to be `done` by the end of this sprint, looking to have a document with this and #902 by early April.
