### ISSUE TITLE
Turn off current conditions timestamp for testing

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#883]
we are using javascript to update the current conditions timestamp to the browser’s local time

- [ ] Turn it off in the `/testing` branch for R3 next week
- [ ] Turn it back on after R3 is completed?

**Comment by greg-does-weather** [comment]
PR #887 makes the change only in the r3 branch.

**Comment by colinmurphy01** [comment]
Closing since #887 has been merged
