### ISSUE TITLE
Add hazard images to alerts in design environment for R3

### ISSUE THREAD

**Issue by partly-igor** [weather-gov/weather.gov#886]
### Description
The [designs](https://www.figma.com/proto/0dSABt9zCqoknaKua6DHmP/NOAA---Weather.gov?page-id=3451%3A14277&type=design&node-id=4086-40695&viewport=298%2C-706%2C0.21&t=8A8q9n6AsBtGAKt2-1&scaling=min-zoom&mode=design) for our alert details include the "hazard on a map." For our testing round we will just use screenshot/static images in place of the dynamic map we decided on perviously. We need to add an image that corresponds to each alert at the bottom of the accordion for that alert.  @partly-igor will provide the images shortly. 

### Acceptance Criteria
- [ ] Accordion for alert 1 has an image
- [ ] Accordion for alert 2 has an image

**Comment by colinmurphy01** [comment]
@partly-igor @greg-does-weather has this been assigned to someone? greg you mentioned in a thread that you were working on this?

**Comment by greg-does-weather** [comment]
Closed by #891
