### ISSUE TITLE
Add aggregated details to daily overview

### ISSUE THREAD

**Issue by partly-igor** [weather-gov/weather.gov#888]
Simmilar to to #876 now that we support /gridpoint #859 we should add details to the daily forecast items for the first 4 days to match the [Figma design](https://www.figma.com/proto/0dSABt9zCqoknaKua6DHmP/NOAA---Weather.gov?page-id=3470%3A33994&type=design&node-id=3470-33995&viewport=178%2C737%2C0.39&t=L4Y52voRmJ3FhLzC-1&scaling=min-zoom&mode=design). 

These should be the "aggregate" values for the day for:
- Wind (Max)
- Gusts (Max)
- Relative Humidity (TBD)
- Toal Precipitation (Total)

**Comment by colinmurphy01** [comment]
Product to answer: how should we represent these values at a daily level if they're only represented at the hourly level.

- Wind is covered in /daily endpoint

**Comment by colinmurphy01** [comment]
Humidity might need further thinking.

**Comment by partly-igor** [comment]
Discussed in PO review – holding off on this and going to work on it together along with work on representing trends.

**Comment by colinmurphy01** [comment]
To add to @partly-igor's comment, we are comfortable with this falling outside of MVP.

**Comment by colinmurphy01** [comment]
Doing some backlog cleaning. 

I suspect we can close this with the new interface (quick forecast > accordion/tabs provide details).
