### ISSUE TITLE
Define a centralized/employee-sourced sysadmin team and policy

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#893]
Coming out of #523 there was interest in sourcing a "centralized" sys-admin team across the NWS org, similar to NWS Chat. 

We need to define things like:

- Who would that be?
- What are the availability and response requirements?
- What are the management requirements?
- Risks and mitigation strategies

NWS Chat 2.0 can be a starting place for this policy.

Timing:
- This is probably not critical for MVP, however getting this team setup will be important in June/July
- As we're rolling out CMS support across WFOs, sys admins are onboarding into their roles and supporting that effort

**Comment by kmranjo** [comment]
Yes, but I think we have a duplicate. I've got #1003
