### ISSUE TITLE
Internal Rollout and Comms

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#904]
- [x] Draft Plan
- [x] Draft Talking Points and FAQs
- [ ] Review / Feedback
- [ ] Schedule

**Comment by colinmurphy01** [comment]
Working doc: https://docs.google.com/document/d/1whdtBadV-kcroLD_uB07AKQT2aDSIbqxTYvwhyyosLM/edit#heading=h.i71h9i7cdpcg

**Comment by colinmurphy01** [comment]
Need @shadkeene and @coreypieper to review.

**Comment by shadkeene** [comment]
Is this on hold @colinmurphy01  for now?

**Comment by colinmurphy01** [comment]
Moving back to `doing` as we follow CMU's process
