### ISSUE TITLE
Wind gusts need to be added to wherever sustained winds are

### ISSUE THREAD

**Issue by shadkeene** [weather-gov/weather.gov#906]
Currently, only sustained winds are displayed on beta.weather.gov.  Wind gusts are the maximum 3-second average running average wind speed and direction, and sustained winds are the 2-minute average wind speed and direction.  Wind gusts can do significant damage and are often the most impactful between the two, because it is the highest wind speed.  Most wind-oriented watches and warnings are based on sustained AND gusts, so either one hitting a designated criteria can trigger a watch/warning.  

User story for wind gusts in Current Conditions: I want to be able to view the maximum wind speed currently occurring near my location, so I can make decisions based on real-time weather for myself, family/friends, and property.

User story for wind gusts in Daily and Hourly Forecast: I want to be able to view the maximum wind speed expected over an entire day and each hour near my location, so I can make decisions based on the expected weather for myself, family/friends, and property.

Side-note for County/State/National views: For CSN information, upstream wind observations would probably be beneficial to allow for a sense of what is observed nearby and what may be coming impacting a downstream location soon.

![Capture](https://github.com/weather-gov/weather.gov/assets/139174561/5f6940ed-3daf-44ea-b8dc-dafc1672a3b0)
![Capture](https://github.com/weather-gov/weather.gov/assets/139174561/88bad1b1-0fe8-459c-992b-a70597913231)
![Capture](https://github.com/weather-gov/weather.gov/assets/139174561/76585e3d-4ade-47a4-a1e4-d6dfbf0062b0)

**Comment by colinmurphy01** [comment]
Tracking in #975
