### ISSUE TITLE
Post R3: Turn off /testing?

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#908]
- We temporarily turned off timestamps and hardcoded them for R3 for #883 in #887.
- Do we want to maintain the testing environment?

**Comment by colinmurphy01** [comment]
After testing, turn it off.

For next round of testing, update R3 branch from Main and then update data.

**Comment by colinmurphy01** [comment]
@greg-does-weather or @loganmcdonald-noaa can we turn off the `-design` environment so that it doesn't cost us money while we don't use it?

**Comment by greg-does-weather** [comment]
We can definitely turn it off. I'm not sure if it's costing us anything (maybe the database?), but it's probably "correct" to shut it down anyway.

**Comment by greg-does-weather** [comment]
Deleted the Drupal and API proxy apps along with the Drupal database.

**Comment by loganmcdonald-noaa** [comment]
Yes, to clarify - this doesn't "cost us" any money we haven't already allocated as part of our memory reservation. It is usually good practice not to have things you aren't using running. But should double check with design that we aren't using it and won't in the near future. It takes about an hour or so of operator time to get back up and running and about 15 minutes to spin down. Both are scripts but do need some manual intervention. The remove script should be run when spinning down.
