### ISSUE TITLE
Replace cardinal wind direction in current conditions with arrow

### ISSUE THREAD

**Issue by shadkeene** [weather-gov/weather.gov#909]
On current conditions, wind direction is communicate via cardinal direction (e.g. NE, SW).  
![image](https://github.com/weather-gov/weather.gov/assets/139174561/6a907556-97cf-42fd-a911-f9972a8d9f88)

We'd like the current conditions component to use an arrow instead, similar to how we display it in the hourly table.
![image](https://github.com/weather-gov/weather.gov/assets/139174561/96fa6d54-9da3-40d2-9409-73cbeecfc7b8)

Reasoning it's believed that arrows communicate the wind more clearly considering it's pointing where the wind is going, whereas the cardinal direction notes where the wind originates.

Accessibility will be tracked in #1007

**Comment by colinmurphy01** [comment]
@partly-igor adding this to `backlog` for consideration. I think I heard someone comment on the arrows in R3 as well.

**Comment by colinmurphy01** [comment]
Will discuss in Design/PO sync on 4/3

**Comment by partly-igor** [comment]
It is my understanding  from the recap from 4/3 we will use both the cardinal direction and the icon. 

@greg-does-weather I see you are assigned to this one. When you pick it up, could you also replace the icon with the latest [iteration](https://drive.google.com/file/d/1dT4JkznftyPX3W1nZtWcH-uLA94CwZhh/view?usp=drive_link)? I wanted to increase the visual weight of icon a bit to better match the text. I am happy to open a separate PR, but was thinking it's very closely related to this issue.

**Comment by colinmurphy01** [comment]
@partly-igor is that right? Is it weird we'd have cardinal and the arrow saying two different things?

**Comment by partly-igor** [comment]
Caveat that I wasn't at that meeting but that's what I understood when catching up on notes and in design conversations.

But that also makes sense to me. That the wind is in the "from" direction is not intuitive (though standard) but that's what the arrow helps with. Combining the two is perhaps a chance to help inform folks. 

That said, if you feel strongly is should _just_ be the arrow I am not opposed – in that case we'll need to make sure to add aria-label to the svg with the cardinal direction.

**Comment by colinmurphy01** [comment]
Yes, we settled on just using the arrow.

I have a separate ticket for the accessibility updates in #1007 because it's also missing in the hourly table.
