### ISSUE TITLE
Missing temp data in hourly table

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#912]
### Description
Some temp data is missing in the hourly table. I didn't see it occurring for other data points.
![Image](https://github.com/weather-gov/weather.gov/assets/24654605/87c19e24-c3c2-46f0-b960-8ea2f94dbeba)

### Acceptance criteria

- [ ] Temperature data shows up consistently for each hour
- [ ] Tests have been implemented or modified to capture the bug
- [ ] Changes have been tested for accessibility

**Comment by greg-does-weather** [comment]
Captured here: [bundle_65f84b9c5e7c7.zip](https://github.com/weather-gov/weather.gov/files/14637512/bundle_65f84b9c5e7c7.zip)
