### ISSUE TITLE
Location Search Component

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#914]
Related to #814

**Comment by colinmurphy01** [comment]
Start identifying the component or best option for our needs.

**Comment by eric-gade** [comment]
Adding a [link to the USWDS combobox issue here](https://github.com/uswds/uswds/issues/5161)

**Comment by colinmurphy01** [comment]
Also adding a link to [USWDS's testing findings](https://github.com/uswds/uswds/issues/5522)

**Comment by eric-gade** [comment]
@colinmurphy01 correct -- will be a separate ticket. I'm dealing with some testing-related headaches at the moment, but once I have a PR for the new component I will also spin off several other follow up tickets
