### ISSUE TITLE
Revisit prioritization of alerts in alert list/details

### ISSUE THREAD

**Issue by kmranjo** [weather-gov/weather.gov#918]
In current state, we are using the same prioritization from the WWA map to set the order of priority/display for Alert List and Alert Details. This sometimes results in a very strange experience for the user, where an alert that is currently happening displays lower in the list than other alerts happening later in the day or week. 

Ideally, alerts in these components should display in chronological order based on the "onset" date and time.

**Comment by colinmurphy01** [comment]
Tracking in #940
