### ISSUE TITLE
Hourly table arrows look smaller on mobile devices

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#921]
### Description

Hourly table arrows seem to be smaller on mobile devices. 

- Re-produceable on chrome and safari browsers on an iphone Xr and 14 Pro
- Re-produceable on Today and Daily tabs

![Image](https://github.com/weather-gov/weather.gov/assets/24654605/00461b0c-d426-4aff-9bed-274c73342653)

Not able to reproduce on dev tools (mobile)

![Image](https://github.com/weather-gov/weather.gov/assets/24654605/2918a2b0-403d-4b3d-aa67-a6d1b0ed5fbd)

### Acceptance criteria

- [ ] Arrows are consistent on mobile devices
- [ ] Tests have been implemented or modified to capture the bug
- [ ] Changes have been tested for accessibility

**Comment by partly-igor** [comment]
Also shows up on iPhone 12. But doesn't seem to occur on Android devices 

Not replicable on responsive mode in Chrome or Safari on desktop.
