### ISSUE TITLE
Fahrenheit symbol font varies between operating systems

### ISSUE THREAD

**Issue by partly-igor** [weather-gov/weather.gov#930]
### Description
We currently use the single character "℉" (U + 2109) to represent Fahrenheit throughout the site. However our primary font, Nunito Sans does not have that character (nor do most of the fonts in our font stack). As a result the character renders in one of the system default fonts. This is particularly noticeable on windows machines where it is rendered in Times New Roman, and which appears inconsistent with the rest of the design. 

We should replace the single character with two, the degree symbol "°" and the "F". This will create more consistent rendering across browsers and operating systems, given that Nunito Sans does have the "F" character. 

We should consider adding an aria-label Fahrenheit wherever this symbol is used so that the screen reader reads the unit name rather than "F"

<details>
<summary> Screenshots </summary>
 
![Screenshot from Windows ](https://github.com/weather-gov/weather.gov/assets/150970973/12b24bf7-c487-4cba-8579-7122dddb56c0)

![Screenshot from mac](https://github.com/weather-gov/weather.gov/assets/150970973/7e73518f-0623-4df2-b23b-aaf56674a867)

</details> 

### Acceptance criteria
- [ ] All single character "℉" have been replaced with two characters "°F" 
- [ ] Compare the rendering of the font on different operating systems. 
- [ ] Changes have been tested for accessibility

**Comment by greg-does-weather** [comment]
I think we'll need to keep the single symbol for screenreaders because `aria-label` is meant for interactive elements. We can do sr-only on the single symbol, and `aria-hidden` on the double symbols.
