### ISSUE TITLE
CMS: Roles & Permissions

### ISSUE THREAD

**Issue by kmranjo** [weather-gov/weather.gov#936]
Generated from #826 

Implement workbench access to enable the expected roles and permissions for all users in scope: 
- System admin (granted by system admins) 
- Content admin (granted by system admins)
- Content contributor (granted by system admins)
- Authenticated (automatically assigned upon successful login) 

Recommendations: Add and configure permissions and roles at [https://localhost:55606/admin/people/permissions](https://localhost:55606/admin/people/permissions), or Assign actions and permissions to roles, not individuals. Any custom modules should include a [module.permissions.yml](https://api.drupal.org/api/drupal/core%21modules%21system%21system.permissions.yml/10). Read more about the [permissions layer](https://www.drupal.org/docs/contributed-modules/group/the-permission-layers-explained).

This work has already been done in most (all?) environments. The scope of this ticket is to clean up unintended roles, fully implement the intended roles, and create documentation for how to manage those roles. 
Documentation should include: 
- Description of each role and their associated permissions
- The expectation for who will receive each role
- How to assign authenticated users to roles 
- How to modify or remove roles as needed 
- How roles are applied to editorial sections via workbench 
- What the process should be for creating new editorial sections in future 
- How to troubleshoot common problems with roles/permissions 

Documentation created in the [NOAA drive here](https://docs.google.com/document/d/1dGcuOWK-eIiCNUC3E5S-bHMnh1dMBXorjwvkNKQFGPU/edit?usp=sharing)

**Comment by kmranjo** [comment]
@loganmcdonald-noaa I think the first 3 roles are taken care of if Workbench is set up in beta, but is the authenticated role being view-only something that a system admin can set up, or something engineering needs to configure?

**Comment by loganmcdonald-noaa** [comment]
I think it is setup by default if by "view-only" we mean view all the content. Do we want the authenticated user to have expanded access?

**Comment by kmranjo** [comment]
Nope, just view. That makes sense - then we should be good to go!

**Comment by colinmurphy01** [comment]
@loganmcdonald-noaa can you confirm that @kmranjo has a system admin role for all environments.

**Comment by loganmcdonald-noaa** [comment]
Done @colinmurphy01 - @kmranjo if you are having issues in any environment let me know.

**Comment by kmranjo** [comment]
Documentation created in the first section of what will eventually be our CMS guide. @loganmcdonald-noaa could you review whenever you have a chance just to make sure it makes sense and is accurate, and then we can run it by product?

**Comment by loganmcdonald-noaa** [comment]
Reviewed what we have now and all LGTM!

**Comment by kmranjo** [comment]
Ready for product review in parallel with #935

**Comment by colinmurphy01** [comment]
Added some initial thoughts. This looks good though.

Once we're done with weather story testing and we've identified candidates for SysAdmin roles (#1003) it'd be cool to test the docs and experience with them as well.

**Comment by kmranjo** [comment]
Moved back to in progress while reworking the CMS guide

**Comment by kmranjo** [comment]
Draft has been reworked and is in a good state for re-review

**Comment by colinmurphy01** [comment]
I think the changes are awesome and make it easier for specific roles to see relevant "how-to" guidance for them. So thank you for that!

The [roles and permissions doc](https://docs.google.com/document/d/1cqM9sU6O2fbAONCDbv8cAmzCm262F5jUR-r_CwN2vQ0/edit#heading=h.p4joeepafati) is solid and probably ready for SysAdmin recruitment.

The bummer is that with how much we're changing the CMS, we should call this `done` for now and will have to revisit when changes to data and UX are implemented.
