### ISSUE TITLE
Order alerts chronologically 

### ISSUE THREAD

**Issue by eric-gade** [weather-gov/weather.gov#940]
### Description
  
We current display alerts (both the list and the details) in order of severity according to a priority list of hazards. In R3 we learned that this causes confusions for users because it means that alerts may not be listed chronologically. For example, as seen in the screenshot below, an alert like a "Winter Storm Warning" that is happening _tomorrow_ will get listed before a lower priority alert like "High Wind Warning" that is happening _today_. We should update our sorting logic so that alerts are first sorted chronologically (earliest to latest) and then by priority order (high to low). 
  
### Acceptance criteria
- [ ] Active Alerts (past onset time) are listed according to priority list, first
- [ ] Future Alerts appear in chronological order, second
- [ ] Alerts with same onset time are listed according to the priority list 
- [ ] Alert accordions appear in the same order as the alert links at the top of the page
- [ ] Tests have been implemented or modified to capture the bug
  
![Screen Shot 2024-03-22 at 11 08 39 AM](https://github.com/weather-gov/weather.gov/assets/105373963/836ae844-5ff9-4600-a1c6-55d89f3595d8)

**Comment by colinmurphy01** [comment]
@partly-igor to refine coming out of R3

**Comment by partly-igor** [comment]
Updated the description to match the findings/issue
