### ISSUE TITLE
CMS: Remove options from WYSIWYG

### ISSUE THREAD

**Issue by kmranjo** [weather-gov/weather.gov#941]
Generated from #826
For all instances of the WYSIWYG in any page template or content type, we want to make the following adjustments: 
1 - Remove the ability to inject code
2 - Remove the ability to add an image 
3 - Remove the "text format" dropdown 

![Screenshot 2024-03-22 at 2 12 43 PM](https://github.com/weather-gov/weather.gov/assets/127144183/7e019c95-51fa-4e94-ac06-a4f2135c0d1f)

**1 - Remove the ability to inject code**
From Claire: You can remove “view source” through ck editor library settings

The WYSIWYG contains the Code and View Source options, which can allow users to modify the input at the code level, including injecting javascript. Moving forward, we want to remove the ability for anyone to see and use these options. 

**2 - Remove the ability to add an image** 
Images shouldn't be added in a text field. Adding images should be done in separate fields where things like required alt text cannot be easily missed.

**3 - Remove the "text format" dropdown** 
Below the body text field, there is a Text Format dropdown that users can toggle to adjust the type of input the field will accept. This should be set for the component and not changeable from one instance to the next. We want users to only need to input text and format it using the tools available, not having to rely on HTML. 
![Screenshot 2024-03-22 at 2 16 40 PM](https://github.com/weather-gov/weather.gov/assets/127144183/712cf83d-a5fc-4656-bf64-797ecb630ccf)

**Comment by loganmcdonald-noaa** [comment]
Can cover in #1020
