### ISSUE TITLE
CMS: Workflow design

### ISSUE THREAD

**Issue by kmranjo** [weather-gov/weather.gov#945]
Generated from #826

Conduct a workshop with product to determine how to address error handling by discussing what types of scenarios users may encounter and which ones should be addressed by best practices vs automated guardrails in the system. 

[Prep document saved here](https://docs.google.com/document/d/1kVa7uiDI8hzdWdD80IL-DwjSIoeGDArVUVYHxhxgvQ8/edit?usp=sharing)

**Comment by kmranjo** [comment]
@colinmurphy01  I put some [thoughts together](https://docs.google.com/document/d/1kVa7uiDI8hzdWdD80IL-DwjSIoeGDArVUVYHxhxgvQ8/edit?usp=sharing), but there is likely some overlap with the next steps coming out of the research last week as well. How do we want to relate these two things? Should I put this on hold until we're able to discuss the more specific feedback from research? 

cc @sarahmhgov

**Comment by kmranjo** [comment]
Updated the name of this ticket to reflect the direction it's gone. We met with product yesterday and talked through the desired directions for each one. This will probably spawn a bunch more tickets, once we get eng review.

**Comment by kmranjo** [comment]
@colinmurphy01 @sarahmhgov  I [updated the doc](https://docs.google.com/document/d/1kVa7uiDI8hzdWdD80IL-DwjSIoeGDArVUVYHxhxgvQ8/edit?usp=sharing) with an outline for each section of what tickets might come out of this. They wouldn't all be high priority, and some may overlap with the feedback coming out of research as well, especially with the changes to save and publish flows that we talked about last week. Do these look like the right tickets to create for next steps?

**Comment by colinmurphy01** [comment]
Looks great, thanks for writing that all up.

I added some comments but I feel the tickets you've identified are the right next steps.

**Comment by kmranjo** [comment]
Created tickets #1266 - #1275 coming out of conversations to align on approach. Closing this one now that those are in the backlog.
