### ISSUE TITLE
CMS: Login/logout experience

### ISSUE THREAD

**Issue by kmranjo** [weather-gov/weather.gov#952]
This item addresses several suggested actions coming out of #826

A user of the CMS should be able to: 
- Upon logging into the CMS, land immediately on the workbench OOTB dashboard (most recent content that you engaged with)
- Once logged in, still be able to access the front-facing site in a separate tab or window 
- Upon logging out of the CMS, have the option on that logout page to log back in 

OOS, views based on role - (from Claire) Available OOTB using Views based on Role. Anything more granular might need a custom module.

**Comment by colinmurphy01** [comment]
This was scoped as `Next` but I'm going to move this to `Now` as a consideration. Being able to log in easily seems important for MVP, considering the session timeout.
