### ISSUE TITLE
Day/Night and High/Low in wrong order for Guam

### ISSUE THREAD

**Issue by partly-igor** [weather-gov/weather.gov#958]
### Description

Looking at the point location page for [Guam Intl Airport, Guam, GUM](https://beta.weather.gov/point/13.484/144.797#daily), (which currently displays the wrong name), the oder of both day and night conditions, and and high and low temperature is reversed. Each day shows night first, and low first instead of the correct order Day-Night, High-Low.
![image](https://github.com/weather-gov/weather.gov/assets/150970973/d322e44a-36ac-4557-aa3b-d279e4fb9d07)

### Acceptance criteria

- [ ] Order of day and night and high and low is correct on all point location pages. 
- [ ] Tests have been implemented or modified to capture the bug
- [ ] Changes have been tested for accessibility

**Comment by elijah-wright** [comment]
Guam doesn't have [data for today](https://api.weather.gov/gridpoints/GUM/47,50/forecast), so the data is actually being shifted by one. in other words, the value for the daytime weather for today is actually for tomorrow.

if it's not possible to get today's weather from places like Guam, then the page should reflect that

**Comment by greg-does-weather** [comment]
Hi @elijah-wright! There are actually 3 periods for "today" in the Guam data you linked. Because Guam is just west of the international date line, it's already Wednesday, March 27th there. Guam is one of the first places on Earth to greet each new day!

**Comment by greg-does-weather** [comment]
This is related to #957. Because it's getting the wrong location, it's also getting the wrong timezone. We filter dates based on midnight local time. Where we should be using Pacific/Guam, it's instead using America/New_York, so it's using the wrong midnight by about 16 hours. I suspect when #963 is ready and merged, this will also be fixed.

**Comment by colinmurphy01** [comment]
Moving to `doing`

**Comment by mgwalker** [comment]
Can confirm that when Guam places are loaded properly locally, the day/night ordering is correct again.

![image](https://github.com/weather-gov/weather.gov/assets/1775733/44a1b2b7-c01e-452e-9087-cc78d0aef4ad)
