### ISSUE TITLE
Hazard Map

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#961]
### User Stories
- I want to understand at-a-glance what, where, and how bad the threat/impact level of a hazard for a specific location
- I'd like to know when and where the hazard is in order to see if the hazard is approaching me or near me/specific location

### MVP Features
- It will live within each hazard's accordion
- It will display 1 hazard (never multiple, even if user zooms out)
- Static plot of hazard
- Display marker for user's location
- Display is automatically zoomed to user's location (within ### radius)
- Capability (and UI) to zoom in, out, and pan around map 
- Understand what the colors represent (legend)
- Base Map Details
  - State borders
  - Names of cities, towns
  - Major roads
  - County borders
  - _Should have_ Places of interest (stadiums, parks, etc)
  - _Should have_ large geographic formations (rivers, mountain ranges, etc) 
  - _Should have_ Names of major roads, large geographic formations (rivers, mountain ranges, etc)
- Hide
  - Playback controls
  - Radar legend
  - View selection
  - Search
  - Hamburger menu with additional controls

OOS
- Tap on map to get forecast for that area

Additional questions to answer with Design
- Where will this live within our UX?
- How will it render on a desktop vs. mobile device?
- Legend: will include color of hazard and definition, design will figure out how it is displayed
- How far zoomed in should the map default to?
- How should we display a link to radar.weather.gov?

### Acceptance Criteria
- I can view a pin of my location on the map
- I can view a hazard plotted on the map
- I can zoom in, out, pan around the map as much as I want and view radar in other locations
- I can pause and scrub to a specific time, time is responsive to my actions
- As a secondary call to action, I can click to radar.weather.gov 

Design Brief: https://docs.google.com/document/d/16QfzH-2viPfBoWdpZ0O59qiz1u3qeGsoajq7lCIuArs/edit#heading=h.kon9y41wjk0o

Related: #773

**Comment by greg-does-weather** [comment]
The CMI library does not support loading a single alert. It does allow filtering by severity, but we can't tell it to only show a specific alert. That will require custom mapping on our end. And if we want it to be interactive, then it has to be implemented client-side. (To be clear, this is all fine, just wanted to lay out what it means.)

**Comment by partly-igor** [comment]
Details look right to me!

**Comment by colinmurphy01** [comment]
Size considerations:

- Stitching together counties and zones
- Loading fire and forecast zones

**Comment by colinmurphy01** [comment]
Discussed in blocker huddle ([notes](https://docs.google.com/document/d/1Fb5kF1b5lWdHez9CRMntDVF7-yEOQf_ySlW4TbjeJM8/edit#heading=h.4bm6vpklzjcf)

Proposal:
- use the leaflet tool for this use case, keep the CMI tool for radar and assess user feedback from testing
- beta will continue to prototype our mapping use cases and requirements in order to inform a longer-term strategy

**Comment by greg-does-weather** [comment]
Pausing on this one for a couple days. There's a prerequisite step to load zones into our spatial database, and while I'm doing that, I want to spend a little time cleaning those scripts up and changing how we load data – instead of deleting and completely reloading data, just load new data and remove any deleted data.

**Comment by colinmurphy01** [comment]
Is there a ticket for getting zones and cleaning up our db?

**Comment by greg-does-weather** [comment]
No. Loading zones, at least, would be a subset of this PR, IMO. Cleaning up the scripts can be separate. I'll create that ticket.

**Comment by greg-does-weather** [comment]
#1102 is done, #1103 is in review. Those two unblock this, so I'm back on it now.

**Comment by greg-does-weather** [comment]
Closed by #1106
