### ISSUE TITLE
Radar Legend

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#967]
### Background
The reflectivity scale included in radar.weather.gov requires more education and can be confusing, especially to members of the public.

[This page](https://www.noaa.gov/jetstream/reflectivity) was generated to explain reflectivity.

### User story
As an uneducated user, I want to easily understand the scale in order to assess the conditions around me.

### Considerations

Here is a summary table within that briefing page
![Image](https://github.com/weather-gov/weather.gov/assets/24654605/f205d7a1-04d9-4488-bdc0-8c940ba9d13f)

**Comment by colinmurphy01** [comment]
Since hazard on a map is in staging, is it possible to include a legend for that in the scope of this as well?

**Comment by partly-igor** [comment]
[Radar legend mockups](https://www.figma.com/proto/0dSABt9zCqoknaKua6DHmP/NOAA---Weather.gov?page-id=5558%3A149380&type=design&node-id=5774-222769&viewport=8%2C765%2C0.26&t=64delBci36CtJ2U5-1&scaling=min-zoom&starting-point-node-id=5774%3A222769)

[Radar legend documentation ](https://www.figma.com/file/0dSABt9zCqoknaKua6DHmP/NOAA---Weather.gov?type=design&node-id=5774%3A223161&mode=design&t=fwAylhpoqYdUlCyS-1)

**Comment by colinmurphy01** [comment]
Seems ready for `eng`?

Maybe we just update the tags and move to the backlog?

**Comment by partly-igor** [comment]
That works though I think engineering prefers new tickets

**Comment by partly-igor** [comment]
Created #1204, I believe we can now close this one.
