### ISSUE TITLE
Review and adjust headings

### ISSUE THREAD

**Issue by partly-igor** [weather-gov/weather.gov#969]
### Description
During R3 we heard some concerns from a screen reader user about the heading levels used within the accordion. We should take another pass at the headings and make sure the document structure makes sense, and if want to make adjustments such introducing an additional SR only heading and remove other h3 level headings. Following the implementation of this ticket we can test the site as a team, and consider additional review (as well as testing with users, of course).

### Acceptance Criteria
- [x] Pages headings have been reviewed
- [x] Adjustments are proposed in a google doc
- [x] `Eng` ticket is documented

https://docs.google.com/document/d/1QM5piZgOpatkOlh7M-R5_eOnpp1v5fUAaWo9AnwufEM/edit?usp=sharing

**Comment by kmranjo** [comment]
Structure in the document has been updated to reflect discussions and decisions through the week. Created the corresponding eng ticket #1036 
Closing as complete
