### ISSUE TITLE
Move Safety Tips inside hazard accordion 

### ISSUE THREAD

**Issue by partly-igor** [weather-gov/weather.gov#970]
### Description
Following a conversation within design, we'd like to try having the safety information live inside the respective hazard accordion for the next round of research. Note that Local Safety resources will remain outside the accordions for now. 

Design mockups
[Mobile](https://www.figma.com/proto/0dSABt9zCqoknaKua6DHmP/NOAA---Weather.gov?page-id=4645%3A62060&type=design&node-id=4645-62061&viewport=465%2C456%2C0.11&t=sq4oy5imEPeGNmcv-1&scaling=scale-down&show-proto-sidebar=1&starting-point-node-id=4645%3A62061&mode=design) 
[Desktop](https://www.figma.com/proto/0dSABt9zCqoknaKua6DHmP/NOAA---Weather.gov?page-id=4645%3A64341&type=design&node-id=4645-64342&viewport=465%2C456%2C0.14&t=Mxg0OuOOeOHpc5SB-1&scaling=min-zoom&starting-point-node-id=4645%3A64342&show-proto-sidebar=1&mode=design)

### Acceptance Criteria
- [ ] The local safety tips ("Tips to Stay Safe") are show in the hazard accordion that the content corresponds to (e.g. Winter Storm Warning content is in the Winter Storm Warning hazard accordion/alert details)
- [ ] The heading levels is adjusted accordingly 
- [ ] Local Resources (not yet built) stay outside the accordions below the Radar 
- [ ] "Tips to Stay Safe" heading text only shows up when there is content below it

` Tag the related milestone to this story`

**Comment by colinmurphy01** [comment]
Related #931

**Comment by partly-igor** [comment]
completed in #997
