### ISSUE TITLE
Adjust Hourly Table Scroll

### ISSUE THREAD

**Issue by partly-igor** [weather-gov/weather.gov#972]
### Description
In R3 we heard users express some frustration with the scroll interaction on the hourly table. As an initial step we propose adjusting the amount the table scrolls on button press. Engineering and design will need to pair to figure out the right amount, and  this will need to be dependent on the screen size (i.e. based on how many hours are displayed in the viewport), 

### Acceptance Criteria
- [ ] Clicking on the left and right scroll buttons will scroll more than 1 hour
- [ ] Design and engineering pair to determine how much more

**Comment by colinmurphy01** [comment]
Related question: what's the ideal minimum amount of hours a user wants to view?

**Comment by eric-gade** [comment]
Closed by #1159
