### ISSUE TITLE
High / Low temps are based on comparison between Day and Night

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#976]
Options

- Compare high and lows for Day and Night, and display the highest and lowest between the two
- Compare high and low across hourly data, and display when it'll be high vs. low

**Comment by greg-does-weather** [comment]
This works for future days, where we have the whole day's range of hours (except the 7th day, where we only have its first 12 hours at first). For "today," we only have the current and future hours available to us, so if the high or low is in the past, we don't have any way of getting it. That could lead to a situation that undermines user trust, where at 8pm, we say "oh the high is 30º" but it was in fact 50º a few hours prior. Our users might see that as a mistake. Combining high and low with time might help with that, but I dunno.

But for future days, we can totally use the hourly data.

**Comment by colinmurphy01** [comment]
Discussed this in meeting ([notes](https://docs.google.com/document/d/1Fb5kF1b5lWdHez9CRMntDVF7-yEOQf_ySlW4TbjeJM8/edit#heading=h.4bm6vpklzjcf))

Action items

- Keep this as is for now, there isn't a simple answer
- Add to our consideration set for visualizations (temperature trends over the day, rising and falling)
- Add to the API wishlist for future consideration, can the API handle the logic for checking a high and low temp over a 24 our period

Closing this ticket for now
