### ISSUE TITLE
Remove NOS links in footer

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#978]
### Description

Currently the NOS links are in the footer, which is another NOAA office.

![Image](https://github.com/weather-gov/weather.gov/assets/24654605/ae9cc61c-070d-47f0-8262-09e351aaf55d)

Remove these links

### Acceptance criteria
- [ ] links are removed in the footer
- [ ] Tests have been implemented or modified to capture the bug
- [ ] Changes have been tested for accessibility

**Comment by greg-does-weather** [comment]
This is primarily a content edit. We don't sync content automatically between environments (anymore? yet?). I'll log into beta and update it there!

**Comment by colinmurphy01** [comment]
Oh my b, for the future we can update these links via CMS?

**Comment by greg-does-weather** [comment]
Yes, but there is a dev component as well! We keep a copy of that kind of content in our repo so when we stand up a new environment, it'll be consistent. So I opened #984 when removes the NOS links from the content stored in the repo, but removing it from beta and staging will be done directly in the CMS.
