### ISSUE TITLE
We will use continuous integration and deployment tools

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#98]
### Context

In order to continuously support a new weather.gov we need to be able to automatically run tests and deploy without human intervention in a way that does not interfere with the continuous operation of the site and maintain compliance and code standards. We also need to identify the risks inherent in any CI/CD tools we use along with mitigations we're adopting to address those risks.

### Decision

Our initial sketch of how deployments will work includes the following: 

* We will use Github to track code changes as a development team.
* We will use Github Actions to run automated tests (functional, UX, accessibility, etc.), code quality scans (linting, CodeQL, etc.), and security scanning (static and dynamic) for those changes.
* We will push tagged releases from `main` to vLab to be stored as the "golden copy" of source code as required by NOAA.
* We will store secrets for production releases in vLab and secrets for non-production releases in Github. 
* We will use AWS CodeBuild to build and deploy updates from vLab.
* We will use AWS ECR to store our container images.

As we progress on building our CI/CD pipeline, we will add additional decision records for particular design choices for these sub-decisions. 

### Consequences

* There is a consequence to using Github as part of source control management because it is not Fedramped beyond Low. We believe we can mitigate particular controls where the risk comes into play. We do not believe the use of Github has any impact on the availability of weather.gov. 
* Using services like ECR, CodeBuild, and CodePipeline increase our dependence on AWS as a platform. We see this as a risk we can accept.
* Because of NOAA protocols around use of Github, there will be added complexity in our CI pipeline that does not serve a technical purpose, but a compliance one.

**Comment by mgwalker** [comment]
I'm unclear how this is different from #92.

**Comment by colinmurphy01** [comment]
Good question, I made and labeled this as **the** ADR ticket based on the process we discussed. So I might have been confused. Would you prefer to keep #92 as the ADR ticket?

**Comment by mgwalker** [comment]
Oh I see! So this is a process hiccup.

Nah, this as the ADR ticket is fine. We'll need to edit the body of the issue in order for the automation to work properly when we get to that, but doing it this way is fine. Mind if I massage the issue title and body to make that clearer?

**Comment by colinmurphy01** [comment]
yes please, and apologies for not using the ADR template when generating this ticket. That's my b

**Comment by mgwalker** [comment]
![no worries](https://media.giphy.com/media/JePHwKPJ6OkFKd7lqG/giphy.gif)

**Comment by mgwalker** [comment]
I've tried to capture the major decisions from Logan's CI/CD diagram. I'm wondering if maybe this should actually be several ADRs, but since they're all tightly-related, it makes sense to draft/discuss/accept them together. If splitting them up makes sense, we can do that after accepting them.

**Comment by mgwalker** [comment]
Closing because we're back at square one. We'll probably need an ADR around this eventually, but rather than dragging this one along kicking and screaming, we'll just create a new one when it comes up again.

**Comment by greg-does-weather** [comment]
I forgot to use my right account again. 🤷‍♂️
