### ISSUE TITLE
Widen hourly forecast in order to view more hours at once

### ISSUE THREAD

**Issue by shadkeene** [weather-gov/weather.gov#988]
Right now on beta, alert text and hourly forecasts are smaller than the screen view for desktops.
![image](https://github.com/weather-gov/weather.gov/assets/139174561/36bc6f5a-edac-4979-aebb-d91ef1474bb4)
On the "today" tab, the hourly forecast stretches all the way, so one can see more hours at once.  This has been a point of discussion in some of the user feedback sessions.
![image](https://github.com/weather-gov/weather.gov/assets/139174561/5bcebd83-386b-4ff5-85e4-bb0b249a36ca)

Is there a way to get a broader/wider view of all hourly forecasts (in daily tab) on desktop (leverage the entire width of the screen) while still maintaining a clear/effective display?  I think the width of hourly forecasts is tied to the width of the daily summary (on the daily tab), so that makes sense.  This ticket is mainly for discussing this overall and if there are any changes needed/considered for these.

**Comment by colinmurphy01** [comment]
We're limiting the written word views (like hazards) to a 65-72 char
13/14 words (both per / line) width/limit for readability.
