### ISSUE TITLE
Search dropdown is hidden behind tab labels

### ISSUE THREAD

**Issue by kmranjo** [weather-gov/weather.gov#989]
### Expected behavior
On a location page, when a user begins to enter something in the search field, the search box begins populating possible matching results in a dropdown. This dropdown should layer in front of any other content on the page so that the user can see all options being displayed.

### Current behavior
If the dropdown attempts to display enough results that it overlaps with the tab menu on page, the tabs appear in front of the dropdown, obscuring some of the results. 
![Image](https://github.com/weather-gov/weather.gov/assets/127144183/30e456c9-3362-4ba8-b003-4905cb5bea85)

**Comment by colinmurphy01** [comment]
using #993 to track
