### ISSUE TITLE
How might we define weather location?

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#99]
### Description
For weather.gov location is determined by X/Y coordinates that correlate to a WFO. Users also define location in different ways - zip code, city, infrastructure, lat/long. We need to understand what's the ideal mapping of location that will make it easier for the user and the system to identify the most relevant weather information.

**Outcome: Easier to Find**

### Justification
- Value: High
- Viability: High
- Alignment: High

```[tasklist]
### Work
- [ ] #90 
- [ ] Outreach and Scheduling
- [ ] Conduct research
- [ ] Synthesize and share research
```

**Comment by colinmurphy01** [comment]
@kmranjo One open question is user research within this Epic. 

Do we need to consider user research into this topic prior to building out MVP? Or do we feel confident in our hypothesis for now to inform MVP and then continue to explore as we build?

**Comment by kmranjo** [comment]
@colinmurphy01  I think we have enough information to get started. We can build our hypothesis around location into our MVP and test it with users, and explore location scaling and edge cases and etc. from there.

**Comment by colinmurphy01** [comment]
Roger.

Are there specific stories coming out of your research that could be added to the Epic #97 and considered for Sprint Planning?

The ones that come to mind for me are:

- 3.1 I can search the site with a zip code to find my weather information
- 3.2 I can search the site with a city to find my weather information
- 3.3 I want the site to know my location automatically

**Comment by kmranjo** [comment]
Those definitely all relate to this, but I'm not sure how we want to break them into stories, and how to determine which ones are/aren't in scope for MVP. The one probably easiest for us to test that is for sure within the scope of what we've been working on so far would be something like "I understand that the forecast presented on this page is relevant to my location" (trying to speak more to that reinforcement/clarity of location than the search process).

**Comment by colinmurphy01** [comment]
That's a good point. We'll hold on spinning these up as stories until we have our MVP discussions.
