### ISSUE TITLE
Fix new location search component styling

### ISSUE THREAD

**Issue by eric-gade** [weather-gov/weather.gov#993]
### Description
Per #992, we should fix the styling of the new location search component so that it is consistent with the existing USWDS based combo-box in terms of layout and appearance.

### Acceptance criteria

- [ ] The layout and appearance of our new location search component matches the USWDS version as closely as possible
- [ ] The z-index of the dropdown list is above any sticky menus (like the wx-tabbed-nav)

**Comment by colinmurphy01** [comment]
@partly-igor are you comfortable if @eric-gade takes a swing at matching the current styles of the site?

**Comment by colinmurphy01** [comment]
Will fix #989

**Comment by partly-igor** [comment]
For sure, and happy to pair if need be.

**Comment by colinmurphy01** [comment]
Igor and Eric paired on this, there are some more complex use cases to explore later on.
