### ISSUE TITLE
Accessibility tweaks: Search component

### ISSUE THREAD

**Issue by eric-gade** [weather-gov/weather.gov#994]
### Description
After #992 and the initial pass at a new location search component, let's jam on the [WCAG recommendation](https://www.w3.org/WAI/ARIA/apg/patterns/combobox/) and make sure the component is in compliance as much as possible.

### Acceptance criteria

- [ ] The new location search component appears to be in compliance with the [WCAG recommendations](https://www.w3.org/WAI/ARIA/apg/patterns/combobox/)
- [ ] Compliance is covered by existing and/or new test cases in either the Cypress or component (jsdom-based) tests of the component
- [ ] Additional issues are documented in tickets as needed

**Comment by colinmurphy01** [comment]
Consider scheduling GSA's 508 compliance lead for this

**Comment by colinmurphy01** [comment]
Tracking updates in #1019
