### ISSUE TITLE
Fix new location component tests

### ISSUE THREAD

**Issue by eric-gade** [weather-gov/weather.gov#995]
### Description
Per #992, there are mysterious failures / flakiness with the component and Cypress tests for the new location search. Let's fix these!

### Acceptance criteria

- [ ] There is a more comprehensive coverage of the location search component
- [ ] Existing Cypress and jsdom-based component tests are passing

**Comment by colinmurphy01** [comment]
If you tell cypress to click, it won't really click.

We resolved by finding another way to trigger a click.

@eric-gade will add details
