### ISSUE TITLE
Additional e2e tests for alerts

### ISSUE THREAD

**Issue by greg-does-weather** [weather-gov/weather.gov#998]
### Description

We currently don't have any tests around the duration text component of alerts. We need to test all those varieties. (See #809.) We may want to look into using [timecop](https://github.com/kiddivouchers/php-timecop) for this.

### Acceptance criteria

- Tests have been implemented for:
  - [ ] alert is in the past (not listed)
  - [ ] alert is active
  - [ ] alert begins between midnight and noon of the current day ("this morning")
  - [ ] alert begins between noon and 6pm of the current day ("this afternoon")
  - [ ] alert begins after 6pm of the current day ("tonight")
  - [ ] alert begins between midnight and noon of the next day ("tomorrow morning")
  - [ ] alert begins between noon and 6pm of the next day ("tomorrow afternoon")
  - [ ] alert begins after 6pm of the next day ("tomorrow night")
  - [ ] alert begins further out ("day of the week")

**Comment by colinmurphy01** [comment]
@greg-does-weather should we move this to the backlog and consider this something for this sprint?

**Comment by greg-does-weather** [comment]
That seems reasonable to me. We can also designate it as a freebie ticket for someone to pick up when they've got some time. It shouldn't be *hard*, but it may take some time to create all the fake alerts.

**Comment by loganmcdonald-noaa** [comment]
Turns out this is pretty well covered in https://github.com/weather-gov/weather.gov/blob/main/web/modules/weather_data/src/Service/Test/AlertUtility.php.test. I spent some time today trying to make Cypress work for testing this in the browser, but it's hard to manipulate Drupal's sense of time prior to running the Cypress tests. If we cannot figure out a way to do this with Cypress, we should leave what we have and consider this issue moot. Will update tomorrow.

**Comment by greg-does-weather** [comment]
It took me a while, but now I remember what this is about. We currently only have unit tests for the alert duration text, so it's isolated from everything else. I thought it would be good to also test them as part of the whole system.

I had imagined these as backend e2e tests (rather than Cypress tests). They might be added here:
https://github.com/weather-gov/weather.gov/blob/main/web/modules/weather_blocks/src/Plugin/Block/Test/EndToEnd/Alerts/Alerts.php.test

I think my reasoning on timecop was that we could create a set of alerts solely for these tests, and give those alerts hardcoded timestamps rather than using our proxy API's dynamic times. Then we could (hopefully) set what time PHP thinks it is and have actual, no-kidding deterministic test outputs (for the first time, hopefully serving as a model of how we could do it elsewhere going forward).
